### PR TITLE
Fix early renew modal stuck loading and error

### LINKED ISSUE #1246: Early renewal modal unresponsive and fails to redirect when Stripe is not the payment method
**Describe the bug**
When using the modal to early renew a subscription (WooCommerce Subscriptions) that is tied to a gateway other than Stripe, the modal fails to redirect the user to the correct URL after processing the payment. Instead, the user is stuck with the modal in a blocked unresponsive state:

Screen Shot 2020-06-26 at 16 38 37

The JavaScript console shows that some JSON parsing errors are the reason:

Screen Shot 2020-06-26 at 15 03 06

Besides the UX being less than ideal, this is also problematic because it gives the impression that the renewal didn't come through, when in fact it could have.

**Additional details**
I did some research and found out that in order to handle SCA, Stripe ["hijacks"](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f597353e4a0caf7fd426e53a7f41262ad5ab3cb5/assets/js/stripe.js#L252-L253
) the early renewal modal submit button. This happens even when Stripe is not the associated payment method.

The callback here ([`onEarlyRenewalSubmit`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f597353e4a0caf7fd426e53a7f41262ad5ab3cb5/assets/js/stripe.js#L796-L821
)) performs the request and expects the result to be from the Stripe gateway, which is in JSON format. As such, it [tries to parse](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f597353e4a0caf7fd426e53a7f41262ad5ab3cb5/assets/js/stripe.js#L809) the result, which under most circumstances (and for other gateways) is plain HTML due to the default handling being a redirect.

Because the request is actually executed, the payment might have happened already, but the UI is stuck due to the JS errors.

Even though it'd be good to add a `try… catch` around the JSON parsing code in this function, this is not really a fix and for a proper one Subscriptions probably needs to make the payment method available somewhere in the early renewal modal (maybe through a `data-…` attribute or a CSS class) so that Stripe can figure out whether it needs to override the default handling or not (if the subscription uses a different payment method).

**To Reproduce**
1. Activate WooCommerce Subscriptions, the Stripe payment gateway and [another gateway with proper Subscriptions support](https://docs.woocommerce.com/document/subscriptions/payment-gateways/). I tested with CyberSource.
2. Enable the early renewal modal. Go to WC > Settings > Subscriptions and make sure the following are enabled: "Accept Early Renewal Payments" and "Accept Early Renewal Payments via a Modal".
3. Create and purchase a subscription product using a gateway other than Stripe.
4. Go to My Account > Subscriptions (or "My Subscription") and click "Renew now".
5. Click "Pay Now".
6. Confirm that the modal gets stuck and no indication of what happened is given to the user.
7. Reload the page and confirm that the renewal probably went through (check the next payment dates).
8. Disable the Stripe extension and try 4-5 again, this time confirming that the modal is not stuck and the final redirect occurs.

**Expected behavior**
Early renewal handling to work correctly, redirecting the user back to the subscription after completing the payment.

**Environment (please complete the following information):**
 - WordPress Version: 5.4.2
 - WooCommerce Version: 4.2.2
 - Stripe Plugin Version: 4.5.0.
 - WooCommerce Subscriptions Version: 3.0.5

### PR DESCRIPTION
**Pull request by ismaeldcom**
# Changes proposed in this Pull Request:

Fixes #1246

Check for payment method attribute before hook Into early renew modal submit button. 
Using the new attribute from WC Subscriptions (4123-gh-woocommerce/woocommerce-subscriptions) we can check the payment method and then hook into it only it uses Stripe gateway.
Added a condition to check for the existence of the attribute to support older versions of WC Subscription too. This way it will work as always for older versions, and prevent the issue on newer ones.

Just to confirm, I should add changelog entries for this, right?

# Testing instructions
You need to use 4123-gh-woocommerce/woocommerce-subscriptions, until it got merged.

Doing an early renew on **My account > Subscriptions**, clicking on **Renew now** button. For a subscription with Stripe gateway or any other, should proceed without issues. Before this, you'll get stuck on a loading state, for a subscription without Stripe as gateway.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: assets/js/stripe.js [hunk 1]
```diff
@@ -253,7 +253,11 @@ jQuery( function( $ ) {
 			);
 
 			// Subscription early renewals modal.
-			$( '#early_renewal_modal_submit' ).on( 'click', this.onEarlyRenewalSubmit );
+			if ($('#early_renewal_modal_submit[data-payment-method]').length) {
+				$('#early_renewal_modal_submit[data-payment-method=stripe]').on('click', this.onEarlyRenewalSubmit);
+			} else {
+				$('#early_renewal_modal_submit').on('click', this.onEarlyRenewalSubmit);
+			}
```
Comment (asumaran) [inline assets/js/stripe.js:260]: @ismaeldcom I wasn't able to test this PR with WooCommerce CyberSource Payment Gateway. To enable it for subscriptions it asks me to enable "Tokenization"

Screen Shot 2021-07-05 at 1 52 25 PM

I've created a test account on CyberSource but haven't found a way to enable it. If you can help me with that so I can review this PR properly it'd be a great help.

Apart from that. Unless the plugin in mention creates another PR button with the exact same ID. I don't see how this code is different from the existing one or solves anything.

Please, let me know how can I enable the plugin to test this correctly.

**Review by asumaran — COMMENTED** [review]
Hey @ismaeldcom Thanks for this PR. I left a comment for you.

File: assets/js/stripe.js (hunk 1 above)
Comment (jorgeatorres) [reply assets/js/stripe.js:260]: Hi @asumaran!

Sorry to barge in but I'd like to see this in and so was following the PR.

> To enable it for subscriptions it asks me to enable "Tokenization"

The tokenization settings are on the same screen as the rest of the gateway settings (WC > Settings > Payments > Cybersource  and scroll down to "Tokenization") but you don't _need_ to use Cybersource for the initial purchase, just a gateway other than Stripe (that supports subscriptions, of course).

> Apart from that. Unless the plugin in mention creates another PR button with the exact same ID. I don't see how this code is different from the existing one or solves anything.

The ID is the same, but the `data-payment-method` attribute didn't exist before and that's what the code above is checking: it was recently added to the "Early Renewal" button in Subscriptions (see 4123-gh-woocommerce/woocommerce-subscriptions). The difference is that for versions of Subscriptions with the button attribute, Stripe will add its callback _only_ if the subscription was purchased with Stripe, leaving subscriptions using other payment methods undisturbed.

Hope I didn't misrepresent anything @ismaeldcom.

Comment (asumaran) [reply assets/js/stripe.js:260]: > The tokenization settings are on the same screen as the rest of the gateway settings (WC > Settings > Payments > Cybersource and scroll down to "Tokenization") but you don't need to use Cybersource for the initial purchase, just a gateway other than Stripe (that supports subscriptions, of course).

@jorgeatorres Yes. I've tried that. Of course the initial purchase I made it using Stripe but in order to test the auto Renew now modal I wanted to enable CyberSource but it asks for a Tokenization Profile ID which I don't know how to get one.

Screen Shot 2021-07-06 at 11 44 01 AM

Comment (jorgeatorres) [reply assets/js/stripe.js:260]: @asumaran: FWIW the initial purchase has to be made using the other gateway, not Stripe. That is, if you want to replicate how Stripe "hijacks" the early renewal dialog.

As for the tokenization profile ID for Cybersource, I can share credentials with you if needed, but as I said before, you don't need to use Cybersource specifically. Feel free to ping me in Slack if you need that info!

Comment (asumaran) [reply assets/js/stripe.js:260]: @jorgeatorres @ismaeldcom I was able to use CyberSource to purchase a subscription and reproduce the issue. It's more clear to me the fix we are doing here after reading #1246. Although it wasn't very clear to me at first I would just add a comment explaining why we are doing this. Other than that this looks good.

**Review by asumaran — APPROVED** [review]
LGTM

File: assets/js/stripe.js (hunk 1 above)
Comment (asumaran) [reply assets/js/stripe.js:260]: I just want to mention that using the "Renew now" button and then clicking the "Pay now" button on the modal it redirects to the checkout page showing the following error.

Screen Shot 2021-07-06 at 9 31 26 PM

I'm assuming this is expected for gateways  other than Stripe?

Comment (ismaeldcom) [reply assets/js/stripe.js:260]: Hey @asumaran! Thanks for looking at this, and sorry for my late reply, I was AFK. I wasn't able to reproduce your latest error. Maybe is something related to the gateway you used?
