### PR TITLE
Fix potential mandate errors if subscription period includes uppercase

### LINKED ISSUE #3072: Mandate interval is case sensitive but output is not checked for casing, potentially causing subscription renewal failure
**Describe the bug**

In 7923275-zd-a8c  the merchant is receiving the following response on subscription renewals

```
{
  "error": {
    "message": "Invalid payment_method_options[card][mandate_options][interval]: must be one of day, week, month, year, or sporadic",
    "param": "payment_method_options[card][mandate_options][interval]",
    "request_log_url": "https://dashboard.stripe.com/logs/req_[redacted]",
    "type": "invalid_request_error"
  }
}
```
The relevant request data is as follows

```
"payment_method_options": {
    "card": {
      "mandate_options": {
        "start_date": "1648152360",
        "amount_type": "fixed",
        "interval": "Year",
        "interval_count": "1",
        "reference": "73007",
        "supported_types": {
          "0": "india"
        },
        "amount": "3000"
      }
```

**To Reproduce**

I successfully replicated this by editing the `_billing_period` of a WooCommerce Subscription from `year` to `Year`

**Expected behavior**

WooCommerce Subscriptions continues to operate correctly except for the failed payment submission. It seems that only Stripe is case sensitive, therefore I would expect output to Stripe to be put to lowercase.

**Workaround**

The following workaround was provided in p1712951294283619/1712885470.587459-slack-C7U3Y3VMY

> Meanwhile, if the merchant wants to change the interval, a possible workaround would be to add a filter to replace Year with year , something like this:

```
add_filter( 'wc_stripe_generate_create_intent_request', 'custom_interval_fix_create_intent_request', 20, 3 );
function custom_interval_fix_create_intent_request( $request, $order, $prepared_source ) {
	if ( isset( $request['payment_method_options']['card']['mandate_options']['interval'] ) ) {
		if ( "Year" === $request['payment_method_options']['card']['mandate_options']['interval'] ) {
		    $request['payment_method_options']['card']['mandate_options']['interval'] = 'year';
		}
	}
	return $request;
}
```

> The priority is important, as the subscriptions trait adds a filter with priority 10.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3072 

## Changes proposed in this Pull Request:

In an uncommon circumstance, if the subscriptions billing period is somehow set to 'Yearly' (note the capital letter). Stripe may throw an error when attempting to generate the mandate data.

Screenshot 2024-04-16 at 2 34 11 pm

I suspect that stores which run into this issue may have imported their subscriptions or something because billing periods with capital letters is not standard.

## Testing instructions

Note: Given this requires an uncommon situation, there is some custom code involved to mimic what I believe may have happened.

1. Install and activate Woo Subscriptions. 
2. Conditional. Create a subscription product if you don't already have one.
3. In the admin dashboard create a new subscription (WooCommerce > Subscriptions > Add new) 
4. Add the product and set the customer ID to your current user. 
5. Save
6. From the edit subscription's actions dropdown create a pending **parent** order. 
9. From the edit subscription's actions dropdown create a pending **renewal** order.
11. Using a plugin like WP console. Run the following code snippet to set your subscription to 'Yearly'.
12. Attempt to pay for the subscription renewal order using Stripe.
    - On `develop` you will get the error mentioned above.
    - On this branch the payment should succeed.  

```php
$subscription = wcs_get_subscription( 7163 ); // Replace with the subscription ID you created.
$subscription->set_billing_period( 'Year' ); 
$subscription->save();
```

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 1]
```diff
@@ -683,20 +683,15 @@ private function create_mandate_options_for_order( $order, $subscriptions ) {
...
+			return [];
 		}
 
 		// Get the first subscription associated with this order.
 		$sub = reset( $subscriptions );
 
-		// If the amount zero we just return since mandate is not required and can not be created with zero amount.
-		if ( 0 === $sub_amount ) {
-			return [];
-		}
```
Comment (james-allan) [inline includes/compat/trait-wc-stripe-subscriptions.php:695]: Just noting that I removed this because it was the exact same logic above. If the subscription total is 0, return. I also fixed the undefined `$request` variable above.

**Review by a-danae — APPROVED** [review]
Thanks for fixing this so quickly, @james-allan ! 🙂 

✅ I was able to replicate the problem in `develop` following the testing instructions. It's no longer happening in this branch.
✅ The code makes sense to me.
