### PR TITLE
Fix validation error message in settings

### LINKED ISSUE #2047: fix: validation error on settings save
**Describe the bug**
Settings are not saved when I _don't_ provide a "short" statement descriptor and the "Add customer order number to the bank statement" checkbox is un-checkeched, the validation fails.

Screen Shot 2021-10-06 at 2 15 31 PM

**To Reproduce**
- Ensure you have the `_wcstripe_feature_upe_settings` flag enabled
- Go to http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings
- Check the "Add customer order number to the bank statement" checkbox (if it isn't already)
- Clear the "Shortened customer bank statement" field
- Un-check the "Add customer order number to the bank statement" checkbox
- Save the settings
- Error appears
Screen Shot 2021-10-07 at 11 32 12 AM

**Expected behavior**
Error is appearing because of failing validation in the backend.
We probably shouldn't validate the "Shortened customer bank statement" field when the "Add customer order number to the bank statement" checkbox is un-checked.

### PR DESCRIPTION
**Pull request by cesarcosta99**
# Changes proposed in this Pull Request:

Fixes #2047 

This PR addresses a fix for the validation in the settings REST controller. The field `short_statement_descriptor` is supposed to rely on `is_short_statement_descriptor_enabled` and it was being validated and erroring. The changes here enforces that relation in the validation, and only applies proper validation when `is_short_statement_descriptor_enabled` is `true`, keeping it untouched when `is_short_statement_descriptor_enabled` is `false`.

This also includes a small fix for the validation error message.

# Testing instructions
1. Ensure you have `_wcstripe_feature_upe_settings` option set to `yes`.
2. Go to http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings
3. Tick the `Add customer order number to the bank statement` box.
4. Clear the `Shortened customer bank statement` field and save.
5. You should see the notice and exact error below (attention to the "...5 and 10 characters long..." part):
image
6. Fill in `Shortened customer bank statement` with at least 5 characters and save.
7. You should receive a `Settings saved.` notice.
8. Clear the `Shortened customer bank statement` field.
9. Untick the `Add customer order number to the bank statement` box and save.
10. You should receive a `Settings saved.` notice.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-gateway-stripe.php [hunk 1]
```diff
@@ -1288,7 +1288,13 @@ public function validate_account_statement_descriptor_field( $value, $max_length
 			! preg_match( $has_one_letter, $value ) ||
 			! preg_match( $no_specials, $value )
 		) {
-			throw new InvalidArgumentException( __( 'Customer bank statement is invalid. Statement should be between 5 and 22 characters long, contain at least single Latin character and does not contain special characters: \' " * &lt; &gt;', 'woocommerce-gateway-stripe' ) );
+			throw new InvalidArgumentException(
+				sprintf(
+					/* translators: %u Number of the maximum characters allowed */
+					__( 'Customer bank statement is invalid. Statement should be between 5 and %u characters long, contain at least single Latin character and does not contain special characters: \' " * &lt; &gt;', 'woocommerce-gateway-stripe' ),
```
Comment (diegocurbelo) [inline includes/class-wc-gateway-stripe.php]: We are using the same validation failed message for both `Full bank statement` and `Shortened customer bank statement` fields, with the following message prefix: `Customer bank statement is invalid. Statement ...`, maybe we should have 2 different messages 🤷🏼?

On the other hand, the message is displayed above each of the fields so is clear which field has the error... feel free to dismiss this if you already evaluated the different messages.

Anyway, I just added an `a` to the message in the code suggestion. 

```suggestion
					__( 'Customer bank statement is invalid. Statement should be between 5 and %u characters long, contain at least a single Latin character and not contain special characters: \' " * &lt; &gt;', 'woocommerce-gateway-stripe' ),
```

**Review by diegocurbelo — APPROVED** [review]
Code looks good and tests well!

Left a suggestion about a typo, but approved and ready to merge... 🚢 🚢

File: includes/class-wc-gateway-stripe.php (hunk 1 above)
Comment (cesarcosta99) [reply includes/class-wc-gateway-stripe.php]: Good catch, I think it really makes sense to properly name each field so I addressed it in 41deb3b.
