### PR TITLE
Fix the Radar-related webhooks

### LINKED ISSUE #818: Elevated Risk level set to Processing.
#### Affected ticket(s)

1889635-zen

#### What I expected

I'd found this earlier issue, https://github.com/woocommerce/woocommerce-gateway-stripe/pull/535, and like how that looked like it works. I'm not having the same experience though at the moment, and neither is a customer I had in chat.

What I expect is that if Stripe flags the transaction with an elevated risk level, meaning the Stripe account owner needs to approve the transaction, the order in WooCommerce should be On Hold and reflect the actions the above PR once showed.

#### What happened instead

Using the test card for an elevated risk for Radar, the order just goes to Processing without warning the store owner it needs reviewed in Stripe before they process the order and ship out the product.
#### Steps to reproduce the issue

Use the elevated card number here with any valid expiration date and made up CVC.

4100000000000019

You'll then see the order is Processing and appears fine in WooCommerce while in Stripe, it'll tell you to review the transaction.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #818

Sorry this issue flew under our radar (pun absolutely intended) for so long.

When a payment triggers a Stripe Radar rule and it's placed "under review", the merchant's site is notified woth a webhook. When the merchant goes to Stripe Dashboard and approves the review ("unlocking" the payment), there's another webhook.

The webhooks `review.opened` and `review.closed` previously had a property `object.charge` with the Charge ID that triggered the review. Now, with the Payment Intent logic, that property is `null`, and instead the webhook includes the Intent ID in `object.payment_intent`. This PR fixes the webhook logic to look for the `payment_intent` property.

To test:
- Make a payment using this CC: `4000000000009235`
- On the order screen, you'll see that it has been pun "On Hold" and there's an order note prompting you to review the payment
- Follow the link in the order note, and approve the payment
- Refresh the order page, it should go to "Processing" state and there's an order note indicating why

These are my order notes after the whole process:
Screenshot 2019-07-02 at 15 29 54

Question: Can you imagine any use case where the `charge` property would still be used instead of `payment_intent`? I can't think of anything, so keeping the old logic in case `charge` isn't `null` seemed pointless.

### CODE REVIEW

**Comment by allendav** [comment]
> Sorry this issue flew under our radar

OMG @DanReyLop

File: includes/class-wc-stripe-webhook-handler.php [hunk 1]
```diff
@@ -503,10 +503,10 @@ public function process_webhook_refund( $notification ) {
 	 * @param object $notification
 	 */
 	public function process_review_opened( $notification ) {
-		$order = WC_Stripe_Helper::get_order_by_charge_id( $notification->data->object->charge );
+		$order = WC_Stripe_Helper::get_order_by_intent_id( $notification->data->object->payment_intent );
 
 		if ( ! $order ) {
-			WC_Stripe_Logger::log( 'Could not find order via charge ID: ' . $notification->data->object->charge );
+			WC_Stripe_Logger::log( 'Could not find order via intent ID: ' . $notification->data->object->payment_intent );
```
Comment (allendav) [inline includes/class-wc-stripe-webhook-handler.php]: The logged message is exactly the same here and below. Would that make debugging harder?

Comment (allendav) [inline includes/class-wc-stripe-webhook-handler.php]: Is it at all possible for `$notification` to not have a `data`, for data to not have an `object`, or object to not have a `payment_intent`? (i.e. do we need to defend against a PHP notice here and below)?

**Comment by allendav** [comment]
Opening a 4.2.3 for this and anything else we think can't wait for 4.3

File: includes/class-wc-stripe-webhook-handler.php (hunk 1 above)
Comment (DanReyLop) [reply includes/class-wc-stripe-webhook-handler.php]: I don't think it's a problem, because the webhooks are different (review opened and review closed), and the "closed" one only happens when the merchant takes a manual action in the Stripe dashboard.

Comment (allendav) [reply includes/class-wc-stripe-webhook-handler.php]: Will the logged messages have adjacent logged context as to which webhook was in play?

Comment (DanReyLop) [reply includes/class-wc-stripe-webhook-handler.php]: I spot-checked some of the other webhook handlers and they all assume `$notification->data->object` contains the expected object type. The only cases where that wouldn't be true would be:
- A forged webhook (in which case a PHP notice would be welcome IMHO)
- Closing a review that was opened before 4.2.0 (that is, before the Payment Intents were introduced). In that case, the webhook would contain a `charge` object instead of a `payment_intent`. But I don't think a review can just stay opened for months, so it's not worth coding that path.

Comment (DanReyLop) [reply includes/class-wc-stripe-webhook-handler.php]: No, it would just have a timestamp above the log message.

Comment (allendav) [reply includes/class-wc-stripe-webhook-handler.php]: Then I think we should add a short string to each with "review opened" and "review closed" or something like that.

Comment (DanReyLop) [reply includes/class-wc-stripe-webhook-handler.php]: Done in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/908/commits/7ab522cff0cb91ed1db87b6784018e0090040a65

Comment (dechov) [reply includes/class-wc-stripe-webhook-handler.php]: Not sure how big a deal it is, but thought it would be worth pointing out that anyone recently upgrading from <4.2.0 and then closing a review would run into the latter path.

Comment (DanReyLop) [reply includes/class-wc-stripe-webhook-handler.php]: @dechov Good point! It somehow didn't occur to me that people can just skip over versions when they update. I've opened #919 with a quick fix.

**Comment by ryanr14** [comment]
Thank you for getting this added!
