### PR TITLE
Use dummy data for billing address info if none is provided

### LINKED ISSUE #1770: UPE fails to process payment if some checkout fields are missing
**Describe the bug**
This is a reference to a similarly discovered bug from a [WCPay issue](https://github.com/Automattic/woocommerce-payments/issues/2785). When using a plugin that allows editing the checkout fields such as [Checkout Field Editor](https://woocommerce.com/products/woocommerce-checkout-field-editor/), it is possible to remove a field that gets referenced during a UPE checkout. When creating the UPE element [we tell it that there is no need to collect certain fields](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/1de740902485806f48d28b75ea7e57ed7a540f8e/client/classic/upe/index.js#L109) on the expecation that we will be passing them in later. We then [retrieve those fields to pass in when we process the payment](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/1de740902485806f48d28b75ea7e57ed7a540f8e/client/classic/upe/index.js#L211), but if the fields are removed this causes an error.

There will be scenarios where fields won't be necessary to UPE, like a second address line. But there will also could be scenarios where a required field is removed, like country or postal code for credit cards. Any fix for this issue should handle both cases.

**To Reproduce**
- Start with a store with this branch and UPE enabled (_wcstripe_feature_upe set to 'yes' in wp_options table) and the new checkout experience enabled from the WC Stripe settings page.
- Install a plugin that allows you to edit checkout fields, such as [Checkout Field Editor](https://woocommerce.com/products/woocommerce-checkout-field-editor/).
- Disable one of the fields, such as `billing_address_2`
- As a customer, go to checkout with a product.
- Enter valid payment details in the UPE and click Place Order.
- Confirm that the error message in the screenshot below is displayed and customer is unable to checkout.

**Expected behavior**
Any non-required address fields should not prevent a checkout and any required fields should not be removed from the UPE so the customer could still checkout even if the required fields are removed elsewhere.

**Screenshots**
UPE-checkoutfields-error

### PR DESCRIPTION
**Pull request by superdav42**
closes #1770

If checkout fields editor or another plugin is used to hide billing address fields checkout will fail with UPE.
This is same fix as we used in [WCPay](https://github.com/Automattic/woocommerce-payments/pull/2853)

This does not prevent merchants from hiding fields that are used by billing address verification and thus breaking all checkout. But address and postal code verification are not enabled by default. Merchants will have to enable them in the dashboard and if they do I can hope they will not hide them from checkout. 

# Testing instructions

### Testing instructions 1
- Install checkout field editor.
- goto WooCommerce => Checkout fields.
- Hide billing_phone or/and billing_address_2 fields.
- Try checking out with UPE.
- Order should pass through, no errors observed.

### Testing instructions 2

- Install checkout field editor.
- goto WooCommerce => Checkout fields.
- Keep billing_phone or/and billing_address_2 fields but do not mark them as required.
- Try checking out with UPE.
- Order should pass through, no errors observed.

### Testing instructions 3

- Install checkout field editor.
- goto WooCommerce => Checkout fields.
- Keep billing_phone or/and billing_address_2 fields and mark them as required.
- Try checking out with UPE.
- Order should pass through, no errors observed.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by superdav42** [comment]
> But there will also could be scenarios where a required field is removed, like country or postal code for credit cards. Any fix for this issue should handle both cases.

The first fix did not address the problem if the merchant hides required fields such as postal code. The last commit should address this. If postal code is hidden it will be shown in the stripe element like so:
image

I need to find a good way to test this. I can enable postal code verification in stripe dashboard. At https://dashboard.stripe.com/settings/radar/rules but the [test credit cards](https://stripe.com/docs/testing) do not provide a card with needs a matching zip. Just cards that force the failure case. I'm not sure how to test that the zip is being provided correctly.

If we feel this fix is needed we should port it to WCPay.

File: client/classic/upe/index.js [hunk 1]
```diff
@@ -110,16 +111,36 @@ jQuery( function ( $ ) {
...
+				: 'auto',
+			city: enabledBillingFields.includes( 'billing_city' )
+				? 'never'
+				: 'auto',
+			state: enabledBillingFields.includes( 'billing_state' )
+				? 'never'
+				: 'auto',
+			postalCode: enabledBillingFields.includes( 'billing_postcode' )
+				? 'never'
+				: 'auto',
```
Comment (FangedParakeet) [inline client/classic/upe/index.js:143]: I think this part is pretty important and we should probably open a quick issue to add this to WCPay, but let me know if you think it's just a nice-to-have perk instead.

**Review by FangedParakeet — APPROVED** [review]
I tested the scenarios provided in the testing instructions and many, many more and everything worked as expected! I tried testing the zip code verification myself as well and as far as I can tell, that disappointingly appears to be impossible. I tried by using an international card from Belgium with a US address and zipcode, which does not follow the same format as Belgian zip codes (Belgian zip codes contain four digits, while US zips contain five), but when I checked the payment intent in Stripe's dashboard, the Zip check passed anyways.

As far as I'm concerned, I think showing the zip code input inside the UPE when the billing field is not present at checkout is enough for me to think that we're covering our hides; but let me know if you'd feel more comfortable having a proper way to test this and perhaps we can go and bother the Stripe devs and see if they have any better options. 

Anyways, in conclusion, LGTM. I approve.

File: client/classic/upe/index.js (hunk 1 above)
Comment (superdav42) [reply client/classic/upe/index.js:143]: Now I'm concerned if we send `'-'` as postal code [below](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1795/files#diff-cafcea010e8e6c0d90e1dc3a72c2727bd09bb2f9038a5af2d3e625ca88e51ee3R260) that it will override whatever the customer enters in the stripe element. Could you tell by your testing if this was happening?

Comment (superdav42) [reply client/classic/upe/index.js:143]: Well I figured it out. Looking the the XHR requests in the network tab I found:
```
Request URL: https://api.stripe.com/v1/payment_intents/pi_3JXMFvB6usZchzRk0xzuo59b/confirm
Request Method: POST
Status Code: 200 
...
payment_method_data[billing_details][address][postal_code]: 83687
payment_method_data[type]: card
payment_method_data[card][number]: 4242 4242 4242 4242
payment_method_data[card][cvc]: 155
payment_method_data[card][exp_month]: 12
payment_method_data[card][exp_year]: 25
...
```

83687 is the zip code I entered in the stripe element so I think we're ok as it is.
