### PR TITLE
Prevent editing uncaptured order

### LINKED ISSUE #916: Customer sent order processing email after an order has failed
This bug occurs when a charge has been authorized, and the merchant attempts to increase the price of the order before capturing the payment. (It's currently not possible to capture a charge for more than the authorized amount.)

To capture the payment, the merchant must change the order status to processing. As a result, the customer is sent an order processing email, even though the order is automatically switched to FAILED on the order detail screen. 

#### Steps to reproduce the issue

- uncheck "Capture charge immediately" in the stripe payment gateway settings
- create a test order on the front end of the site. Use an email address you own, so you'll receive automated emails from WooCommerce that are related to your order.
- in the order details screen for the test order, increase the quantity of the items purchased, so that the price increases. 
- change the order status from on-hold to processing, to attempt payment capture
- note the failed payment status in the order details
- note order now processing sent to customer's email address

#### Extra Credit

Open up a separate issue to add validation / prevent merchants from attempting capture when the price of an order has increased - or at least let them know ahead of time that it will cause the order to fail if they do. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #916 

The original issue #916 describes a bug that occurs when a charge has been authorized, and the merchant attempts to increase the price of the order before capturing the payment. The order fails when the merchant changes the order status to `processing` after updating the price. Because in Stripe it is not possible to capture a charge for more than the authorized amount. Despite the order failure, the customer receives a order processing email.
 
Though the bug description focuses on the wrong email sent to the customer, my understanding is we should not allow the merchants to update the amount in the corresponding order if the amount has already been authorized (as we know it is definitely going to fail)

## Changes proposed in this Pull Request:
- Not allowing to update the order if the intent has `requires_capture` status (indicating the charge has been authorized)

## Testing instructions

- Enable `Issue an authorization on checkout, and capture later` in the Stripe settings page.
- As a shopper, purchase a product with a card.
- As an admin, go to the order edit page.
- Confirm that the order items are not editable. You can not increase/decrease the number of items, add/remove coupons, update price/tax etc. (anything that would change the total amount)
- You should see `This order is no longer editable` message and the tooltip should explain the reason.

### CODE REVIEW

File: includes/class-wc-stripe-order-handler.php [hunk 1]
```diff
@@ -40,6 +42,77 @@ public static function get_instance() {
...
+			WC_Stripe_Logger::log( 'Error getting intent from order: ' . $e->getMessage() );
+		}
+
+		return $editable;
+	}
+
+	/**
+	 * Only attach the gettext callback when on admin edit order screen
+	 */
+	public static function maybe_attach_gettext_callback() {
```
Comment (Mayisha) [inline includes/class-wc-stripe-order-handler.php:73]: Followed [this](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/admin/class-wc-subscriptions-admin.php#L1848-L1900).

File: includes/class-wc-stripe-order-handler.php [hunk 2]
```diff
@@ -40,6 +42,77 @@ public static function get_instance() {
...
+	}
+
+	/**
+	* When order items are not editable due to the charge being authorized to capture the current amount,
+	* change the tooltip to explain the reason
+	*/
+	public static function change_order_item_editable_text_tooltip( $translated_text, $text, $domain ) {
+		switch ( $text ) {
+			case 'To edit this order change the status back to "Pending payment"':
+				$translated_text = __( 'This order is no longer editable because the charge has been authorized.', 'woocommerce-gateway-stripe' );
```
Comment (Mayisha) [inline includes/class-wc-stripe-order-handler.php]: Please suggest if you can think of a better message.

File: includes/class-wc-stripe-order-handler.php [hunk 3]
```diff
@@ -40,6 +42,77 @@ public static function get_instance() {
...
+			WC_Stripe_Logger::log( 'Error getting intent from order: ' . $e->getMessage() );
+		}
+
+		return $editable;
+	}
+
+	/**
+	 * Only attach the gettext callback when on admin edit order screen.
+	 */
+	public function maybe_attach_gettext_callback() {
```
Comment (Mayisha) [inline includes/class-wc-stripe-order-handler.php:78]: Followed [this](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/admin/class-wc-subscriptions-admin.php#L1848-L1900).

File: includes/class-wc-stripe-order-handler.php [hunk 4]
```diff
@@ -40,6 +42,77 @@ public static function get_instance() {
...
+
+		if ( is_admin() && function_exists( 'get_current_screen' ) ) {
+			$screen = get_current_screen();
+
+			if ( true || ( is_object( $screen ) && in_array( $screen->id, [ 'woocommerce_page_wc-orders', 'edit-shop_order' ], true ) ) ) {
```
Comment (mattallan) [inline includes/class-wc-stripe-order-handler.php]: There's some debug in here and also in `maybe_unattach_gettext_callback()`

File: includes/class-wc-stripe-order-handler.php (hunk 2 above)
Comment (mattallan) [reply includes/class-wc-stripe-order-handler.php]: I think this text is fine.

Another option like "This order is not editable because there's a charge pending authorization for this order total. Cancel the order to remove the authorization."

🤷 Might be a bit long idk.

File: includes/class-wc-stripe-order-handler.php [hunk 5]
```diff
@@ -40,6 +42,77 @@ public static function get_instance() {
...
+	/**
+	 * Disables the ability to edit for orders with uncaptured payment.
+	 *
+	 * @param $editable boolean The current editability of the order.
+	 * @param $order WC_Order The order object.
+	 * @return boolean false if the order has uncaptured payment, true otherwise.
+	 */
+	public function disable_edit_for_uncaptured_orders( $editable, $order ) {
+		try {
+			$intent = $this->get_intent_from_order( $order );
```
Comment (mattallan) [inline includes/class-wc-stripe-order-handler.php:59]: This is probably a minor thing but what are your thoughts on first checking the orders payment method to confirm it's still a Stripe order before we send off a request to Stripe to fetch an intent object?

Something like:

```
if ( ! WC_Stripe_Helper::payment_method_allows_manual_capture( $order->get_payment_method() ) {
    return $editable;
}
```

I was thinking whether it's possible for a customer to first attempt a purchase with Stripe, it fails, it has an intent ID on it, then they fix it up PayPal. Now each time they view this order, we're sending a request off to Stripe to get the intent object when it's not needed.

**Review by mattallan — CHANGES_REQUESTED** [review]
Nice changes @Mayisha ! I agree with the approach you went with by making the totals not editable!

From initial testing this looks good but I left a few comments :)

File: includes/class-wc-stripe-order-handler.php (hunk 5 above)
Comment (Mayisha) [reply includes/class-wc-stripe-order-handler.php:59]: This is a very good catch. Thanks @mattallan.
Fixed in [878eb9d](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3646/commits/878eb9dae1490418ccfbcc5b9ab3aedb262fe6e4)

File: includes/class-wc-stripe-order-handler.php [hunk 6]
```diff
@@ -40,6 +42,80 @@ public static function get_instance() {
...
+
+	/**
+	 * Only attach the gettext callback when on admin edit order screen.
+	 */
+	public function maybe_attach_gettext_callback() {
+
+		if ( is_admin() && function_exists( 'get_current_screen' ) ) {
+			$screen = get_current_screen();
+
+			if ( ( is_object( $screen ) && in_array( $screen->id, [ 'woocommerce_page_wc-orders', 'edit-shop_order' ], true ) ) ) {
```
Comment (mattallan) [inline includes/class-wc-stripe-order-handler.php]: Very minor nit, but there's an extra set of brackets surrounding this whole condition. And same in the `maybe_unattach_gettext_callback()` function

**Review by mattallan — APPROVED** [review]
Thanks @Mayisha ! I've tested the latest changes and just left a small comment which is not blocking.

Approving this one :)

**Comment by aheckler** [comment]
I should have caught this before now, but I just saw this change in the 9.1.0 notes. :/

Frankly, it should be possible for merchants to edit an authorized (but not yet captured) order and then capture it, as long as the total amount they end up capturing is less than or equal to the amount they first authorized. This is called a "partial capture" and it's a totally valid use case. 

You can see how WooPayments handles it [in the docs](https://woocommerce.com/document/woopayments/settings-guide/authorize-and-capture/#partial-captures).

**Comment by danielmx-dev** [comment]
@Mayisha @mattallan We have received feedback from merchants that rely on partial captures in their stores and created the following issue https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3723 As mentioned by Adam, it is a valid use case.

**Comment by Mayisha** [comment]
Thanks @aheckler and @danielmx-dev for flagging this. Working on it 👀
