### PR TITLE
#1208: Move links from action to meta section

### LINKED ISSUE #1208: Move `Docs` and `Support` links from action to meta section
Both, the _Akismet Anti-Spam_, the _Jetpack by WordPress.com_ and the _WooCommerce_ plugin only show the `Settings` and the `Deactivate` link within the action section (below the plugin title). The _WooCommerce Stripe Gateway_ extension, however, shows the `Settings`, the `Docs`, the `Support` and the `Deactivate` link within the action section. Other WooCommerce plugins from us show the `Docs` and the `Support` links within the meta section (in line with the plugin version number).

**To Reproduce**
1. Go to `/wp-admin/plugin-install.php`
2. Install _Akismet Anti-Spam_, _Jetpack by WordPress.com_, _WooCommerce_ and _WooCommerce Stripe Gateway_.
3. Look up links within the action and meta sections.

**Expected behavior**

The  `Docs` and the `Support` links should be shown within the meta section (in line with the plugin version number).

**Screenshots**

Screenshot 2020-05-20 at 17 35 49

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #1208.

#### Changes proposed in this Pull Request:

- Update - Move `Docs` and `Support` links on plugin page from action section (below plugin title) to meta section (inline with plugin version number).

**Before:**

#1208-before

**After:**

#1208-after

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by roykho** [comment]
Hi @nielslange - It is best to ask the team that handles this extension for review.

**Comment by nielslange** [comment]
> Hi @nielslange - It is best to ask the team that handles this extension for review.

Thanks for pointing this out, @roykho. I've added you based on GitHub's suggestion. It won't happen again. 😀

File: woocommerce-gateway-stripe.php [hunk 1]
```diff
@@ -205,20 +206,37 @@ public function install() {
...
-					'<a href="https://docs.woocommerce.com/document/stripe/">' . esc_html__( 'Docs', 'woocommerce-gateway-stripe' ) . '</a>',
-					'<a href="https://woocommerce.com/my-account/create-a-ticket?broken=primary&select=18627">' . esc_html__( 'Support', 'woocommerce-gateway-stripe' ) . '</a>',
 				);
 				return array_merge( $plugin_links, $links );
 			}
 
+			/**
+			 * Add plugin action links.
+			 *
+			 * @since 4.x
```
Comment (dwainm) [inline woocommerce-gateway-stripe.php:224]: `@since 4.3.4`

**Comment by dwainm** [comment]
Thank you for the PR @nielslange!
