### PR TITLE
Fix error message translation for intent creation errors

### LINKED ISSUE #4885: Error messages not translated
### Description

I have an issue with the error messages corresponding to the "There was an error processing the payment:" error.<br>In my shop, the messages after that are not being translated and are instead being displayed in english.

### Steps to reproduce

1. Add a product to the cart.
2. Go to the checkout.
3. Use any of the declined card numbers for testing: [https://docs.stripe.com/testing#declined-payments](<https://docs.stripe.com/testing#declined-payments>)

### Expected behavior

The full message "There was an error processing the payment: Detailed message." is translated (in my case to german).<br>While looking for ways to find the translation and translating it in wpml I checked the plugin code and in the "wc_stripe_localized_messages" filter "expired_card" is defined as "The card has expired." instead of the error message I see for this error "Your card has expired". So it seems like it could be a similiar issue to: [https://github.com/woocommerce/woocommerce-gateway-stripe/issues/438](<https://github.com/woocommerce/woocommerce-gateway-stripe/issues/438>).

### Screenshots

Image

### System report

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 10.4.2
Legacy REST API Package Version: Auf dieser Website ist das alte REST-API-Plugin nicht installiert.
Action Scheduler Version: ✔ 3.9.3
Log Directory Writable: ✔
WP Version: ❌ 6.8.3 - Es ist eine neuere Version von WordPress verfügbar (6.9)
WP Multisite: –
WP Memory Limit: 3 GB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
Server Architecture: Linux 5.14.0-503.40.1.el9_5.x86_64 x86_64
PHP Version: 8.3.20
PHP Post Max Size: 3 GB
PHP Time Limit: 480
PHP Max Input Vars: 5000
cURL Version: 8.13.0
OpenSSL/3.2.2

SUHOSIN Installed: –
MySQL Version: 11.8.3-MariaDB-log
Max Upload Size: 3 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 15
acf-field-group: 5
attachment: 738
custom_css: 1
elementor_library: 22
elementor_snippet: 8
language_switcher: 4
nav_menu_item: 394
oembed_cache: 2
page: 44
portfolio: 8
post: 2
product: 98
product_variation: 42
revision: 94
shop_coupon: 1
shop_order_placehold: 281
team: 4
wp_global_styles: 1
wp_navigation: 1
wpclv: 1
yaymail_template: 16

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (42) ###

Advanced Custom Fields Multilingual: von OnTheGoSystems – 2.1.5
Admin and Site Enhancements (ASE): von wpase.com – 8.1.2
Advanced Custom Fields PRO: von WP Engine – 6.7.0.2
Borlabs Cookie: von Borlabs GmbH – 3.3.22
Elementor Pro: von Elementor.com – 3.33.2
Elementor: von Elementor.com – 3.33.6
Envato Market: von Envato – 2.0.12
F4 Salutation Fields for WooCommerce: von FAKTOR VIER – 1.0.20
FacetWP - Cache: von FacetWP
LLC – 1.7.1

FacetWP - Color: von FacetWP
LLC – 1.7.1

FacetWP - Elementor: von FacetWP
LLC – 1.9.3

FacetWP - Multilingual support: von FacetWP
LLC – 1.0.1

FacetWP - Relevanssi integration: von FacetWP
LLC – 0.8.2

FacetWP: von FacetWP
LLC – 4.4.1

FluentSMTP: von FluentSMTP & WPManageNinja Team – 2.2.92
Index WP MySQL For Speed: von Oliver Jones
Rick James – 1.5.6

LiteSpeed Cache: von LiteSpeed Technologies – 7.7
Local Google Fonts: von EverPress – 0.24.0
Mailchimp for WooCommerce: von Mailchimp – 5.6
MainWP Child: von MainWP – 5.4.1
Savoy Theme - Content Elements: von NordicMade – 1.8.1
Savoy Theme - Settings Panel: von NordicMade – 1.2.7
Savoy Theme - Wishlist: von NordicMade – 2.5
Relevanssi: von Mikko Saari – 4.26.0
Rank Math SEO: von Rank Math SEO – 1.0.260
WPML Multilingual CMS: von OnTheGoSystems – 4.7.6
SQLite Object Cache: von Oliver Jones – 1.6.0
Password Strength Settings for WooCommerce: von Daniel Santoro – 3.0.1
Converter for Media: von matt plugins – 6.4.0
Force Authentification Before Checkout for WooCommerce: von Luiz Bills – 1.4.5
WooCommerce.com Update Manager: von Automattic – 1.0.3
WooCommerce AJAX Cart: von Moises Heberle – 1.3.25
WooCommerce Stripe-Gateway: von Stripe – 10.2.0
German Market: von MarketPress – 3.50
WooCommerce Multilingual & Multicurrency: von OnTheGoSystems – 5.5.1
WooCommerce: von Automattic – 10.4.2
WP Migrate: von WP Engine – 2.7.7
WPML SEO: von OnTheGoSystems – 2.1.1
WPC Linked Variation for WooCommerce: von WPClever – 4.3.8
WPML Media Translation: von OnTheGoSystems – 2.7.7
Wpml String Übersetzung: von Onthegosysteme – 3.3.3
YayMail - WooCommerce Email Customizer: von YayCommerce – 4.3.2

### Inactive Plugins (2) ###

DHL Shipping Germany for WooCommerce: von DHL – 3.9.7
WP-Optimize - Clean, Compress, Cache: von TeamUpdraft
DavidAnderson – 4.4.0


### Dropin Plugins () ###

object-cache.php: SQLite Object Cache (Drop-in)

### Must Use Plugins (3) ###

Hostinger Smart Auto Updates: von Hostinger – 1.0.7
Index WP MySQL For Speed Upgrade Filter for mu-plugins.: von  – 1.5.2
WP Migrate Compatibility: von Delicious Brains – 1.3

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
blueprint
point_of_sale
custom_order_tables


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 Tage
Level threshold: –
Log directory size: 4 MB

### WC Pages ###

Shop-Basis: #9 - /shop/
Warenkorb: #10 - /cart/ -  Enthält den [woocommerce_cart]-Shortcode
Kasse: #11 - /checkout/ -  Enthält den [woocommerce_checkout]-Shortcode
Mein Konto: #12 - /my-account/ -  Enthält den [woocommerce_my_account]-Shortcode
Allgemeine Geschäftsbedingungen: #7569 - /agb/

### Theme ###

Name: Savoy Child
Version: 1.0
Author URL: http://www.nordicmade.com
Child Theme: ✔
Parent Theme Name: Savoy
Parent Theme Version: 3.1.3
Parent Theme Author URL: http://www.nordicmade.com
Theme type: Classic-Theme
WooCommerce Support: ✔

### Templates ###

Overrides: savoy/woocommerce/archive-product.php
savoy/woocommerce/cart/cart-empty.php
savoy/woocommerce/cart/cart-item-data.php
savoy/woocommerce/cart/cart-shipping.php
savoy/woocommerce/cart/cart-totals.php
savoy/woocommerce/cart/cart.php
savoy/woocommerce/cart/cross-sells.php
savoy-child/woocommerce/cart/mini-cart.php
savoy/woocommerce/cart/proceed-to-checkout-button.php
savoy/woocommerce/cart/shipping-calculator.php
savoy/woocommerce/checkout/cart-errors.php
savoy/woocommerce/checkout/form-billing.php
savoy/woocommerce/checkout/form-checkout.php
savoy/woocommerce/checkout/form-coupon.php
savoy/woocommerce/checkout/form-login.php
savoy/woocommerce/checkout/form-pay.php
savoy/woocommerce/checkout/form-shipping.php
savoy/woocommerce/checkout/order-received.php
savoy/woocommerce/checkout/payment-method.php
savoy/woocommerce/checkout/payment.php
savoy/woocommerce/checkout/review-order.php
savoy/woocommerce/checkout/terms.php
savoy/woocommerce/checkout/thankyou.php
savoy/woocommerce/content-product.php
savoy/woocommerce/content-single-product.php
savoy/woocommerce/content-widget-price-filter.php
savoy/woocommerce/content-widget-product.php
savoy/woocommerce/content-widget-reviews.php
savoy/woocommerce/global/breadcrumb.php
savoy/woocommerce/global/form-login.php
savoy/woocommerce/global/quantity-input.php
savoy/woocommerce/global/sidebar.php
savoy/woocommerce/global/wrapper-end.php
savoy/woocommerce/global/wrapper-start.php
savoy/woocommerce/loop/add-to-cart.php
savoy/woocommerce/loop/loop-end.php
savoy/woocommerce/loop/loop-start.php
savoy/woocommerce/loop/no-products-found.php
savoy/woocommerce/loop/pagination.php
savoy/woocommerce/loop/price.php
savoy/woocommerce/loop/rating.php
savoy/woocommerce/loop/result-count.php
savoy/woocommerce/loop/sale-flash.php
savoy/woocommerce/myaccount/dashboard.php
savoy/woocommerce/myaccount/form-add-payment-method.php
savoy/woocommerce/myaccount/form-edit-account.php
savoy/woocommerce/myaccount/form-edit-address.php
savoy-child/woocommerce/myaccount/form-login.php Version 9.2.0 ist veraltet. Die Hauptversion ist 9.9.0
savoy/woocommerce/myaccount/form-lost-password.php
savoy/woocommerce/myaccount/form-reset-password.php
savoy/woocommerce/myaccount/lost-password-confirmation.php
savoy/woocommerce/myaccount/my-account.php
savoy/woocommerce/myaccount/my-address.php
savoy/woocommerce/myaccount/navigation.php
savoy/woocommerce/myaccount/orders.php
savoy/woocommerce/myaccount/view-order.php
savoy/woocommerce/notices/error.php
savoy/woocommerce/notices/notice.php
savoy/woocommerce/notices/success.php
savoy/woocommerce/order/form-tracking.php
savoy/woocommerce/order/order-again.php
savoy/woocommerce/order/order-details-customer.php
savoy/woocommerce/order/order-details-item.php
savoy-child/woocommerce/order/order-details.php
savoy/woocommerce/order/tracking.php
savoy/woocommerce/product-searchform.php
savoy/woocommerce/single-product/add-to-cart/external.php
savoy-child/woocommerce/single-product/add-to-cart/grouped.php Version 7.0.1 ist veraltet. Die Hauptversion ist 10.2.0
savoy/woocommerce/single-product/add-to-cart/simple.php
savoy/woocommerce/single-product/add-to-cart/variable.php
savoy/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
savoy/woocommerce/single-product/add-to-cart/variation.php
savoy/woocommerce/single-product/meta.php
savoy/woocommerce/single-product/photoswipe.php
savoy/woocommerce/single-product/price.php
savoy-child/woocommerce/single-product/product-attributes.php
savoy/woocommerce/single-product/product-image.php
savoy/woocommerce/single-product/product-thumbnails.php
savoy/woocommerce/single-product/rating.php
savoy-child/woocommerce/single-product/related.php Version 3.9.0 ist veraltet. Die Hauptversion ist 10.3.0
savoy/woocommerce/single-product/review-meta.php
savoy/woocommerce/single-product/review-rating.php
savoy/woocommerce/single-product/review.php
savoy/woocommerce/single-product/sale-flash.php
savoy/woocommerce/single-product/share.php
savoy/woocommerce/single-product/short-description.php
savoy/woocommerce/single-product/stock.php
savoy/woocommerce/single-product/tabs/additional-information.php
savoy/woocommerce/single-product/tabs/description.php
savoy/woocommerce/single-product/tabs/tabs.php
savoy-child/woocommerce/single-product/title.php
savoy-child/woocommerce/single-product/up-sells.php
savoy/woocommerce/single-product-reviews.php
savoy/woocommerce/single-product.php
savoy/woocommerce/taxonomy-product-cat.php
savoy/woocommerce/taxonomy-product-tag.php
savoy/woocommerce/content-product_cat.php

Outdated Templates: ❌
					
					
						Erfahre
wie du aktualisieren kannst					 |
					
						
					
					
						Cache mit Systemstatus-Theme-Informationen leeren


### WooCommerce Stripe Payment Gateway ###

Version: 10.2.0
Account ID: acct_1L0QC5FaXBMX3Amr
Test Mode Enabled: Ja
OAuth Connected: ✔
					Ja
Sync Enabled: ✔
					Ja
Optimized Checkout Enabled: Nein
Enabled Payment Methods: card
Express Checkout: ✔
					Deaktiviert
Auth and Capture: ✔
					Ja
Logging: ✔
					Ja

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
experimental-iapi-mini-cart
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
experimental-iapi-runtime
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
products-catalog-api
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
rest-api-v4

Daily Cron: ✔ Next scheduled: 2025-12-21 12:02:11 +00:00
Options: ✔
Notes: 53
Onboarding: completed

### Action Scheduler ###

Abgebrochen: 1
Oldest: -0001-11-30 00:00:00 +0000
Newest: -0001-11-30 00:00:00 +0000

Abgeschlossen: 1.330
Oldest: 2025-11-20 10:40:39 +0000
Newest: 2025-12-20 21:53:07 +0000

Fehlgeschlagen: 106
Oldest: 2022-09-25 14:52:41 +0000
Newest: 2025-09-11 15:03:17 +0000

Ausstehend: 15
Oldest: 2025-12-20 22:01:38 +0000
Newest: 2025-12-27 01:21:09 +0000


### Status report information ###

Generated at: 2025-12-20 22:01:42 +00:00
```

</details>

### PR DESCRIPTION
**Pull request by daledupreez**
Fixes STRIPE-861
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4885

## Changes proposed in this Pull Request:

This PR implements three core changes:
 * It refactors the logic in `WC_Stripe_Payment_Gateway->get_localized_error_message_from_response()` into a static helper method in `WC_Stripe_Helper::get_localized_error_message_from_response()`
 * It updates the error handling in `WC_Stripe_UPE_Payment_Gateway->get_payment_intent_error_message()` to call the new helper method to see if we can translate the returned error.
 * The PR also refactors some other code locations that were replicating the logic in `get_localized_error_message_from_response()` to now call the new helper method.

## Testing instructions

 * Set up a WooCommerce store using a non-English locale like German and/or set up a user with German access
    - The language should have the strings from `WC_Stripe_Helper::get_localized_messages()` translated -- you can check the status via https://translate.wordpress.org/projects/wp-plugins/woocommerce-gateway-stripe/, but German has most of them translated (if not all of them)
 * Ensure that you have the German translations available and installed
    - In my case, I downloaded the German MO file from https://translate.wordpress.org/projects/wp-plugins/woocommerce-gateway-stripe/stable/de/default/ via the Export option at the bottom of the page, and then copied the downloaded file into the `languages` subfolder in my Stripe plugin
 * Connect the plugin to Stripe, and ensure that card transactions are enabled
 * To start with, ensure that Optimised Checkout is disabled
 * Add a product to your cart, and navigate to checkout
 * Ensure that you're seeing the UI in your non-English language
 * Use any of the cards from https://docs.stripe.com/testing#declined-payments to make the purchase
 * Confirm that you see the partially untranslated error message
 * Now enable Optimized Checkout, and retry
 * Confirm that you still see the partially untranslated error message
 * Now switch to this branch
 * Try to check out using one of the cards from the link above that will fail
 * Confirm that you get a fully translated error message
 * Now disable Optimized Checkout
 * Try to check out using one of the cards from the link above that will fail
 * Confirm that you get a fully translated error message

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [N/A] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/class-wc-stripe-helper.php [hunk 1]
```diff
@@ -304,6 +304,33 @@ public static function get_localized_messages() {
...
+
+			return $response->error->message;
+		}
+
+		if ( isset( $localized_messages[ $response->error->type ] ) ) {
+			return $localized_messages[ $response->error->type ];
+		}
+
+		return $response->error->message;
+	}
```
[the remark this answers is not in the document]
Comment (daledupreez) [reply includes/class-wc-stripe-helper.php:348]: Tests added in 492b9b8defc208edb7b501432d5315c58464943c.

[the remark this answers is not in the document]
Comment (daledupreez) [reply includes/class-wc-stripe-helper.php:348]: Defensive code and tests added in 3e30be5872a297272cccd4e0d318ea16db6f79cb.

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 2]
```diff
@@ -466,17 +466,13 @@ public function process_subscription_payment( $amount, $renewal_order, $retry =
 					}
 				}
 
-				$localized_messages = WC_Stripe_Helper::get_localized_messages();
-
-				if ( 'card_error' === $response->error->type ) {
-					$localized_message = isset( $localized_messages[ $response->error->code ] ) ? $localized_messages[ $response->error->code ] : $response->error->message;
-				} elseif ( 'payment_intent_mandate_invalid' === $response->error->type ) {
+				if ( 'payment_intent_mandate_invalid' === $response->error->type ) {
```
Comment (wjrosa) [inline includes/compat/trait-wc-stripe-subscriptions.php:469]: We should consider create new constants for these error codes later

File: includes/class-wc-stripe-helper.php [hunk 3]
```diff
@@ -304,6 +304,42 @@ public static function get_localized_messages() {
...
```
Comment (wjrosa) [inline includes/class-wc-stripe-helper.php:348]: Simplified version by Copilot:
```suggestion
public static function get_localized_error_message_from_response( $response ) {
    // Validate the response object structure.
    if ( ! is_object( $response ) || ! isset( $response->error ) ) {
        return '';
    }

    $error = $response->error;
    $localized_messages = self::get_localized_messages();

    // Check for localized messages based on the error type or code.
    if ( isset( $error->code, $localized_messages[ $error->code ] ) ) {
        return $localized_messages[ $error->code ];
    }

    if ( isset( $error->type, $localized_messages[ $error->type ] ) ) {
        return $localized_messages[ $error->type ];
    }

    // Fallback to the default error message, if present.
    return isset( $error->message ) ? $error->message : '';
}
```

**Review by wjrosa — APPROVED** [review]
Nice work! Looks good to me. Left an optional suggestion + a comment regarding constants

File: includes/class-wc-stripe-helper.php (hunk 3 above)
Comment (daledupreez) [reply includes/class-wc-stripe-helper.php:348]: Those proposed changes result in functional logic changes. In particular, the existing code only looks up `$error->code` when `$error->type === 'card_error'`, while this proposal would _always_ use `$error->code` as the index. In most cases, that should be fine, but I don't know the set of (type, code) tuples well enough to know that we won't see unexpected collisions.

Comment (daledupreez) [reply includes/class-wc-stripe-helper.php:348]: But I do agree that some simplification would be a good thing! I'll take that one shortly.

Comment (daledupreez) [reply includes/class-wc-stripe-helper.php:348]: Done in d9bfbee131a1ab28d5ab79072795f0f252744bad. It doesn't quite use the suggested logic, but it does rely on the local `$error` property, and it also computes a `$fallback_message` variable so we can guard against unexpected `$error->message` values and only check `$error->message` once.

Comment (wjrosa) [reply includes/class-wc-stripe-helper.php:348]: Thanks, Dale. It does look better. Personally, I would replace some of the `isset` checks with `??`, to reduce the code a bit more, but it is totally fine this way.

File: includes/compat/trait-wc-stripe-subscriptions.php (hunk 2 above)
Comment (Mayisha) [inline includes/compat/trait-wc-stripe-subscriptions.php:469]: Shall we include `payment_intent_mandate_invalid` in the `get_localized_messages`? As we have the following fallback in the `get_localized_error_message_from_response` helper method?

```
if ( isset( $localized_messages[ $error->type ] ) ) {
			return $localized_messages[ $error->type ];
		}
```

**Review by Mayisha — APPROVED** [review]
Code looks good to me. However, I see the error message as the following screenshot 🤔 

Screenshot 2025-12-25 at 5 24 04 PM

File: includes/compat/trait-wc-stripe-subscriptions.php (hunk 2 above)
Comment (daledupreez) [reply includes/compat/trait-wc-stripe-subscriptions.php:469]: The specific error text here only applies within this specific context, i.e. when we are processing a subscription renewal. If we push that into the general-purpose messages, we could end up with this message showing in contexts where we would not want it to.

Comment (daledupreez) [reply includes/compat/trait-wc-stripe-subscriptions.php:469]: Good idea: tracked in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4895 / STRIPE-868.

**Comment by daledupreez** [comment]
> Code looks good to me. However, I see the error message as the following screenshot 🤔

@Mayisha, that is really weird, as it looks like that value should be translated as part of the plugin code here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/a275befd12562d78f2d71997426d8e6fb16024a0/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L1324

I am not sure how/why that translation could have ended up missing.

**Review by Mayisha — APPROVED** [review]
The missing translation I was seeing is not part of the changes made in this PR. Changes here look good and are working as described 👍

**Comment by daledupreez** [comment]
Merging as e2e errors are all for ACH and have been happening outside of this PR.
