### PR TITLE
Move Alipay and Multibanco inside Stripe settings when UPE is enabled

### LINKED ISSUE #2852: Move Alipay and Multibanco inside Stripe settings
In PR #2839 all the Stripe methods were moved inside the Stripe settings page and the interface was updated as a common settings page for both UPE and non-UPE. However, for non-UPE scenario, Stripe Alipay and Stripe Multibanco was not moved and they are still listed on the payment settings page. 

#### Steps to reproduce the issue
- Go to Stripe settings page and disable UPE.
- You will find that Alipay and Multibanco are not listed in the Stripe settings page.
- Go to WooCommerce > Settings > Payments. You will find the methods listed here.

#### Expected behavior
- Alipay and Multibanco should be listed in the Stripe settings page with the other Stripe methods.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #2852 

## Changes proposed in this Pull Request:
- Alipay and Multibanco are moved inside the Stripe settings page for UPE enabled state.

**Before**

image

**After**

- On checkout page, Alipay is now rendered as an UPE method. As Multibanco does not use Payments API of Stripe (uses the Stripe Sources API), it can not be rendered as an UPE method. 

**Alipay on checkout page**

**Multibanco on checkout page**

## Testing instructions
- Go to the Stripe settings page and enable UPE.
- Go to the Payment Methods tab on the Stripe settings page. Alipay and Multibanco should be listed here. ( You may not see them on the list as their capabilities are not set by default as per the document https://stripe.com/docs/connect/account-capabilities#payment-methods. You have to activate them from the Stripe dashboard. As I don't have an activated account and could not activate Alipay and Multibanco I tweaked the capabilities [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/892d8a3d7bc2f7a6a705cd0701295e4c4a411b51/client/settings/general-settings-section/payment-methods-list.js#L170) to make them appear in the list).
- Enable/Disable these 2 methods and make sure they are available on the checkout page as per settings.
- Alipay should be rendered as an UPE method, Multibanco should be rendered as a separate payment method as before.
- Purchasing with Alipay and Multibanco should work without errors.

### Note (ToDo)
Multibanco has been moved inside the same Stripe settings page when UPE is enabled but it can not be used as an UPE method at this moment because of using Sources API. When Stripe starts supporting Multibanco with Payments API and it can be moved inside as an UPE method, we should revert the Multibanco specific changes of this PR and create a new UPE class for Multibanco.

### CODE REVIEW

File: includes/admin/class-wc-rest-stripe-payment-gateway-controller.php [hunk 1]
```diff
@@ -1,175 +0,0 @@
...
-		$description = $request->get_param( $field_name );
-
-		if ( null === $description ) {
-			return;
-		}
-
-		$value = sanitize_text_field( $description );
-		$this->gateway->update_option( 'description', $value );
-	}
-}
```
Comment (Mayisha) [inline includes/admin/class-wc-rest-stripe-payment-gateway-controller.php:175]: As all the methods are moved inside Stripe settings page, this separate page for the individual methods is not needed anymore. 

separate


So deleting the controller and relevant tests. Also the tests started to fail as we are not registering any payment method for the payment settings page.

File: includes/class-wc-stripe-helper.php [hunk 2]
```diff
@@ -545,6 +545,41 @@ public static function get_legacy_individual_payment_method_settings() {
...
+		// Multibanco is a non UPE method that uses Stripe sources. Adding to the list if it's enabled
+		// to show it in the Stripe settings page.
+		$multibanco = new WC_Gateway_Stripe_Multibanco();
+		if ( $multibanco->is_enabled() ) {
+			$enabled_gateways[] = 'multibanco';
+		}
+
+		return $enabled_gateways;
+	}
+
```
Comment (Mayisha) [inline includes/class-wc-stripe-helper.php:582]: These helper methods are temporarily added to include Multibanco to the list so that it appears on the Stripe settings page. When Stripe starts supporting Multibanco and we create a new UPE class for Multibanco, these methods won't be needed anymore.

File: includes/payment-methods/class-wc-stripe-upe-payment-method-alipay.php [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+		);
+	}
+
+	/**
+	 * Returns the currencies this UPE method supports for the Stripe account.
+	 * Documentation: https://stripe.com/docs/payments/alipay#supported-currencies.
+	 *
+	 * @return array
+	 */
+	public function get_supported_currencies() {
```
Comment (Mayisha) [inline includes/payment-methods/class-wc-stripe-upe-payment-method-alipay.php:49]: As I moved Alipay inside UPE, I was getting an error on the checkout page when I was using an `US` Stripe account with store currency set as `EURO`. Also the UPE payment methods failed to render on the page because of this error.

error alipay
 
As per my understanding after reading https://stripe.com/docs/payments/alipay#supported-currencies that says `You can create Alipay payments in the currencies that map to your country` I have created this mapping function that returns the supported currency list based on the Stripe account's country. 

Now on the settings page also when UPE is enabled, if your Stripe account is a US account but WC store currency is Euro, it will show Alipay as unsupported for currency.

To the reviewer: please check if my assumption is correct here.

File: includes/class-wc-stripe-helper.php (hunk 2 above)
Comment (mattallan) [reply includes/class-wc-stripe-helper.php:582]: Makes sense! Thanks for the explanation :)

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 4]
```diff
@@ -395,6 +424,7 @@ public function get_upe_enabled_payment_method_ids() {
 	public function get_upe_enabled_at_checkout_payment_method_ids( $order_id = null ) {
 		$is_automatic_capture_enabled = $this->is_automatic_capture_enabled();
 		$available_method_ids         = [];
+		WC_Stripe_Logger::log( 'get_upe_enabled_at_checkout_payment_method_ids---' );
```
Comment (mattallan) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Just checking if this code is intentional, or is this debugging code that accidentally made it into the PR? 😅

There's a few more instances of WC_Stripe_Logger::log() used below this one as well.

File: client/payment-methods-map.js [hunk 5]
```diff
@@ -12,6 +12,92 @@ import OxxoIcon from './payment-method-icons/oxxo';
...
+		'GBP',
+		'HKD',
+		'JPY',
+		'MYR',
+		'NZD',
+		'USD',
+	];
+
+	// cached_account_data = WC_Stripe::get_instance()->account->get_cached_account_data();
+	const country = 'US'; //cached_account_data['country'] ?? null;
```
Comment (mattallan) [inline client/payment-methods-map.js]: I'm assuming this was hardcoded to 'US' for testing?

**Review by mattallan — COMMENTED** [review]
Hey Mayisha! I've left some minor feedback from code review but I've been having trouble getting Alipay to show up in the payment method list.

When I enable UPE this is what I see:
image

From my Stripe dashboard, I can see that Alipay is active/enabled: 
image

When I disable UPE I can see Alipay: image

I noticed you said you had to modify the capabilities, but since I have Alipay enabled, I wanted to double-check there's not a bug that is causing this 🤔

File: client/payment-methods-map.js (hunk 5 above)
Comment (Mayisha) [reply client/payment-methods-map.js]: Yup this was for testing. I will fix it :sweat_smile:

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php (hunk 4 above)
Comment (Mayisha) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: :woman_facepalming:

File: client/utils/use-alipay-currencies.js [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+			'HKD',
+			'JPY',
+			'MYR',
+			'NZD',
+			'USD',
+		];
+	}
+
+	switch ( data?.account?.country ) {
+		case 'AUS':
```
Comment (mattallan) [inline client/utils/use-alipay-currencies.js]: I couldn't enable AliPay on my stripe account even though it had a supported currency (i.e. AUD) and I found out the issue is with this mapping function. My AUS Stripe account has the data.account.country value set to `AU` not `AUS`, I also connected a Canadian account and the data.account.country was `CA`, not `Canada`.

Has something changed since we populated this switch statement and do we need to update these switch cases to use the country codes instead?

From my testing the following account.country values need to be updated:
- `AUS` -> `AU`
- `Canada` -> `CA`
- `HongKong` -> `HK`
- `Japan` -> `JP`
- `Malaysia` -> `MY`
- `Singapore` -> `SG`

Comment (Mayisha) [reply client/utils/use-alipay-currencies.js]: It was a silly mistake on my end. I used country code for some and full country name for some cases :woman_facepalming: 

Thanks @mattallan. Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2870/commits/686f6c8d119b0f87e2a9a364eb9ef3c5e85ebb2e

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 7]
```diff
@@ -166,6 +167,34 @@ public function __construct() {
...
+	 *
+	 * @param WC_Payment_Gateway[] $gateways A list of all available gateways on the payments settings page.
+	 * @return WC_Payment_Gateway[]          The same list if Multibanco is disabled or a list including the Multibanco method.
+	 */
+	public function get_available_payment_gateways( $gateways ) {
+		$stripe_index          = array_search( 'stripe', array_keys( $gateways ), true );
+		$gateways_upto_stripe  = array_slice( $gateways, 0, $stripe_index + 1 );
+		$gateways_after_stripe = array_slice( $gateways, $stripe_index + 1 );
+
+		$multibanco_gateway = new WC_Gateway_Stripe_Multibanco();
```
Comment (mattallan) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Instantiating a new instance of the Multibanco class here is causing all of the hooks inside the __construct to be registered multiple times, causing things like this on the thank-you page and probably other issues: 
image

**Review by mattallan — CHANGES_REQUESTED** [review]
Thanks @Mayisha for all of your work on this PR!! 💯 

- [x] Alipay and Multibanco now part of the payment methods list within Stripe Settings.
- [x] Confirmed Alipay now part of the UPE on checkout
  - [x] tested purchasing with Alipay on both shortcode and block checkouts 👍 
- [x] Confirmed Multibanco is not part of the UPE
  - [ ] tested purchasing with multibanco checkout :x:

I'm noticing a couple of issues while testing Multibanco when comparing things to `develop`.

- On Edit Order page the "Payment via " is display payment method instead of the expected title

I had a quick look into this and couldn't find the cause. I'm thinking maybe it has something to do with the multibanco class missing a `get_title()` function?

| `develop` | this branch |
|--------|--------|
|image|image| 

- Order thankyou page instructions are being duplicated

This is being caused by multiple instances of `WC_Gateway_Stripe_Multibanco` being instantiated. I left a comment below with which code I think it's coming from.

| `develop` | this branch |
|--------|--------|
|image|image|

**Comment by Mayisha** [comment]
Thanks @mattallan for the thorough review and for finding the issues. :+1: 

> On Edit Order page the "Payment via " is display payment method instead of the expected title

As we found this issue to be present in `develop` and also for non-UPE settings, I would like to handle this as a separate issue.

> Order thankyou page instructions are being duplicated

I have removed the Multibanco instantiation in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2870/commits/ddc8d7052041fff48f0bf0ba03bf98e426988b0c and now using the instance from the helper method.

**Review by mattallan — APPROVED** [review]
Thanks @Mayisha! I've tested the latest changes and didn't find any issues! 💯
Code also looks good to me :)

Time to ship it!!
