### PR TITLE
Prevent WooCommerce's hold stock setting from canceling pending orders which are waiting for a customer action

### LINKED ISSUE #1756: Payment not recorded in WC for 3DS transaction if completion takes longer than hold stock value
**Describe the bug**
When using a card that's 3D secure, if a customer takes longer than the value of hold stock to `Complete Authentication` in the Stripe pop-up then the payment is successful and they are taken to an order confirmation screen, however, the order in WC will show as canceled and not have a record of the Stripe transaction.

**To Reproduce**
1. Set `hold stock` to 1 minute
2. Create a test simple product
3. Place an order using a 3DS card
4. Wait for more than 1 minute before clicking on `Complete Authentication`
5. See order details in WP Admin

**Expected behavior**
I would expect that the order would display in WooCommerce as processing as payment was successfully received

**Environment (please complete the following information):**
 - WordPress Version: 5.8
 - WooCommerce Version: 5.6
 - Stripe Plugin Version: 5.4
 - Browser: Chrome 92.0.4515.159. Also tested in FireFox with same results, assuming the browser is irrelevant
 - Any other plugins installed: No

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #1756 

## Changes proposed in this Pull Request:

WooCommerce has a **hold stock** setting that cancels all pending orders after x minutes which is useful for returning stock quantities for abandoned carts/orders.
This has a negative side-effect for orders purchased with Stripe where the payment is waiting for the customer or Stripe to process the payment/webhook; this is especially a problem on stores that have a very short amount of minutes set to hold stock (i.e. can be as short as one minute).

image

When a store has one minute hold stock setting, what can happen is customers can checkout using either a 3D secure card or an alternative payment method (APM) that requires redirect and while they're confirming the order or processing the payment, the hold stock query could run and cancel their order.

This leaves the order as paid on Stripe's end, but cancelled in WooCommerce 👎 

### Solution

In this PR, I'm fixing this problem by using the `woocommerce_cancel_unpaid_order` filter which allows 3rd party code to filter out individual orders from being cancelled by the hold stock setting.

To identify which orders shouldn't be cancelled, I'm adding `_stripe_payment_awaiting_action` meta data to all orders with intents that respond with `requires_action` or `requires_confirmation` and then when the confirmation or redirect has been processed or failed, I'm removing the meta.

On the `woocommerce_cancel_unpaid_order` filter, I've also added some additional logic so that if the order is still pending after one day, we should just assume that it's been abandoned and cancel it.

> [!IMPORTANT]  
> Using metadata like this isn't ideal, so another approach I considered was instead of adding and removing metadata from the order, what if we just check if the pending order is stripe and it has an intent ID saved on it, if so, don't cancel it.
>
> The assumption with this approach is that stripe orders that are still pending and have payment/setup intent ID saved would most likely mean it's still processing the payment or waiting for customer action, so don't cancel it.
>
> Curious to hear others thoughts on this 🙂

## Testing instructions

**Initial setup**
- Go **WooCommerce > Settings > Products > Inventory** and set the Hold stock setting to 1 (minute)
- Install a plugin that lets you run snippets of code (I use WP Console). This is how I'll be manually triggering the `woocommerce_cancel_unpaid_orders` WP cron event. Alternatively you could install WP Crontrol and manually trigger it.

**Instructions**
1. Checkout this branch.
2. Add a regular WC Product to your cart and purchase it through the shortcode or block checkout using a 3DS test card (`4000002760003184`)
1. When you're presented with the 3DS window keep this open and open a new tab and go to your test store > WooCommerce > Orders note the new pending order ID.
3. Open the `wp_wc_orders_meta` database table and search for the order ID.
4. Confirm the new `_stripe_payment_awaiting_action` metadata is present and set to 'yes'
5. Wait a minute if it hasn't been a minute since purchasing the order.
6. Open up WP Console and manually trigger `do_action( 'woocommerce_cancel_unpaid_orders' );` to run WooCommerce cancel unpaid orders query.
7. Visit **WooCommerce > Orders** and confirm the pending order is still pending and hasn't been cancelled.
8. Go back to the checkout window which should still have the 3DS pop-up and complete the authentication.
9. Go back to the database and confirm `_stripe_payment_awaiting_action` metadata has been removed and confirm the order is processing.

While running through the same steps on `develop` branch, you will notice when you get to step 7, the order will be cancelled.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/class-wc-gateway-stripe.php [hunk 1]
```diff
@@ -456,6 +456,10 @@ public function process_payment( $order_id, $retry = true, $force_save_source =
 				if ( 'requires_action' === $intent->status ) {
 					$this->unlock_order_payment( $order );
 
+					// If the order requires some action from the customer, add meta to the order to prevent it from being cancelled by WooCommerce's hold stock settings.
```
Comment (wjrosa) [inline includes/class-wc-gateway-stripe.php:458]: Can we move this to a new helper method? Since it is being used twice

File: includes/class-wc-gateway-stripe.php [hunk 2]
```diff
@@ -915,6 +919,13 @@ public function verify_intent_after_checkout( $order ) {
 		}
 
 		$this->unlock_order_payment( $order );
+
```
Comment (wjrosa) [inline includes/class-wc-gateway-stripe.php:920]: Same as my previous comment.

**Review by wjrosa — APPROVED** [review]
Awesome work! Left some minor comments. I would also consider adding a test for this.

As for your concern, I don't see a big issue with using metas. I don't think the impact on the DB will be big.

Test results:

- New meta:
Screenshot 2024-04-05 at 11 42 15

- Order still pending after cancellation was triggered:
Screenshot 2024-04-05 at 11 47 37

File: includes/class-wc-gateway-stripe.php (hunk 1 above)
Comment (mattallan) [reply includes/class-wc-gateway-stripe.php:458]: I added helper methods in ab133cff3eca9ebe15725079e71d5977b939fead. Let me know your thoughts and thanks for the feedback!

**Comment by mattallan** [comment]
Thanks @wjrosa for the review!

I've pushed up the following changes based on your feedback:
- [ab133cf](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3037/commits/ab133cff3eca9ebe15725079e71d5977b939fead) move the setting and deleting of meta into helper functions.
- [80b1f6b](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3037/commits/80b1f6bd5d09010202bf3e90ea7953e5ae87ad4b) Added unit tests to the new order handler function

This is ready for another review :)

File: includes/class-wc-gateway-stripe.php (hunk 1 above)
Comment (wjrosa) [reply includes/class-wc-gateway-stripe.php:458]: Looking great! Thank you

**Review by wjrosa — APPROVED** [review]
Awesome work! Thank you for addressing all of my comments!
