### PR TITLE
Fixes

### LINKED ISSUE #628: JS error triggered on all WooCommerce pages when WooCommerce country is not a Stripe one
#### Affected ticket(s)
N/A (reported in chat)

#### What I expected
For WooCommerce to work normally if WooCommerce country is not supported by Stripe

#### What happened instead
There's a JS error triggered on all pages that blocks all JS actions (AJAX requests, reloading shipping costs, etc):

```
Uncaught Error: Invalid value for paymentRequest(): country should be one of the following strings: AT, AU, BE, BR, CA, CH, DE, DK, EE, ES, FI, FR, GB, HK, IE, IN, IT, JP, LT, LU, LV, MX, NL, NZ, NO, PH, PL, PT, RO, SE, SG, SK, US. You specified: TH.
```

Screenshot
Screenshot: http://cld.wthms.co/yQEF3Z

#### Steps to reproduce the issue
1. In WooCommerce > Settings > General, choose a country that's not supported by Stripe, such as Thailand.
2. Save settings and observe there's no warning in WP Admin.
3. Open any product page and try to switch between product tabs, select a variation, etc - they all become unresponsive due to the JS error above.

Reproduced on Pressable, with Stripe 4.1.2 & WC 3.3.5

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by roykho**
#628 #625 

#### Changes proposed in this Pull Request:
* Add - Hook to manipulate payment request shipping posted values `wc_stripe_payment_request_shipping_posted_values`.
* Add - Accessibility attribute for credit card label.
* Add - Hook to change Stripe supported countries `wc_stripe_supported_countries`.
* Fix - WC 2.6 compatibility issue during a refund.
* Fix - Payment Request JS error when default country setting is not supported.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-payment-request.php [hunk 1]
```diff
@@ -100,10 +100,26 @@ public function __construct() {
 			return;
 		}
 
+		$wc_default_country = substr( get_option( 'woocommerce_default_country' ), 0, 2 );
```
Comment (bor0) [inline includes/payment-methods/class-wc-stripe-payment-request.php]: Can we use `WC()->countries->get_base_country();` instead?
