### PR TITLE
Save regular and 3DS cards only after payment intent is confirmed

### LINKED ISSUE #1362: 3D secure cards saved when not verified by Stripe.
## Describe the bug
When a user is doing a payment using a 3D secure card and selects the option to save the card for future payments the card is saved even if the Authentication failed.

## To reproduce

1. Setup a page with a checkout block.
2. Setup Stripe plugin ( test mode ).
3. Add items to the cart.
4. Complete the checkout form.
5. Use 3D secure Authentication required CC ( for example `4000 0027 6000 3184` ).
6. Select `Save payment information to my account for future purchases.`.
7. On the Authorization modal select to fail the Authorization for this CC.
8. Go My Account -> Payment Methods and see that the CC was saved.

## Expected behavior
If the CC fails authorization it should not be saved.

### LINKED ISSUE #1440: SCA: "Save payment information to my account for future purchases" should work with SCA payments
Steps to repro
1. As customer, purchase subscription
2. Later, check out with non-subscription product
3. Use new card 4000002500003155
4. Check ‘Save payment information to my account for future purchases.’
5. As customer, make the new card the default card and say “Yes” when it asks you if you want to use that card for all subscriptions
6. As admin, renew a subscription. See that it uses the new card. And that it fails due to authentication_required

### PR DESCRIPTION
**Pull request by asumaran**
Fixes: #1362 and Fixes #1440

## Description

Changes how and when cards are saved. Before this PR cards were attached to the customer and saved in the DB  in the same place. We used the `WC_Stripe_Payment_Gateway->add_source` method which [attached and also stored](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/trunk/includes/class-wc-stripe-customer.php#L268) the card details in the DB. This usually worked fine except for 3DS cards because cards were saved no matter if the payment was successful or not.

Key changes we are making on this PR:

- We are using the `setup_future_usage` [payment intent's param](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-setup_future_usage) (per @diegocurbelo's [suggestion](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1362#issuecomment-811666153)) in order to keep the card on Stripe for later usage if the payment intent is confirmed.
- The card is saved in the DB **only** after the payment intent has been confirmed. This is done in two places.
  - For regular cards is done in `WC_Gateway_Stripe-> process_payment()` after the payment intent is confirmed.
  - For 3DS cards is done in `WC_Stripe_Intent_Controller -> verify_intent()` after the user submits the authentication step.
- For 3DS cards in order to know if the user wants to save the payment method (checkbox is marked) at the end of the second step we need to pass along the value of the checkbox via the intent's metadata.

## Observations

- Cards with the exact same information (number, expiry date, CVC) are saved multiple times if the user enters the same card multiple times as "New payment method" This is something that's currently happening in `trunk`. I just wanted to mention it in case this is an unwanted behavior. Stripe seems not to care about it so I'm keeping the behavior since fixing it is out of the scope of the PR.

### User is logged in
- [x] User can purchase using a regular card.
  - Card used: `4242424242424242`
- [x] Using regular card, payment succeeds, checkbox is marked and payment method is saved.
  - Card used: `4242424242424242`
- [x] Using regular card, payment fails, checkbox is marked and payment method is not saved.
  - Card used: `4000000000000119` which declines with a `processing_error` code.
- [x] Using a 3DS card, auth is successful, payment succeeds, checkbox is marked and payment method is saved.
  - Card used: `4000002760003184`
- [x] Using a 3DS card, auth fails, payment fails, checkbox is marked and payment method is not saved.
  - Card used: `4000002760003184`
- [x] User can purchase using saved regular card
  - Saved Card used: `4242424242424242`
- [x] User can purchase using 3DS saved card
  - Saved Card used: `4000002760003184`
- [x] User can purchase using an already saved regular card as "New payment method"
  - Saved card used: `4242424242424242`
  - New card: `4242424242424242`
- [x] User can purchase using an already saved regular card as "New payment method" and checkbox is marked (card is saved again).
  - Saved card used: `4242424242424242`
  - New card: `4242424242424242`
- [x] User can purchase using an already saved 3DS card as "New payment method"
  - Saved card used: `4000002760003184`
- [x] User can purchase using an already saved 3DS card as "New payment method" and checkbox is marked (card is saved again)
  - Saved card used: `4000002760003184`
  - New card: `4000002760003184`
- [x] Test `wc_stripe_force_save_source` hook with regular cards
  - Card used: `4242424242424242`
- [x] Test `wc_stripe_force_save_source` hook with 3DS cards
  - Card used: `4000002760003184`

### User is not logged in

- [x] User can make a purchase using a regular card.
  - Card used: `4242424242424242`
- [x] User makes a purchase using a regular card and it fails gracefully.
  - Card used: `4242424242424242`
- [x] User can purchase using a 3DS card if auth is successful
- [x] User can not purchase using a 3DS card if auth fails

Any suggestion on testing a case not considered on this list would be great.

### CODE REVIEW

File: includes/class-wc-stripe-customer.php [hunk 1]
```diff
@@ -295,6 +297,17 @@ public function add_source( $source_id ) {
 							$wc_token->set_expiry_month( $response->card->exp_month );
 							$wc_token->set_expiry_year( $response->card->exp_year );
 						}
+
+						if ( 'source' === $response->object && 'three_d_secure' === $response->type ) {
```
Comment (asumaran) [inline includes/class-wc-stripe-customer.php]: @diegocurbelo Just to let you know. I'll double test this again. I'm not sure how we were able to save a 3DS card before since the card info was in another object.

Also, this surely can be merged with the previous `if` if we do something like `$response->$response_type->prop_name`

File: includes/class-wc-stripe-intent-controller.php [hunk 2]
```diff
@@ -102,6 +102,23 @@ public function verify_intent() {
...
 			$gateway->verify_intent_after_checkout( $order );
 
+			if ( isset( $_GET['save_payment_method'] ) && ! empty( $_GET['save_payment_method'] ) ) {
+				$intent = $gateway->get_intent_from_order( $order );
+				if ( isset( $intent->last_payment_error ) ) {
+					// Currently, Stripe saves the payment method even if the authentication fails for 3DS cards.
+					// Although, the card is not stored in DB we need to remove the source from the customer on Stripe
+					// in order to keep the sources in sync with the data in DB.
+					$customer = new WC_Stripe_Customer( wp_get_current_user()->ID );
+					$customer->delete_source( $intent->last_payment_error->source->id );
```
Comment (asumaran) [inline includes/class-wc-stripe-intent-controller.php:112]: I haven't found a way to tell Stripe to not to save the 3DS card if the authentication fails. I've chatted with Stripe support about this and I'm waiting for an official response. For now I'm deleting the source from the customer manually.

**Review by diegocurbelo — APPROVED** [review]
Nice work @asumaran... LGTM 🚢

**Comment by v18** [comment]
Hey @asumaran I found a small issue with saved cards in this branch, and it's not reproducible in `trunk`. Here are the steps to repro:

1. log in as customer
2. check out with regular product, use 4242 card, save payment details to account using the checkout 'Save payment information to my account for future purchases.'
3. check out again to buy a subscription product, use the previously-saved 4242 card
4. see that there are now two 4242 cards in account - but only one in stripe's account under `test/customers/cus_123`. expected to see only one 4242 card instead.

It looks like this is happening here:

https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1507/files#diff-8c1f01376167e4e75ce4eee534a35f3082229236433132282465407f7ff244edR632-R634

From what I can see, a solution to this would be to check whether or not we are using a saved source before saving the payment method, using `$this->is_using_saved_payment_method()`.

If the fix required is actually more complex, feel free to open a new issue to fix instead.

**Comment by asumaran** [comment]
> From what I can see, a solution to this would be to check whether or not we are using a saved source before saving the payment method, using $this->is_using_saved_payment_method().

Nice catch and solution @v18. That fixed the issue https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1507/commits/f02be4dd3733e6b1b3e70e237c9472aeb8a43b33
