### PR TITLE
Fix the "Not a valid URL" notice

### LINKED ISSUE #1240: Apple Pay: "Not a valid URL" notice lacks context
A notice with simply "Not a valid URL" can appear if Apple Pay validation fails. Unfortunately, although the notice seems to only appear on the Stripe settings view in wp-admin, it isn't immediately clear what the error means or what the user should do to fix it.

Observed while running a fresh out-of-the-box docker setup.

I recommend rewording the error to something like "WooCommerce Stripe: Apple Pay domain verification failed: (URL) is not a valid URL."

Screen Shot 2020-06-19 at 2 44 54 PM

### PR DESCRIPTION
**Pull request by reykjalin**
Fixes #1240 .

#### Changes proposed in this Pull Request:

- Combines the "Not a valid URL" notice with the "Apple Pay domain verification failed" notice.
- The new notice shows the "Not a valid URL" message in the notice if it exists, otherwise it shows a more generic notice without the message.

image

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-stripe-apple-pay-registration.php [hunk 1]
```diff
@@ -241,34 +242,45 @@ public function process_apple_pay_verification() {
...
+			'a' => array(
+				'href'  => array(),
+				'title' => array(),
+			),
+		);
+
+		echo '<div class="error stripe-apple-pay-message"><p>';
+
+		echo 'Apple Pay domain verification failed';
+		$reason = $empty_notice ? '' : ' with the error: ' . wp_kses( make_clickable( $this->apple_pay_verify_notice ), $allowed_html ) . '';
```
Comment (dechov) [inline includes/class-wc-stripe-apple-pay-registration.php:273]: I like the concise way these cases are combined here, but it's at the cost of the translated string – is that OK? We could just have two separate full translated sentences here, or skip "with the error". I don't know if Stripe's error message would ever be localized, so it might not be that big a deal.

**Comment by dechov** [comment]
Here's a longer one I'm seeing – do we want to add a little more formatting to distinguish Stripe's error message?

**Comment by reykjalin** [comment]
Yeah, I think that's a good idea. How about this:

```html
<p>Apple Pay domain verification failed with the following error:</p>
<p>{{ stripe_error }}</p>
<p>Please check the logs for more details about this issue.</p>
```

which will end up looking something like:

>Apple Pay domain verification failed with the following error:
>
>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
>
>Please check the logs for more details about this issue.

**Comment by dechov** [comment]
@reykjalin Looks good to me 👍

**Comment by reykjalin** [comment]
Done 👍 

Thanks!

File: includes/class-wc-stripe-apple-pay-registration.php [hunk 2]
```diff
@@ -241,34 +242,45 @@ public function process_apple_pay_verification() {
 	 * @since 4.0.6
 	 */
 	public function admin_notices() {
-		if ( ! $this->stripe_enabled ) {
+		if ( ! $this->stripe_enabled || ! $this->payment_request ) {
```
Comment (allendav) [inline includes/class-wc-stripe-apple-pay-registration.php:245]: Why this change?

Comment (allendav) [reply includes/class-wc-stripe-apple-pay-registration.php:245]: Ah, nevermind. I see. Carry on.

File: includes/class-wc-stripe-apple-pay-registration.php [hunk 3]
```diff
@@ -241,34 +242,45 @@ public function process_apple_pay_verification() {
...
+		$allowed_html = array(
+			'a' => array(
+				'href'  => array(),
+				'title' => array(),
+			),
+		);
+
+		echo '<div class="error stripe-apple-pay-message">';
+
+		echo '<p>Apple Pay domain verification failed';
```
Comment (allendav) [inline includes/class-wc-stripe-apple-pay-registration.php:272]: This (less the tag) should also be a localized string

File: includes/class-wc-stripe-apple-pay-registration.php [hunk 4]
```diff
@@ -241,34 +242,45 @@ public function process_apple_pay_verification() {
...
+		$reason = $empty_notice ? '' : ' with the following error:</p><p>' . wp_kses( make_clickable( $this->apple_pay_verify_notice ), $allowed_html );
```
Comment (allendav) [inline includes/class-wc-stripe-apple-pay-registration.php:273]: "with the following error" should be localized

File: includes/class-wc-stripe-apple-pay-registration.php (hunk 3 above)
Comment (reykjalin) [reply includes/class-wc-stripe-apple-pay-registration.php]: Thank you!

Fixed in 456e0e22e880a07305e621e3d330030e5da286dc.

File: includes/class-wc-stripe-apple-pay-registration.php (hunk 4 above)
Comment (reykjalin) [reply includes/class-wc-stripe-apple-pay-registration.php]: Thank you!

Fixed in 456e0e22e880a07305e621e3d330030e5da286dc.

File: includes/class-wc-stripe-apple-pay-registration.php (hunk 1 above)
Comment (reykjalin) [reply includes/class-wc-stripe-apple-pay-registration.php]: I assume you're referring to the `'with the error:'` string? If that's the case are you opposed to how I fixed that in 456e0e22e880a07305e621e3d330030e5da286dc?

If you're referring to the Stripe error, that's already sort of out of our control. Maybe it'd be better to simply skip showing that error and instead always direct people to the log? Doing that would certainly simplify the logic a bit here.

What do you think @allendav?

Comment (dechov) [reply includes/class-wc-stripe-apple-pay-registration.php]: Ah, not Stripe's error, which is unchanged here – I was just referring to "Apple Pay domain verification failed" and "Apple Pay domain verification failed with the error:" – which I'd probably consider two separate full strings for purposes of translation, though I'm not sure which languages would be affected in practice – AFAIK the way it's done in https://github.com/woocommerce/woocommerce-gateway-stripe/commit/456e0e22e880a07305e621e3d330030e5da286dc may be sufficient.

Comment (reykjalin) [reply includes/class-wc-stripe-apple-pay-registration.php]: Actually, thinking about this more, I think you're right; this probably should be 2 separate strings. I think it might be hard for translators to understand the context of "with the error". I'll make this 2 separate strings and use `$empty_notice` to decide which one to use.

Comment (reykjalin) [reply includes/class-wc-stripe-apple-pay-registration.php]: I pushed an update in 5b536e3aaf158df19ac068c2389593c0e72a075f, what do you think?

Also, should I update the pot file in this PR, or will it be updated during the release?

Comment (dechov) [reply includes/class-wc-stripe-apple-pay-registration.php]: Looks good to me – not sure about the POT for this PR, but I _think_ it is (or should be) a release task.

Comment (allendav) [reply includes/class-wc-stripe-apple-pay-registration.php]: The POT will be regenerated by `npm run build` when we release it. PRs can do it too, but its ok to let it wait for release.

File: includes/class-wc-stripe-apple-pay-registration.php [hunk 5]
```diff
@@ -241,34 +242,46 @@ public function process_apple_pay_verification() {
...
 		 * something went wrong so lets notify user.
 		 */
-		if ( ! empty( $this->secret_key ) && $this->payment_request && ! $this->apple_pay_domain_set ) {
+		$allowed_html                      = array(
+			'a' => array(
+				'href'  => array(),
+				'title' => array(),
+			),
+		);
+		$error_from_stripe                 = $empty_notice ? '' : '<p>' . wp_kses( make_clickable( esc_html( $this->apple_pay_verify_notice ) ), $allowed_html ) . '.</p>';
```
Comment (dechov) [inline includes/class-wc-stripe-apple-pay-registration.php:269]: I don't think we need a `.` at the end here, since it looks like some messages already have one (see [screenshot](https://cloudup.com/cXBarovKk2D)) and we're already isolating it from our own strings.

File: includes/class-wc-stripe-apple-pay-registration.php [hunk 6]
```diff
@@ -241,34 +242,46 @@ public function process_apple_pay_verification() {
...
 			/* translators: 1) HTML anchor open tag 2) HTML anchor closing tag */
-			echo '<div class="error stripe-apple-pay-message"><p>' . sprintf( __( 'Apple Pay domain verification failed. Please check the %1$slog%2$s to see the issue. (Logging must be enabled to see recorded logs)', 'woocommerce-gateway-stripe' ), '<a href="' . admin_url( 'admin.php?page=wc-status&tab=logs' ) . '">', '</a>' ) . '</p></div>';
-		}
+			esc_html__( 'Please check the %1$slogs%2$s for more details on this issue. Logging must be enabled to see recorded logs.', 'woocommerce-gateway-stripe' ),
+			'<a href="' . admin_url( 'admin.php?page=wc-status&tab=logs' ) . '">',
+			'</a>'
+		);
+
+		$notice_text = $empty_notice ? $verification_failed_without_error : $verification_failed_with_error;
+		echo '<div class="error stripe-apple-pay-message">';
```
Comment (dechov) [inline includes/class-wc-stripe-apple-pay-registration.php:280]: Not a big deal, just a thought: since it's all structure here, what do you think of having HTML here instead of PHP strings? And `$error_from_stripe` could be in a conditional maybe?

File: includes/class-wc-stripe-apple-pay-registration.php [hunk 7]
```diff
@@ -228,6 +228,7 @@ public function process_apple_pay_verification() {
 
 		} catch ( Exception $e ) {
 			$this->stripe_settings['apple_pay_domain_set'] = 'no';
+			$this->apple_pay_domain_set                    = false;
```
Comment (dechov) [inline includes/class-wc-stripe-apple-pay-registration.php:231]: Looks like this is needed to show the error if it fails after having succeeded earlier – sort of an edge case but good catch nonetheless!

**Comment by dechov** [comment]
Screenshots [before](https://cloudup.com/cSOAQdlUxO8) & [after](https://cloudup.com/cXBarovKk2D). Looks good, except I was kind of thinking we could add some styling to distinguish the different lines more – like italics on the error? Not too big a deal.

Haven't reproduced that particular "Not a valid URL" – let me know if you know how to, but the changes are independent of the returned error content anyway.

File: includes/class-wc-stripe-apple-pay-registration.php (hunk 6 above)
Comment (reykjalin) [reply includes/class-wc-stripe-apple-pay-registration.php:280]: That's a good idea I think 🤔 

I think I'll go ahead and do that 😄

**Comment by reykjalin** [comment]
>I was kind of thinking we could add some styling to distinguish the different lines more – like italics on the error?

I like that idea! Done!

This is what the errors look like now:

image

> Haven't reproduced that particular "Not a valid URL" – let me know if you know how to

I just spun up the docker container and without any configuration that's the error I see. Beyond that I have no idea how to specifically get that error.

I suspect it's becuase the URL it's trying to verify is a `localhost` URL.

File: includes/class-wc-stripe-apple-pay-registration.php (hunk 6 above)
Comment (reykjalin) [reply includes/class-wc-stripe-apple-pay-registration.php]: Done in 99bd5552585397ede97d5312ec814abcea834c63. What do you think?

File: includes/class-wc-stripe-apple-pay-registration.php (hunk 5 above)
Comment (reykjalin) [reply includes/class-wc-stripe-apple-pay-registration.php]: Fixed in dff28b197184c8bc2803dfe3314751f9b6666075 🎉

File: includes/class-wc-stripe-apple-pay-registration.php (hunk 6 above)
Comment (dechov) [reply includes/class-wc-stripe-apple-pay-registration.php]: I like it 👍

**Review by dechov — APPROVED** [review]
Without error | With error
-- | --
apple-pay-notice-without-error | apple-pay-notice-with-error



Works well and code LGTM :shipit:
