### PR TITLE
Prevent duplicate failed order emails

### LINKED ISSUE #1229: Duplicate failed order emails
**Describe the bug**

In some cases, a webhook handler explicitly sends a failed order email after updating order status to `'failed'` (which also triggers that same email), as pointed out by @DanReyLop in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1108#discussion_r396561802. For instance:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/19e5f4a47d4ad94d4d367a588b3cd4b227c9f80d/includes/class-wc-stripe-webhook-handler.php#L673-L678

Also, the failed email is currently sent when a dispute comes in, even though the order status is _not_ set to `'failed'` – is this desirable?

**To Reproduce**
To trigger the example case above, check out with failure case test card 4000008400001629 then click for successful verification, then verify it fails (as expected) and that _two identical emails_ are sent. (Tested on remote test site so that the emails are properly sent, but can also probably hook into core email module for logging.)

### PR DESCRIPTION
**Pull request by annemirasol**
When an order changes status from pending/on-hold to failed, [a failed-order email is triggered in core](https://github.com/woocommerce/woocommerce/blob/0f2fa403f1ad0dc26bdd82ec3e901cb1794201e6/plugins/woocommerce/includes/emails/class-wc-email-failed-order.php#L40). In our Stripe webhooks code, we also manually trigger these emails when certain processes fail, e.g. `payment_intent.payment_failed`. This causes duplicate emails for some scenarios.

Fixes #1229

## Changes proposed in this Pull Request:
Before manually triggering a failed-order email, we first check if the status change to `failed` will not trigger its own email send.

## Testing instructions
1. Stripe webhooks need to be set up and working:
    - Use a tunneling service like ngrok or Jurassic Tube, -or-
    - Test these changes on publicly accessible servers
2. Install the WP Mail Logging plugin: https://wordpress.org/plugins/wp-mail-logging/
4. As a shopper, add a product to cart and go to checkout.
5. Use `4000 0084 0000 1629` as the credit card number, with any expiry date and CVC.
    - This should trigger 3D Secure 2 authentication, but payment will eventually fail. 
    - Click "Complete" to authenticate. 
    - You should see the error banner above the payment element, with a message like `Your card has been declined.`
6. Go to the WP Mail Logging dashboard: `wp-admin/admin.php?page=wpml_plugin_log`
7. You should see a failed order email, with the subject `Order #XY has failed`.
    - You should see only one failed order email.
    - Note: customers re-attempting and again failing will trigger another failed order email. This is expected.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/class-wc-stripe-webhook-handler.php [hunk 1]
```diff
@@ -1115,6 +1127,31 @@ protected function handle_deferred_payment_intent_succeeded( $order, $intent_id
 
 	}
 
+	/**
+	 * Check if setting an order to failed will trigger a failed order email.
+	 *
+	 * @param string $status The status of the order prior to setting it to failed.
+	 * @return bool
+	 */
+	private function has_failed_order_email_hooks( $status ) {
```
Comment (wjrosa) [inline includes/class-wc-stripe-webhook-handler.php]: Smart solution 👍

**Review by wjrosa — CHANGES_REQUESTED** [review]
Unfortunately, it is not working as expected for me (still receiving 2 emails). I have included the following line to log your new method after `$send_email = ! $this->has_failed_order_email_hooks( $order->get_status() );`:
```
					WC_Stripe_Logger::error( 'has_failed_order_email_hooks: ' . wc_bool_to_string( ! $send_email ) . ' / ' . $order->get_status() );
```

For me, on a JN site, `has_failed_order_email_hooks` always return `false` and `$order->get_status()` is always `pending` at that point.

**Comment by annemirasol** [comment]
@wjrosa So sorry about that! I think during testing, I wasn't properly ensuring I was failing on a fresh order ID, so it was only sending one email because there was no status update actually happening! 🫠 

Anyway, there were a few things wrong in my old code:
- typo on the class name ☠️ 
- I was using the class name in the callback param, when I should be using a class instance

Fixes:
- actually use the correct class and instance
- move the logic to inside `WC_Stripe_Payment_Gateway`'s `send_failed_order_email()` -- this one is more of a rework than a fix. I realized the Stripe webhook code should not know too much about how emails are sent, and so I moved the dedupe logic to the method that is actually in charge of sending emails. Let me know what you think of this!

Tested, making sure orders are fresh!

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 2]
```diff
@@ -622,13 +622,33 @@ public function process_response( $response, $order ) {
 	 * @since 3.1.0
 	 * @version 4.0.0
 	 * @param int $order_id
+	 * @param array $status_update Optional. Use fields 'to' and 'from' to provide context
+	 *    when a status change has occurred for the order.
 	 * @return null
```
Comment (wjrosa) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]:
```suggestion
	 * @return void
```

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 3]
```diff
@@ -622,13 +622,33 @@ public function process_response( $response, $order ) {
...
+
+		if ( empty( $emails ) || empty( $order_id ) || ! isset( $emails['WC_Email_Failed_Order'] ) ) {
+			return;
 		}
+
+		// To prevent duplicate failed order emails, check if a status update
+		// will trigger its own failed order email.
+		if (
+			isset( $status_update['to'] ) &&
+			isset( $status_update['from'] ) &&
```
Comment (wjrosa) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: You can replace both `isset` with `isset( $status_update['to'], $status_update['from'] )`

**Review by wjrosa — APPROVED** [review]
Thanks for fixing the issues, Anne! It now works as expected 👍 . Left some minor (non-blocker) comments.

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 3 above)
Comment (annemirasol) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Thanks, TIL!
