### PR TITLE
Deferred intent UPE - Fix errors when attempting to add payment methods via My Account > Payment methods

### LINKED ISSUE #2798: Investigate creating a Stripe payment element with mode 'payment' when loading the form on Add Payment Method page
### Description

While working on https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2791 which is adding deferred intent support to the **My Account > Payment methods > Add payment method** page, I noticed that when we're creating the Stripe PE, we are using the following options:

```
const amount = Number( getStripeServerData()?.cartTotal );
const options = {
	mode: amount < 1 ? 'setup' : 'payment',
	currency: getStripeServerData()?.currency.toLowerCase(),
	amount,
	paymentMethodCreation: 'manual',
	paymentMethodTypes,
	appearance: initializeUPEAppearance(),
	fonts: getFontRulesFromPage(),
};
```

Note that for the `mode` property we're setting it to either `'setup'` or `'payment'` depending on the `cartTotal` arg served to us from the backend. From my understanding, we want to be using "setup" mode for adding a payment method since no payment is going to be taken, however, if you add a product to your cart, then visit **My Account > Payment methods > Add payment method**, the Stripe PE will be loaded with `mode` set to payment.

From my testing, setting the mode to payment or setup doesn't have any impact on saving the payment method and from the Stripe docs, it looks like this 'mode' is just used for determining which payment methods to display: https://stripe.com/docs/js/elements_object/update#elements_update-options-mode

Given we're moving to split deferred intent, it might not matter what we set mode to.

This issue is to investigate this setting further and determine whether we need to force the mode to be 'setup' when on the add payment method page

> [!NOTE]
> WooPayments uses this same code that sets the mode based on the cart totale and it doesn't seem to be an issue for them on their Add Payment Method page so I suspect it's not problem.

### LINKED ISSUE #2907: [Split PE] Payment methods can't be added via My Account > Payment Methods
**Describe the bug**

An error is displayed, and no local token is created when adding a new payment method via My Account > Payment methods. The payment method is created in Stripe.

**To Reproduce**
1. As a shopper, go to My Account > Payment Methods > Add Payment Method http://localhost:8082/my-account/add-payment-method/
2. Save a new card `4242424242424242`
3. Notice that:
- You get an error message saying "Cannot read properties of undefined (reading 'error')"
image

- There's an error message in the debug log saying
```
PHP Notice:  Undefined index: return_url in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-intent-controller.php on line 959
```
- No local token is created
- A payment method gets created in Stripe

**Expected behavior**
A local token and a remote payment method must be created when saving a card via the My Account > Payment Methods page. No error message must be displayed and there must not be any entries in the debug log.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #2907
Fixes #2798

## Changes proposed in this Pull Request:

This PR fixes a couple of issues encountered when trying to add payment methods via the My Account > Payment methods screen. 

Namely: 

1. Undefined `return_url` errors. As reported in #2907.
2. APMs that require a redirect like Bancontact and iDEAL are not correctly redirected and tokens created on returning to the store. 
3. Adding a SEPA payment method now properly calls the UPE gateway instance of `add_payment_method()`, rather than falling through to the base class. 

## Testing instructions

Setup: 

1. Use a Stripe account with access to all European APMS (iDEAL, Bancontact, SEPA, Sofort).
2. Enable UPE in the Stripe gateway advanced settings. 
3. Set your store to Euro currency. 
4. Enable all available payment methods in the Stripe plugin Settings.  
1. Go to My Account > Payment methods and delete all payment methods (this will just make it easier to track new tokens as they are being created).

#### Standard Card
1. **My Account > Payment methods > _Add payment Method_**
2. Enter a default card ID `4242424242424242`
3. Fill all required fields and submit the form. 
4. On the following page, make sure the new payment method you just added is now listed.
5. Check the `wp_woocommerce_payment_tokens` database and confirm the the token was created with the `stripe` payment gateway ID. 

#### 3DS Card
1. **My Account > Payment methods > _Add payment Method_**
2. Enter a default card ID `4000002500003155`
3. Fill all required fields and submit the form. 
4. You should be shown a VISA auth popup modal. Hit **'Complete'**. 
6. On the following page, make sure the new payment method you just added is now listed.
5. Check the `wp_woocommerce_payment_tokens` database and confirm the the token was created with the `stripe` payment gateway.

### iDEAL/Bancontact/Sofort
1. **My Account > Payment methods > _Add payment Method_**
2. Select **iDEAL** or **Bancontact** or **Sofort**. 
3. Fill all required fields and submit the form. 
4. You should be redirected Stripe test page where you can confirm/deny authorization.
5. Hit Authorize
6. On the following page, make sure the new payment method you just added is now listed.
   - iDEAL payment methods end with  `5264`. 
   - Bancontact payment methods end with `7061`.
   - Sofort payment methods end with `3000 `
6. Check the `wp_woocommerce_payment_tokens` database and confirm the the token was created with the `stripe_ideal` payment gateway.

Screenshot 2024-02-19 at 5 52 30 pm

> [!note]
> If you're fail the authorization after the redirect, you will return to the store with an appropriate failure notice. 

### SEPA
1. **My Account > Payment methods > _Add payment Method_**
2. Select **SEPA**
3. Fill all required fields and submit the form and enter the test IBAN `AT61 1904 3002 3457 3201`
6. On the following page, make sure the new payment method you just added is now listed.
   - SEPA PMs end with `3201 `. 
6. Check the `wp_woocommerce_payment_tokens` database and confirm the the token was created with the `stripe_sepa_debit` payment gateway.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 1]
```diff
@@ -401,6 +401,8 @@ public function javascript_params() {
 					)
 				);
 			}
+		} elseif ( is_wc_endpoint_url( 'add-payment-method' ) ) {
+			$stripe_params['cartTotal'] = 0;
```
Comment (james-allan) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:405]: The question about this cartTotal was raised here https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2798. 

Without this change, if you had items in your cart and you tried to add a Bancontact payment method, you would be presented with this error. 

Screenshot 2024-02-19 at 6 01 41 pm

**Review by wjrosa — APPROVED** [review]
Looking good!

Works as expected:
Screenshot 2024-02-19 at 17 43 20
Screenshot 2024-02-19 at 17 43 51
