### PR TITLE
[ECE] Hide express payment buttons on switch subscription page

### LINKED ISSUE #3608: [ECE] Fix ECE button behavior on switch subscription page
When subscription switching and prorating is enabled, user can select to upgrade their subscription and we charge them only the outstanding amount for upgrade. On subscription switch product page, the express checkout button is displayed and if you try to pay from this product page, it charges you the full amount instead of the difference.

### Steps to reproduce
- Create a variable subscription product with 2 variations (Blue: 50 USD and Red: 60 USD).
- Purchase the Blue variation.
- From My Account > Subscriptions page find your subscription.
- Click on upgrade your subscription button.
- You will be taken to the product page to switch the product variation.
- If you click the switch button, go to the checkout page and try paying with ECE/PRB on the checkout page, you will be charged 10 USD (the difference)
- If you try to pay from the product page with ECE/PRB, you will be charged 60 USD (the full price)

### Expected behavior
- Hide the ECE/PRB buttons from the product page in this scenario.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #3608 

## Changes proposed in this Pull Request:
As switch subscription page is basically the product page, when paid with ECE/PRB the full amount is charged instead of the difference. We are hiding the PRB/ECE buttons from the switch subscription page. 

## Testing instructions
- Enable the new checkout experience.
- Enable the ECE feature flag.
- Enable Google/Apple Pay from Stripe settings page.
- Install the `WooCommerce Subscription` plugin.
- Go to 'WooCommerce > Settings > Subscriptions' page. Enable subscription switching and prorating.
- Create a variable subscription product with 2 variations (Blue: 50 USD and Red: 60 USD).
- As a shopper, purchase the Blue variation.
- From 'My Account > Subscriptions' page find your subscription.
- Click on upgrade your subscription button.
- You will be taken to the product page to switch the product variation.
- In `develop` branch, you can see the ECE button on this page. 

Screenshot 2024-11-18 at 1 21 49 PM

- On this branch, you should not see the ECE button on the switch subscription page.
- Confirm that the ECE buttons are rendered correctly on cart and checkout pages when you click the switch button and it is added to the cart.

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-express-checkout-element.php [hunk 1]
```diff
@@ -85,6 +85,11 @@ public function init() {
 			return;
 		}
 
+		// Don't load for switch subscription page.
+		if ( isset( $_GET['switch-subscription'] ) ) {
+			return true;
```
Comment (wjrosa) [inline includes/payment-methods/class-wc-stripe-express-checkout-element.php]: Is there a particular reason for the `true` value here? I'm just asking because the other return statements above do not have a value (void).

Comment (Mayisha) [reply includes/payment-methods/class-wc-stripe-express-checkout-element.php]: Good catch. I added this check inside another function (which should return a boolean) at first and copied it over from there. It is a copy paste error on my end 🤦‍♀️ 

Fixed in [2a0929f](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3610/commits/2a0929f135535e506deaf208debbc04e85f6c38d)

**Review by wjrosa — APPROVED** [review]
Nice fix, Mayisha! Works as expected:

> On this branch, you should not see the ECE button on the switch subscription page.

Screenshot 2024-11-19 at 14 18 56

> Confirm that the ECE buttons are rendered correctly on cart and checkout pages when you click the switch button and it is added to the cart.

Screenshot 2024-11-19 at 14 16 05
Screenshot 2024-11-19 at 14 16 17
