### PR TITLE
After automatically configuring a webhook, delete any previously configured ones sent to the current site

### LINKED ISSUE #3270: Delete previously added webhook secret at Stripe when reconfiguring webhooks
**Describe the bug**
If a merchant manually created a webhook endpoint and copied the secret into their Stripe plugin settings and then clicks the "Reconfigure webhooks" button introduced in 8.5.0 (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3209) the previous webhook endpoint they manually created would continue to exist. 

This is because Stripe requires us to use the webhook ID to send delete request and we never obtained the webhook ID when the customer manually added the webhook secret. 

**To Reproduce**

1. In your Stripe Dashboard go to **Developers > Webhooks**
2. Create a webhook with any endpoints and enter the correct URL for your site
eg `https://example.com/?wc-api=wc_stripe`
3. Checkout Stripe 8.4.0
4. Go to **WooCommerce > Settings > Payments > Stripe > Settings (tab)**
5. Open the account keys modal
6. In the webhook secret field copy the webhook secret from the Stripe dashboard
7. Save account keys.
8. Checkout `develop` or `8.5.0`
9. run `npm run build`
10. Open the account keys modal and click the **Reconfigure webhooks** button.
11. View your webhooks in the Stripe Dashboard and you'll notice that there are now 2 webhooks for your site. 

Screenshot 2024-07-12 at 3 28 08 PM

**Expected behavior**
We should still attempt to delete all webhook endpoints that are no longer relevant.

**Additional context**

Stripe give us APIs to [fetch all webhooks on the account](https://docs.stripe.com/api/webhook_endpoints/list), those responses don’t include the secret so we can’t match the previous-manually-entered webhook secret to find which one to delete. The only way I can think of resolving this is by matching the URLs. i.e when reconfiguring a webhook, if there’s no webhook ID for the current secret we fetch all webhooks, and delete those with a URL matching this store’s.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3270 

## Changes proposed in this Pull Request:

Merchants previously set up webhooks manually by creating the endpoint and copying the webhook secret into their Stripe settings. In 8.5.0 we introduced a button that could be used to configure the webhooks automatically. 

If they used the option to configure webhooks, they would end up with 2 endpoints. The original 1 they manually set up and the 2nd one we set up automatically. As we've discovered in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3326, if a store has multiple endpoints set up, they will process multiple webhooks leading to duplicate order notes and emails etc. 

This PR makes sure that after we configure their webhooks, we delete any webhook that is sent to the current site. This should prevent any previously set up webhook being sent and leading multiple webhooks. 

## Testing instructions

1. Go to your Stripe dashboard and the Webhooks page
    - https://dashboard.stripe.com/test/webhooks
2. Manually create 2 webhooks
   - One should be sent to your local site. 
   - The other one should be sent to a made up URL. eg `https://example.com/?wc-api=wc_stripe`
3. In your WP Admin dashboard go to **WooCommerce → Settings → Payments → Stripe → Settings (tab)**
4. Open the keys/connection modal.
5. Click the **Reconfigure webhooks** button
6. Check your webhooks in the Stripe dashboard. 
   - You should have a 1 new one.
   - All previously configured webhooks that were sent to your site should have been deleted.
   - Any other webhooks sent to different sites should remain unaffected.
7. If you check your Stripe logs in the dashboard or in WC you will see the requests to delete those duplicate webhooks. 

**BEFORE**
<p align="center">
Screenshot 2024-08-02 at 1 02 07 PM
</br>
<sup>3 duplicate webhooks all being sent to my local site. 1 sent to another site</sup>
</p> 

**AFTER**

<p align="center">
Screenshot 2024-08-02 at 1 09 14 PM
</br>
<sup>1 webhook being sent to my local site. 1 still sent to another site (undeleted)</sup>
</p> 

| Screenshot 2024-08-02 at 1 12 34 PM | Screenshot 2024-08-02 at 1 15 42 PM |
|--------|--------|

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: tests/phpunit/helpers/class-wc-helper-stripe-api.php [hunk 1]
```diff
@@ -14,16 +14,88 @@
 class WC_Helper_Stripe_Api {
```
Comment (james-allan) [inline tests/phpunit/helpers/class-wc-helper-stripe-api.php:15]: The rest of the changes below are unit tests. Because `WC_Stripe_Api` is a static class, mocking the returned values is finicky.

File: includes/admin/class-wc-rest-stripe-account-keys-controller.php [hunk 2]
```diff
@@ -441,6 +441,9 @@ public function configure_webhooks( WP_REST_Request $request ) {
 			WC_Stripe_API::request( [], "webhook_endpoints/{$configured_webhook_id}", 'DELETE' );
```
Comment (Mayisha) [inline includes/admin/class-wc-rest-stripe-account-keys-controller.php]: Is this needed anymore as we are calling the `delete_previously_configured_manual_webhooks` function to delete the webhooks below?

**Review by Mayisha — COMMENTED** [review]
Thanks @james-allan for the changes. 

I have tested the PR with a setup where I had total 8 webhooks in my Stripe dashboard for the same URL. The webhooks were created in following way-
- Already had one manually created webhook from before.
- In develop branch, I clicked the `Reconfigure webhook` button a few times.
- Created one webhook manually for testing this PR

Screenshot 2024-08-02 at 7 50 25 PM


Then I checkout to this branch and clicked the `Reconfigure webhooks` button. Notice that the webhook I had from before is not deleted. 

Screenshot 2024-08-03 at 12 43 54 AM

I think it's because the URL is a bit different as the old one has `http`. Should we consider this case also when the URL is the same except for the protocol part?

File: includes/admin/class-wc-rest-stripe-account-keys-controller.php (hunk 2 above)
Comment (james-allan) [reply includes/admin/class-wc-rest-stripe-account-keys-controller.php]: Yeah good question that's no longer needed. I confirmed that after removing this line, the old webhook is deleted by the `delete_previously_configured_webhooks()`.

**Review by Mayisha — APPROVED** [review]
Changes look good and it is working as expected. 🎉 

With the latest changes when I clicked the `Reconfigure webhooks` button, all the webhooks having the same URLs were deleted (including the `http` one).

Screenshot 2024-08-06 at 1 58 28 AM
