### PR TITLE
Catch request failure errors

### LINKED ISSUE #2528: Handle request failures to Stripe's API more gracefully
## Describe the bug

If the Stripe API is unreachable for some reason we don't always catch those exceptions resulting in fatal errors and similar messages appearing on the front-end that's visible to customers.

### To Reproduce

1. Block requests to Stripe's API, e.g. by adding an entry to your `/etc/hosts` file.
2. Add a product to your cart.
3. Try to complete a payment.
4. Note a fatal error appearing.

### Expected behavior

The fatal error should not appear. Instead an error message should be displayed saying something along the lines of "We are unable to process your payment at this time. Please try again later."

## Screenshots

Provided from a merchant (one screenshot available in p1673654197130999-slack-CHG7MTCAF omitted due to identifiable information):

- https://snipboard.io/3GrB2z.jpg
- https://snipboard.io/oXAs8S.jpg
- https://snipboard.io/qXDzco.jpg 

## Environment (please complete the following information):

I have not reproduced the issue yet, so TBD for now.

## Additional context

Reported in p1673654197130999-slack-CHG7MTCAF.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #2528 

## Changes proposed in this Pull Request:
Added try/catch block in some places where exception catches are missing. These missing exception catches could cause fatal errors in the application and make it visible in the UI.

## Testing instructions
- Block requests to Stripe by adding `127.0.0.1  api.stripe.com` in your `etc/hosts` file.
- Check the Stripe settings in the admin dashboard and make sure there is no visible fatal error in the UI.
- Go to the shop as a customer. Add a payment method and a subscription to your account. Check different pages of `My Account`, Cart, Checkout, etc and make sure there is no visible fatal error in the UI.

### CODE REVIEW

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -705,7 +705,11 @@ public function get_latest_charge_from_intent( $intent ) {
 		if ( ! empty( $intent->charges->data ) ) {
 			return end( $intent->charges->data );
 		} else {
-			return $this->get_charge_object( $intent->latest_charge );
+			try {
+				return $this->get_charge_object( $intent->latest_charge );
+			} catch ( WC_Stripe_Exception $e ) {
```
Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: If we don't let this bubble up, the following flows that expect this exception will never be triggered:
- WC_Stripe_UPE_Payment_Gateway::process_payment_with_saved_payment_method * → save_intent_to_order
- WC_Stripe_UPE_Payment_Gateway::process_upe_redirect_payment * → process_order_for_confirmed_intent → save_intent_to_order
- WC_Stripe_Intent_Controller::update_order_status_ajax * → process_order_for_confirmed_intent → save_intent_to_order
- WC_Gateway_Stripe::process_payment * → create_intent → save_intent_to_order
- WC_Stripe_Intent_Controller::update_failed_order_ajax * → save_intent_to_order
- WC_Stripe_Pre_Orders_Trait::process_pre_order_release_payment * → create_and_confirm_intent_for_off_session → save_intent_to_order

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 2]
```diff
@@ -992,34 +996,38 @@ public function save_source_to_order( $order, $source ) {
...
-					$order->save();
+					if ( is_callable( [ $order, 'save' ] ) ) {
+						$order->save();
+					}
 				}
+			} else {
+				WC_Stripe_Logger::log( 'Unable to update fees/net meta for order: ' . $order->get_id() );
 			}
-		} else {
+		} catch ( Exception $e ) {
```
Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Here, the following high-level methods expect this exception:
- WC_REST_Stripe_Orders_Controller::capture_terminal_payment * → capture_payment
- WC_Gateway_Stripe::process_payment * → process_response

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 3]
```diff
@@ -1543,15 +1564,19 @@ public function save_intent_to_order( $order, $intent ) {
...
-		$intent_id = $order->get_meta( '_stripe_setup_intent' );
+			// The order doesn't have a payment intent, but it may have a setup intent.
+			$intent_id = $order->get_meta( '_stripe_setup_intent' );
 
-		if ( $intent_id ) {
-			return $this->get_intent( 'setup_intents', $intent_id );
+			if ( $intent_id ) {
+				return $this->get_intent( 'setup_intents', $intent_id );
+			}
+		} catch ( WC_Stripe_Exception $e ) {
```
Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: For `get_intent_from_order`, the following methods expect the exception:
- WC_Gateway_Stripe::process_payment *
- WC_Gateway_Stripe::prepare_order_pay_page * → prepare_intent_for_order_pay_page
- WC_Gateway_Stripe::render_payment_intent_inputs * → prepare_intent_for_order_pay_page

**Review by a-danae — COMMENTED** [review]
Thanks for addressing these, Mayisha!

There are some scenarios where the exceptions aren't being handled, triggering fatal errors. But other scenarios do seem to expect the exceptions.

By catching them in the low-level methods and not letting the exception bubble up, I'm concerned that the high-level functionality that depends on them won't be triggered. For example, we'll stop displaying relevant error messages in some interfaces, or triggering error actions for some flows.

I didn't check all flows, but I left a comment below for the few ones I checked. The asterisk (*) is for the high-level method that expects the exception.

I think it'd be better to check the specific scenarios where the exceptions aren't expected but _could_ be triggered, and catch them on a case-by-case basis. But let me know if I missed something!

**Comment by Mayisha** [comment]
Removed the unnecessary try/catch from the functions in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2668/commits/40a0bfe6e5a0b8128aa14a616d09d2f7bf984df9 where the higher level functions expect the exception.

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 4]
```diff
@@ -1086,33 +1086,46 @@ public function process_refund( $order_id, $amount = null, $reason = '' ) {
...
 				}
 			}
-		}
 
-		if ( ! $intent_cancelled && 'yes' === $captured ) {
-			$response = WC_Stripe_API::request( $request, 'refunds' );
+			if ( ! $intent_cancelled && 'yes' === $captured ) {
+				$response = WC_Stripe_API::request( $request, 'refunds' );
+			}
+		} catch ( WC_Stripe_Exception $e ) {
```
Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php:1118]: Should we let this exception bubble up?

Looks like WooCommerce would [catch it](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-order.php#L395).

The only path I'm seeing with this method is
[WC_Order::status_transition()](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-order.php#L387-L443) * -> WC_Stripe_Order_Handler::construct() -> actions woocommerce_order_status_cancelled and woocommerce_order_status_refunded -> WC_Stripe_Order_Handler::cancel_payment() -> WC_Stripe_Order_Handler::process_refund()

File: includes/class-wc-stripe-payment-tokens.php [hunk 5]
```diff
@@ -262,28 +267,33 @@ public function woocommerce_get_customer_upe_payment_tokens( $tokens, $user_id,
...
 				}
+				add_action( 'woocommerce_get_customer_payment_tokens', [ $this, 'woocommerce_get_customer_payment_tokens' ], 10, 3 );
 			}
-			add_action( 'woocommerce_get_customer_payment_tokens', [ $this, 'woocommerce_get_customer_payment_tokens' ], 10, 3 );
+		} catch ( WC_Stripe_Exception $e ) {
+			wc_add_notice( $e->getLocalizedMessage(), 'error' );
+			WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
 		}
 
 		// Eliminate remaining payment methods no longer known by Stripe.
```
Comment (a-danae) [inline includes/class-wc-stripe-payment-tokens.php]: Should we add these lines (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2668/files#diff-f80280bf89ae5350f2729f8c88d0d39cd4df34c7f13fe87db1445bcb03d6ac34R299-R306) that eliminate the remaining payment methods within the `try` block?

These lines would still execute if an exception is thrown. We unset some items within $remaining_tokens down  in the `try` block (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2668/files#diff-f80280bf89ae5350f2729f8c88d0d39cd4df34c7f13fe87db1445bcb03d6ac34R289). My concern is that, if an exception is thrown, some items of $remaining_tokens won't be unset and may get unexpectedly deleted.

File: includes/class-wc-stripe-payment-tokens.php [hunk 6]
```diff
@@ -364,7 +374,11 @@ public function woocommerce_payment_token_deleted( $token_id, $token ) {
 		$stripe_customer = new WC_Stripe_Customer( get_current_user_id() );
 		if ( WC_Stripe_Feature_Flags::is_upe_checkout_enabled() ) {
 			if ( WC_Stripe_UPE_Payment_Gateway::ID === $token->get_gateway_id() ) {
-				$stripe_customer->detach_payment_method( $token->get_token() );
+				try {
```
Comment (a-danae) [inline includes/class-wc-stripe-payment-tokens.php:378]: How about also having a `try` block to handle $stripe_customer->delete_source() below (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2668/files#diff-f80280bf89ae5350f2729f8c88d0d39cd4df34c7f13fe87db1445bcb03d6ac34R385) too? Looks like it can throw an Exception as well.

File: includes/class-wc-stripe-payment-tokens.php [hunk 7]
```diff
@@ -262,28 +267,33 @@ public function woocommerce_get_customer_upe_payment_tokens( $tokens, $user_id,
...
-				} else {
-					// Count that existing token for payment method is still present on Stripe.
-					// Remaining IDs in $remaining_tokens no longer exist with Stripe and will be eliminated.
-					unset( $remaining_tokens[ $payment_method->id ] );
 				}
+				add_action( 'woocommerce_get_customer_payment_tokens', [ $this, 'woocommerce_get_customer_payment_tokens' ], 10, 3 );
 			}
-			add_action( 'woocommerce_get_customer_payment_tokens', [ $this, 'woocommerce_get_customer_payment_tokens' ], 10, 3 );
+		} catch ( WC_Stripe_Exception $e ) {
+			wc_add_notice( $e->getLocalizedMessage(), 'error' );
```
Comment (a-danae) [inline includes/class-wc-stripe-payment-tokens.php:305]: Just curious. Why do we add a WC notice in this and woocommerce_get_customer_payment_tokens_legacy cases, but not in other of the exceptions we're catching?

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 8]
```diff
@@ -1247,7 +1247,12 @@ public function set_payment_method_title_for_order( $order, $payment_method_type
 	 * @return string
 	 */
 	public function generate_upe_checkout_experience_accepted_payments_html( $key, $data ) {
-		$stripe_account      = $this->stripe_request( 'account' );
+		try {
+			$stripe_account = $this->stripe_request( 'account' );
+		} catch ( WC_Stripe_Exception $e ) {
+			WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
```
Comment (a-danae) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:1253]: Shouldn't we bail out, although gracefully, if $stripe_account triggers an exception?

This variable is used below. I'd expect some errors down this method if an exception is thrown by $this->stripe_request( 'account' ) because $stripe_account won't be the object this method expects.

**Review by a-danae — CHANGES_REQUESTED** [review]
Thanks for the update @Mayisha! 
I only noticed one more case where a higher-level method expects an exception, but let me know if I got anything wrong. Besides that, I only left some minor comments.

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 4 above)
Comment (Mayisha) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php:1118]: This one I actually kept similar to the case https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2668/files#diff-ff9f40fcdc185cf88b584288b5b59cb3f733a3fd3d53a3ce383e43da20104992R1131-R1141 when there is a `$response ->error` present. What do you think about keeping them similar? :eyes:

File: includes/class-wc-stripe-payment-tokens.php (hunk 7 above)
Comment (Mayisha) [reply includes/class-wc-stripe-payment-tokens.php:305]: These 2 will add the error notice on the checkout page. I have noticed that if anything goes wrong, we show an error notice on the checkout page. For this reason, I have added these 2 notices here. :sweat_smile:

File: includes/class-wc-stripe-payment-tokens.php (hunk 6 above)
Comment (Mayisha) [reply includes/class-wc-stripe-payment-tokens.php:378]: Good catch :+1:

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php (hunk 8 above)
Comment (Mayisha) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:1253]: As it is gracefully handled below with `isset( $stripe_account->capabilities )` and `isset( $stripe_capabilities[ $capability_id ] )` checked, we should not get any error even if `$stripe_account` got an exception. We are good here :sunglasses:

File: includes/class-wc-stripe-payment-tokens.php (hunk 5 above)
Comment (Mayisha) [reply includes/class-wc-stripe-payment-tokens.php]: Agree with this. Moved this part within the try/catch. :heavy_check_mark:

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php (hunk 8 above)
Comment (a-danae) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:1253]: Right! Scratch that. Thanks for clarifying it!

Btw, do you see who invokes this method? I was trying to find the call stack, but I'm missing who calls it. I don't see it in the PR (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1646/files) that introduced this method either.

Comment (Mayisha) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:1253]: Looks like it's getting rendered by WooCommerce. WooCommerce [generates the HTML](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php#L348) for settings based on [the type](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php#L345). On the Stripe end the type is being [set here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/fix/displaying-of-prb-wallets/includes/admin/stripe-settings.php#L285).

File: includes/class-wc-stripe-payment-tokens.php (hunk 7 above)
Comment (a-danae) [reply includes/class-wc-stripe-payment-tokens.php:305]: Gotcha, thanks!

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 4 above)
Comment (a-danae) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php:1118]: Nice! Sounds good to me. I've also tested a forced failure here and things work as expected this way.

**Review by a-danae — APPROVED** [review]
Big thanks for replying to my bunch of questions, @Mayisha ! 🙌  Things look good to me!
