### PR TITLE
Do not return WP_Error when processing sub renewals

### LINKED ISSUE #1094: In some cases, process_subscription_payment returns WP_Error instead of throwing a catchable Exception
**Describe the bug**

In the method process_subscription_payment, within includes/compat/class-wc-stripe-subs-compat.php, there are two cases where WP_Error is returned, instead of the correct exception being thrown. These are the cases:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/71e259406b74f9a44a56e888f18eeaeab1d473f5/includes/compat/class-wc-stripe-subs-compat.php#L222

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/71e259406b74f9a44a56e888f18eeaeab1d473f5/includes/compat/class-wc-stripe-subs-compat.php#L237

What should happen with these errors, is a WC_Stripe_Extension exception being thrown. Like how it is handled here, in the same method:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/71e259406b74f9a44a56e888f18eeaeab1d473f5/includes/compat/class-wc-stripe-subs-compat.php#L278

Because then WC_Stripe_Extension is caught here:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/71e259406b74f9a44a56e888f18eeaeab1d473f5/includes/compat/class-wc-stripe-subs-compat.php#L320

And handled properly:

- An error is logged
- Order is set to failed
- wc_gateway_stripe_process_payment_error action is triggered

In it's current state, in these cases, the renewal payment fails silently. No emails are sent to the customers, order status isn't changed, so there's no way of knowing there's been a problem, unless you know to tail the logs looking for these errors.

**To Reproduce**
1. Create a subscription using Woocommerce Subscriptions or another subscriptions plugin that uses the WC Subscriptions system
2. After the initial order, remove the order's "_stripe_customer_id" meta
3. That should trigger the "Customer not found" case

**Expected behavior**
Order is shown as failed, customer gets payment failed email

**Environment (please complete the following information):**
 - WordPress Version N/A
 - WooCommerce Version N/A
 - Stripe Plugin Version - any, at least all the recent ones

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #1094 

#### Changes proposed in this Pull Request:
- Replaced `WP_Error` with `WC_Stripe_Exception` to be in line with the rest of the function

Despite the scary repro steps below, this PR is just bringing the code in line with the rest of the function. WP_Errors would not be handled at all and are just an early return, while the Exceptions would be logged in [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/323cf377574cd942b48647436bc3af315c4e5449/includes/compat/class-wc-stripe-subs-compat.php#L361) and the order would be marked as failed.

#### Test steps:
* Enable logging in this extension
* Purchase a subscription
* In wp-admin, open the subscription
* Under actions, select "Create pending renewal order"
* In the database, delete `_stripe_customer_id` from `wp_postmeta` for that new renewal order ID
* Go back to the pending renewal order and select `Retry renewal payment` action
* The order should be marked as failed and a message like `Customer not found while processing renewal for order ***` should appear in the logs.

### CODE REVIEW

**Comment by allendav** [comment]
Since the error messages returned are identical, could that make debugging harder? Should the SEPA related ones mention SEPA?

File: includes/compat/class-wc-stripe-subs-compat.php [hunk 1]
```diff
@@ -267,7 +271,10 @@ public function process_subscription_payment( $amount = 0.0, $renewal_order, $re
 			$source_object   = $prepared_source->source_object;
 
 			if ( ! $prepared_source->customer ) {
-				return new WP_Error( 'stripe_error', __( 'Customer not found', 'woocommerce-gateway-stripe' ) );
+				throw new WC_Stripe_Exception(
+					'Customer not found while processing renewal for order ' . $renewal_order->get_id(),
```
Comment (vbelolapotkov) [inline includes/compat/class-wc-stripe-subs-compat.php:275]: As we have both customer term in WooCommerce and Stripe it may be a bit confusing. At least it's sometimes confusing to me. How about making the message more explicit, e.g. `Failed to process renewal for order "orderId". Stripe customer id is missing in the order.`

**Comment by vbelolapotkov** [comment]
> Since the error messages returned are identical, could that make debugging harder? Should the SEPA related ones mention SEPA?

@allendav don't think this is a problem because the order id is mentioned in the log message and the next debugging step would be to check billing details in the specific order anyway.

File: includes/compat/class-wc-stripe-subs-compat.php (hunk 1 above)
Comment (marcinbot) [reply includes/compat/class-wc-stripe-subs-compat.php]: Fixed in 1f22ccf
