### PR TITLE
Prevent tokens associated with sources from being displayed with the updated checkout experience

### LINKED ISSUE #3134: SEPA payments fail when using Sources tokens with the Payment Methods API
**Describe the bug**

The following flows fail when using a SEPA source with the Payment Methods API (we also have to check the behavior for cards):

- Regular purchase

> There was an error processing the payment: Using a SEPA Debit Source in the `payment_method` field has been deprecated and is no longer a valid integration path. Please migrate your Source objects to PaymentMethods using the Dashboard migration tooling here: https://dashboard.stripe.com/sources-migration

- Purchasing a subscription

> There was an error processing the payment: Using a SEPA Debit Source in the `payment_method` field has been deprecated and is no longer a valid integration path. Please migrate your Source objects to PaymentMethods using the Dashboard migration tooling here: https://dashboard.stripe.com/sources-migration

- Purchasing a subscription with a free trial

> SEPA Debit Sources used as a PaymentMethod are not supported with the Setup Intents API. These Sources have mandate information and thus are already "set up"

- Changing the payment method of a subscription as a shopper

> SEPA Debit Sources used as a PaymentMethod are not supported with the Setup Intents API. These Sources have mandate information and thus are already "set up".

A merchant reported the following error, but I haven't been able to replicate it so far:

> SEPA Debit Sources used as a PaymentMethod have mandate information already stored. You cannot pass the `mandate_data` or `mandate` parameters. Please re-confirm without those parameters.

**To Reproduce**
1. Check out 8.0.1. There's an error in later versions where SEPA payment methods can't be saved on the Legacy experience
2. As a merchant, enable the Legacy experience
3. As a shopper, add a product to the page and go to the checkout page
4. Check off "Save payment method for future purchases"
5. Use a SEPA src_ payment method to complete the purchase. Like AT611904300234573201
6. Checkout the latest Stripe version
7. As a merchant, disable the Legacy experience. This will make requests go through the Payment Methods API
8. As a shopper, add a product to your cart and go to the checkout page
9. Use the SEPA payment methods you saved previously
10. Notice the payment fails, and the following error is displayed:

> There was an error processing the payment: Using a SEPA Debit Source in the `payment_method` field has been deprecated and is no longer a valid integration path. Please migrate your Source objects to PaymentMethods using the Dashboard migration tooling here: https://dashboard.stripe.com/sources-migration

**Expected behavior**

TBD.

a. Don't display src_ payment methods when the Legacy experience is disabled?
- This could affect subscription renewals, which do work with src_
- It wouldn't be a smooth transition for shoppers, who would find all of they payment methods gone once the merchant disabled the Legacy experience. Although the payment methods they see today won't work anyway, so maybe this wouldn't be a problem.

b. Migrate src_ tokens to pm_?
- We'll depend on the merchant to run the migration on their end

**Reports**
- 7886598-zd-a8c
- https://wordpress.org/support/topic/no-sepa-payment-with-new-checkout-experience/
- 8119078-zd-a8c
- 8090629-zd-a8c
- 8130440-zd-a8c
- https://wordpress.org/support/topic/using-a-sepa-debit-source-in-the-payment_method-field-has-been-deprecated/
- 8115012-zd-a8c
- 8049601-zd-a8c
- 8168237-zd-a8c

### PR DESCRIPTION
**Pull request by a-danae**
Fixes #3134

## Changes proposed in this Pull Request:

- Stop creating tokens for sources attached to the customer when the updated checkout experience (PaymentMethods API) is used.
- Delete the local tokens associated with sources.

This PR doesn't handle creating tokens because they will already be created. If sources were migrated for the merchant account, the shopper will have payment methods attached for these sources. We're [already creating tokens](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8.4.0/includes/class-wc-stripe-payment-tokens.php#L313-L319) for payment methods that exist in Stripe and not locally. 

#### Setup
1. Select EUR as the store currency
3. Check out 8.0.1. There's an error in later versions where SEPA payment methods aren't attached to the customer on the Legacy experience
5. As a merchant, enable the Legacy experience
4. Enable SEPA under the Payment methods tab
6. As a shopper, go to My account > Payment methods > Add payment methods
7. Add some SEPA payment methods. Find some account numbers [here](https://docs.stripe.com/sources/sepa-debit#testing)
8. Checkout the latest Stripe version
9. As a merchant, disable the Legacy experience. This will make requests go through the Payment Methods API

#### Confirm src_ tokens are not displayed

1. In the database, go to the `woocommerce_payment_token` table
2. Retrieve the tokens for the shopper you used to add payment methods
3. Confirm there are no rows where the `gateway_id` = `stripe_sepa_debit` and the `token` = `src_%`
4. As a shopper, go to the checkout page
5. Confirm no payment methods are displayed for SEPA
6. Confirm step 3 is still true

#### Confirm existing src_ tokens are deleted

1. Check out `develop`
2. As a shopper, go to the checkout page
3. Confirm some payment methods are displayed for SEPA
4. In the database, go to the `woocommerce_payment_token` table
5. Retrieve the tokens for the shopper you used to add payment methods
7. Confirm there are some rows where the `gateway_id` = `stripe_sepa_debit` and the `token` = `src_%`
8. Check out this branch
9. Go to the checkout page
10. Confirm no payment methods are displayed for SEPA
11. On the `woocommerce_payment_token` table, confirm there are no rows where the `gateway_id` = `stripe_sepa_debit` and the `token` = `src_%` for this shopper

#### Confirm migrated payment methods are created

ℹ️ You'll need to reach out to Stripe for them to perform the migration for you.

1. Request Stripe to run the src_ migration on your account. Reach out to them in Slack with your Stripe account number.
2. Go to you Stripe dashboard > The customer you used in previous steps
3. Confirm there are some SEPA payment methods using `pm_` instead of `src_`
4. As a shopper, go to the checkout page
5. Confirm there are some saved SEPA payment methods displayed
6. Confirm you can place an order with them
7. On the `woocommerce_payment_token` table:
  - Confirm there are no rows where the `gateway_id` = `stripe_sepa_debit` and the `token` = `src_%` for this shopper
  - Confirm there are tokens `gateway_id` = `stripe_sepa_debit` with a `token` = `pm_%` value for this shopper

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/class-wc-stripe-payment-tokens.php [hunk 1]
```diff
@@ -262,15 +262,19 @@ public function woocommerce_get_customer_upe_payment_tokens( $tokens, $user_id,
...
 				if ( in_array( $token->get_gateway_id(), self::UPE_REUSABLE_GATEWAYS_BY_PAYMENT_METHOD, true ) ) {
 
-					// APM tokens from before Split PE was in place that will get removed.
-					if ( 'stripe' === $token->get_gateway_id() && 'sepa' === $token->get_type() ) {
+					// Remove the following deprecated tokens:
+					// - APM tokens from before Split PE was in place.
+					// - Tokens using the sources API. Payments using these will fail with the PaymentMethods API.
+					if (
+						( 'stripe' === $token->get_gateway_id() && 'sepa' === $token->get_type() ) ||
+						str_starts_with( $token->get_token(), 'src_' )
```
Comment (a-danae) [inline includes/class-wc-stripe-payment-tokens.php:276]: Alternatively, I [evaluated](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3241/commits/1827a7b613dc639ccde4cd90d489ac5f6c590238) only removing the local sources tokens _when_ they were already migrated on the Stripe end.

I decided to take the current approach because:
- Processing a payment with a source using the PaymentMethods API will fail
- Assuming the merchant hasn't migrated their sources, the solution for the shopper would be to save the payment method again
- With the current approach, they won't see any of their saved payment methods. This isn't ideal, but probably a better experience than having their payment fail
- If they see their payment methods displayed, they won't likely try to save a new one

Happy to take a different approach!

**Review by wjrosa — APPROVED** [review]
Code is good and works as expected!

> 3. Confirm there are no rows where the gateway_id = stripe_sepa_debit and the token = src_%

Screenshot 2024-07-04 at 19 19 41

> 5. Confirm no payment methods are displayed for SEPA

Screenshot 2024-07-04 at 19 21 47

> 3. Confirm some payment methods are displayed for SEPA

Screenshot 2024-07-04 at 19 23 57

> 6. Confirm there are some rows where the gateway_id = stripe_sepa_debit and the token = src_%

Screenshot 2024-07-04 at 19 24 31

> 9. Confirm no payment methods are displayed for SEPA

Screenshot 2024-07-04 at 19 25 15

> 10. On the woocommerce_payment_token table, confirm there are no rows where the gateway_id = stripe_sepa_debit and the token = src_% for this shopper

Screenshot 2024-07-04 at 19 25 57

> 5. Confirm there are some saved SEPA payment methods displayed

Screenshot 2024-07-04 at 19 37 30

As for the migration part, my tokens were migrated after I requested it in Slack, but I had to test multiple PRs later and had to remove those from my test store :(

File: includes/class-wc-stripe-payment-tokens.php (hunk 1 above)
Comment (giilby) [reply includes/class-wc-stripe-payment-tokens.php:276]: Hi @a-danae! Thanks for your work on this plugin. I just filed https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3498 because I think there might be a slight misunderstanding here. You say, "Processing a payment with a source using the PaymentMethods API will fail," but according to [Stripe's API Docs](https://docs.stripe.com/payments/payment-methods/transitioning#compatibility), they do support using credit card Sources with the new Payment Methods API.

Comment (james-allan) [reply includes/class-wc-stripe-payment-tokens.php:276]: @giilby Danae no longer works on this project. I don't know exactly what she meant by that comment, however, IIRC the issue we were seeing is specifically related to SEPA. If you look at the issue this PR was created to address (https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3134) it specifically mentions SEPA. 

At the time `src_` tokens were synonymous with SEPA tokens and SEPA sources were/are failing when using the Payment methods API. While that Stripe doc you mentioned says that sources will continue to work with the Payment Methods API, the Sources Doc (https://docs.stripe.com/sources) says that Source objects for local payment methods (LPM), like SEPA, won't work, are deprecated and we should no longer generate Source objects for card payments either.  

So I think putting those two points together -- **source objects linked to cards should continue to work**, however **source objects for local methods won't**. 

We should update the code added in this PR to make sure card source objects can still be used, while source objects for LPMs don't. I'll make a comment on your issue to make sure that nuance is captured.
