### PR TITLE
Fix preferred card brand selection

### LINKED ISSUE #3167: Confirm we're passing the expected request body for co-branded cards
This issue aims to confirm whether our requests for co-branded cards contain the correct information.

Right now, looks like we're only using the preferred network to store it under the `_stripe_card_brand` order meta, but I didn't find any other use of this information.

I temporarily removed the request parameters passed when updating a payment intent in [this other PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3161) because it was failing, but it'd be good to double-check what the correct parameters are.

## Questions

1. Should we pass any information about the co-branded card to our requests for creating and updating payment intents?
2. If so, where are we doing it?

## Some background

- In the docs, they mention passing the preferred network when creating the PaymentMethod, the PaymentIntent, and the SetupIntent. [Reference](https://docs.stripe.com/co-badged-cards-compliance?type=custom-integration#pass-network-preference-to-api)
- I see we're passing the [following information](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-intent-controller.php#L814-L821) to the request when updating a payment intent, but I don't see us passing this when creating it.
- Still, updating a payment intent with a co-branded card fails. See the replication steps below.

**Replication steps - Reusing a payment intent with co-branded cards failure**

1. Check out `trunk` or the 3.8.1 tag
3. As a shopper, add a product to the cart and proceed to checkout
4. Enter the details of a failing card, like `4000 0000 0000 0002`
5. Place the order
6. Try again using the details of a co-branded card, like `4000 0025 0000 1001`
7. On the dropdown at the right of the field, select "Cartes bancaires"
5. Notice that the payment processing fails with a 400 error code and the following information

```
parameter_unknown - payment_method_options[card][brand]
Received unknown parameter: payment_method_options[card][brand]
```

<details>

<summary>Request body</summary>

```
{
  "capture_method": "automatic",
  "payment_method": "pm_1PM51MDhoeKpknCIpl4x6gwH",
  "mandate_data": {
    "customer_acceptance": {
      "type": "online",
      "online": {
        "user_agent": "WooCommerce Stripe Gateway8.3.0; http://localhost:8082",
        "ip_address": "xxx"
      }
    }
  },
  "payment_method_options": {
    "card": {
      "brand": "cartes_bancaires"
    }
  },
  "shipping": {
    "address": {
      "country": "US",
      "line1": "Street 123",
      "state": "CA",
      "postal_code": "94110",
      "city": "Lecity",
      "line2": ""
    },
    "name": "Francis TheFrench"
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #3167

## Changes proposed in this Pull Request:

Since some weeks ago, unit tests started to fail. @a-danae created PR to fix it [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3161). The error highlights the preferred card brand parameter as invalid:
```
parameter_unknown - payment_method_options[card][brand]
Received unknown parameter: payment_method_options[card][brand]
```

By looking at [the Stripe docs](https://docs.stripe.com/api/payment_intents/object#payment_intent_object-payment_method_options-card-network) again, I see the parameter name is different. It is `network`, not `brand`. I am not sure if it was wrong since the beginning or if it was renamed just now, as this feature is new.

This PR renames the param and also simplifies part of the implementation.

## Testing instructions

- Set your Stripe account country to France and enable Cartes Bancaires on it
- Connect it to your test store
- Change your store currency to EUR
- As a shopper, add a product to the cart and proceed to checkout
- Enter the details of a failing card, like `4000 0000 0000 0002`
- Place the order
- Try again using the details of a co-branded card, like `4000 0025 0000 1001`
- On the dropdown at the right of the field, select "Cartes bancaires"
- Confirm the payment succeeded, and you can see the correct brand for the order on Stripe's dashboard

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

cc @a-danae

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 1]
```diff
@@ -2045,15 +2049,29 @@ private function prepare_payment_information_from_request( WC_Order $order ) {
...
-			$payment_information['payment_method_options'] = [
+			$payment_method_options = [
 				'wechat_pay' => [
 					'client' => 'web',
 				],
 			];
 		}
 
+		// Add the updated preferred credit card brand when defined
+		$preferred_brand = $payment_information['payment_method_details']->card->networks->preferred ?? null;
```
Comment (diegocurbelo) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: We could use `$payment_method_object` instead of `$payment_information['payment_method_details']`, which got me thinking that maybe `$payment_method_details` is a more descriptive name? 🤷🏼 
```suggestion
		$preferred_brand = $payment_method_object->card->networks->preferred ?? null;
```

**Review by diegocurbelo — APPROVED** [review]
Thanks for working on this @wjrosa ..

The code looks good... I left a comment, but variable names are subjective  🤷🏼, so feel free to disregard it and merge it once the `readme` and `changelog` conflicts are solved 🚢 

All PR checks pass now (👏🏼 ), and it tests well.
image 2
