### PR TITLE
Hide Multibanco on the checkout page when the Stripe account's country doesn't support it

### LINKED ISSUE #3227: Hide Multibanco on the checkout page when the Stripe account's country doesn't support it
**Describe the bug**

With the implementation of Multibanco using the Payment Methods API, https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3204, this payment method is being displayed on the checkout pages, even though the connected Stripe account belongs to a country that [doesn't support](https://docs.stripe.com/payments/multibanco#:~:text=Stripe%20users%20in%20the%20following%20countries%20can%20accept%20Multibanco%20payments) Multibanco.

**To Reproduce**
1. Create a Stripe account associated with a country that's not in [this list](https://docs.stripe.com/payments/multibanco#:~:text=Stripe%20users%20in%20the%20following%20countries%20can%20accept%20Multibanco%20payments), like India
2. Connect your store to this account
3. Select Euro as your store currency, at `/wp-admin/admin.php?page=wc-settings&tab=general`
4. Go to the Payment Methods tab, at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`
5. Enable Multibanco
6. As a shopper, add a product to the cart and proceed to the checkout page
7. Select Multibanco
8. Click on Place Order
9. Notice an error message is displayed saying that Multibanco isn't available for your account's country

**Expected behavior**
Multibanco must not be displayed on the checkout pages when it's not available for the connected account's country.

It had this behavior in the last release. Also, other country-limited payment methods follow this behavior, like OXXO and Boleto.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #3227 

This PR fixes the 

## Changes proposed in this Pull Request:
- Added the supported country list for Multibanco. Find the list of supported countries in Stripe documentation [here](https://docs.stripe.com/payments/multibanco).
- Multibanco is available on the settings page only when the connected Stripe account is of a supported country.

## Testing instructions

1. Create a Stripe account associated with a country that's not in [this list](https://docs.stripe.com/payments/multibanco#:~:text=Stripe%20users%20in%20the%20following%20countries%20can%20accept%20Multibanco%20payments), like India.
2. Connect your store to this account.
3. Select Euro as your store currency.
4. Go to the Stripe settings page and confirm that Multibanco is not in the payment method list. 
5. Now connect to a US Stripe account and recheck the payment methods list.
6. This time Multibanco should be present in the payment methods list.
7. Enable Multibanco.
8. As a shopper make a purchase with Multibanco. Confirm that the payment is successful and the order is placed.

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php [hunk 1]
```diff
@@ -21,6 +21,7 @@ public function __construct() {
 		$this->title                = __( 'Multibanco', 'woocommerce-gateway-stripe' );
 		$this->is_reusable          = false;
 		$this->supported_currencies = [ 'EUR' ];
+		$this->supported_countries  = [ 'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GI', 'GR', 'HU', 'IE', 'IT', 'LV', 'LI', 'LT', 'LU', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'CH', 'GB', 'US' ];
```
Comment (james-allan) [inline includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php:24]: Screenshot 2024-07-16 at 2 02 16 PM

Confirmed that this list matches. 👍

**Comment by james-allan** [comment]
**VERIFY BUG**
Confirmed that on `develop`, after connecting to an Indian based Stripe account that Multibanco is listed. 

<p align="center">
Screenshot 2024-07-16 at 1 56 05 PM
</p> 

Confirmed that on `develop` if you attempt to make a purchase using this Indian based account, it will fail:

<p align="center">
Screenshot 2024-07-16 at 1 59 19 PM
</p>

--- 

**VERIFY FIX**

- After checking out this PR, Multibanco is no longer listed on the settings page for India (ineligible) merchants. ✅ 
- Changing to a US based account which presents Euros, Multibanco is available. ✅

<p align="center">
Screenshot 2024-07-16 at 2 15 28 PM
</p>  

- If you change out of Euros, Multibanco is no longer available. ✅

**Review by james-allan — APPROVED** [review]
@Mayisha changes look good and test well. Just noting that we'll need a changelog entry. :)
