### PR TITLE
Fix error handling in subscription renewal processing

### LINKED ISSUE #4842: subscription payment retry
### Description

When a subscription renewal is processed - all (scheduled action “subscription payment retry” or manual action “wcs_retry_renewal_payment” on the order), I get this error:

Call to a member function unlock_order_payment() on null in:
wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php:522

### System report

WordPress: 6.8.3
WooCommerce Stripe Gateway: 10.1.0
WooCommerce Subscriptions: 8.1.0
PHP: 8.3

</details>

### Error

2025-12-03T07:02:13+00:00 Erreur scheduled action 945343 (subscription payment retry) failed to finish processing due to the following exception: Call to a member function unlock_order_payment() on null in /home/sites/www_XXX/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php:522  
Contexte supplémentaire
2025-12-03T07:02:13+00:00 Erreur scheduled action 945343 (subscription payment retry) failed to finish processing due to the following exception: Call to a member function unlock_order_payment() on null in /home/sites/www_XXX/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php:522  
Contexte supplémentaire
{
    "action_args": "order_id: 1233463",
    "error_trace": "#0 /home/sites/www_XXX/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php(364): WC_Stripe_Payment_Gateway->process_subscription_payment()n#1 /home/sites/www_XXX/wp-includes/class-wp-hook.php(341): WC_Stripe_Payment_Gateway->scheduled_subscription_payment()n#2 /home/sites/www_XXX/wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters()n#3 /home/sites/www_XXX/wp-includes/plugin.php(522): WP_Hook->do_action()n#4 /home/sites/www_XXX/wp-content/plugins/woocommerce-subscriptions/includes/gateways/class-wc-subscriptions-payment-gateways.php(120): do_action()n#5 /home/sites/www_XXX/wp-content/plugins/woocommerce-subscriptions/includes/payment-retry/class-wcs-retry-manager.php(377): WC_Subscriptions_Payment_Gateways::trigger_gateway_renewal_payment_hook()n#6 /home/sites/www_XXX/wp-includes/class-wp-hook.php(341): WCS_Retry_Manager::maybe_retry_payment()n#7 /home/sites/www_XXX/wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters()n#8 /home/sites/www_XXX/wp-includes/plugin.php(570): WP_Hook->do_action()n#9 /home/sites/www_XXX/wp-content/plugins/woocommerce/packages/action-scheduler/classes/actions/ActionScheduler_Action.php(86): do_action_ref_array()n#10 /home/sites/www_XXX/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(103): ActionScheduler_Action->execute()n#11 /home/sites/www_XXX/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(188): ActionScheduler_Abstract_QueueRunner->process_action()n#12 /home/sites/www_XXX/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(158): ActionScheduler_QueueRunner->do_batch()n#13 /home/sites/www_XXX/wp-includes/class-wp-hook.php(341): ActionScheduler_QueueRunner->run()n#14 /home/sites/www_XXX/wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters()n#15 /home/sites/www_XXX/wp-includes/plugin.php(570): WP_Hook->do_action()n#16 /home/sites/www_XXX/wp-cron.php(191): do_action_ref_array()n#17 {main}"
}

### PR DESCRIPTION
**Pull request by daledupreez**
Fixes STRIPE-823

## Changes proposed in this Pull Request:

This PR updates the error handling and logic in `WC_Stripe_Subscriptions_Trait->process_subscription_payment()` to ensure we don't trigger errors from our error handling. The key changes are to track whether we've locked the current payment, and to unlock it only when we've already locked it _and_ we have a reference to our order helper object.

This PR also updates the logging for the method to use the newer `debug()` and `error()` log methods, and updates the unit tests to ensure we catch the two most likely error conditions.

## Testing instructions

* Code inspection should be a good first step here, as I haven't made changes to the core functional aspects.
* Next, we want to verify that the unit tests _fail_ against develop
   - Check out and update this branch to make sure you have all the commits: `git checkout fix/fatal-error-in-subscription-processing && git pull`
   - Now check out `develop` - `git checkout develop`
   - Now apply the unit test changes from c22cda4f15f224fdfa39619b714a92054ee6848e to the local develop: `git show -p c22cda4f15f224fdfa39619b714a92054ee6848e | git apply` (you could also cherry-pick, or any other mechanism you prefer -- this approach doesn't commit or stage any files)
   - Now run the PHP unit tests: `npm run test:php -- --filter=WC_Stripe_Subscription_Renewal_Test`
   - You should see that the `test_missing_customer` test triggers an error due to `$order_helper` being undefined
* Functionally, test that a subscription renewal works correctly (though my changes are focused on the error handling)

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 1]
```diff
@@ -513,13 +522,24 @@ public function process_subscription_payment( $amount, $renewal_order, $retry =
 				throw new WC_Stripe_Exception( print_r( $response, true ), $localized_message );
 			}
 		} catch ( WC_Stripe_Exception $e ) {
-			WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
+			WC_Stripe_Logger::error(
+				'Error processing subscription payment: ' . $e->getMessage(),
+				[
+					'order_id'          => $order_id,
```
[the remark this answers is not in the document]
Comment (daledupreez) [reply includes/compat/trait-wc-stripe-subscriptions.php]: Fixed in 55d7172abc23520dee0ab44dd6b1677eabf895dd.

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 2]
```diff
@@ -459,6 +467,7 @@ public function process_subscription_payment( $amount, $renewal_order, $retry =
 				$is_authentication_required = false;
 			} else {
 				$order_helper->lock_order_payment( $renewal_order );
+				$order_locked               = true;
```
Comment (diegocurbelo) [inline includes/compat/trait-wc-stripe-subscriptions.php:436]: [nit] I'd prefer we could get the actual lock status from `lock_order_payment()` and `unlock_order_payment()`:
```
$order_locked = $order_helper->lock_order_payment( $renewal_order );
```

But that would require a change to `lock_order_payment`, as it currently returns true if it has already been locked and false if the method just locked it. And then, in a few places, we use `lock_order_payment()` to lock or return
```
// Lock the order or return if the order is already locked.
if ( $order_helper->lock_order_payment( $order ) ) {
	return;
}
```

**Review by diegocurbelo — APPROVED** [review]
The changes look good to me.

I left a nit suggestion, but the changes required to implement it might not be worth it, at least not as part of this PR.

File: tests/phpunit/WC_Stripe_Subscription_Renewal_Test.php [hunk 3]
```diff
@@ -391,4 +388,116 @@ public function test_renewal_authorization_required() {
...
+		$this->assertEquals( $expected_raw_error, $thrown_exception->getMessage() );
+		$this->assertEquals( $expected_localized_error, $thrown_exception->getLocalizedMessage() );
+	}
+
+	public function test_payment_intent_returns_non_retryable_error() {
+		$renewal_order = WC_Helper_Order::create_order();
+		$source        = 'src_123abc';
+		$customer      = 'cus_123abc';
+
+		// Mock prepare_order_source() to return a missing customer.
```
Comment (Mayisha) [inline tests/phpunit/WC_Stripe_Subscription_Renewal_Test.php]:
```suggestion
		// Mock prepare_order_source() to return a valid customer.
```

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 4]
```diff
@@ -513,13 +522,24 @@ public function process_subscription_payment( $amount, $renewal_order, $retry =
 				throw new WC_Stripe_Exception( print_r( $response, true ), $localized_message );
 			}
 		} catch ( WC_Stripe_Exception $e ) {
-			WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
+			WC_Stripe_Logger::error(
+				'Error processing subscription payment: ' . $e->getMessage(),
```
Comment (Mayisha) [inline includes/compat/trait-wc-stripe-subscriptions.php]: Nit: just to be clear about the type.
```suggestion
				'Error processing subscription renewal payment: ' . $e->getMessage(),
```

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 5]
```diff
@@ -586,12 +606,22 @@ public function process_subscription_payment( $amount, $renewal_order, $retry =
 				$this->process_response( ( ! empty( $latest_charge ) ) ? $latest_charge : $response, $renewal_order );
 			}
 		} catch ( WC_Stripe_Exception $e ) {
-			WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
+			WC_Stripe_Logger::error(
+				'Error processing subscription payment: ' . $e->getMessage(),
```
Comment (Mayisha) [inline includes/compat/trait-wc-stripe-subscriptions.php]: Nit.
```suggestion
				'Error processing subscription renewal payment: ' . $e->getMessage(),
```

**Review by Mayisha — APPROVED** [review]
Code looks good to me and the subscription renewal is working well 👍

File: includes/compat/trait-wc-stripe-subscriptions.php (hunk 2 above)
Comment (daledupreez) [reply includes/compat/trait-wc-stripe-subscriptions.php:436]: Agreed that I think it would be clearer, but that should be handled in a dedicated PR. :-/
Could you create an issue to track the suggestion, @diegocurbelo?

**Review by daledupreez — COMMENTED** [review]
Thanks for catching those small items, @Mayisha! I've committed them in a50b02692aac79d5769047cb99f75c2e7d1aaf70
