### PR TITLE
Fix block editor incompatibility warning

### LINKED ISSUE #4949: Payment methods show an "Incompatible with block-based checkout" error when editing Checkout page
### Description

Some of the Stripe payment methods show an "Incompatible with block-based checkout" error when editing the Checkout page. All of our payment methods are compatible, so we need to address the issue.

### Steps to reproduce

1. Install the Stripe plugin and connect your account to Stripe using a US account and USD as the currency.
2. Enable all payment methods, including Klarna, Affirm, and Afterpay.
3. Open up our block-based checkout page in the page editor.
4. Select the Payment Options block.
5. Inspect the Block options in the Inspector on the right hand side.
6. See the errors.

### Expected behavior

No warnings should be shown, as the payment methods are compatible with block checkout.

### Screenshots

Image

### Additional context

Originally reported in WOOPMNT-5640
Related to https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4913
Related to STRIPE-876

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes STRIPE-913
Fixes #4949 

## Changes proposed in this Pull Request:

WooCommerce's block editor compares `globalPaymentMethods`  against `availablePaymentMethods` (JS methods registered via registerPaymentMethod()). If there is any mismatch, then the block editor shows this incompatibility notice.

In `add_gateways` method, we are adding all UPE methods irrespective of whether they are available on the checkout page or not. But in the frontend, we only [send the list ](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L538)that is enabled at checkout.

In this PR, I am filtering out the gateways that are not enabled at checkout from the `add_gateways` method so that both the list aligns.

## Testing instructions
- Connect to an US Stripe account.
- Set store currency to Euro and enable a few Euro supported payment methods like SEPA, iDeal etc.
- Switch store currency to USD enable a few other USD supported payment methods.
- Go to the checkout block editor and select the payment block.
- In `develop` notice that there are 'Incompatible with block-based checkout' beside some methods.
- In this branch, those incompatible methods should be hidden and for the displayed methods there should be no incompatibility notice.

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/class-wc-stripe.php [hunk 1]
```diff
@@ -507,16 +507,30 @@ public function add_gateways( $methods ) {
...
 						return false;
 					}
+
+					if ( $method instanceof WC_Stripe_UPE_Payment_Method ) {
+						$method_id = $method->get_id();
+						if ( isset( $upe_payment_methods[ $method_id ] ) && $upe_payment_methods[ $method_id ] instanceof WC_Stripe_UPE_Payment_Method ) {
+							if ( ! $upe_payment_methods[ $method_id ]->is_enabled_at_checkout() ) {
+								return false;
+							}
+						}
```
Comment (daledupreez) [inline includes/class-wc-stripe.php]: Why do we need to reach into `$upe_payment_methods` if we already have a UPE payment method instance?
```suggestion
						if ( ! $method->is_enabled_at_checkout() ) {
							return false;
						}
```

File: changelog.txt [hunk 2]
```diff
@@ -16,7 +16,7 @@
 * Fix - Add validation to prevent fatal error when setting default payment token if token doesn't exist
 * Fix - Validate order object before accessing methods in my account orders actions to prevent fatal errors
 * Dev - Use WC_STRIPE_PLUGIN_PATH constant instead of __DIR__ for more reliable file path resolution
-* Dev - Automate release note creation PR
```
Comment (daledupreez) [inline changelog.txt:22]: I think we should keep the previous entry here.
```suggestion
* Dev - Automate release note creation PR
* Fix - Prevent incompatibility warnings for payment methods in block editor

File: includes/class-wc-stripe.php (hunk 1 above)
Comment (daledupreez) [reply includes/class-wc-stripe.php]: I also found a case where this fails: when Optimized Checkout is enabled, we only show the main gateway, so we get warnings for all other enabled payment methods.
```suggestion
						// When Optimized Checkout is enabled, we only show the main payment gateway, so remove all other UPE methods.
						if ( $is_oc_enabled ) {
							return false;
						}

						// If the payment method is not enabled at checkout, remove it.
						if ( ! $method->is_enabled_at_checkout() ) {
							return false;
						}
```

**Review by daledupreez — CHANGES_REQUESTED** [review]
The fix doesn't handle OCS correctly, but I think I have a working proposal to address that.

File: includes/class-wc-stripe.php (hunk 1 above)
Comment (Mayisha) [reply includes/class-wc-stripe.php]: Addressed both of the comments.

**Comment by Mayisha** [comment]
Fixing tests....

File: includes/class-wc-stripe.php [hunk 3]
```diff
@@ -498,25 +498,44 @@ public function plugin_row_meta( $links, $file ) {
 	 * @version 5.6.0
 	 */
 	public function add_gateways( $methods ) {
-		$main_gateway = $this->get_main_stripe_gateway();
-		$methods[]    = $main_gateway;
+		$main_gateway  = $this->get_main_stripe_gateway();
+		$methods[]     = $main_gateway;
+		$is_oc_enabled = $main_gateway->get_option( 'optimized_checkout_element', 'no' );
```
Comment (daledupreez) [inline includes/class-wc-stripe.php]: Nit: the naming makes me think the value will be a boolean rather than `'yes'|'no'`. It may be worth making it a boolean so it matches the name.
```suggestion
		$is_oc_enabled = 'yes' === $main_gateway->get_option( 'optimized_checkout_element', 'no' );
```

**Review by daledupreez — COMMENTED** [review]
The main code changes are looking good and testing well. We just need to get the PHP tests working, and I think we should be in good shape.

There were also e2e test failures during the first run, but those looked to be due to `apt` connectivity issues during the system setup rather than anything in the tests, but those all passed on a re-run.

File: tests/phpunit/WC_Stripe_Test.php [hunk 4]
```diff
@@ -421,10 +425,12 @@ public function provide_test_add_gateways(): array {
 		$klarna_gateway = $this->getMockBuilder( \WC_Stripe_UPE_Payment_Method_Klarna::class )
 			->disableOriginalConstructor()
 			->getMock();
+		$klarna_gateway->method( 'is_enabled_at_checkout' )->willReturn( true );
 
 		$afterpay_clearpay_gateway = $this->getMockBuilder( \WC_Stripe_UPE_Payment_Method_Afterpay_Clearpay::class )
 			->disableOriginalConstructor()
 			->getMock();
+		$afterpay_clearpay_gateway->method( 'is_enabled_at_checkout' )->willReturn( true );
```
Comment (malithsen) [inline tests/phpunit/WC_Stripe_Test.php:433]: nit: Should we also include a test that returns `is_enabled_at_checkout` as `false`, since that seems to be a path that's not currently covered?

**Review by malithsen — APPROVED** [review]
This looks good to me and tests as described.

**Review by daledupreez — APPROVED** [review]
The updates look good to me! And thanks for taking on all the test updates, too!

File: tests/phpunit/WC_Stripe_Test.php (hunk 4 above)
Comment (Mayisha) [reply tests/phpunit/WC_Stripe_Test.php:433]: Added ✌️
