### PR TITLE
Prevent deletion of unrelated Stripe webhooks

### LINKED ISSUE #4116: Stripe webhooks safe deleting
**Describe the bug**
The problem is in deleting of webhooks on Stripe side by your plugin. We have different webhooks on Stripe side and they are for our business processes. During updating of your plugin we have lost our webhooks several times. By logs on Stripe side the deleting processes were initiated by your plugin. Your plugin has deleted your webhook and other webhooks (our) too.

The problem has been detected with following versions:

V 9.1.0 – 2025-01-09
V 9.3.0 – 2025-03-13
V 9.3.1 – 2025-03-14

**To Reproduce**
1. Create any additional webhook on the Stripe side for your webstore, something like https://yourstore.url/?wc-api=hook-key
2. Update the woocommerce-gateway-stripe plugin 
3.  In a few minute the created webhook on the Stripe side will be deleted.

**Expected behavior**
By default the plugin has its own webhook like https://yourstore.url/?wc-api=wc_stripe, it should be updated (delete and recreate) this webhook only. Other webhooks should be saved without any changes

**Screenshots**

Image

Image

**Environment (please complete the following information):**
 - WordPress Version latest
 - WooCommerce Version latest
 - Stripe Plugin Version 9.3.1

### PR DESCRIPTION
**Pull request by daledupreez**
Fixes STRIPE-359
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4116

## Changes proposed in this Pull Request:

This PR uses stricter checks for comparing webhooks to ensure that we don't remove webhooks that were created for other purposes. The removed webhooks reported in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4116 stem from two underlying issues:
 * When we check for valid webhooks, we remove webhook configurations that don't match the current webhook ID _and_ match the current webhook URL for the site
 * The comparison we're using for webhook URLs in `WC_Stripe_Helper::is_webhook_url()` is very loose, and only checks that the host and URL path match, which means we incorrectly detect unrelated webhooks as being from Stripe
   - @diegocurbelo mentioned that this was likely lingering from the days of manually created webhooks

The key problem stems from the matching logic, because we're not being selective enough. This PR updates the comparison logic in `WC_Stripe_Helper::is_webhook_url()` to be notably stricter:
 * We continue to ignore the protocol from the URL (though we could change this to require both are one of `http` or `https`)
 * If the host or path don't match, we flag the supplied URL as a mismatch
 * If the supplied URL doesn't include any URL query parameters, we flag it as a match, as this is likely a misconfigured webhook
    - This restriction could be relaxed, but it feels like a webhook URL with that format is going to be hard to process for _anyone_ - I am happy to take feedback on this call
 * If the webhook URL doesn't have any URL query parameters, we flag it as a mismatch, as the supplied URL has query parameters. (This won't occur for our default webhook URL, but the method allows alternative webhook URLs to be supplied.)
 * We then process each of the key/value pairs in the webhook URL, and verify that the supplied URL includes all of them.
   - If a key is missing, or the value is not identical, we flag it as a mismatch.
   - If the supplied URL includes all of those key/value pairs, and possibly additional URL parameters, we flag it as a match.

## Testing instructions

* Create a test site that has a domain reachable/addressable by webhook targets (i.e. not a local site)
* Ensure that the test site has WooCommerce installed
* Ensure that the test site has an earlier version of the WooCommerce Stripe payment gateway installed -- version 9.3.2 should be enough. You can download the older version from https://wordpress.org/plugins/woocommerce-gateway-stripe/advanced/#download-previous-link.
* Ensure that you have created a connection to Stripe where you can access the Stripe dashboard
* Check out this code locally and create an installable zip file by running `npm run build`

For ease of use, it's going to be easiest if you get set up with three tabs:
 * One open to wp-admin for your test site
 * One tab should be open to the Stripe webhook configuration. I've enabled their Workbench feature, so that's at https://dashboard.stripe.com/test/workbench/webhooks for me. (You can drop `/test` from the path if you're testing in live mode.)
 * One tab open to the Stripe logs, which is at https://dashboard.stripe.com/test/workbench/logs. (As above, remove the `/test` if you're in Live mode.)

* In the Stripe webhooks UI create the following webhook destinations:
  - `https://yourstore.url/` - you should replicate the host and path for the existing webhook that was configured during connection, but leave no other URL parameters on the URL. Feel free to name this webhook to reflect that we expect to delete it.
  - `https://yourstore.url/?wc-api=wc_stripe&test=true` - As above, replicate the host name and path from the existing webhook. You can add further URL parameters or replace the `test` URL parameter with another value. Feel free to give the webhook a name that reflects it has an extra parameter _and that we expect it to be removed_.
  - `https://yourstore.url/?test=webhook` - you should replicate the host and path as above, and can add anything to the URL query string. We expect this webhook to be retained.
 * In your wp-admin tab, navigate to _Plugins_ -> _Add Plugin_, and then click on the "Upload plugin" button
 * Select the zip file created by `npm run build` and continue with the installation
 * If you're prompted to confirm the plugin upgrade, do so.
 * Verify that the plugin upgrade proceeds
 * Refresh your Stripe webhooks tab, and verify the following:
   - the main webhook for the site (with `?wc-api=wc_stripe`) should still be present
   - the webhook with no query string should not be present
   - the webhook that included `wc-api=wc_stripe` as well as additional parameters should not be present
   - the webhook that included a non-empty test string should still be present
 * Refresh the Stripe Logs tab and verify that you see multiple `DELETE
/v1/webhook_endpoints/we_****` events, and that each of those `DELETE` events includes a User agent that starts with `WooCommerce Stripe Gateway/`

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [N/A] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/class-wc-stripe-helper.php [hunk 1]
```diff
@@ -1592,15 +1597,58 @@ public static function is_webhook_url( $url, $webhook_url = '' ) {
...
+		if ( $url_host !== $webhook_host || $url_path !== $webhook_path ) {
+			return false;
+		}
+
+		// If the supplied URL has an empty query string, we will treat it as a webhook URL for the plugin,
+		// as we're guessing that it was created manually in the long-distant past when webhook
+		// management was all manual.
+		if ( '' === $url_query ) {
+			return true;
+		}
```
Comment (Mayisha) [inline includes/class-wc-stripe-helper.php:1619]: This URL without a query param could be intentionally added too. However, in the reports, we haven't seen URLs created without any meaningful query params. So let's keep it this way and revisit if we get any complaints.

**Review by Mayisha — APPROVED** [review]
This is mostly working as expected. Thank you @daledupreez for adding these extensive checks 👍 

The only thing I noticed from my functional testing is that the URL without any query params (`https://stripe-local.jurassic.tube/`) was not deleted.

My webhooks in Stripe (manually created most of them for testing)

Screenshot 2025-04-24 at 4 09 48 PM

Remaining webhooks

Screenshot 2025-04-24 at 4 34 04 PM

I am approving this PR as this is not a blocker.

**Comment by daledupreez** [comment]
@Mayisha, I tracked down the issue to us calling `untrailingslashit()` on these lines:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b1d1a548e143327b38b1c9b5dc185ef8c5595038/includes/class-wc-stripe-helper.php#L1587-L1588

For this case where the plain URL is `https://example.com/`, the trailing `/` will get removed, which means that the path doesn't match.

I'll fix that in a follow-up PR shortly.

**Comment by LiliFlore** [comment]
Hi team,

I had been following issue #4116, which is now closed and redirects here.

While reading through #4116, I saw that one user reported the issue is still happening in version 9.4.1 — that WooCommerce Stripe Gateway is still deleting unrelated webhooks.

So I just want to clarify:
→ Was the fix supposed to be included in 9.4.1, or is it coming in a future release?

Apologies if I missed that detail — just trying to make sure before updating or re-creating webhooks again.

Thanks!
Lili

**Comment by Mayisha** [comment]
Hi @LiliFlore 

Thank you for sharing the details in [your comment](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4116#issuecomment-2806124468) in #4116. It was helpful.
We have fixed this in our working branch but the fix is not shipped yet. This fix will be out in the next version (`9.5.0`)

**Comment by LiliFlore** [comment]
Thanks for the clarification!
