### PR TITLE
Restrict Affirm and Klarna to domestic and cross EEA border transactions

### LINKED ISSUE #3096: [Klarna] Handle non-domestic transactions for shoppers from supported countries
**Describe the bug**

When the shopper is from a country supported by Klarna and the transaction isn't a domestic one, the following error gets displayed:

| Checkout Error    | Stripe Error |
| -------- | ------- |
| Screenshot 2024-04-24 at 3 10 05 pm | Screenshot 2024-04-24 at 3 11 45 pm  |

This error seems to be related to Klarna only accepting domestic transactions, with the [exception of the EEA, UK, and Switzerland](https://docs.stripe.com/payments/klarna#:~:text=If%20you%E2%80%99re%20based%20in%20the%20EEA%2C%20UK%2C%20or%20Switzerland).

We already hide Klarna for unsupported customer countries, but we're not handling the domestic transaction restriction.

**To Reproduce**

1. Connect your store to a Stripe account from a Klarna-supported country, like France
2. Enable Klarna
3. As a shopper, add a product to your cart and proceed to checkout
4. As the billing country, select one different from the one your Stripe account is from, like Australia
5. Place the order
6. Notice error mentioned above is displayed and that the payment can't be completed

**Expected behavior**

Klarna must be hidden for the shopper when the transaction isn't a domestic one. This is, when the billing country isn't the same as the Stripe account country, with the [exception of the EEA, UK, and Switzerland](https://docs.stripe.com/payments/klarna#:~:text=If%20you%E2%80%99re%20based%20in%20the%20EEA%2C%20UK%2C%20or%20Switzerland).

**Additional context**

Mentioned by @james-allan in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3040#pullrequestreview-2018712355

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3096 

## Changes proposed in this Pull Request:

Customers paying with Klarna, Affirm and Afterpay/Clearpay have specific cross border restrictions they must adhere to. ie Customers can only purchase from the same country the Stripe account is located. eg AU to AU. The one exception to this is Klarna where customers and merchants located in the European Economic Area (EEA) + the UK and Switzerland can also transact. eg a customer in the UK can transact with a merchant in Germany. 

This is documented in Stripe docs: 

- https://docs.stripe.com/payments/klarna
- https://docs.stripe.com/payments/afterpay-clearpay
- https://docs.stripe.com/payments/affirm

This PR implements this restriction by ensuring that the payment method is only enabled on checkout if the transaction is considered domestic using their respective ruleset. 

### Strictly Domestic - eg US.

1. Add Stripe API credentials for a country that is eligible for Klarna eg US. 
2. Make sure to set your store currency to the matching currency. 
3. Enable Klarna as a payment method. 
4. Add a simple product to your cart. 
5. Go to the checkout. 
6. Change your billing country to a country that doesn't match your Stripe Account's base country. eg if your account is in the US, set it AU or something else. 
7. On this branch Klarna should not be available. 
8. Change your billing country to match the stripe accounts country. 
9. It should now be shown. 

### EEA 

1. Create a EU based Stripe Account
1. Add Stripe API credentials for a country that is eligible for Klarna and located in the EU eg France. 
2. Make sure to set your store currency to the matching currency eg Euro. 
3. Enable Klarna as a payment method. 
4. Add a simple product to your cart. 
5. Go to the checkout. 
6. Change your billing country to a country any country in the EU that doesn't match your Stripe Account's base country. eg if your account is in the France, set it Germany or something else. 
7. Klarna should be available. 
8. Change your billing country to match the Stripe account's country. 
7. Klarna should be available. 
8. Change your billing country to the US or AU etc.
9. Klarna shouldn't be available.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Comment by james-allan** [comment]
Placing this one on-hold as I think there's a better way to approach this and it will fix it for the Block checkout too.

**Comment by james-allan** [comment]
@a-danae do you mind reviewing this one. I've tweaked your code that you introduced in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3040 so wanted to double check this is inline with your understanding of the code you introduced.

File: includes/payment-methods/class-wc-stripe-upe-payment-method.php [hunk 1]
```diff
@@ -258,10 +258,13 @@ public function is_enabled_at_checkout( $order_id = null, $account_domestic_curr
 	/**
 	 * Returns the supported customer locations for which charges for a payment method can be processed.
 	 *
-	 * @return array
+	 * @return array Supported customer locations.
 	 */
-	public function get_countries() {
```
Comment (james-allan) [inline includes/payment-methods/class-wc-stripe-upe-payment-method.php:276]: This function was only used to populate the JS data with a list of eligible countries. Given I've changed it's purpose to return billing countries, I changed the name. Because this function is unreleased, there are no backwards compatibility concerns here.

**Review by a-danae — APPROVED** [review]
Thanks for tackling this, @james-allan ! Things look good to me 👍 

I tested the following scenarios:

US Stripe account
✅ Domestic country - US
✅ Non-domestic, Klarna-supported country - AU
✅ Non-supported country - MX

France Stripe account
✅ Domestic country - FR
✅ Country from within the EEA - ES
✅ Non-domestic, Klarna-supported country - AU
✅ Non-supported country - MX

UK Stripe account
✅ Domestic country - UK
✅ Non-domestic, Klarna-supported country - AU
✅ Non-supported country - MX

🟡 Cross-border transactions where the currency of the Stripe account and the customer billing country don't match are failing. We could address that separately - https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3118

This PR also fixed a console error we were getting when changing the billing country from a non-supported to a supported one 🎉 

Glad to see this merged. Thanks again!

**Comment by a-danae** [comment]
Merging this PR to create the test package!
