### PR TITLE
Address QIT PHPStan test errors

### LINKED ISSUE #3256: Address QIT PHPStan test errors
As identified in the [Phase 1 assessment](https://10upwoo.wordpress.com/2024/07/01/woocommerce-extension-assessment-woocommerce-stripe-payment-gateway/), Woo QIT is not being checked or enforced on this extension. However, when the QIT Activation tests are run on the develop branch manually, the tests [fail](https://qit.woo.com/?qit_results=4627218.WxDJoqJ4Ulmou4lmTbHcTs96Mzn5otcsTqZKclZgp0DhbFInkMBr0fS2r8EFllAK) with 215+ File Errors. 

The goal of this task is to add Woo QIT as a GitHub Action to check PHPStan tests on PRs, and then to resolve any errors to ensure the test passes on the develop branch.

### PR DESCRIPTION
**Pull request by faisal-alvi**
Fixes #3256

## Changes proposed in this Pull Request:

The PHPStan test errors reported by the QIT have been fixed in this PR. 

The WC_Stripe class not found errors are being skipped because there are over 100 locations where ignore statements would need to be added. After [internal discussion](https://fueled10up.slack.com/archives/C01UCQGPBDJ/p1720795010181959?thread_ts=1720782873.335989&cid=C01UCQGPBDJ), we concluded that we currently do not have the capability to override the config file to globally ignore these errors. As a result, we have skipped the errors and not added ignore statements too, which will lead to QIT test failures. We must ignore these errors for now.

## Testing instructions

1. Run QIT PHPStan Test GH action. It may fail for a few locations for now those are intentional.
2. Regression testing of the extension.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

## Changelog

Fix - Address QIT PHPStan test errors

### CODE REVIEW

**Comment by faisal-alvi** [comment]
Noting that the `fix-qit-security` is set as a base branch as the required workflow files are added there but it seems like the QIT won't run here until we change the base branch to `develop`.

File: includes/abstracts/abstract-wc-stripe-connect-rest-controller.php [hunk 1]
```diff
@@ -94,7 +94,7 @@ public function get_internal( $request ) {
 
 		$this->prevent_route_caching();
 
-		return $this->get( $request );
+		return $this->get( $request ); // @phpstan-ignore-line
```
Comment (dkotter) [inline includes/abstracts/abstract-wc-stripe-connect-rest-controller.php]: Anywhere we are ignoring something, would be nice to add a short comment explaining why

Comment (dkotter) [reply includes/abstracts/abstract-wc-stripe-connect-rest-controller.php]: In addition, now looking at the rest of the changes here, most of what we're doing is just ignoring lines. I'm not super familiar with PHPStan but assuming it's similar to PHPCS, are there consistent things we are ignoring such that we could ignore those globally, in some sort of config file? This would prevent us from littering the code with a bunch of ignore statements

**Review by dkotter — CHANGES_REQUESTED** [review]

**Comment by faisal-alvi** [comment]
@dkotter Thanks for the feedback; it has been addressed. Additionally, as per our [internal discussion](https://fueled10up.slack.com/archives/C01UCQGPBDJ/p1720795010181959?thread_ts=1720782873.335989&cid=C01UCQGPBDJ), I've removed unnecessary ignore statements and provided reasons for the remaining ones.

**Review by dkotter — APPROVED** [review]

**Comment by vikrampm1** [comment]
@ankitguptaindia @qasumitbagthariya this is ready for QA.

**Comment by qasumitbagthariya** [comment]
### QA Update ✅ 

---

I have verified this PR in the `fix-qit-phpstan-errors` branch and it is functioning as intended.

I tested the following on this branch:

- Credit / Debit card
- Link payment
- Google pay
- Bancontact
- iDEAL
- Przelewy24
- Alipay

**Testing Environment** 

<Details>

- WordPress: 6.6.1
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.2
- WooCommerce - 9.1.4
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 

</Details>

image


Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)

Note:
While testing i found one issue which is logged [here.](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3324)

**Review by qasumitbagthariya — APPROVED** [review]

**Comment by jeffpaul** [comment]
@Mayisha checking in on your code review here to see if there's someone else on the team we should ping for this PR?

File: includes/compat/class-wc-stripe-email-failed-authentication-retry.php [hunk 2]
```diff
@@ -71,7 +71,7 @@ public function trigger( $order_id, $order = null ) {
 
 		$this->find['retry-time'] = '{retry_time}';
 		if ( class_exists( 'WCS_Retry_Manager' ) && function_exists( 'wcs_get_human_time_diff' ) ) {
-			$this->retry                 = WCS_Retry_Manager::store()->get_last_retry_for_order( wcs_get_objects_property( $order, 'id' ) );
+			$this->retry                 = function_exists( 'wcs_get_objects_property' ) ? WCS_Retry_Manager::store()->get_last_retry_for_order( wcs_get_objects_property( $order, 'id' ) ) : null;
 			$this->replace['retry-time'] = wcs_get_human_time_diff( $this->retry->get_time() );
```
Comment (Mayisha) [inline includes/compat/class-wc-stripe-email-failed-authentication-retry.php]: When `$this->retry` is `null` then this line will cause error for `$this->retry->get_time()`.

**Comment by jeffpaul** [comment]
@woocommerce/quark is anyone else able to help review this PR?

**Comment by Mayisha** [comment]
Hey @jeffpaul 👋 

I tested this PR while testing #3260 last week. Apologies for not adding the comment/approval and creating confusion.

**Review by Mayisha — APPROVED** [review]
Thanks for working on the fix.

✅ In the legacy checkout experience, checkout with a regular card, 3ds card and other payment methods are working correctly. Tested with iDeal, Multibanco and AfterPay from other payment methods.
✅ In the new checkout experience, checkout with a regular card, 3ds card and other payment methods are working correctly. Tested with iDeal, Multibanco and AfterPay from other payment methods.

We are missing the changelog entry. Please add this.

File: includes/compat/class-wc-stripe-email-failed-authentication-retry.php (hunk 2 above)
Comment (faisal-alvi) [reply includes/compat/class-wc-stripe-email-failed-authentication-retry.php]: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3268/commits/15f096b24a4e0ee5b6ca5c313c34f2450f3d0ee1

**Comment by vikrampm1** [comment]
@diegocurbelo @Mayisha the PR has completed all the steps from our end and is now ready to be merged by you / Woo.

**Comment by Mayisha** [comment]
Hi @faisal-alvi 👋 

Please add a changelog entry in `changelog.txt` and `readme.txt`.
