### PR TITLE
Fix: Unable to process payment for $0 subscription with recurring coupon

### LINKED ISSUE #4384: Unable to process payment for $0 subscription with recurring coupon
### Description
When a recurring coupon is applied to a subscription, that makes the subscription total and the upcoming renewal total 0, the checkout fails with the following error-

```
There was an error processing the payment: This value must be greater than or equal to 1.
```

### Steps to reproduce
- Install WooCommerce Subscription.
- Set store currency to USD.
- Enable `card` payment method in your Stripe settings page.
- Create a simple subscription product priced $99.
- Create a coupon for `Recurring Product Discount` for amount $99 and 3 usages.

Image

- As a shopper, add the subscription to your cart and go to the checkout page.
- Select free shipping.
- Apply the recurring coupon.
- Your total and recurring total amounts should be $0.
- Now try to checkout with a card.
- Notice that the checkout fails and you get the following error

```
There was an error processing the payment: This value must be greater than or equal to 1.
```

### Expected behavior
- The checkout should be processed successfully.
- The coupon should be applied for n number of renewals (3 renewals for the above example)
- The payment should be processed starting from the (n+1)th renewal order (4th order for the above example)

### Screenshots

Image

### Environment

- WordPress Version: 6.8.1
- WooCommerce Version: 9.8.5
- Stripe Plugin Version: 9.5.2
- Browser: Chrome
- Any other plugins installed: WooCommerce Subscriptions

### Additional context
9807205-zen

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes STRIPE-491
Fixes #4384

## Changes proposed in this Pull Request:
For supporting [India recurring payments](https://docs.stripe.com/india-recurring-payments), we need to set `mandate_options` parameter during the `payment_intent` and `setup_intent` requests. `mandate_option` has it's own defined child parameters, `amount` is one of them which must not be 0.

When we use a recurring coupon that makes a subscription order price `0`, we end up sending `amount=0` in `mandate_options`. As the total amount is `0` but we need to save the payment method for renewal, this goes through the setup intent flow. In this PR, I have added a check for setup intent flow and now assigning the amount from `subtotal`  in `mandate_option`. 

## Testing instructions

**Note** 
- A mandate gets created only when the Stripe account is based in India and the store currency is INR.
- After purchasing a subscription

### Setup
- Set store currency to INR.
- Connect to a Stripe account based in India.
- Enable card payment method in your Stripe settings page.
- Enable logs in your Stripe settings page.
- Install WooCommerce Subscriptions.
- Create a simple subscription product priced $99 (we will use this to test this fix)
- Create a subscription with a free trial (for regression tests)

### Test the bug fix
- Create a coupon for Recurring Product Discount for amount $99 and 3 usages.

image

- As a shopper, add the simple subscription to your cart and go to the checkout page.
- Select free shipping.
- Apply the recurring coupon.
- Your total and recurring total amounts should be $0.
- Now try to checkout with a card for [Indian recurring payment](https://docs.stripe.com/india-recurring-payments?integration=paymentIntents-setupIntents#testing) (`4000003560000123`) (this goes through setup_intents flow)
- In `develop`, notice that the checkout fails and you get the following error-

image

- In this branch, checkout should be successful without any errors.
- Go to **WooCommerce > Status > Logs** and open the logs for this transaction.
- Find the `setup_intent.succeeded` logs for this order and confirm that there is a `mandate` returned in the event body. Note the mandate id.
- As an admin, go to the subscription edit page and renew the subscription until the first order with a payment is created (as the coupon was created for 3 usages, the 4th order should be charged).
- Check your logs again and confirm that the `payment_intents` request contains the mandate id you noted before.

### Regression tests
- Purchase and renew a simple subscription with a regular card (`4242424242424242`). It should work without any error.
- Purchase a simple subscription with a card for Indian recurring payment (`4000003560000123`). It should work without error. (this goes through the payment_intents flow)
    - Go to **WooCommerce > Status > Logs** and open the logs for this transaction.
    - Find the `Processing response` logs for this payment intent request and confirm that there is a `mandate` returned in the event body. Note the mandate id. 
    - As an admin, go to the subscription edit page and renew the subscription.
    - Check your logs again and confirm that the `payment_intents` request contains the mandate id you noted before.
- Purchase a subscription with a free trial with a card for Indian recurring payment (`4000003560000123`). It should work without error. (this goes through setup_intents flow)
    - Go to **WooCommerce > Status > Logs** and open the logs for this transaction.
    - Find the `setup_intent.succeeded` logs for this order and confirm that there is a `mandate` returned in the event body. Note the mandate id.
    - As an admin, go to the subscription edit page and renew the subscription.
    - Check your logs again and confirm that the `payment_intents` request contains the mandate id you noted before.
- Confirm that you can add a regular card and a 3DS card in **My Account > Payment methods** page.
- Connect to a US Stripe account and set your store currency to USD.
    - Confirm that you can purchase a simple subscription without any errors.
    - Confirm that you can purchase a subscription with free trial without any errors.
    - Confirm that you can purchase a subscription with a recurring coupon without any errors.

### CODE REVIEW

File: includes/class-wc-stripe-intent-controller.php [hunk 1]
```diff
@@ -848,30 +848,13 @@ private function maybe_add_mandate_options( $request, $payment_method_type, $is_
 		}
 
 		if ( WC_Stripe_Payment_Methods::CARD === $payment_method_type && $order && $is_setup_intent ) {
-			$currency = $order->get_currency();
```
Comment (wjrosa) [inline includes/class-wc-stripe-intent-controller.php:851]: Just to confirm, this was removed here because we have the same now in `create_mandate_options_for_order` (with the exceptions of some parameters that you updated here), right?

**Review by wjrosa — APPROVED** [review]
Nice work! Good code and works as described. Left a question.

> Your total and recurring total amounts should be $0.

Screenshot 2025-06-26 at 10 12 45

> In this branch, checkout should be successful without any errors.

Screenshot 2025-06-26 at 10 21 55

> Check your logs again and confirm that the payment_intents request contains the mandate id you noted before.

Not really the ID (since it is present outside the mandate object), but the other parameters match:
Screenshot 2025-06-26 at 10 31 41
Screenshot 2025-06-26 at 10 31 58

#### Regression tests

> Purchase and renew a simple subscription with a regular card (4242424242424242). It should work without any error.

Screenshot 2025-06-26 at 10 36 56

> Purchase a simple subscription with a card for Indian recurring payment (4000003560000123). It should work without error. (this goes through the payment_intents flow)

Screenshot 2025-06-26 at 10 44 24

> Purchase a subscription with a free trial with a card for Indian recurring payment (4000003560000123). It should work without error. (this goes through setup_intents flow)

Screenshot 2025-06-26 at 10 47 30

> Confirm that you can add a regular card and a 3DS card in My Account > Payment methods page.

Screenshot 2025-06-26 at 10 50 25

Screenshot 2025-06-26 at 10 51 54

> Connect to a US Stripe account and set your store currency to USD.

> * Confirm that you can purchase a simple subscription without any errors.

Screenshot 2025-06-26 at 10 55 59

> * Confirm that you can purchase a subscription with free trial without any errors.

Screenshot 2025-06-26 at 10 57 02

> * Confirm that you can purchase a subscription with a recurring coupon without any errors.

Screenshot 2025-06-26 at 11 00 23

**Review by malithsen — APPROVED** [review]
Code changes look good to me.

> Connect to a Stripe account based in India.

I am unable to create a Stripe account in India as it's now an invite-only process https://support.stripe.com/questions/how-can-i-open-a-stripe-account-in-india

Regression tests look good.

File: includes/class-wc-stripe-intent-controller.php (hunk 1 above)
Comment (Mayisha) [reply includes/class-wc-stripe-intent-controller.php:851]: That's correct. `mandate_option` are added based on the specific subscription in `create_mandate_options_for_order` function now. I have also moved the `setup_intent` related logic there, so no need to set them here anymore.
