### PR TITLE
Fix setup button being always disabled

### LINKED ISSUE #1461: "Clear Stripe account keys" button is always disabled
**Describe the bug**

https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1226 introduced a bug on the settings screen, causing the "Clear all Stripe account keys." button to always be disabled. This is because the event triggered [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e2447605a9a5460dbef8bde5d8acea55967b4088/assets/js/stripe-admin.js#L147) puts the form in an "unsaved changes" state for purposes of that button (handled [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e2447605a9a5460dbef8bde5d8acea55967b4088/assets/js/stripe-admin.js#L115)).

**To Reproduce**
Go to Stripe settings, and verify that button is disabled on page load:

**Expected behavior**
Button should not be disabled until something is actually changed by the merchant:

### PR DESCRIPTION
**Pull request by marcinbot**
# Changes proposed in this Pull Request:

Fixes #1461

Fixes a problem where the "setup"/"clear keys" button is always disabled because of the webhook time setting check. Now the time is checked once and the warning is shown straight away, not just when the webhook field is changed.

# Testing instructions

- Change  the call to `time()` in [`includes/class-wc-gateway-stripe.php:352`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f02be4dd3733e6b1b3e70e237c9472aeb8a43b33/includes/class-wc-gateway-stripe.php#L352) to `0`
- Load the settings page
- The warning should be shown and the button should be active. Editing any of the settings fields should disable the button.
Screenshot 2021-04-22 at 14 28 46

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by dechov** [comment]
@marcinbot Thanks for looking into this one.

The original code was intended to only show the message when the webhook secret field currently has a value, and the proposed change is to just show it whether there's a value or not, is that correct? The warning only applies when a webhook secret is set, so I didn't want to unnecessarily distract or alarm users who weren't setting it, but I think this isn't a major concern considering that setting the secret is recommended. (cc @v18 just in case you have thoughts on that)

File: assets/js/stripe-admin.js [hunk 1]
```diff
@@ -129,22 +129,13 @@ jQuery( function( $ ) {
...
-						}
-					} else {
-						$warning.remove();
-					}
-				} )
-				.change();
+			if ( isTimeOutOfSync ) {
+				var $td = $( '#woocommerce_stripe_test_webhook_secret, #woocommerce_stripe_webhook_secret' ).closest( 'td' );
+				var $warning = $td.find( '.webhook_secret_time_sync_warning' );
+				if ( ! $warning.length ) {
```
Comment (dechov) [inline assets/js/stripe-admin.js]: This check is unnecessary if it's only run the one time on init – do you agree @marcinbot?

**Review by dechov — COMMENTED** [review]
Tests well and looks good to me if we're fine with showing it regardless of whether there's a value – left just one note about simplifying it even further in that case.

File: assets/js/stripe-admin.js (hunk 1 above)
Comment (marcinbot) [reply assets/js/stripe-admin.js]: Yep, fixed in ee4dfa6

**Review by dechov — APPROVED** [review]
The class attribute is unnecessary now, but won't hurt. I think it needs a new build after latest commit. Otherwise, tests well and looks good.
