### PR TITLE
Amazon Pay ECE: fix payment method issues for subscriptions

### LINKED ISSUE #3937: Payment: N/A when purchasing subscription with Amazon Pay
**Describe the bug**
After purchasing a subscription product using Amazon Pay. The subscription correctly shows up in My Account -> Subscriptions, but under subscription details, the Payment field has a value of N/A.

Image

 

**To Reproduce**
1. As a shopper, add a subscription product to the cart.
2. Choose the "Amazon Pay" option at checkout and proceed to complete the order.
3. Go to My Account -> Subscriptions and select the subscription that was just placed.
4. Note that the Payment field has a value of "N/A"

**Expected behavior**
Payment field should have the last 4 digits of the card number, similar to other payment methods.

### LINKED ISSUE #3938: Amazon Pay: Subscription renewal failure.
**Describe the bug**
Subscriptions fails to auto-renew with the following error when using Amazon Pay:

```
Sorry, we are unable to process the payment at this time. Reason: You cannot confirm this PaymentIntent because it’s missing a payment method. You can either update the PaymentIntent with a payment method and then confirm it again, or confirm it again directly with a payment method or ConfirmationToken.
```

**To Reproduce**

1. As a merchant, navigate to 'WooCommerce -> Settings -> Subscriptions'
2. Enable 'Display the auto renewal toggle' and click 'Save changes' button on page bottom.
3. As a shopper, purchase a subscription using Amazon Pay. Note the subscription ID on the confirmation page.
4. As a merchant go to WooCommerce -> Status -> Scheduled actions and search actions by the subscriptions ID.
5. Run the actions with the name `woocommerce_scheduled_subscription_payment`.
6. Go to WooCommerce -> Orders.
7. Note that the subscription renewal failed.

### PR DESCRIPTION
**Pull request by annemirasol**
Part of #3859 
Fixes #3937
Fixes #3938 

## Changes proposed in this Pull Request:

This PR fixes subscription renewal issues for Amazon Pay, by adding logic to save payment method details in the subscription meta, and creating a payment token for the payment method.

## Testing instructions
1. Install Subscriptions, and add a simple subscription product.
2. Turn on the feature flag for Amazon Pay by using the Stripe helper plugin or by setting `_wcstripe_feature_amazon_pay` to `yes` in `wp_options`.
3. Enable Amazon Pay as a payment method.
4. As a shopper, purchase a subscription using Amazon Pay.
5. In My Account > Payment methods, verify that you can see the Amazon Pay saved payment method.
6. In My Account > My Subscription, verify that you can see the subscription's payment info as "Via Amazon Pay (\<your Amazon Pay email address\>)"
7. Go to the subscription page and process a renewal. Verify that the renewal order succeeds.
8. As a shopper, add a product to cart and go to checkout.
9. Use the Amazon Pay saved payment method to purchase the product.

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-method-amazon-pay.php [hunk 1]
```diff
@@ -24,6 +25,36 @@ public function __construct() {
...
+	 * Create new WC payment token and add to user.
+	 *
+	 * @param int $user_id        WP_User ID
+	 * @param object $payment_method Stripe payment method object
+	 *
+	 * @return WC_Payment_Token_Amazon_Pay
+	 */
+	public function create_payment_token_for_user( $user_id, $payment_method ) {
+		$token = new WC_Payment_Token_Amazon_Pay();
+		$token->set_email( $payment_method->billing_details->email ?? '' );
```
Comment (malithsen) [inline includes/payment-methods/class-wc-stripe-upe-payment-method-amazon-pay.php:52]: Is there a scenario where a billing email will not be provided? Wondering if we should allow empty emails in the token or error out.

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 2]
```diff
@@ -2245,42 +2255,42 @@ protected function prepare_payment_information_from_request( WC_Order $order ) {
...
 				$payment_information['payment_method_options'][ $selected_payment_type ]['setup_future_usage'] = 'off_session';
 			}
+		} else {
+			$payment_information['payment_method']         = $payment_method_id;
+			$payment_information['capture_method']         = $capture_method;
+			$payment_information['payment_method_options'] = $this->get_payment_method_options(
+				$selected_payment_type,
+				$order,
+				$payment_method_details
+			);
```
Comment (malithsen) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Just thinking out loud, and I'm not requesting changes. 

`prepare_payment_information_from_request` is growing pretty large with confirmation token handling. Perhaps we might be able to slightly refactor it to make things more readable. Something like:

```
protected function prepare_payment_information_from_request( WC_Order $order ) {
    ... common stuff

    if ( empty( $_POST['wc-stripe-payment-method'] ) && ! empty( $_POST['wc-stripe-confirmation-token'] ) ) {
        return $this->prepare_payment_information_using_confirmation_token(
            $base_payment_information,
            $selected_payment_type,
            $capture_method
        );
    } else {
        return $this->prepare_payment_information_using_payment_method_id(
            $base_payment_information,
            $selected_payment_type,
            $capture_method
        );
    }

```

**Review by malithsen — APPROVED** [review]
Great work here 👏 

Tests well and the code looks great. I left a couple of comments mostly out of curiosity and not expecting changes.

File: includes/payment-methods/class-wc-stripe-upe-payment-method-amazon-pay.php (hunk 1 above)
Comment (annemirasol) [reply includes/payment-methods/class-wc-stripe-upe-payment-method-amazon-pay.php:52]: Yeah, the check is most likely not needed, according to https://docs.stripe.com/api/payment_methods/object#payment_method_object-billing_details-email. I guess I thought it best to gracefully handle, as it's run at a point where the subscription is already paid for, and an error might make the shopper re-attempt payment.

What do you think?

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php (hunk 2 above)
Comment (annemirasol) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Agree. It would make things more readable. 

Makes sense to include that with this PR, as I've already rewritten this part anyways. Will work on adding that, and ping you for a re-review!

Comment (annemirasol) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: @malithsen Refactored as suggested in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4008/commits/b3791d62d2cdb39a2629de4d5854d2bcb950a95a

File: includes/payment-methods/class-wc-stripe-upe-payment-method-amazon-pay.php (hunk 1 above)
Comment (malithsen) [reply includes/payment-methods/class-wc-stripe-upe-payment-method-amazon-pay.php:52]: ah makes sense, let's keep it as is.

**Review by malithsen — APPROVED** [review]
The latest refactor looks great.

✅ Retested subscriptions with Amazon Pay
✅ Smoke tested some flows (Credit card payments, payment method updates)

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php (hunk 2 above)
Comment (malithsen) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Looks great 💯
