### PR TITLE
[Wallets] Display payment declines on the checkout and re-enable the Place order button after closing the modal

### LINKED ISSUE #3168: [Wallets] The Place Order button remains disabled on the Block checkout after closing the wallet modal
**Describe the bug**

Closing the modal without completing the payment disables the Place Order button on the Block checkout when using either WeChat or Cash App wallets. Shoppers must reload the page to be able to place the order.

**To Reproduce**

1. As a merchant, enable WeChat and Cash App on the payment methods tab, at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`
2. Create a page that uses the checkout block, if you don't have one already
3. As a shopper, add a product to the cart and go to the Block checkout page
4. Select WeChat or Cash App as the payment method
5. Click on Place Order
6. Close the modal without proceeding with the payment
7. Notice that the Place Order button remains disabled. It's not possible to place the order until you reload the page

**Expected behavior**

I'd expect the Place Order button to get enabled again after closing the wallet's payment modal.

**Screenshots**

https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/205d6c14-a94c-4275-9945-2d1dbf5abc7a

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3168

## Changes proposed in this Pull Request:

This PR fixes 2 issues with Wallet payment methods (Cash App and WeChat).

1. If you close the QR code modal on the Block checkout, the **Place order** button remains disabled and the customer would need to refresh the page to bring it back. 
2. If you fail the payment, you're redirected to the order received page rather than being left on the checkout.

With this PR if you fail the wallet payment it will now leave you on the checkout and display the error received from Stripe. If you close the modal, the block checkout is reinitialised so you can reattempt payment. 

## Testing instructions

1. As a merchant, enable **WeChat** and **Cash App**.
2. Create a Checkout Block page, if you don't have one already.
3. As a shopper, add a product to the cart and go to the Block Checkout page
4. Select **WeChat** or **Cash App** as the payment method
5. Click on **Place Order**
6. Close the modal without proceeding with the payment
    7. On develop the Place Order button remains disabled. It's not possible to place the order until you reload the page.
    8. On this branch the place order button should be ready to go again. 

| `develop` | This branch |
|--------|--------|
| Screenshot 2024-06-07 at 10 01 15 PM | Screenshot 2024-06-07 at 9 59 27 PM | 

1. As a shopper, add a product to the cart and go to the Block Checkout page
4. Select **WeChat** or **Cash App** as the payment method
5. Click on **Place Order**
6. Scan the QR code on your mobile device.
7. At Stripe click the **Fail test payment** button.
   - On `develop` you would be redirected to the order received page. Where you would need to  re-navigate to the checkout to reattempt payment.
   - On this branch you should receive the failed notice on the checkout. 

<p align="center">
Screenshot 2024-06-07 at 10 06 01 PM
<p>

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: client/stripe-utils/utils.js [hunk 1]
```diff
@@ -526,3 +536,34 @@ export const togglePaymentMethodForCountry = ( upeElement ) => {
...
+	if ( ! wcSettings.wcBlocksConfig ) {
+		return;
+	}
+
+	const checkoutStore = dispatch( CHECKOUT_STORE_KEY );
+
+	// We need to unset the redirect URL otherwise WC core will redirect the the previous checkout redirectURL.
+	// For Wallet payment methods, that will include the #wc-stripe-wallet-... hash and cause the modal to show again.
+	checkoutStore.__internalSetRedirectUrl( null );
+	checkoutStore.__internalSetIdle();
```
Comment (james-allan) [inline client/stripe-utils/utils.js:553]: This branch uses a number of functions marked as internal. I'm not sure if that's not a good idea but this was the only way I could get the payment form to unblock and for the payment elements to be reusable.

File: client/stripe-utils/utils.js [hunk 2]
```diff
@@ -8,6 +8,8 @@ import {
 	getPaymentMethodsConstants,
 } from './constants';
 
+const { CHECKOUT_STORE_KEY, PAYMENT_STORE_KEY } = window.wc.wcBlocksData;
```
Comment (diegocurbelo) [inline client/stripe-utils/utils.js]: The file `client/stripe-utils/utils.js` is imported by both the `blocks` and the `shortcode` checkouts... and is causing the E2E tests to fail because the Stripe elements do not load in the shortcode checkout

Screenshot 2024-06-09 at 5 08 56 PM

Maybe we can move this into both `unblockBlockCheckout` and `resetBlockCheckoutPaymentState` functions, they each use one of the keys 🤷🏼

**Review by diegocurbelo — CHANGES_REQUESTED** [review]
Thanks for working on this @james-allan.

I found a problem with reading `window.wc.wcBlocksData` in the `utils.js`... getting the constants after checking `wcSettings.wcBlocksConfig` in each function seems like the easiest solution 🤷🏼

File: client/stripe-utils/utils.js (hunk 1 above)
Comment (diegocurbelo) [reply client/stripe-utils/utils.js:553]: It works as described, but I agree the internal functions are not ideal... maybe we can get some guidance from @woocommerce/rubik?

File: client/stripe-utils/utils.js (hunk 2 above)
Comment (james-allan) [reply client/stripe-utils/utils.js]: 👍 Sounds good. I've moved the const definitions out of file scope and in behind the `is-blocks` check. [a857630](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3187/commits/a857630fb9957c074461255c7c043975ce4ac667)

File: client/stripe-utils/utils.js (hunk 1 above)
Comment (senadir) [reply client/stripe-utils/utils.js:553]: I'm struggling to understand this, what would cause this flow to trigger? a failed express payment?

Comment (james-allan) [reply client/stripe-utils/utils.js:553]: > I'm struggling to understand this, what would cause this flow to trigger?

So the set up is a little unorthodox. 

When you click the place order button, the process payment request on the server responds with a redirect URL that triggers a modal to be shown.

https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/c3dcabdc-8f8d-4c0f-be6a-7353d4c0d804

When you close that modal, or if payment fails (and Stripe auto close the modal) we needed to reinit the checkout because it was stuck in the "complete" status from the previous request. This code is essentially doing that. 

1) We need to set the URL to `null` because otherwise calling `__internalSetIdle()` would cause WC core to redirect the "currentURL" which was the last URL response. I've lost the copy of the stacktrace I had that indicated this but let me know if you want it I should be able to find it again.
2) I then set the status to idle so the checkout can be resubmitted. Without this the checkout remained completed and the place order button was disabled.

So, this function is called when the modal is closed so the customer can reattempt checkout.

**Review by diegocurbelo — APPROVED** [review]
Thanks @james-allan... it works perfectly now 🚢
