### PR TITLE
Hide PRB when all variations are out-of-stock

### LINKED ISSUE #1580: Hide Apple Pay button when all variations are out of stock
4014744-zen

**Describe the bug**
When all variations are out of stock, payment request button is shown even though item cannot be added to cart.

**To Reproduce**
1. Create a variable product and set all variations to out of stock
2. Visit product page, see Apple Pay button
3. Select any variation to see out of stock message
4. Click Buy with Apple Pay, error dialogue appears.

**Expected behavior**
Payment request buttons are hidden when all variations are out of stock, to match behaviour of simple product pages. 

**Screenshots**

Error shown after clicking Buy with Apple Pay:
https://d.pr/i/XiG65J
Full Image: https://d.pr/i/XiG65J

Simple product page for out of stock item, Apple Pay is hidden:
https://d.pr/i/89Tr5e
Full Image: https://d.pr/i/89Tr5e

**Environment (please complete the following information):**
 - WordPress Version 5.7.2
 - WooCommerce Version 5.3.0
 - Stripe Plugin Version 5.2.0
 - Browser [e.g. chrome, safari] and Version Safari Version 14.1 (16611.1.21.161.3)

### PR DESCRIPTION
**Pull request by lovo-h**
## Changes proposed in this Pull Request:

Fixes #1580 

* Don't display the payment request button (PRB) when all variations of the product are out-of-stock.
* Don't display the PRB when an out-of-stock variation is selected.

This PR ensures that the PRB is not displayed when all of a product's variations are out of stock. Additionally, when a product has at least one variation that is not out-of-stock, this PR also ensures that the PRB is not displayed when the user selects a variation that is out-of-stock. 

This fixes an issue where users were seeing an "Out of stock" warning and the PRB, at the same time. Which may have caused some confusion. Now, only the warning is displayed. Also, this fix makes it so that the PRB's behavior in variable product pages matches that of the simple product pages.

At the moment, this entire part of the code is not being tested. Additionally, this change was a small enough not to warrant e2e tests.

## Testing instructions

**Don't display the PRB when all variations of a `variable product` are out-of-stock**
To test this new behavior, we need to create a variable product with at least two variants:

* Create a new product: `Products > Add New`
* Select "Variable product" as `Product data`
* Click `Attributes`, then click `Add` while "Custom product attribute" is selected
* Create "Size" attribute with "Small | Medium" as values
* Ensure `Used for variations` is checked
* Click `Variations` then while "Create variations from all attributes" is selected click `Go`
* Add a `Regular price ($)` for each variation
* Select "Out of stock" on the `Stock status` field, for each variation
* `Save changes` and go to the product's page

Note that the PRB is not visible. Also, note that switching between `Size` variations keeps the PRB hidden.

**Don't display the PRB when an out-of-stock variation is selected, for a `variable product`**
To test this new behavior, go back and edit the variable product created above and do the following:

* Click `Variations`
* Update the `Stock status` of the "small" variation to "In stock"
* `Save changes` and go to the product's page

Note that the PRB is visible, upon loading the product page. Also, note that selecting the "Small" `Size` variation makes the PRB show. But switching to the "Medium" variation makes the PRB hide. 

---

Note: for the following tests, the `WooCommerce Subscriptions` plugin will need to be active.

**Don't display the PRB when all variations of a `variable subscription` are out-of-stock**
To test this new behavior, we need to create a variable subscription with at least two variants:

* Create a new product: `Products > Add New`
* Select "Variable subscription" as `Product data`
* Click `Attributes`, then click `Add` while "Custom product attribute" is selected
* Create "Billing Period" attribute with "1 Month | 2 Months" as values
* Ensure `Used for variations` is checked
* Click `Variations` then while "Create variations from all attributes" is selected click `Go`
* Add a `Subscription price ($)` for each variation
* Select "Out of stock" on the `Stock status` field, for each variation
* `Save changes` and go to the product's page

Note that the PRB is not visible. Also, note that switching between "Billing Period" variations keeps the PRB hidden.

**Don't display the PRB when an out-of-stock variation is selected, for a `variable subscription`**
To test this new behavior, go back and edit the variable subscription created above and do the following:

* Click `Variations`
* Set the `Stock status` of the "1 Month" variation to "In stock"
* `Save changes` and go to the product's page

Note that the PRB is visible, upon loading the product page. Also, note that selecting the "1 Month" `Billing Period` variation makes the PRB show. But switching to the "2 Months" variation makes the PRB hide. 

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [x] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-payment-request.php [hunk 1]
```diff
@@ -906,6 +906,32 @@ public function should_show_payment_request_button() {
 			return false;
 		}
 
+		if ( $this->is_product() && $this->get_product()->get_type() === 'variable' ) {
```
Comment (lovo-h) [inline includes/payment-methods/class-wc-stripe-payment-request.php]: @asumaran, should we also apply this behavior to `variable-subscription`?

File: includes/payment-methods/class-wc-stripe-payment-request.php [hunk 2]
```diff
@@ -906,6 +906,32 @@ public function should_show_payment_request_button() {
...
+				'parent'       => $this->get_product()->get_id(),
+				'type'         => 'variation',
+				'stock_status' => $valid_stock_statuses,
+				// All we need is for 1 variation to exist to determine
+				// whether product is "instock" or "onbackorder".
+				'limit'        => 1,
+			];
+
+			// Retrieve variable product's variations that are not 'outofstock' (e.g. 'instock', 'onbackorder').
+			$variations = wc_get_products( $product_args );
```
Comment (asumaran) [inline includes/payment-methods/class-wc-stripe-payment-request.php]: If I read this correctly. Here we are trying to hide the button if **all** variations are out of stock right? We could leverage `$this->get_product()->get_available_variations()` like this:

```php
if ( $this->is_product() && $this->get_product()->get_type() === 'variable' ) {
  $stock_availability = array_column($this->get_product()->get_available_variations(), 'is_in_stock');
  return array_unique($stock_availability) !== [false];
}
```

Which will hide the PRB if all variations are out of stock.

File: assets/js/stripe-payment-request.js [hunk 3]
```diff
@@ -649,7 +653,11 @@ jQuery( function( $ ) {
 							displayItems: response.displayItems,
 						} )
 					).then( function () {
-						$( document.body ).trigger( 'wc_stripe_unblock_payment_request_button' );
+						if (response.is_in_stock) {
+							$( document.body ).trigger( 'wc_stripe_unblock_payment_request_button' );
+						} else {
+							$( document.body ).trigger( 'wc_stripe_hide_payment_request_button' );
```
Comment (asumaran) [inline assets/js/stripe-payment-request.js]: I think it's better if we use `wc_stripe_payment_request.unblockPaymentRequestButton()` directly here instead of registering and firing a custom jQuery event. In the case if `wc_stripe_unblock_payment_request_button` we created an event with that name because we wanted 3rd party extensions to be able to trigger the event.

File: assets/js/stripe-payment-request.js [hunk 4]
```diff
@@ -675,7 +683,11 @@ jQuery( function( $ ) {
 								displayItems: response.displayItems,
 							} )
 						).then( function () {
-							$( document.body ).trigger( 'wc_stripe_unblock_payment_request_button' );
+							if (response.is_in_stock) {
+								$( document.body ).trigger( 'wc_stripe_unblock_payment_request_button' );
+							} else {
+								$( document.body ).trigger( 'wc_stripe_hide_payment_request_button' );
```
Comment (asumaran) [inline assets/js/stripe-payment-request.js]: same as previous comment.

File: assets/js/stripe-payment-request.js [hunk 5]
```diff
@@ -675,7 +683,11 @@ jQuery( function( $ ) {
 								displayItems: response.displayItems,
 							} )
 						).then( function () {
-							$( document.body ).trigger( 'wc_stripe_unblock_payment_request_button' );
+							if (response.is_in_stock) {
```
Comment (asumaran) [inline assets/js/stripe-payment-request.js]: Not sure waiting for the backend response to show/hide the PRB is best here. I mean, it'd be the best option if we also updated the whole product data in the frontend (which we currently do not). I think we should get the `is_in_stock` for each variant from the form (`$('.variations_form').data('product_variations')[0].is_in_stock;`) and show/hide the button accordingly.

File: assets/js/stripe-payment-request.js [hunk 6]
```diff
@@ -718,6 +730,20 @@ jQuery( function( $ ) {
 			}
 		},
 
+		hidePaymentRequestButton: function () {
+			$( '#wc-stripe-payment-request-wrapper, #wc-stripe-payment-request-button-separator' ).hide();
+		},
+
+		unhidePaymentRequestButton: function () {
+			const stripe_wrapper_ele = $( '#wc-stripe-payment-request-wrapper' );
+			const stripe_separator_ele = $( '#wc-stripe-payment-request-button-separator' );
```
Comment (asumaran) [inline assets/js/stripe-payment-request.js]: no need to add `_ele` suffix

**Review by asumaran — CHANGES_REQUESTED** [review]
PR is looking good! I'm glad that you were able to work on this issue on your own. I left a few comments for you @lovo-h. Let me know if you have any questions. Happy to discuss any of the comments I'm leaving.

File: includes/payment-methods/class-wc-stripe-payment-request.php (hunk 1 above)
Comment (asumaran) [reply includes/payment-methods/class-wc-stripe-payment-request.php]: @lovo-h we should check if the fix also applies for variable subscriptions as well since we support variable subscriptions with PRBs https://github.com/woocommerce/woocommerce-gateway-stripe/blob/aa2de49012b8a434dd74e56742ef190a8fa4901c/includes/payment-methods/class-wc-stripe-payment-request.php#L560-L562

File: assets/js/stripe-payment-request.js (hunk 3 above)
Comment (lovo-h) [reply assets/js/stripe-payment-request.js]: Ah, I see. Good call.

File: assets/js/stripe-payment-request.js (hunk 5 above)
Comment (lovo-h) [reply assets/js/stripe-payment-request.js]: That's true: waiting until the backend responds to update the PRB does seem a bit odd. Will update 👍

File: includes/payment-methods/class-wc-stripe-payment-request.php (hunk 2 above)
Comment (lovo-h) [reply includes/payment-methods/class-wc-stripe-payment-request.php]: Pretty neat. Didn't know we already had `get_available_variations()`. Good call 👍

File: includes/payment-methods/class-wc-stripe-payment-request.php (hunk 1 above)
Comment (lovo-h) [reply includes/payment-methods/class-wc-stripe-payment-request.php]: I tested for this and it looks like this fix should also be applied to `variable-subscription`. 

I'll go ahead and update this piece of code and update the PR's notes so that it includes a test for `variable-subscription`.

File: assets/js/stripe-payment-request.js [hunk 7]
```diff
@@ -453,6 +453,53 @@ jQuery( function( $ ) {
 			} );
 		},
 
+		getSelectedVariationCachedData: function () {
```
Comment (asumaran) [inline assets/js/stripe-payment-request.js]: I think we should minimize introducing code outside the scope of Payment Request buttons in this file and in the extension in general.

Note that when changing the dropdowns the product changes according to the selected attributes. So there must be code that can get the right variation.



And that code is here: 
 https://github.com/woocommerce/woocommerce/blob/fd3dfdbf3e05ce87138831d2f8eff3734eeb4572/plugins/woocommerce/assets/js/frontend/add-to-cart-variation.js#L239

Which is called here if the variation is found https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/assets/js/frontend/add-to-cart-variation.js#L210 

I think we should leverage the existing events attached to the form and use it to get the selected variation and with that we could hide/unhide the PRB accordingly.

The code can be simplified to just (within `attachProductPageEventListeners()` method):


```js
if ( $('.variations_form').length ) {
  $('.variations_form').on('found_variation.wc-variation-form', function (evt, variation) {
    if (variation.is_in_stock) {
      wc_stripe_payment_request.unhidePaymentRequestButton();
    } else {
      wc_stripe_payment_request.hidePaymentRequestButton();
    }
  });
}
```

**Review by asumaran — CHANGES_REQUESTED** [review]
@lovo-h Unfortunately, I think we need to do some changes on how do we get the selected variation.

File: assets/js/stripe-payment-request.js (hunk 7 above)
Comment (lovo-h) [reply assets/js/stripe-payment-request.js]: I didn't notice that there was existing code that already retrieved the right variation 🤦  

Good call. That definitely looks cleaner 👍

**Review by asumaran — APPROVED** [review]
LGTM! :shipit: 

#### Variable Products

- [x] 2 variation (color:red|green) in stock,
  - [x] no default - PRB is displayed but can't open payment sheet
  - [x] red is selected - PRB is displayed, payment sheet opens
  - [x] green is selected - PRB is displayed, payment sheet opens, price is updated
  - [x] red and green default - PRB is displayed, payment sheet opens, price is updated when changing variations
- [x] 2 variation (color:red|green) green is out of stock,
  - [x] no default - PRB is displayed but can't open payment sheet
  - [x] red is selected - PRB is displayed
  - [x] green is selected - PRB hides
  - [x] red as default - PRB is displayed, payment sheet opens - switching to green PRB hides
  - [x] green as default - PRB is displayed but can't open payment sheet
- [x] 4 variation (color: red|green, size: small|medium) - red-medium and green-medium are out of stock
  - [x] no default - PRB is displayed but can't open payment sheet
  - [x] red-small is selected - PRB is displayed, payment sheet opens
  - [x] red-medium is selected - PRB hides
  - [x] red-small/green-small as default - PRB is displayed, payment sheet opens - switching to red-medium PRB hides
  - [x] red-medium/green-medium as default - PRB is displayed but can't open payment sheet

#### Variable Subscriptions

- [x] 4 variation (color: red|green, size: small|medium) - red-medium and green-medium are out of stock - logged out user
  - [x] no defaults - works as expected with all cases - displays alert user must login.
  - [x] with defaults - works as expected
- [x] 4 variation (color: red|green, size: small|medium) - red-medium and green-medium are out of stock - logged in user
  - [x] no defaults - works as expected
  - [x] with defaults - works as expected
