### PR TITLE
Hide future payments message from payment element when manual renewal is required

### LINKED ISSUE #4332: Stripe Payment Element displays misleading “future payments” notice with manual renewals in WooCommerce Subscriptions
### Payment Element shows misleading “future payments” notice with manual renewal subscriptions

**Describe the issue**

When using the new Stripe **Payment Element** (with “Enable legacy checkout” disabled), a message appears under the card input fields:

> “By providing your card information, you allow [Site Name] to charge your card for future payments in accordance with their terms.”

This message is appropriate in auto-renewing subscription setups - but in our case, **all subscriptions are configured for manual renewal** via the WooCommerce Subscriptions plugin. No off-session payments are made.

However, the Stripe gateway plugin still sets the `setup_future_usage` parameter to `off_session`, which triggers the appearance of this message.

---

**Why this is a problem**

- Customers are misled into thinking their card will be charged automatically.
- It decreases trust and can negatively impact conversion rates.
- The behavior does not reflect actual store logic - the merchant will never charge a saved card automatically.

---

**Expected behavior**

If WooCommerce Subscriptions is active **and** the subscription is set for **manual renewal**, the plugin should:
- Not set `setup_future_usage: 'off_session'`,
- Prevent Stripe from rendering the “future payments” disclosure.

---

**Steps to reproduce**

1. Install and activate the official WooCommerce Stripe Gateway plugin.
2. Disable "Enable legacy checkout" to use the new Stripe Payment Element.
3. Enable WooCommerce Subscriptions.
4. Create a subscription product with **manual renewal**.
5. Proceed to checkout and enter payment details.

**Actual result:** the message appears below the card form.
**Expected result:** no message should appear when no future charges are scheduled.

---

**Environment**

- WooCommerce: the latest version
- WooCommerce Subscriptions: the latest version
- WooCommerce Stripe Gateway: the latest version
- WordPress: the latest version
- Payment method: Card (via Payment Element)

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes STRIPE-460
Fixes #4332 

## Changes proposed in this Pull Request:
- Checking if automatic renewal is disabled for the site. 
- When automatic renewal is disabled and manual renewal is required,
    - Prevent showing the terms stating future usage conditions.
    - Prevent saving the payment method.

## Testing instructions
- Install the WooCommerce Subscriptions plugin and create a subscription product.
- Go to `WooCommerce > Settings > Subscriptions` and disable auto renewal.

Screenshot 2025-05-21 at 12 07 13 PM

- As a shopper, add the subscription product to your cart and go to the checkout page. (Test on both shortcode and block checkout)
- Confirm that the Stripe terms about saving the payment method for future usage are not displayed.

Shortcode Checkout | Block Checkout
--- | ---
Screenshot 2025-05-23 at 3 36 33 PM | Screenshot 2025-05-23 at 3 36 11 PM

- Go to `My Account > Payment methods` page and confirm that the card has not been saved.
- Go to `My Account > Subscriptions` and view the subscription. Confirm that the subscription is set to manual renewal.
- Regression test
    - Enable automatic payment.
    - As a shopper, purchase a subscription.
    - Confirm that on the checkout page, the Stripe terms about saving the payment method for future usage are displayed.

    Screenshot 2025-05-23 at 3 24 45 PM

    - Confirm that the card is saved in `My Account > Payment methods` page.

### CODE REVIEW

File: client/blocks/upe/upe-deferred-intent-creation/payment-elements.js [hunk 1]
```diff
@@ -155,7 +155,9 @@ const PaymentElements = ( {
 
 			// If the cart contains a subscription or the payment method supports saving, we need to use off_session setup so Stripe can display appropriate terms and conditions.
 			if (
-				getBlocksConfiguration()?.cartContainsSubscription ||
+				( getBlocksConfiguration()?.cartContainsSubscription &&
+					! getBlocksConfiguration()
+						?.subscriptionRequiresManualRenewal ) ||
```
Comment (malithsen) [inline client/blocks/upe/upe-deferred-intent-creation/payment-elements.js]: Maybe extract this into a new function to make it more readable

```
const shouldSetupOffSessionPayment = () => {
    const config = getBlocksConfiguration();
    const hasAutoRenewingSubscription = config?.cartContainsSubscription && 
        !config?.subscriptionRequiresManualRenewal;
    
    return hasAutoRenewingSubscription || props.showSaveOption;
};

if ( shouldSetupOffSessionPayment() ) {
    // ...
}
```

**Review by malithsen — CHANGES_REQUESTED** [review]
Thanks for working on this fix @Mayisha  👍 

Noticed an issue when testing.
On shortcode checkout, regardless of manual/auto renewal the notice is always displayed.

CleanShot 2025-05-27 at 14 50 32

File: client/blocks/upe/upe-deferred-intent-creation/payment-elements.js (hunk 1 above)
Comment (Mayisha) [reply client/blocks/upe/upe-deferred-intent-creation/payment-elements.js]: Done in [ef230da](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4340/commits/ef230dab476d1bbaa96f5d706cf92055c4b2643c)

**Comment by Mayisha** [comment]
Thanks @malithsen. I have addressed the feedback about the code extraction to a separate function. 
However, I am unable to reproduce the shortcode issue. Could you share some more details about your subscription renewal setting, Stripe settings etc? 👀

**Review by malithsen — APPROVED** [review]
> However, I am unable to reproduce the shortcode issue. Could you share some more details about your subscription renewal setting, Stripe settings etc? 👀

Hm, I am not able to replicate this anymore either 🤷 

I tested legacy, new and optimized checkout with logged in logged out users. Both Block and shortcode looks good to me now.
