### PR TITLE
Fix duplicate emails and order notes when processing setup intent requests

### LINKED ISSUE #3414: Double order notes and double emails still occurs in version `8.6.1`
**Describe the bug**
We fixed the [double order notes and emails](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463) issue in Stripe `8.6.1` ([PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3331)). While some reporters confirmed that the issue is now fixed for them [[1]](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2278498228)[[2]](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2284341791), some users reported that they are still facing this issue-

1. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2288522780
2. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2299160831
3. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2323284089
4. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2327301387

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #3414 

## Changes proposed in this Pull Request:

In https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3331 (shipped in 6.6.1) we added `lock_order_payment()` and `unlock_order_payment()` to the start and end of our `process_payment_with_deferred_intent()` function to fix an issue with duplicate order notes and order emails being sent.

Because the `lock_order_payment()` was only added inside the `$payment_needed` condition, the bug was unfortunately still present for our setup intent requests (i.e. Subscriptions with no initial payment).

To fix this, I've moved the lock to be outside of the `$payment_needed` condition but still before the payment and setup intents are created/confirmed. This will cause our webhook handler to exit early ([code ref](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/88fc09add69f71ad1ca4c8b3dfccc3d2d5385211/includes/class-wc-stripe-webhook-handler.php#L1002-L1004)) while the order is locked and let `process_payment_with_deferred_intent()` finish processing the payment and marking the order as processing/completed.

To help visualise the issue, here's a very rough timeline of how the duplicate customer emails & order notes issue occurs:

```
Timeline A: Checkout Process                             Timeline B: Webhook handling
------------------------------------------------         ------------------------------------------------
1. Customer purchases trial subscription product         1. -
------------------------------------------------         ------------------------------------------------
2. process_payment_with_deferred_intent() is called      2. - 
------------------------------------------------         ------------------------------------------------
3. We fetch an instance of $order which is "pending"     3. - 
------------------------------------------------         ------------------------------------------------
4. Send request to create and confirm setup intent       4. Stripe sends the `setup_intent.succeeded` webhook
------------------------------------------------         ------------------------------------------------
5. Save the new intent to the order                      5. Order is fetched by intent ID and still has pending status.
------------------------------------------------         ------------------------------------------------
6. Save the payment method                               6. Check if order payment is locked
------------------------------------------------         ------------------------------------------------
7. Calls $order->payment_complete()                      7. Calls $order->payment_complete()
------------------------------------------------         ------------------------------------------------
8. Order status transitions from pending to processing   8. Order status transitions from pending to processing
------------------------------------------------         ------------------------------------------------
```

## Testing instructions

> [!IMPORTANT]
> To replicate this issue you need to have the `setup_intent.succeeded` webhook processed at the same time that `process_payment_with_deferred_intent()` is still processing the payment for the current order.
>
> Specifically, we want the order to still have a "pending" status when an instance is fetched in our webhook handling code.
>
> Since we cannot easily control when Stripe sends the webhook, I was able to consistently replicate this by adding a `sleep(2);` just before `$order->payment_complete();` in our `process_payment_with_deferred_intent()` ([here in the code](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/88fc09add69f71ad1ca4c8b3dfccc3d2d5385211/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L909))
>
> **How does this happen?**
> It's hard to pin-point exactly how this would happen however, Stripe controls when the webhooks are sent and there's a lot of processing between sending our intent requests -> receiving the response -> completing the payment/checkout process.
>
> This means if there's any unexpected lag or delays (i.e. slow DB reads, slow API request, slow third party code), it could cause both the webhook handling and process payment functions to have a pending order and try to mark it as completed at the same time, resulting in duplicate emails and order notes.

1. Activate the latest Woo Subscriptions and create a subscription product with free trial
2. Enable the cards payment method and new checkout experience.
3. Make sure webhooks are setup correctly so that your test site is receiving them (I use ngrok)
4. Enable customer emails and if using a local site, activate something like WP Mail Logging plugin to easily test emails. 
5. Add a free trial subscription to your cart
6. While on `develop` complete the checkout using the standard `4242424242424242` card
7. On completion, view the Edit Order admin page and confirm there's duplicate order notes image
9. Open WP Mail Logging and confirm that two emails for the same order ID were sent a few seconds apart: image

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 1]
```diff
@@ -795,11 +795,13 @@ private function process_payment_with_deferred_intent( int $order_id ) {
 				$this->update_saved_payment_method( $payment_method_id, $order );
 			}
 
+			// Lock the order before we create and confirm the payment/setup intents to prevent Stripe sending the success webhook before this request is completed.
+			$this->lock_order_payment( $order );
```
Comment (mattallan) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:799]: Hey @Mayisha, in the changes you made in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3331, the lock was added after the `validate_minimum_order_amount()` call and so I've been trying to test and break this PR to see if there's any issues with it being before `validate_minimum_order_amount()`.

When I tested with a $0.40 product, the lock gets added even though there's a checkout error, but I haven't been able to break it because when I add 2 of these to meet the minimum amount, the checkout is then successful.

I wanted to ping you on this issue to ask if you discovered any issues with this?

The alternative was to either add two calls to `lock_order_payment()` for both payment/setup intent calls or move the `validate_minimum_order_amount()` higher up in the `process_payment_with_deferred_intent()` function 🤔 
Let me know if you had any thoughts :)

Comment (Mayisha) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:799]: You are right Matt. I intended to add the lock right before processing the intent if it passes `validate_minimum_order_amount`. 
However, I also could not break it and the checkout was successful on second attempt (when I increased the number of items or add a shipping charge).

What happens here is, on the first attempt an order is created and the order status is `failed`. On the second attempt a new order gets created then successfully gets processed and so the lock on the first order does not hamper the checkout.

Screenshot 2024-09-06 at 12 20 37 AM

In the database, the transient of the first failed orders remain.

Screenshot 2024-09-06 at 1 23 29 AM

It is alright in my opinion as the transient will be cleared once it reaches the expiration time.

**Review by Mayisha — APPROVED** [review]
Thanks @mattallan for working on this. Reproducing this issue was difficult and you did a great job there.

The changes look good to me 🎉 
- In `develop` branch I can reproduce the double note/email issue for a subscription product having free trial.
- In this branch, I do not get any duplicate notes or emails neither for a regular product nor for a subscription product having free trial.

Note: Remember to add the changelog entry also in `readme.txt` 👀

**Comment by mattallan** [comment]
Thanks @Mayisha for the review!

> Note: Remember to add the changelog entry also in readme.txt 👀

Opps, thanks for the reminder! Fixed in [689a4de](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3421/commits/689a4def986e8b24ea93fd7d8582f444f82f911d). I'll merge this once the checks pass :)

**Comment by dwh10045** [comment]
Hello, I am still having issues with this. I have the most recent version. Is there anything I need to update?

**Comment by pawelkmpt** [comment]
@dwh10045 we had the same issue and decided to use 8.6.1 as 7.x doesn't have this commit. So far just one order came through without duplicates.

**Comment by Mayisha** [comment]
Hi @dwh10045 

Please share which version of the Stripe plugin you are using and the payment methods used in the affected orders.
