### PR TITLE
[Split PE] Fixes error on block checkout when attempting to pay for failed renewal with a saved card

### LINKED ISSUE #2904: [Split PE] Unable to pay for a failed renewal order using a saved card on the block checkout
**Describe the bug**

On our deferred intents base branch (`add/deferred-intent`) there's an issue where customers cannot pay for a failed renewal order using an existing saved card while on the checkout block.

Here's the error they're presented on checkout:

image

<details><summary>View full Stripe logs:</summary>
<pre>
2024-02-15T04:01:40+00:00 DEBUG 
====Stripe Version: 7.9.1====
====Start Log====
payment_intents/seti_1OjvEnG0R5hw25lMLuxpYZYA request: Array
(
    [payment_method] => pm_1OjuZsG0R5hw25lM4FLyePbr
    [payment_method_types] => Array
        (
            [0] => card
            [1] => sepa_debit
        )

    [amount] => 1600
    [currency] => eur
    [description] => Woo - Order 3591
    [metadata] => Array
        (
            [customer_name] => Matt Example
            [customer_email] => test1@example.com
            [order_id] => 3591
            [site_url] => https://woo.localhost
            [payment_type] => recurring
        )

    [customer] => cus_PQpGYW162Pd0F3
    [shipping] => Array
        (
            [name] => Matt Example
            [address] => Array
                (
                    [line1] => 969 Market Street
                    [line2] => 
                    [city] => 94103
                    [country] => US
                    [postal_code] => 94103
                    [state] => CA
                )

        )

    [setup_future_usage] => off_session
    [payment_method_options] => Array
        (
            [card] => Array
                (
                    [mandate_options] => Array
                        (
                            [amount_type] => fixed
                            [interval] => month
                            [interval_count] => 1
                            [amount] => 1600
                            [reference] => 3591
                            [start_date] => 1707966204
                            [supported_types] => Array
                                (
                                    [0] => india
                                )

                        )

                )

        )

)

====End Log====

2024-02-15T04:01:41+00:00 DEBUG 
====Stripe Version: 7.9.1====
====Start Log====
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [code] => resource_missing
            [doc_url] => https://stripe.com/docs/error-codes/resource-missing
            [message] => No such payment_intent: 'seti_1OjvEnG0R5hw25lMLuxpYZYA'
            [param] => intent
            [request_log_url] => https://dashboard.stripe.com/test/logs/req_qXoRHZIEslTHM2?t=1707969701
            [type] => invalid_request_error
        )

)

====End Log====
</pre>
</details> 

Using the stripe logs, it looks like the issue is caused by our code sending a `payment_intents/` request with a setup intent ID (`payment_intents/seti_1OjvEnG0R5hw25lMLuxpYZYA`).

**To Reproduce**

1. Enable UPE gateway and checkout `add/deferred-intent` branch
2. Set a block checkout as your default checkout
3. Purchase a subscription using a successful card (i.e. 4242)
4. From the My Account > View subscription, change the payment method on this subscription to a card that will fail on next renewal: `4000000000000341`
5. Process a renewal order from the WP Admin Edit Subscription actions
6. Go to My Account > Orders and click on "Pay" next to the most recent failed order
7. Attempt to use the saved 4242 card to fix up the failed renewal order
8. Notice the checkout fails.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #2904 

## Changes proposed in this Pull Request:

This issue is fairly edge case, nevertheless, after changing a subscription's payment method via the **My Account > View Subscription** page, this incorrectly stores the `_stripe_setup_intent` metadata on the subscription which then gets copied to future renewal orders.

If a renewal order fails and has this setup_intent data, when a customer attempts to pay for the renewal order with a saved card on the checkout block, they will get an error on the checkout.
image

After digging into error there are actually two main issues at play:
1. Block checkout isn't always setting the `wc-stripe-is-deferred-intent` data, when using a standard Stripe saved card. This causes the `process_payment()` function to call `process_payment_with_saved_payment_method()` instead of the expected `process_payment_with_deferred_intent()`. Fixed by 7d32890aa51f9dca8820b9d2623a70183cc37fff
2. When changing a subscriptions payment method from the My Account > View Subscription page, we're saving the setup intent on the subscription which is then being copied to all future renewal orders. This setup intent is then being used to attempt payment which won't work. 8b08b230bafaf4e62dad1ea1b39e31d7a88788b9

## Testing instructions

1. Enable UPE gateway and checkout `add/deferred-intent` branch
2. Set a block checkout as your default checkout.
3. Checkout `add/deferred-intent`
4. Purchase a subscription using a successful card (i.e. 4242)
5. From the **My Account > View subscription** page, change the payment method on your subscription to a card that will fail on the next renewal i.e. `4000000000000341`
6. Process a renewal order from the WP Admin Edit Subscription actions drop-down
7. From My Account click "Pay" next to the most recent failed order
8. Attempt to use the saved 4242 card to fix up the failed renewal order
9. Notice the checkout fails
10. Checkout this branch and attempt to use the saved card again to fix up the failed order. It should succeed.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -1548,6 +1548,11 @@ public function confirm_intent( $intent, $order, $prepared_source ) {
 	 * @param stdClass $intent Payment intent information.
 	 */
 	public function save_intent_to_order( $order, $intent ) {
+		// Don't save any intent information on a subscription.
+		if ( $this->is_subscription( $order ) ) {
```
Comment (mattallan) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php:1552]: I'm a little bit unsure about this change so I'd like to get others' opinions on it.
I can't ever see a reason we'd want to store an intent ID on the subscription because an intent is specific to the individual payments and/or parent order, not the subscription specifically.

File: includes/class-wc-stripe-blocks-support.php [hunk 2]
```diff
@@ -354,39 +354,38 @@ public function add_payment_request_order_meta( PaymentContext $context, Payment
...
+
+		if ( ! $is_stripe_payment_method ) {
+			return;
+		}
+
+		/**
+		 * When using UPE on the block checkout and a saved token is being used, we need to set a flag
+		 * to indicate that deferred intent should be used.
+		 */
+		if ( $is_upe && isset( $data['issavedtoken'] ) && $data['issavedtoken'] ) {
```
Comment (mattallan) [inline includes/class-wc-stripe-blocks-support.php:375]: I ended up refactoring this function a little bit so that we are able to add the `wc-stripe-is-deferred-intent` data when the payment method is just 'stripe' and the store has UPE enabled.

Not sure if these changes make the function harder to understand, but I'm open to any other suggestions to improve this :)

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 1 above)
Comment (james-allan) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php:1552]: I tend to agree because as you mentioned subscription's don't typically store the set up intent. The only reason this happens is if you change a subscriptions payment method and the `process_payment()` function is passed a subscription rather than an order and so an setup intent gets saved to a subscription rather than an order. 

In that case, I don't think there's any reason the set up intent is stored on the subscription.

**Review by james-allan — APPROVED** [review]
Changes look good and worked for me. 

I confirmed that this does fix the issue of trying to pay for a failed renewal order after a payment method change. 

I also confirmed with the changes that setup intent ID were being recorded on subscriptions, but aren't anymore on this branch.
