### PR TITLE
Using Blocks API to process ECE orders

### LINKED ISSUE #1573: Spike: use the Blocks API instead of our AJAX APIs for the Payment Request Buttons
The WooCommerce Blocks API has seen significant improvements since #1467 was opened, and we should try to make use of those improvements.

The Blocks API brings with it significant improvements in terms of the Checkout flow, especially in terms of UX; it's more light-weight than the current implementation; and  by using the Blocks API without maintaining our own custom solution for that.

Part of what we should try to do here is to build 2 versions of our Payment Request scripts; one can be the legacy version using our AJAX APIs, and the other a newer version that entirely relies on the Blocks API. We then conditionally load the right script based on what version of WooCommerce Blocks is installed.

## What we need to understand

- How much code will have to be duplicated?
- Will this be easier if we include the shortcode flow in the new webpack based build system?
- Are there still limitations in the Blocks API that prevent us from fully embracing it?
    - These limitations should be reported in https://github.com/woocommerce/woocommerce-gutenberg-products-block
- How will this change our maintenance burden going forward?
- Should we move some of the more complex normalization functions to JS and re-use that code across the block-based and shortcode flows?
- Should we include _some_ AJAX requests even though we're using the Blocks API for normalization and such?
- Should we change how payments are processed in `process_payment` so they work for both the Shortcode and Blocks API flows without the need to write much JS for each type of flow?

## What if something doesn't work or isn't possible?

- Clearly document the issue; reproduction steps (if applicable), code examples, any other details that apply.
- Alert the WooCommerce Blocks team; do they have a solution? If not, provide input to help them come up with one.

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #1573

## Changes proposed in this Pull Request:

This PR changes how ECE orders are processed. Those will now use the Blocks API. To do that, I have introduced multiple new methods on the front end that request the API endpoint (`/wc/store/v1/checkout/`) and format the body according to the new structure.

The new flow is controlled by the `express_checkout_use_blocks_api` Stripe setting.

## Testing instructions

- Checkout and build this branch on your test environment (`tweak/using-blocks-api-to-process-ece-orders`)
- Connect your Stripe account and enable express payment methods (Google Pay, Apple Pay, Link)
- Enable the use of Blocks API for ECE. You can do it by hardcoding `true` as the returning value of `use_blocks_api`
- Access your store by a public-facing address (with either JN website or something like Ngrok)
- As a shopper, purchase any product using express methods (on both blocks checkout and shortcode checkout)
- Confirm you can complete the transaction

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

cc @reykjalin

### CODE REVIEW

File: client/express-checkout/utils/normalize.js [hunk 1]
```diff
@@ -122,3 +201,35 @@ export const normalizeShippingAddress = ( shippingAddress ) => {
...
+			value: expressPaymentType,
+		},
+		{
+			key: 'wc-stripe-payment-method',
+			value: paymentMethodId,
+		},
+		{
+			key: 'express_payment_type',
+			value: expressPaymentType,
+		},
```
Comment (Mayisha) [inline client/express-checkout/utils/normalize.js:225]: QQ: Is `payment_request_type` and `express_payment_type` both needed here?

File: client/express-checkout/event-handler.js [hunk 2]
```diff
@@ -122,6 +124,89 @@ export const onConfirmHandler = async (
...
+				errorMessage = paymentDetailsErrorMessage;
+			}
+		}
+		if ( ! errorMessage ) {
+			errorMessage = __(
+				'There was a problem processing the order.',
+				'woocommerce-gateway-stripe'
+			);
+		}
+		return abortPayment( event, getErrorMessageFromNotice( errorMessage ) );
```
Comment (Mayisha) [inline client/express-checkout/event-handler.js]:
```suggestion
		return abortPayment( event, getErrorMessageFromNotice( errorMessage ) , true);
```

I came across a scenario where I was trying to pay with GPay when I was logged out as a customer. I got this error notice which is expected.

Screenshot 2025-01-10 at 12 31 18 AM

But also got the following error in the console which goes away if you set the third param as `true`.

**Review by Mayisha — COMMENTED** [review]
The changes look good to me. I updated the `use_blocks_api` function to return `true` and confirmed that the ECE checkout is now using the Blocks API. 👍 

I have a little suggestion to avoid a error below.

Question: What is the plan for setting `express_checkout_use_blocks_api`?

File: client/express-checkout/utils/normalize.js (hunk 1 above)
Comment (wjrosa) [reply client/express-checkout/utils/normalize.js:225]: I think it is not needed. I see we check for both already on the backend, but `express_payment_type` prevails. Removed it in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3691/commits/714ec586734d4c7d8427c8c69711f0551e9673e7

File: client/express-checkout/event-handler.js (hunk 2 above)
Comment (wjrosa) [reply client/express-checkout/event-handler.js]: Good catch! Suggestion accepted in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3691/commits/003bce9dc1f64fcdecc9e7d44edb0dc7386213b5

**Comment by wjrosa** [comment]
> The changes look good to me. I updated the `use_blocks_api` function to return `true` and confirmed that the ECE checkout is now using the Blocks API. 👍
> 
> I have a little suggestion to avoid a error below.
> 
> Question: What is the plan for setting `express_checkout_use_blocks_api`?

Thanks for the review and suggestions, Mayisha! I will perform some additional testing/updates for the order attribution information on the next PR and then force the feature flag to be true in another PR. Do you think it is a good plan?

**Review by Mayisha — APPROVED** [review]
Thanks for the updates @wjrosa. Looks good to me 🎉 

> I will perform some additional testing/updates for the order attribution information on the next PR and then force the feature flag to be true in another PR. Do you think it is a good plan?

Absolutely. Sounds like a good plan 👍
