### PR TITLE
Stripe appearance improvements

### LINKED ISSUE #3788: Appearance: Block elements are not styled
**Describe the bug**
Stripe Appearance API is used to style the payment element to match the checkout page styles. However, we don't currently send [Block](https://docs.stripe.com/elements/appearance-api#block) component, making it use the default styles.

**To Reproduce**
1. As a merchant, enable Afterpay (or any payment method that uses the Block style)
2. As a shopper, go to the checkout page and select Afterpay. 
3. Notice that the inner background looks different from the page background.

**Expected behavior**
The background color and text of the Block element should match rest of the checkout page.

**Screenshots**

Image

**Additional context**
P2 Project Thread: peNR48-17o-p2

### PR DESCRIPTION
**Pull request by malithsen**
Fixes #3788, #3789

## Changes proposed in this Pull Request:

This PR introduces a series of minor fixes to improve the visibility of Stripe payment fields. 

- Improve text visibility across light/dark themes
- Improve label visibility on dark themes.
- Use the site's background color in the [Block](https://docs.stripe.com/elements/appearance-api#block) element

With a light color palette
|| Before | After|
|---|---|---|
|Block| CleanShot 2025-01-29 at 10 50 24 | CleanShot 2025-01-29 at 10 40 25|
|Shortcode| CleanShot 2025-01-29 at 10 49 23 | CleanShot 2025-01-29 at 10 40 52 |

With a dark color palette
|| Before | After|
|---|---|---|
|Block|CleanShot 2025-01-29 at 11 44 37|CleanShot 2025-01-29 at 11 34 49|
|Shortcode|CleanShot 2025-01-29 at 11 44 09|CleanShot 2025-01-29 at 11 35 26|

## Testing instructions

1. Clear out any appearance-related transients from the db (`select * from wp_options where option_name like '%_appearance%'`)
2. Update the site theme to use a light color palette.
3. As a shopper, go to the checkout page and select the "Credit / Debit Card" payment method.
4. All labels and text should be visible.
5. Switch to Affirm payment method, inner area should match the site background color.
6. Now customize the theme and change to a dark color palette.
7. Clear out the appearance-related transients again (This step isn't necessary if https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3791 is fixed)
8. Test the payment fields again for matching background and text visibility.
---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: client/styles/upe/index.js [hunk 1]
```diff
@@ -345,19 +382,42 @@ export const getAppearance = ( isBlocksCheckout = false ) => {
...
 			'.Tab--selected': selectedTabRules,
 			'.TabIcon:hover': tabIconHoverRules,
 			'.TabIcon--selected': selectedTabIconRules,
-			'.Text': labelRules,
-			'.Text--redirect': labelRules,
+			'.Text': isColorLight( backgroundColor )
+				? darkParagraphRules
+				: paragraphRules,
+			'.Text--redirect': isColorLight( backgroundColor )
+				? darkParagraphRules
```
Comment (malithsen) [inline client/styles/upe/index.js:419]: `darkParagraphRules` are obtained from the hidden input field. When using a dark palette, we use input text color for non-input text. This is a bit hacky but needed because, in shortcode checkout, there's always a light overlay. So, if we use paragraph rules, we will have light text on a light background.

Comment (annemirasol) [reply client/styles/upe/index.js:419]: I see this for block checkout, 2025 theme. Is this expected?

Screenshot 2025-01-29 at 4 08 38 PM

Comment (malithsen) [reply client/styles/upe/index.js:419]: @annemirasol That doesn't look right. This is what I get 
CleanShot 2025-01-29 at 19 37 20

Can you double-check the transients in the db to make sure it's not using the cached styles?

Comment (annemirasol) [reply client/styles/upe/index.js:419]: Oof, you're right! I forgot to clear the transients in between switching palettes!

**Review by annemirasol — APPROVED** [review]
Everything looks great ✨  Thanks for the improvements! 🚢
