### PR TITLE
Display the wallets in the PRBs according to the plugin settings

### LINKED ISSUE #2634: Link button doesn't show up when Apple Pay and Google Pay are disabled
**Describe the bug**
The Link button doesn't appear when enabled if Apple Pay and Google Pay are disabled.

**To Reproduce**
1. Enable UPE. Under the Stripe plugin's Settings tab -> Advanced settings -> New checkout experience, check off "Enable the updated checkout experience"
2. Enable all express buttons. Under the Stripe plugin's Payment Methods tab -> Express checkouts, enable Link and Google Pay/Apple Pay
3. Visit the store as a shopper in private navigation and add a product to the cart. 
4. Go to the checkout page and confirm that the Link button shows up
5. As a merchant, disable Apple Pay/Google Pay (leave Link enabled)
6. As a shopper, refresh the checkout page. Notice that the Link button disappears

**Expected behavior**
The Link button should show up when Link is enabled, and must not disappear if Apple Pay/Google Pay are disabled.

**Screenshots**

https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/a6ae0315-b232-4505-99be-850c8113e750

### LINKED ISSUE #2713: Link shows up in the checkout block even though it's disabled
**Describe the bug**
The express button for Link shows up in the Block checkout, even though it's disabled in the WP's Stripe settings. It doesn't show up in the classic checkout.

**To Reproduce**
1. In the plugin settings:
- Enable UPE
- Enable Apple Pay/Google Pay
- Disable Link
2. Create a page that uses the checkout block, if you don't have one already
3. As a shopper in incognito/private navigation, add a product to the cart
4. Visit the page with the checkout block
5. Notice that Link shows up under the Express checkout section

**Expected behavior**
If link is disabled in the plugin settings, I expect it not to show up on either of the checkout pages.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by a-danae**
Fixes #2713
Fixes #2634

## Changes proposed in this Pull Request:

- Replace the call to woocommerce_gateway_stripe() in WC_Stripe_UPE_Payment_Method_Link::is_link_enabled() to avoid redefining the WC_Stripe class.
- Check whether Link and Google Pay / Apple Pay are enabled in the plugin settings when deciding whether to initiate the WC_Stripe_Payment_Request class.
- Use disableWallets for conditionally disabling Link and Google Pay / Apple Pay from the displayed wallets.

## Testing instructions

To test Apple Pay, you'll need to verify your domain and have access to a device with MacOS or iOS.

**Setting things up**
1. Make your store publicly accessible. Jurassic tube does the trick
2. Create a page with the classic checkout and another with the block checkout, if you don't have them already
3. Open both the classic checkout and block checkout in different browsers where the three wallets can show up. [Reference](https://stripe.com/docs/stripe-js/elements/payment-request-button). For example:
- Any browser in private navigation, where Link would appear
- Google Chrome with a profile that has a registered payment method, where Google Pay would appear
- Safari, where Apple Pay would appear

**Testing**
1. Go to the Stripe plugin settings page (/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods) -> Express checkouts
2. Disable both Link and Apple Pay / Google Pay
3. Confirm that no Express checkout appears in any browsers, in either the block or classic checkout pages
4. Enable Link
5. Confirm that Link shows up at the top of both the block and classic checkout pages, for all of the browsers.
6. Confirm that the email address field shows up as the first form field in the classic checkout page
7. Enable both Link and Apple Pay / Google Pay
8. Confirm that:
  - Private navigation displays Link
  - Chrome displays Google Pay
  - Safari displays Apple Pay
 9. Disable Link, leaving only Apple Pay/Google Pay enabled
   - Private navigation displays no Express button
  - Chrome displays Google Pay
  - Safari displays Apple Pay

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: assets/js/stripe-payment-request.js [hunk 1]
```diff
@@ -360,6 +360,25 @@ jQuery( function( $ ) {
 				paymentDetails = cart.order_data;
 			}
 
+			// Prevent displaying Link in the PRBs if disabled in the plugin settings.
+			if ( ! wc_stripe_payment_request_params?.stripe?.is_link_enabled ) {
+				options.disableWallets = [ 'link' ];
+			}
```
Comment (Mayisha) [inline assets/js/stripe-payment-request.js]: This block is a duplicate of [lines 370-373](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e3cd93916d6a5f3df30723e206f23f68ec96473a/assets/js/stripe-payment-request.js#L370-L373). This one can be removed.

**Review by Mayisha — COMMENTED** [review]
LGTM. Tests well for Google Pay and Link. :tada: 
However, I could not try it for Apple Pay as I own neither MacOS nor iOS. Shall we ask someone else from the team to have a test for Apple Pay? :eyes:

File: assets/js/stripe-payment-request.js (hunk 1 above)
Comment (a-danae) [reply assets/js/stripe-payment-request.js]: Whoops! Good catch 😄 Removed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2714/commits/9acc9a7f2d0b57786acd14bcf0f6df4f9a43fdb6

**Comment by a-danae** [comment]
Thanks for reviewing and testing this, @Mayisha !

> Shall we ask someone else from the team to have a test for Apple Pay? 👀

Sounds good to me. Posting it in the channel.

**Comment by james-allan** [comment]
> Shall we ask someone else from the team to have a test for Apple Pay? 

I've tested Apple Pay. 

With it **disabled** in the settings, it doesn't show up on the checkout and block checkout pages.

| Checkout | Block Checkout |
|--------|--------|
| Screenshot 2023-09-27 at 10 29 33 am | Screenshot 2023-09-27 at 10 31 48 am |


With it **enabled** in the settings, it does get displayed on the checkout and block checkout pages.

| Checkout | Block Checkout |
|--------|--------|
| Screenshot 2023-09-27 at 10 30 53 am | Screenshot 2023-09-27 at 10 30 35 am |

**Review by Mayisha — APPROVED** [review]
As Apple Pay is also confirmed to be working as expected, this is good to get merged :tada:
