### PR TITLE
Enhancements

### LINKED ISSUE #638: Failing Charge webhook function does return without notification if order status is not "on-hold"
The function `process_webhook_charge_failed` returns without any information if the order status is not "on-hold" (https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-webhook-handler.php#L386) and the following code is not executed. 
As it is possible to change the order-status to any other status manually the shop owner will not be notified of a failing charge not even a log entry is made?!

I would expect that the order status is always updated to "failed" regardless of the previous status.
Also I would expect that in any case an order-note is added and an E-Mail is sent to the shop admins.

One approach for correcting this is to change the function to ignore the order status and always set it to failed.
Another way would be to provide a hook in the `process_webhook` function so custom code can be developed.

### PR DESCRIPTION
**Pull request by roykho**
Fixes #638 

#### Changes proposed in this Pull Request:
* Tweak - Refactor initialization of plugin.
* Tweak - Webhook failed handler now handles all payment methods.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/admin/class-wc-stripe-admin-notices.php [hunk 1]
```diff
@@ -175,9 +175,9 @@ public function stripe_check_environment() {
...
+				if ( function_exists( 'wc_site_is_https' ) && ! wc_site_is_https() ) {
 					/* translators: 1) link 2) link */
-					$this->add_admin_notice( 'ssl', 'notice notice-warning', sprintf( __( 'Stripe is enabled, but the <a href="%1$s">force SSL option</a> is disabled; your checkout may not be secure! Please enable SSL and ensure your server has a valid <a href="%2$s" target="_blank">SSL certificate</a> - Stripe will only work in test mode.', 'woocommerce-gateway-stripe' ), admin_url( 'admin.php?page=wc-settings&tab=checkout' ), 'https://en.wikipedia.org/wiki/Transport_Layer_Security' ), true );
+					$this->add_admin_notice( 'ssl', 'notice notice-warning', sprintf( __( 'Stripe is enabled, but the <a href="%1$s">SSL</a> is not detected. Your checkout may not be secure! Please enable SSL and ensure your server has a valid <a href="%2$s" target="_blank">SSL certificate</a> - Stripe will only work in test mode.', 'woocommerce-gateway-stripe' ), admin_url( 'admin.php?page=wc-settings&tab=checkout' ), 'https://en.wikipedia.org/wiki/Transport_Layer_Security' ), true );
```
Comment (laurendavissmith) [inline includes/admin/class-wc-stripe-admin-notices.php]: `Stripe is enabled, but the <a href="%1$s">SSL</a> is not detected` that wording is a bit awkward maybe just remove `the` so its `Stripe is enabled, but <a href="%1$s">SSL</a> is not detected`

Comment (roykho) [reply includes/admin/class-wc-stripe-admin-notices.php]: Revised.
