### PR TITLE
Fix Stripe Link saved payment methods

### LINKED ISSUE #3224: "Missing required param: mandate_data" error prevents adding card payment method to My Account page while Link is enabled
**Describe the bug**
Adding a payment method on My Account shows an error: "Missing required param: mandate_data"

**To Reproduce**
1. Go to My Account -> Payment Methods
2. Try to add a new payment method
3. See the error comes up and the method is not added.

**Expected behavior**
The method should be added and saved.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version: 6.6
 - WooCommerce Version: 9.1
 - Stripe Plugin Version 8.4
 - Browser [e.g. chrome, safari] and Version: Edge
 - Any other plugins installed: None besides WordPress Beta tester and WC Core.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3224

On top of fixing that this PR also includes some improvements to the general Stripe Link saved payment method flow.

## Changes proposed in this Pull Request:

This PR fixes 4 things with Stripe Link saved payment methods: 

1. When the customer cache is cleared, we weren't clearing the saved Link payment methods. This would cause Link payment methods to not actually be saved until the cache would naturally expire (24 hours).
2. Fix the display of Link Payment methods.
3. Subscriptions purchased with a Stripe Link payment method weren't displaying the correctly on the My Account Subscription details. 
4. Unable to add saved payment method. You would get the following error. 

**MY ACCOUNT PAYMENT METHODS ERROR**
<p align="center">
Screenshot 2024-07-24 at 12 42 50 PM
</p> 

---

**LINK TOKEN DISPLAY**
| Checkout | My Account |
|--------|--------|
| Screenshot 2024-07-24 at 3 09 21 PM<p align="center"><sup><strong>Before:</strong> Stripe Link tokens displayed default value</sup></p> | Screenshot 2024-07-24 at 3 04 53 PM<p align="center"><sup><strong>Before:</strong> Stripe Link tokens missing value</sup></p> |
| Screenshot 2024-07-24 at 3 11 36 PM<p align="center"><sup><strong>After:</strong> Stripe Link tokens now displayed their display name (like shortcode checkout)</sup></p> | Screenshot 2024-07-24 at 3 03 32 PM<p align="center"><sup><strong>After:</strong> Stripe Link tokens now display the brand</sup></p>| 

---
**SUBSCRIPTION LINK PM DISPLAY**

| Before | After |
|--------|--------|
| Screenshot 2024-07-24 at 3 56 20 PM | Screenshot 2024-07-24 at 3 55 21 PM | 

## Testing instructions

> [!note]
> You will need to be logged into Link and have a stored payment method to test this PR.

1. Enable Stripe Link in your Stripe payment method settings
3. Go to the **My Account > Payment methods** page. 
4. Add a payment method.
5. Attempt to add a card.
   - On develop you will get the mandate required error.
   - On this branch there shouldn't be any error.
6. View the My Account > Payment methods page. 
7. Note that the Stripe Link token you just added has the **Stripe Link** name. 
8. Add a product to your cart.
9. Go to the block checkout and confirm that the token also displays there with the email address used to create the Stripe Link payment method. 

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/class-wc-stripe-payment-tokens.php [hunk 1]
```diff
@@ -388,12 +388,13 @@ public function get_account_saved_payment_methods_list_item( $item, $payment_tok
 			$item['method']['brand'] = esc_html__( 'SEPA IBAN', 'woocommerce-gateway-stripe' );
 		}
 
-		if ( 'cashapp' === strtolower( $payment_token->get_type() ) ) {
-			/**
-			 * WC's wc_get_credit_card_type_label() function will automatically replace underscores and dashes with spaces.
-			 * Cashtags can include `_` and `-` characters and so to keep the cashtag intact, we need to avoid that by using their HTML entity.
-			 */
-			$item['method']['brand'] = str_replace( [ '_', '-' ], [ '&#95;', '&#8211' ], $payment_token->get_display_name() );
+		switch ( strtolower( $payment_token->get_type() ) ) {
```
Comment (wjrosa) [inline includes/class-wc-stripe-payment-tokens.php:386]: I think we could include the `sepa` condition inside the `switch` clause.

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 2]
```diff
@@ -784,36 +784,38 @@ public function maybe_render_subscription_payment_method( $payment_method_to_dis
...
-							$payment_method_to_display = sprintf( __( 'Via Cash App Pay (%1$s)', 'woocommerce-gateway-stripe' ), $source->cashapp->cashtag );
-						}
+					if ( isset( $source->type ) && 'card' === $source->type ) {
+						$card = $source->card;
+					} elseif ( isset( $source->object ) && 'card' === $source->object ) {
+						$card = $source;
+					}
 
-						break;
+					if ( $card ) {
```
Comment (wjrosa) [inline includes/compat/trait-wc-stripe-subscriptions.php]: I think this can be another `switch` clause (`switch ( true )`).

File: includes/class-wc-stripe-payment-tokens.php (hunk 1 above)
Comment (james-allan) [reply includes/class-wc-stripe-payment-tokens.php:386]: 👍 100% agree. I missed that.

File: includes/compat/trait-wc-stripe-subscriptions.php (hunk 2 above)
Comment (james-allan) [reply includes/compat/trait-wc-stripe-subscriptions.php]: `switch ( true )` statements can be a little janky in my opinion and sometimes aren't intuitive. I agree that this if else stack would be better served by a switch statement so I've changed it to a `switch ( $type )` one.

File: includes/class-wc-stripe-intent-controller.php [hunk 3]
```diff
@@ -956,7 +956,7 @@ public function is_mandate_data_required( $selected_payment_type, $is_using_save
 	public function create_and_confirm_setup_intent( $payment_information ) {
 		$request = [
 			'payment_method'       => $payment_information['payment_method'],
-			'payment_method_types' => $payment_information['payment_method_types'],
+			'payment_method_types' => $payment_information['payment_method_types'] ?? [ $payment_information['selected_payment_type'] ],
```
Comment (james-allan) [inline includes/class-wc-stripe-intent-controller.php:959]: @wjrosa this fixes the `"message": "The type of the provided PaymentMethod (pm_1PgpCJGwEEw4tjx00ZY6OPTb) is link. This does not match the expected type card. Try confirming with a PaymentMethod of type card.",` error you mentioned to me in Slack. 

In https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3310 I changed this to use the provided `payment_method_types`, however this add payment method flow didn't provide that arg. see [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/fix/3224-link-payments-require-mandate/includes/class-wc-stripe-intent-controller.php#L1010-L1016).

**Comment by james-allan** [comment]
@wjrosa this should be testable again now.

The error you were seeing occurred when using a 3D-Secure card with Stripe Link enabled. It is essentially the same error I fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3309. When using a 3DS card we need to confirm the setup intent using Stripe's `confirmSetup()` rather than the `confirmCardSetup()` which can only be used for cards. [48d10e5](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3311/commits/48d10e5b7b52ccf8cb854607cc43883c923ef027)

**Review by wjrosa — APPROVED** [review]
Code is great and works as expected! Thanks for your patience guiding me to test this change. After the lastest fixes it is all good 👍 
Screenshot 2024-08-06 at 11 35 36
Screenshot 2024-08-06 at 11 39 23
