### PR TITLE
Fix UPE on Pay for Order page

### LINKED ISSUE #1669: UPE - Pay for Order page
The goal of this issue is to make sure UPE is available to pay for orders created by the admin. This implementation can get a little bit tricky as the submit pay for order flow may not allow for the proper redirecting needed from UPE. The [WCPay implementation](https://github.com/Automattic/woocommerce-payments/pull/2274) avoids this by just confirming the intent client-side like usual for UPE and having that redirect to the order complete page. During the loading of the order complete page, all of the usual process from Pay for Order submission is performed. 

There may be an alternative solution to this flow already in the plugin since it handles other redirect payment methods, so it would be best to explore how something like Giropay handles the Pay for Order pages and hopefully keep the process similar. It should also be noted that the Pay for Order page is also used during manual renewals of subscriptions. If #1665 is not implemented already, create an additional issue to confirm manual renewals work as expected from this page. If #1665 is already implemented, confirm that manual renewals works as part of this issue.

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #1669 

This PR is a port and adaptation of the changes from WCPay (2274-gh-Automattic/woocommerce-payments)

# Changes proposed in this Pull Request:

* Add an endpoint to update the intent before confirming, so we add metadata, customer and level3 data.
* Once the payment is confirmed and the order updated with `process_upe_redirect_payment`, the user is redirected to the order received page.

# Testing instructions

1. With UPE enabled, create an order from **WooCommerce > Orders > New Order**, or change an existing order to "Pending Payment". Click "Create/Update".
2. Click on "Customer payment page" and you should see the UPE form.
3. The credit card payment should work as expected with UPE enabled.

Saving a payment method still doesn't work. Support for it should be added via #1730 or a subsequent issue.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-stripe-intent-controller.php [hunk 1]
```diff
@@ -264,11 +265,11 @@ public function create_setup_intent() {
 	/**
 	 * Handle AJAX request for creating a payment intent for Stripe UPE.
 	 *
-	 * @throws Process_Payment_Exception - If nonce or setup intent is invalid.
+	 * @throws Exception - If nonce or setup intent is invalid.
```
Comment (diegocurbelo) [inline includes/class-wc-stripe-intent-controller.php]: This can be removed, no exception is thrown, a valid JSON is always returned

File: includes/class-wc-stripe-intent-controller.php [hunk 2]
```diff
@@ -326,14 +327,105 @@ public function create_payment_intent( $order_id = null ) {
 		];
 	}
 
+	/**
+	 * Handle AJAX request for updating a payment intent for Stripe UPE.
+	 *
+	 * @since x.x.x
+	 *
+	 * @throws Exception - If nonce or setup intent is invalid.
```
Comment (diegocurbelo) [inline includes/class-wc-stripe-intent-controller.php]: This can be removed, no exception is thrown, a valid JSON is always returned

**Review by diegocurbelo — APPROVED** [review]
Code looks good and tests well..  just left a couple of comments regarding the cleanup of phpdocs

File: includes/class-wc-stripe-intent-controller.php (hunk 2 above)
Comment (ricardo) [reply includes/class-wc-stripe-intent-controller.php]: Nice catch! Got them both removed.
