### PR TITLE
Fix syncing of local tokens with remote payment methods

### LINKED ISSUE #2896: [Split PE] Local tokens not being synced with the payment methods in Stripe from the Block checkout
**Describe the bug**

When the local tokens and the payment methods in Stripe are out of sync, they don't get synced by visiting the Block checkout.

Bit of context:
When retrieving the tokens for a user, we check them with the payment methods saved in Stripe. The payment methods in Stripe are our source of truth. Local payment methods will get created or deleted according to those. This is handled by WC_Stripe_Payment_Tokens::woocommerce_get_customer_upe_payment_tokens().

**To Reproduce**

Deleting local tokens:
1. Check out `add/deferred-intent`
2. Under the Stripe extension settings, enable UPE
3.  As a shopper, go to My account > Payment methods > Add new
4. Select Cards as the payment method
5. Enter `4242424242424242 ` and save
6. Go to My Account > Payment methods and confirm a token exists for the selected card
7. On the Stripe dashboard, go to the page for this customer
8. Delete the payment method you just saved
image

9. As the shopper, add a product to the cart and go to the Block checkout page
10. Notice that the payment method continues to be displayed
image

Creating local tokens:

1. As a shopper, go to My Account > Payment methods
2. Notice the payment methods that are listed
3. On the Stripe dashboard, go to the page for this customer
4. Add a new card
image

5. As the shopper, add a product to the cart and go to the Block checkout page
6. Notice that the newly added payment method isn't listed in the local tokens

**Expected behavior**
When visiting the Block checkout page, local tokens must be synced to the payment methods that exist in Stripe.

### PR DESCRIPTION
**Pull request by a-danae**
Fixes #2896 

## Changes proposed in this Pull Request:

- Reduce the amount of iteration when syncing local tokens with the payment methods in Stripe. We had four loops, two of them nested within each other. Now we're using two, not nested.
- (Hopefully) Simplify the logic behind the syncing process.

## Testing instructions

**Pulling remote payment methods**
1. Log in as a shopper
2. Go to My Account > Payment methods
3. Take note of the payment methods displayed
image

4. On the Stripe dashboard, go to the page for the customer associated with this shopper. It's in `https://dashboard.stripe.com/test/customers/cus_xxxx`
5. Under Payment Methods, click on Add > Add card
6. Enter a test card, like `4000056655665556`
image

7. Skip the stored transient. Either remove the transient in wp_options `LIKE '%stripe_payment_methods_%'`, or assign `false` to [this variable](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/fix/tokens-syncing/includes/class-wc-stripe-customer.php#L451)
8. As the shopper, reload the My Account > Payment methods page
9. Confirm that the card you just added to Stripe is listed
image

**Deleting local payment methods when removed remotely**
1. Log in as a shopper
2. Go to My Account > Payment methods
3. Take note of the payment methods displayed there
image

4. On the Stripe dashboard, go to the page for the customer associated with this shopper. It's in `https://dashboard.stripe.com/test/customers/cus_xxxx`
5. Under Payment Methods, delete one of the payment methods
image

6. Skip the stored transient. Either remove the transient in wp_options `LIKE '%stripe_payment_methods_%'`, or assign `false` to [this variable](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/fix/tokens-syncing/includes/class-wc-stripe-customer.php#L451)
7. As the shopper, reload the My Account > Payment methods page
8. Confirm that the payment method you deleted in Stripe is no longer listed
image

**Regression tests**

Listing of payment methods from other extensions
1. Enable WooPayments
2. Save some card and SEPA payment methods
3. Visit the My Account > Payment methods page
4. Confirm all the tokens are listed as expected: The tokens are listed, and they don't get duplicated or deleted

Listing saved APMs
1. Purchase a subscription using iDEAL, SEPA, or Bancontact
2. Go to the My Account > Payment Methods page
3. Confirm all the tokens are listed as expected

Disabling specific payment method types with saved payment methods
1. As a shopper, save a card and a SEPA payment method
2. Go to the My Account > Payment Methods page and note the listed payment methods
3. As a merchant, go to the Stripe settings page in the WP dashboard > Payment methods tab
4. Disable SEPA
5. As a shopper, go to the My Account > Payment Methods page
6. Confirm no SEPA payment methods are listed

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/class-wc-stripe-payment-tokens.php [hunk 1]
```diff
@@ -250,65 +250,99 @@ public function woocommerce_get_customer_upe_payment_tokens( $tokens, $user_id,
 			return $tokens;
 		}
 
-		$gateway     = WC_Stripe::get_instance()->get_main_stripe_gateway();
-		$upe_gateway = null;
+		try {
+			$gateway  = new WC_Stripe_UPE_Payment_Gateway();
```
Comment (Mayisha) [inline includes/class-wc-stripe-payment-tokens.php]: Could there be any side effect of instantiating this class here? i.e. recreating or firing subscription hooks, etc?

File: includes/class-wc-stripe-payment-tokens.php [hunk 2]
```diff
@@ -250,65 +250,99 @@ public function woocommerce_get_customer_upe_payment_tokens( $tokens, $user_id,
...
+					continue;
+				}
 
-			// Prevent unnecessary recursion, WC_Payment_Token::save() ends up calling 'woocommerce_get_customer_payment_tokens' in some cases.
-			remove_action( 'woocommerce_get_customer_payment_tokens', [ $this, 'woocommerce_get_customer_payment_tokens' ], 10, 3 );
+				$payment_method_type = $this->get_payment_method_type_from_token( $token );
 
-			foreach ( $payment_methods as $payment_method ) {
-				if ( ! isset( $current_tokens[ $payment_method->id ] ) ) {
-					$payment_method_type = $this->get_original_payment_method_type( $payment_method );
```
Comment (Mayisha) [inline includes/class-wc-stripe-payment-tokens.php:285]: As this `get_original_payment_method_type` is not used anymore, it can be removed I think.

**Review by Mayisha — COMMENTED** [review]
I had already half reviewed this PR last Friday so decided to finish my review. I have tested the scenarios mentioned in the description and got the following outcomes.
- Pulling remote payment methods :heavy_check_mark: 
- Deleting local payment methods when removed remotely :heavy_check_mark: 
- Regression tests (tested with WooPayments by saving a card) :heavy_check_mark:
- Listing saved APMs (tested by purchasing a subscription using SEPA) :heavy_check_mark: 
- Disabling specific payment method types with saved payment methods (for iDeal and Bancontact) :heavy_check_mark: 

I found 2 problems.
- When sepa is enabled, I see it on the checkout page and even save the method while purchasing a subscription but I don't see it on `My Account` page. 

no sepa

-  I can not add a payment method from `My Account` page. I get the following error
```
Notice: Undefined index: return_url in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-intent-controller.php on line 959 {"success":true,"data":{"status":"succeeded","id":"seti_1OkQJ2CBKj0yxC0ZfaFbFojV","client_secret":"seti_1OkQJ2CBKj0yxC0ZfaFbFojV_secret_PZZRODQG5VdX2jq6fUlByCTtxWcipL0"}}
```
The issues seem unrelated to this PR. Let me know your thoughts.

**Note**: This one is not important but thought I would add it discovered during testing. Adding/deleting a payment method works find both ways to/from Stripe Dashboard and My Account page. When I set a default method on My account page it's reflected on the Stripe Dashboard. But setting default from Stripe does not reflect on the My account page. It's a unlikely scenario though, as a merchant won't be setting a default for a shopper.

File: includes/class-wc-stripe-payment-tokens.php (hunk 1 above)
Comment (a-danae) [reply includes/class-wc-stripe-payment-tokens.php]: Great insight. This actually was a problem in a previous PR. Updated in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2897/commits/2aada620fad04fe3d4d1c4cbcd0155df4850e4f3

File: includes/class-wc-stripe-payment-tokens.php (hunk 2 above)
Comment (a-danae) [reply includes/class-wc-stripe-payment-tokens.php:285]: Updated in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2897/commits/207d5673c6959b91dc5541b04131cdb15d1c0159

**Comment by a-danae** [comment]
Thanks for the thorough review, @Mayisha !

> I can not add a payment method from My Account page. I get the following error

There's a GH issue for this over here https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2907

> When sepa is enabled, I see it on the checkout page and even save the method while purchasing a subscription but I don't see it on My Account page.

Good catch. I can replicate in `add/deferred-intent`, so I'd say we check this in a separate issue. ~Creating it...~ GH issue created https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2922

> This one is not important but thought I would add it discovered during testing. Adding/deleting a payment method works find both ways to/from Stripe Dashboard and My Account page. When I set a default method on My account page it's reflected on the Stripe Dashboard. But setting default from Stripe does not reflect on the My account page. It's a unlikely scenario though, as a merchant won't be setting a default for a shopper.

I can replicate this in `develop`. I also don't see any code intended to keep this option in sync. 
But it might not be an issue. Do you see any potential problems with keeping it as is? We could create a GH issue to spike whether we'd like to change this behavior.

**Review by Mayisha — APPROVED** [review]
Thanks Danae for the fix. Addressing the two issues with their separate tickets sounds good. 

> Do you see any potential problems with keeping it as is?

Also I don't see any problems here as it is not anything that significaant.
