### PR TITLE
Fix Subscriptions flows incompatible with HPOS

### LINKED ISSUE #2531: Some critical flows are failing with HPOS enabled
The following [critical flows](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience) are failing when [HPOS is enabled](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Enabling-High-Performance-Order-Storage-(HPOS)) with both UPE and non-UPE checkouts:

- [x] Shopper - Subscriptions - Change payment method to new card.
- [x] Shopper - Subscriptions - Change payment method to saved card.
- [x] Shopper - Subscriptions - Set default payment method – https://github.com/Automattic/woocommerce-subscriptions-core/pull/395.
- [x] Shopper - Subscriptions - Change default payment method – https://github.com/Automattic/woocommerce-subscriptions-core/pull/395.
- [x] Merchant - Subscriptions - Renew subscription automatically.

### PR DESCRIPTION
**Pull request by cesarcosta99**
Fixes #2531 

## Changes proposed in this Pull Request:

Replace all post meta usage with subscription methods that deal with the meta tags properly regardless HPOS is enabled or not.

## Testing instructions

1. Set up a store with WooCommerce Subscriptions 4.8.0, latest WooCommerce and Stripe in this branch.
2. [Enable HPOS](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Enabling-High-Performance-Order-Storage-(HPOS)).
3. Test and confirm the following flows work as expected:
  - [Shopper - Subscriptions - Change payment method to new card](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#change-payment-method-to-new-card).
  - [Shopper - Subscriptions - Change payment method to saved card](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#change-payment-method-to-saved-card).
  - [Shopper - Subscriptions - Set default payment method](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#set-default-payment-method).
  - [Shopper - Subscriptions - Change default payment method](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#change-default-payment-method).

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 1]
```diff
@@ -557,15 +561,16 @@ public function maybe_render_subscription_payment_method( $payment_method_to_dis
...
+			$stripe_source_id   = $parent_order->get_meta( '_stripe_source_id', true );
 
 			// For BW compat will remove in future.
 			if ( empty( $stripe_source_id ) ) {
-				$stripe_source_id = get_post_meta( $subscription->get_parent_id(), '_stripe_card_id', true );
+				$stripe_source_id = $parent_order->get_meta( '_stripe_card_id', true );
 
 				// Take this opportunity to update the key name.
-				update_post_meta( $subscription->get_parent_id(), '_stripe_source_id', $stripe_source_id );
+				$parent_order->update_meta_data( '_stripe_source_id', $stripe_source_id );
```
Comment (mattallan) [inline includes/compat/trait-wc-stripe-subscriptions.php:575]: Missing a `$parent_order->save()` after updating the meta.

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 2]
```diff
@@ -430,8 +432,8 @@ public function delete_renewal_meta( $renewal_order ) {
 	 * @return void
 	 */
 	public function update_failing_payment_method( $subscription, $renewal_order ) {
-		update_post_meta( $subscription->get_id(), '_stripe_customer_id', $renewal_order->get_meta( '_stripe_customer_id', true ) );
-		update_post_meta( $subscription->get_id(), '_stripe_source_id', $renewal_order->get_meta( '_stripe_source_id', true ) );
+		$subscription->update_meta_data( '_stripe_customer_id', $renewal_order->get_meta( '_stripe_customer_id', true ) );
+		$subscription->update_meta_data( '_stripe_source_id', $renewal_order->get_meta( '_stripe_source_id', true ) );
```
Comment (mattallan) [inline includes/compat/trait-wc-stripe-subscriptions.php:437]: Missing a `$subscription->save();` after updating meta data.

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 3]
```diff
@@ -397,12 +399,12 @@ public function maybe_update_source_on_subscription_order( $order, $source ) {
...
-		delete_post_meta( $resubscribe_order->get_id(), '_stripe_customer_id' );
-		delete_post_meta( $resubscribe_order->get_id(), '_stripe_source_id' );
+		$resubscribe_order->delete_meta_data( '_stripe_customer_id' );
+		$resubscribe_order->delete_meta_data( '_stripe_source_id' );
 		// For BW compat will remove in future.
-		delete_post_meta( $resubscribe_order->get_id(), '_stripe_card_id' );
+		$resubscribe_order->delete_meta_data( '_stripe_card_id' );
 		// Delete payment intent ID.
-		delete_post_meta( $resubscribe_order->get_id(), '_stripe_intent_id' );
+		$resubscribe_order->delete_meta_data( '_stripe_intent_id' );
```
Comment (mattallan) [inline includes/compat/trait-wc-stripe-subscriptions.php:407]: Missing a `$resubscribe_order->save()` at the end of this function

**Review by asumaran — APPROVED** [review]
LGTM. Tests well!

**Review by reykjalin — APPROVED** [review]
I think the changes here all look and test great, but there's a significant amount of function calls still using post meta directly:

```
$ grep -r '_post_' includes

# Unfiltered list, there is some noise here

includes/admin/class-wc-stripe-privacy.php:							'value' => get_post_meta( $order->get_id(), '_stripe_source_id', true ),
includes/admin/class-wc-stripe-privacy.php:							'value' => get_post_meta( $order->get_id(), '_stripe_customer_id', true ),
includes/admin/class-wc-stripe-privacy.php:							'value' => get_post_meta( $subscription->get_id(), '_stripe_source_id', true ),
includes/admin/class-wc-stripe-privacy.php:							'value' => get_post_meta( $subscription->get_id(), '_stripe_customer_id', true ),
includes/admin/class-wc-stripe-privacy.php:		$stripe_source_id = get_post_meta( $subscription_id, '_stripe_source_id', true );
includes/admin/class-wc-stripe-privacy.php:			delete_post_meta( $renewal_order_id, '_stripe_source_id' );
includes/admin/class-wc-stripe-privacy.php:			delete_post_meta( $renewal_order_id, '_stripe_refund_id' );
includes/admin/class-wc-stripe-privacy.php:			delete_post_meta( $renewal_order_id, '_stripe_customer_id' );
includes/admin/class-wc-stripe-privacy.php:		delete_post_meta( $subscription_id, '_stripe_source_id' );
includes/admin/class-wc-stripe-privacy.php:		delete_post_meta( $subscription_id, '_stripe_refund_id' );
includes/admin/class-wc-stripe-privacy.php:		delete_post_meta( $subscription_id, '_stripe_customer_id' );
includes/admin/class-wc-stripe-privacy.php:		$stripe_source_id   = get_post_meta( $order_id, '_stripe_source_id', true );
includes/admin/class-wc-stripe-privacy.php:		$stripe_refund_id   = get_post_meta( $order_id, '_stripe_refund_id', true );
includes/admin/class-wc-stripe-privacy.php:		$stripe_customer_id = get_post_meta( $order_id, '_stripe_customer_id', true );
includes/admin/class-wc-stripe-privacy.php:		delete_post_meta( $order_id, '_stripe_source_id' );
includes/admin/class-wc-stripe-privacy.php:		delete_post_meta( $order_id, '_stripe_refund_id' );
includes/admin/class-wc-stripe-privacy.php:		delete_post_meta( $order_id, '_stripe_customer_id' );
includes/admin/class-wc-stripe-inbox-notes.php:	const POST_SETUP_SUCCESS_ACTION    = 'wc_stripe_apple_pay_post_setup_success';
includes/class-wc-stripe-helper.php:		delete_post_meta( $order_id, self::META_NAME_FEE );
includes/class-wc-stripe-helper.php:		delete_post_meta( $order_id, self::LEGACY_META_NAME_FEE );
includes/class-wc-stripe-helper.php:		delete_post_meta( $order_id, self::META_NAME_NET );
includes/class-wc-stripe-helper.php:		delete_post_meta( $order_id, self::LEGACY_META_NAME_NET );
includes/abstracts/abstract-wc-stripe-connect-rest-controller.php:		add_filter( 'rest_post_dispatch', [ $this, 'send_nocache_header' ], PHP_INT_MAX, 2 );
includes/payment-methods/class-wc-stripe-payment-request.php:		return is_product() || wc_post_content_has_shortcode( 'product_page' );
includes/payment-methods/class-wc-stripe-payment-request.php:		} elseif ( wc_post_content_has_shortcode( 'product_page' ) ) {
includes/class-wc-gateway-stripe.php:		clean_post_cache( $order->get_id() );
```

I don't think we should fix all of these in this PR, but maybe we should open a new PR per-file?

Also not sure how to test these, or if these are even a problem. @cesarcosta99 @asumaran maybe you've already noticed these and determined the leftovers are not an issue?

**Comment by cesarcosta99** [comment]
>Also not sure how to test these, or if these are even a problem.

Thanks for flagging this, @reykjalin. I can't say for sure because we'd need to trace the calls, but I'd expect that issues would have been caught by our extensive testing while going through the critical flows.

On the other hand, I'd like to be extra safe too and have those updated to be in sync with the newest implementations. I created #2538 to pull this into a new issue/PR.
