### PR TITLE
Fix custom product type price calculation

### LINKED ISSUE #3202: Products with custom product types will be added with price 0 to the cart when using the Apple Pay button
**Describe the bug**
The WC_Stripe_Payment_Request::ajax_add_to_cart() function won't allow custom product-type products to be added to the cart. It will return 0 as the price to the Apple Pay modal (It seems to work properly with Google Pay). 

The Google and Apple Pay buttons appear on the custom product page because we used the 'wc_stripe_payment_request_supported_types' filter to add our types.

Product types allowed:
variable
variable-subscription
simple
variation
subscription
subscription_variation

Any additional type won't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Apple Pay must be enabled in the plugin and configured in Stripe.
2. Go to a custom-type product page on the front end using a Mac (Safari required) or an iPhone with Apple Pay enabled.
3. Click on the Apple Pay button.
4. The modal pops up with the correct price set, but it connects to the add_to_cart function and replaces the price by 0

**Expected behaviour**
It should check and set the correct price for all product types. Maybe two filters could be added, one for parent products and the other for simple products.

**Screenshots**
The Apple Pay button
image
The modal with the correct price
image
The modal after refreshing the price using the ajac_add_to_cart function
image

**Environment (please complete the following information):**
 - WordPress Version: 6.5.4
 - WooCommerce Version: 8.9.3
 - Stripe Plugin Version: 8.3.1
 - Browser: Safari 17.5

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #3202

## Changes proposed in this Pull Request:

When purchasing custom product types using express checkout (payment request buttons or express checkout element), the price is calculated as 0, because currently we only add to cart the following types: `variable`, `variable-subscription`, `simple`, `variation`, `subscription`, and `subscription_variation`. See:

```php
if ( ( 'variable' === $product_type || 'variable-subscription' === $product_type ) && isset( $_POST['attributes'] ) ) {
	$attributes = wc_clean( wp_unslash( $_POST['attributes'] ) );

	$data_store   = WC_Data_Store::load( 'product' );
	$variation_id = $data_store->find_matching_product_variation( $product, $attributes );

	WC()->cart->add_to_cart( $product->get_id(), $qty, $variation_id, $attributes );
}

if ( in_array( $product_type, [ 'simple', 'variation', 'subscription', 'subscription_variation' ], true ) ) {
	WC()->cart->add_to_cart( $product->get_id(), $qty );
}
```

The fix consists of reversing the second condition to check only for those product types that we do not want to consider when adding to the cart (`grouped` and `external`)

## Testing instructions

I could not find a good extension to create custom product types, so I have included a hardcoding below step to reproduce the scenario.

- Checkout and build this branch on your test environment (`fix/custom-product-types-price-calculation`)
- Enable express checkout payment methods (Apple Pay, Google Pay, Link)

### Payment Request Button

- Make sure ECE is disabled. You can hardcode `is_stripe_ece_enabled` return to `false`
- To emulate a custom product type, hardcode it on `includes/payment-methods/class-wc-stripe-payment-request.php#1449` like:
```php
$product_type = 'random-type';
```
- As a shopper, add a product to your cart
- Go to the checkout page
- Complete the purchase using any express payment method
- Confirm the final price is correct in the modal
Screenshot 2024-12-02 at 14 13 32

### Express Checkout Element

- Make sure ECE is enabled. You can hardcode `is_stripe_ece_enabled` return to `true`
- To emulate a custom product type, hardcode it on `includes/payment-methods/class-wc-stripe-express-checkout-ajax-handler.php#89` like:
```php
$product_type = 'random-type';
```
- As a shopper, add a product to your cart
- Go to the checkout page
- Complete the purchase using any express payment method
- Confirm the final price is correct in the modal

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-express-checkout-ajax-handler.php [hunk 1]
```diff
@@ -98,9 +98,7 @@ public function ajax_add_to_cart() {
 			$variation_id = $data_store->find_matching_product_variation( $product, $attributes );
 
 			WC()->cart->add_to_cart( $product->get_id(), $qty, $variation_id, $attributes );
-		}
-
-		if ( in_array( $product_type, [ 'simple', 'variation', 'subscription', 'subscription_variation', 'booking' ], true ) ) {
+		} elseif ( ! in_array( $product_type, [ 'grouped', 'external' ], true ) ) { // Grouped and external products should not be added to the cart.
```
Comment (diegocurbelo) [inline includes/payment-methods/class-wc-stripe-express-checkout-ajax-handler.php]: Instead of allowing any `product_type`, I think we should use the `supported_product_types()` function, which allows the list to be filtered by `wc_stripe_payment_request_supported_types` as mentioned in the issue.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/7779798d9031963026f18c09dbbfd428641320ab/includes/payment-methods/class-wc-stripe-express-checkout-helper.php#L343-L358

File: includes/payment-methods/class-wc-stripe-payment-request.php [hunk 2]
```diff
@@ -1458,9 +1458,7 @@ public function ajax_add_to_cart() {
 			$variation_id = $data_store->find_matching_product_variation( $product, $attributes );
 
 			WC()->cart->add_to_cart( $product->get_id(), $qty, $variation_id, $attributes );
-		}
-
-		if ( in_array( $product_type, [ 'simple', 'variation', 'subscription', 'subscription_variation' ], true ) ) {
+		} elseif ( ! in_array( $product_type, [ 'grouped', 'external' ], true ) ) { // Grouped and external products should not be added to the cart.
```
Comment (diegocurbelo) [inline includes/payment-methods/class-wc-stripe-payment-request.php]: Same here, but maybe makes sense to use`class-wc-stripe-payment-request.php` instead of the newer `class-wc-stripe-express-checkout-helper.php` here (we are deprecating this in the near future anyway):
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/7779798d9031963026f18c09dbbfd428641320ab/includes/payment-methods/class-wc-stripe-payment-request.php#L569-L584

**Review by diegocurbelo — CHANGES_REQUESTED** [review]
Thanks for working on this @wjrosa!

I'm not sure about allowing any `product_type`, it could open the door to unexpected problems.

I think it's best to maintain an allowed list, which can be filtered by merchants if they want to support additional product types.

File: includes/payment-methods/class-wc-stripe-express-checkout-ajax-handler.php (hunk 1 above)
Comment (wjrosa) [reply includes/payment-methods/class-wc-stripe-express-checkout-ajax-handler.php]: Alright! I think it works, too. I have updated the main implementation to use these methods instead 👍

File: includes/payment-methods/class-wc-stripe-payment-request.php (hunk 2 above)
Comment (wjrosa) [reply includes/payment-methods/class-wc-stripe-payment-request.php]: Done in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3632/commits/eedd116acc6b98e4bb0e5c10b9e0f934e9df1ab4

**Review by diegocurbelo — APPROVED** [review]
