### PR TITLE
Trim the refund reason to a max of 500 characters

### LINKED ISSUE #1446: Trim refund reason to a max of 500 characters
**Describe the bug**

Issuing a refund where the refund reason is >500 characters long will return an error in Stripe, but WC mostly behaves like the refund worked.

**To Reproduce**

0. Start with a test WC site + Stripe in test mode.
1. Place an order for a product.
2. Refund the full amount of the order. In the Reason box, insert some dummy text greater than 500 chars in length.
3. Issue the refund.
4. Notice the order status changes to Refunded.
5. Click the txn ID at the top to go directly to the Stripe page for the transaction.
6. Scroll down to the "Events and logs" section.
7. There will be an error like so:

Markup on 2021-01-12 at 10:37:02

The only clue to the issue in WooCommerce is the lack of a refund ID in the order notes.

Correct refund order notes:

Markup on 2021-01-12 at 10:38:17

Order notes for refunds with reasons >500 chars:

Markup on 2021-01-12 at 10:38:52

**Expected behavior**

It looks like we just pass the reason along without any trimming:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.7.0/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L853-L857

Should be an easy fix to trim it down to 500 chars max?

As far as I can see, this is not documented in Stripe's API docs anywhere, but it's happening a lot over on WooCommerce.com:

8871-gh-Automattic/woocommerce.com

### PR DESCRIPTION
**Pull request by aheckler**
# Changes proposed in this Pull Request:

Issuing a refund where the refund reason is >500 characters will return an error in Stripe, but WC mostly behaves like the refund worked. This change trims the refund reason down to fit within Stripe's limit.

Fixes #1446

# Testing instructions

1. Start with a test WC site + Stripe in test mode.
2. Place an order for a product.
3. Refund the full amount of the order. In the Reason box, insert some dummy text greater than 500 chars in length.
4. Issue the refund.
5. Notice the order status changes to Refunded.
6. Click the txn ID at the top to go directly to the Stripe page for the transaction.
7. Scroll down to the "Events and logs" section.
8. There will be an error indicating that the refund reason "must be a string under 500 characters."
9. Apply the change in this pull request.
10. Repeat this same test with a different transaction.
11. Stripe should issue the refund, with the trimmed refund reason visible in the logs.

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by aheckler** [comment]
Maybe it's obvious, but just in case: the "explainer text" I added is so that if someone is looking at the refund in their Stripe logs, the reason isn't just cut off without explanation. With this merge, it will look like so:

Markup on 2021-01-13 at 17:10:08

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -851,6 +851,13 @@ public function process_refund( $order_id, $amount = null, $reason = '' ) {
 		}
 
 		if ( $reason ) {
+			// Trim the refund reason to a max of 499 characters.
+			if ( strlen( $reason ) >= 500 ) {
+				$reason = substr( $reason, 0, 450 );
+				// Add some explainer text indicating where to find the full refund reason.
```
Comment (ricardo) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php:857]: I believe we could use `strlen( $reason ) > 500` instead of `strlen( $reason ) >= 500`, so that we use exactly the maximum limit Stripe allows us. I've tested with a 500 characters long refund reason, and it worked.

Perhaps we could change that first comment as well to make it clear that we're doing this because of Stripe's hard limit on metadata values, so other developers can understand the reason for this condition right away.

From what I've tested, this fix works great, but I found an edge case, which may not be that critical, but I'm used to face this type of problem because I speak Portuguese: `substr` unfortunately counts for bytes instead of characters. If it happens that the refund reason gets cut right on an accented character or any multi-byte character, the character gets corrupted, and for some reason the refund doesn't go through.

You can test it with the following refund reason:

```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Loreé dsadsadasdsadsadsadsadsadasdasdasdasdasdasdasdasda
```

The above text is 501 characters long, and it will be trimmed right in the "é" character, which is the 450th character.

As fallback for such case, we could maybe use [mb_substr](https://www.php.net/manual/pt_BR/function.mb-substr.php), which [doesn't come by default](https://www.php.net/manual/en/mbstring.installation.php) with PHP, but I believe most hosts should have it.

It seems like Automattic always [checks if this function exists](https://github.com/Automattic/jetpack-threat-library-cegfault/blob/2742d49cabb98add6b07922786a8e8fe1e01bdbf/false-positives/top-plugins/the-events-calendar/common/src/functions/multibyte.php#L82) first. And you could do the same here:

```php
$reason = function_exists( 'mb_substr' ) ? mb_substr( $reason, 0, 450 ) : substr( $reason, 0, 450 );
```

For `strlen` it's not multi-byte either, but I believe there's no problem in using it, because it will always count for more characters than the actual number of characters if there is any accent, so that's not a problem.

**Review by ricardo — CHANGES_REQUESTED** [review]
Good job on this PR :+1:

That edge case will be very, very rare, but I believe there's no reason not to check for `mb_substr` and use it, to avoid any bugs.

Also, in this repository, we're changing the `@version` comment on the function header whenever we update a function. So you can use the next minor version from the changelog.txt:

```
@version 4.8.0
```

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 1 above)
Comment (aheckler) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php:857]: > I believe we could use strlen( $reason ) > 500 instead of strlen( $reason ) >= 500, so that we use exactly the maximum limit Stripe allows us. I've tested with a 500 characters long refund reason, and it worked.

Ah, good! I did think of that, but considering that the error messages states that the reason "must be a string under 500 characters", I chose to play it safe and cut it off at 499, since technically speaking a 500 character string is not "a string under 500 characters."

Anyway, yeah, I'll change the value. :) Thanks for testing it!

> Perhaps we could change that first comment as well to make it clear that we're doing this because of Stripe's hard limit on metadata values, so other developers can understand the reason for this condition right away.

Will do!

> As fallback for such case, we could maybe use `mb_substr`, which doesn't come by default with PHP, but I believe most hosts should have it.

I thought of this as well, but then looking at the code for this extension, we don't use `mb_substr` at all, just `substr`, so that's what I went with. ¯\_(ツ)_/¯ Happy to check for it first and fall back to plain old `substr` though.

**Comment by aheckler** [comment]
@ricardo Should be good to go provided Travis is happy. :)

**Review by ricardo — APPROVED** [review]
IDK if the checks can take this long or it got stuck, but I tested and it looks great.

LGTM 🚢

**Comment by aheckler** [comment]
Ah, this still needs a changelog entry here:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/09e2c2871ceb48b34af90b0dad212d08d8d1fe2a/changelog.txt#L3

But I'm not sure how to rebase this PR or whatever so it doesn't conflict with `trunk`...
