### PR TITLE
Fix pre-orders status when UPE is enabled (with a new payment method)

### LINKED ISSUE #2572: With UPE enabled. Pre-orders paid for with a *not-saved* card are moved directly to the processing status with no payment taken
**Describe the bug**
With Stripe UPE enabled. Pre-orders paid for with a not-saved card are moved directly to the processing status with no payment taken.

**To Reproduce**
1. Create a Pre-order product and set it to charge upon release
2. Set up the [Stripe](https://woocommerce.com/products/stripe/?aff=10486&cid=1131038) plugin for testing
3. Enable UPE
4. Purchase the product using the [Stripe Testing Card](https://stripe.com/docs/testing#use-test-cards) and save it for later use
5. See that your initial purchase is moved directly to `processing` as though it has been charged, but no payment is taken.
6. Purchase the product again, this time using the saved card
7. See that your order is correctly held in the pre-order status	

**Expected behavior**
Pre-orders should stay in the correct order status after being made, upon product being released pre-orders should be properly charged

**Actual Behavior**
When a pre-order is made with UPE enabled and a not-saved card, the status changes to `processing` and upon release no payment is taken.

In some instances no payment or setup information is saved to the order at all and so no charge can be made.

**Screenshots**
See a video of the behavior here -

https://user-images.githubusercontent.com/45057772/224432124-077c46cc-9b4d-4d72-b6c2-071851225b3c.mp4

First payment with a new, not-saved card is moved directly to the processing status when it should remain in the Pre-ordered Status

Second Payment with a saved card functions as intended and retains the correct status

**Environment (please complete the following information):**
 - WordPress Version 6.1.1
 - WooCommerce Version 7.4.1
 - Stripe Plugin Version 7.2.0
 - Any other plugins installed
  - Pre-orders, Jetpack.

**Additional context**
Due to other outstanding issues in the Pre-orders plugin I have yet to be able to verify whether the pre-orders incorrectly held in the processing status are correctly charged when the pre-ordered product is released. If the pre-order is manually completed then the charge is collected as expected.

A bug report with this same name exists in the pre-orders repo with more details.

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #2572

## Changes proposed in this Pull Request:

This PR fixes an issue when checking out pre-order products with a new payment method. Currently, there's a bug that puts pre-orders into the `processing` status on this case (the status should remain as `pre-ordered`).

The fix consists in replicating part of the non-UPE purchase flow and not calling the `process_response` or `payment_complete` for pre-orders.

## Testing instructions

- Checkout to this branch on your local environment
- Run `npm install`, `npm build:webpack` and `npm run up`
- Access your admin and install [pre-orders plugin](https://github.com/woocommerce/woocommerce-pre-orders/releases)
- Create a pre-order product
- Purchase it using a new payment method
- Confirm that the order status will be `pre-ordered` as expected

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [x] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -707,14 +707,15 @@ public function get_charge_object( $charge_id = '', $params = [] ) {
...
 	 * @param object $intent Stripe API Payment Intent object response.
 	 *
-	 * @return object
+	 * @return string|object
 	 */
 	public function get_latest_charge_from_intent( $intent ) {
 		if ( ! empty( $intent->charges->data ) ) {
 			return end( $intent->charges->data );
-		} else {
+		} elseif ( ! empty( $intent->latest_charge ) ) {
```
Comment (wjrosa) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: This just fixes a warning shown at the top of the page for pre-orders, the `latest_charge` property does not exist in this case (per my tests). Also, [can be nullable per Stripe's documentation](https://docs.stripe.com/api/payment_intents).

**Comment by a-danae** [comment]
Thanks for your work here @wjrosa! Could we please point these changes to the `add/deferred-intent` branch instead of `develop`?

The UPE files we're changing in this PR are heavily updated in that branch. By implementing these changes there directly, we'd save ourselves some potential conflicts and extra testing when updating that branch with the latest `develop`.

**Comment by wjrosa** [comment]
> Thanks for your work here @wjrosa! Could we please point these changes to the `add/deferred-intent` branch instead of `develop`?
> 
> The UPE files we're changing in this PR are heavily updated in that branch. By implementing these changes there directly, we'd save ourselves some potential conflicts and extra testing when updating that branch with the latest `develop`.

Hi @a-danae ! Sure, just did it 😄

**Comment by a-danae** [comment]
Thanks Wesley! 🙌

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 1 above)
Comment (Mayisha) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: The `latest_charge` issue has been fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2910. Sharing this in case you would like to update this to avoid conflicts later.

**Review by Mayisha — APPROVED** [review]
The fix works as described :tada: 

Before this change: status of a pre-order is set as `Processing`

**In this branch:**
- Status of a pre-order is set as `Pre-ordered` :heavy_check_mark: 
- Status of a normal order is set as `processing`  :heavy_check_mark:
