### PR TITLE
SCA: Generate PaymentIntents within `process_payment`

### LINKED ISSUE #804: [On Hold] SCA: Save intent IDs when generating them and respond in webhooks.
Currently we are not storing intents and relying on the checkout flow to retrieve the intent ID from a hidden field and proceed based on that.

We should figure out a way to save those intents and also handle intent-related webhooks.

### LINKED ISSUE #821: [On Hold] SCA: Save payment intents in session
Currently PaymentIntents are created when visitors try to complete the checkout process. This does not change, but in case visitors abandon the checkout process after a PI has been generated, that PI should still be updated & used later.

### Expected behavior

1. Add products to the cart
2. Open the checkout form and try submitting it. This will create a PI, but the payment will fail.
3. Close and re-open the website & checkout page.
4. Once everything has been filled in, the existing PI should be used instead of creating a new one.

IIRC the WC session class does not support arbitrary metadata (like the ID of the payment intent), but I might have missed something.

### LINKED ISSUE #822: [On hold] SCA: Update PaymentIntents when costs change (ex. shipping)
Currently Payment Intents are generated once and their amount never gets updated. This means that if additional costs (ex. shipping) change after the creation of a payment intent, those changes will never reach the intent.

### PR DESCRIPTION
**Pull request by RadoslavGeorgiev**
## Changes proposed in this Pull Request

 __Until now__ we were creating intents through AJAX, before an order exists yet. This lead to multiple complications:

- An additional AJAX call to generate PaymentIntents once the checkout form was submitted.
- We had to 1) *create*, 2) *update*, and 3) *confirm* PaymentIntents, leading to the possiblity that an intent would be created, authorized, and left unattached.
- We could not use webhooks.
- Parallel support for both intents and sources in order to support APMs.

__This PR__ changes the moment when intents are created. Instead of the additional AJAX call that was in place so far, now they are created within `process_payment`: A method that is only called once an order exists. This yields multiple benefits:

- All actions (create, ~~update,~~ and confirm/capture) are performed simultaneously. The only exception is when 3DS is required, when the confirmation is delegated to `handleCardPayment`.
- Intents are associated with orders from the start, allowing orders to reuse the same intent until a successful payment. This minimizes the amount of intents in customer dashboard, but also adds a lot of lifecycle information to the events that are created.
- Compatibility classes (Subscriptions, Pre-Orders, etc.) have their own versions of `process_payment`, allowing us to release a version with PaymentIntents support even before all details around those methods are ironed out.
- No hanging PaymentIntents (without an associated order).

Some particular changes are mentioned below, but here is an __overview of most changes__:

1. Undo a lot of SCA work that does not work with this flow.
2. Add error placeholders to saved cards in order to properly show Stripe Errors.
3. Add the `openIntentModal` method to JavaScript in order to show the modal when required.
4. Add the `onHashChange` method to JS to open the Stripe PI modal when the hash changes.
5. Add the necessary PHP code to save intents to orders, and retrieve those intents while processing payments.
6. Customize the "Pay for Order" page when a `wc-stripe-confirmation` parameter is present.
7. Add webhooks to handle both the failure and success of PaymentIntents.

__Open tasks__:

o Discuss the hash-based confirmations with Proton
o Bring back 3DS support for Stripe Checkout (#827)
o Check for proper legacy WC version support (#828)
o Check intent stati without webhooks 

#### Pay for Order page

This PR customizes the built-in "Pay for Order" page, and uses it to display the PaymentIntents modal. This allows `process_payment` to redirect to that page if 3DS is required.

Screenshot 2019-04-01 at 14 18 50

This happens based on a `GET` parameter. When the parameter is present, all payment methods are disabled and the submit button is hidden, leaving us with the perfect canvas to display the modal on top of.

*Note:* The wording of the "Amost there!..." message needs some improvement.

#### Hash-based confirmations

Even though the "Pay for order" page above will work with SCA, I wanted to make the process more seamless. To do this, in [`stripe.js`](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/826/files#diff-1f8d151e9960b8b51bc43b4a2aba09d4R812) I added a slighly unorthodox solution: Monitor `window.location.hash` and use it in order to call `handleCardPayment`. This allows the following flow:

1. Customer fills in the checkout form and submits it either with the source ID of a new card, or the ID of a saved one.
2. If validation passes and `process_payment` is reached, it uses the given source object to create/update a payment intent and tries to confirm it.
3. If no 3DS flow is needed, the payment process is finished.
If additional authentication is needed (`requires_source_action` status), the returned `redirect_url` would look like this: `#confirm-pi-<PaymentIntentID>:<RedirectURL>`.
4. The customer gets redirected to the new hash, but stays on the same page.
5. Our JS detects the change of the hash, extracts the needed data from it and calls `handleCardPayment`.
6. On success, JS uses the given redirect URL. On failure, an error message is displayed, and the payment can be retried.

This approach allows us to keep the single-page checkout flow of WooCommerce, but might be considered "hacky" by some people. If that is the case, "Pay for order" is always available as a fallback.

## Testing instructions

This PR is complex and requires some manual testing. There are various possible scenarios and all of them depend on a few conditions.

#### Starting points

- The __Checkout page__ is the normal flow for most users.
- __Pay for Order__ can be reached by navigating to *My Account* &raquo; *My Orders* and clicking the *Pay* button next to an order that is "pending payment" or "failed".
- __WooCommerce Subscriptions__ sends emails to customers when a subscription needs a payment, or has a failed payment. They use the checkout page to complete those payments, meaning that it should all work without issues, but this is an important thing to test.

#### PaymentIntent states

- __None:__ A payment intent does not exist yet. Always the default case.
- __Initiated:__ Someone selected/entered a card and submitted the checkout/pay for order form,  saw the PaymentIntent modal, but navigated away (or closed the tab) without neither authenticating nor rejecting the payment.
- __Failed:__ The intent was rejected by the bank/within the 3DS modal.

#### Cards

- New
- Saved
- New with 3DS support (requires 3DS)
- Saved with 3DS support (requires 3DS)

In order to properly test all flows, you'd need to combine everything:

1. Start the payment process at each of the starting points.
2. Enter one of the three states.
4. Use all types of cards.

While doing this, it would be good to monitor the Stripe Dashboard for those payment intents. If everything works as it should, a single order should always keep on using the same payment intent, even if it was created at one of the starting points, and completed somewhere else.

Also, compare the status of orders in `wp-admin` with Stripe's dashboard. There should be no discrepancies (ex. a paid order in WC with an incomplete intent in Stripe).

This closes #822, closes #821, and closes #804.

### CODE REVIEW

File: assets/js/stripe.js [hunk 1]
```diff
@@ -268,6 +260,16 @@ jQuery( function( $ ) {
 					return false;
 				} );
 			}
+
+			// Listen for hash changes in order to handle payment intents
+			window.addEventListener( 'hashchange', wc_stripe_form.onHashChange );
+			if ( $( '.stripe-intent-id' ).length && $( '.stripe-intent-return' ).length ) {
```
Comment (allendav) [inline assets/js/stripe.js]: Is there any chance there could be multiple elements with this class present in the DOM?

File: assets/js/stripe.js [hunk 2]
```diff
@@ -762,7 +690,7 @@ jQuery( function( $ ) {
 		 * Removes all Stripe errors and hidden fields with IDs from the form.
 		 */
 		reset: function() {
-			$( '.wc-stripe-error, .stripe-source, .stripe-intent' ).remove();
+			$( '.wc-stripe-error, .stripe-source' ).remove();
```
Comment (allendav) [inline assets/js/stripe.js]: Consider adding a comment as to why the .stripe-intent field is no longer removed?

File: assets/js/stripe.js [hunk 3]
```diff
@@ -879,43 +807,50 @@ jQuery( function( $ ) {
...
 		/**
-		 * Queries the server for a PaymentIntent.
-		 *
-		 * @param {string} savedCard The ID of the saved card. (Optional)
-		 * @return {Promise} A promise that resolves to a payment intent.
+		 * Handles changes in the hash in order to show a modal for PaymentIntent confirmations.
 		 */
-		getIntent: function( savedCard ) {
-			savedCard = savedCard || 'new';
+		onHashChange: function() {
```
Comment (allendav) [inline assets/js/stripe.js]: The hash approach is cool but might be difficult to immediately understand for the next maintainer. Please document how it works either in a few comments here or in a README.md in this repo or something.

File: assets/js/stripe.js [hunk 4]
```diff
@@ -879,43 +807,50 @@ jQuery( function( $ ) {
...
-							code   : 'ajax_failed',
-							message: wc_stripe_params.payment_intent_error,
-						} );
-					},
+			var intentClientSecret = partials[1];
+			var successRedirectURL = decodeURIComponent( partials[2] );
+
+			wc_stripe_form.openIntentModal( intentClientSecret, successRedirectURL );
+
+			// Cleanup the URL
```
Comment (allendav) [inline assets/js/stripe.js]: Should this move up above at least the openItentModal just to ensure the hash is cleaned up even if the wc_stripe_form.openIntentModal call explodes?

File: includes/class-wc-gateway-stripe.php [hunk 5]
```diff
@@ -779,7 +780,8 @@ public function complete_free_order( $order ) {
 	 */
 	public function process_payment( $order_id, $retry = true, $force_save_source = false, $previous_error = false ) {
 		try {
-			$order = wc_get_order( $order_id );
+			$order  = wc_get_order( $order_id );
+			$intent = null;
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: Please move initialization of intent closer to where it is first used below.

File: includes/class-wc-gateway-stripe.php [hunk 6]
```diff
@@ -841,6 +835,26 @@ public function process_payment( $order_id, $retry = true, $force_save_source =
...
+			if ( ! empty( $intent ) ) {
+				// Use the last charge within the intent to proceed.
+				$response = end( $intent->charges->data );
+
+				// If the intent requires a 3DS flow, redirect to it.
+				if ( 'requires_source_action' === $intent->status ) {
+					if ( is_wc_endpoint_url( 'order-pay' ) ) {
+						$redirect_url = add_query_arg( 'wc-stripe-confirmation', 1, $order->get_checkout_payment_url( false ) );
+					} else {
+						// $redirect_url = add_query_arg( 'wc-stripe-confirmation', 1, $order->get_checkout_payment_url( false ) );
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: ???

File: includes/class-wc-gateway-stripe.php [hunk 7]
```diff
@@ -1191,4 +1061,204 @@ public function retry_after_error( $response, $order, $retry, $force_save_source
...
+     * @return object                   An intent (that is either successful or requires an action) or an error.
+     */
+    public function create_and_confirm_intent( $order, $prepared_source ) {
+        // The request for a charge contains metadata for the intent.
+        $full_request = $this->generate_payment_request( $order, $prepared_source );
+
+        $request = array(
+            'source'               => $prepared_source->source,
+            'amount'               => WC_Stripe_Helper::get_stripe_amount( $order->get_total() ),
+            'currency'             => get_woocommerce_currency(),
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: Maybe use WC_Order get_currency instead

File: includes/class-wc-gateway-stripe.php [hunk 8]
```diff
@@ -1191,4 +1061,204 @@ public function retry_after_error( $response, $order, $retry, $force_save_source
...
+
+        if ( $prepared_source->customer ) {
+            $request['customer'] = $prepared_source->customer;
+        }
+
+        // Create an intent that awaits an action.
+        $intent = WC_Stripe_API::request( $request, 'payment_intents' );
+        if ( ! empty( $intent->error ) ) {
+            return $intent;
+		}
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: Too much ident here and next line too

File: includes/class-wc-gateway-stripe.php [hunk 9]
```diff
@@ -1191,4 +1061,204 @@ public function retry_after_error( $response, $order, $retry, $force_save_source
...
+
+		$order->add_order_note( sprintf( __( 'Stripe PaymentIntent initiated (ID: %s)', 'woocommerce-gateway-stripe' ), $intent->id ) );
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: Maybe put this behind a debug flag? Not sure the merchant will get much out of seeing this in the order notes

File: includes/class-wc-gateway-stripe.php [hunk 10]
```diff
@@ -1191,4 +1061,204 @@ public function retry_after_error( $response, $order, $retry, $force_save_source
...
+
+        // Try to confirm the intent & capture the charge (if 3DS is not required).
+        $request = array(
+			'source' => $request['source'],
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: Too much indent? Please run linter.

File: includes/class-wc-gateway-stripe.php [hunk 11]
```diff
@@ -1191,4 +1061,204 @@ public function retry_after_error( $response, $order, $retry, $force_save_source
...
+        if ( ! empty( $confirmed_intent->error ) ) {
+			return $confirmed_intent;
+        }
+
+        // Save the intent ID to the order
+		$this->save_intent_to_order( $order, $confirmed_intent );
+
+		// Save a note about the status of the intent.
+		if ( 'succeeded' === $confirmed_intent->status ) {
+			$order->add_order_note( sprintf( __( 'Stripe PaymentIntent succeeded (ID: %s)', 'woocommerce-gateway-stripe' ), $intent->id ) );
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: Same comment as above about only adding these to the order notes in a debug mode. Same comment for the below note too.

File: includes/class-wc-gateway-stripe.php [hunk 12]
```diff
@@ -1191,4 +1061,204 @@ public function retry_after_error( $response, $order, $retry, $force_save_source
...
+	 */
+	public function update_existing_intent( $intent, $order, $prepared_source ) {
+		$request = array();
+
+		if ( $prepared_source->source !== $intent->source ) {
+			$request['source'] = $prepared_source->source;
+		}
+
+		$new_amount = WC_Stripe_Helper::get_stripe_amount( $order->get_total() );
+		if ( $intent->amount !== $new_amount ) {
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: I assume there is no way we can get oddities from comparing floating point numbers here?

File: includes/class-wc-gateway-stripe.php [hunk 13]
```diff
@@ -1191,4 +1061,204 @@ public function retry_after_error( $response, $order, $retry, $force_save_source
...
+		return __( "Almost there!<br />Your order has already been created, the only thing that still needs to be done is for you to authorize the payment with your bank.", 'woocommerce-gateway-stripe' );
+	}
+
+	/**
+	 * Renders hidden inputs on the "Pay for Order" page in order to let Stripe handle PaymentIntents.
+	 *
+	 * @since 4.2
+	 */
+	public function render_payment_intent_inputs() {
+		$order     = wc_get_order( absint( $GLOBALS['wp']->query_vars['order-pay'] ) );
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: Can you use https://codex.wordpress.org/Function_Reference/get_query_var

File: includes/class-wc-gateway-stripe.php [hunk 14]
```diff
@@ -1191,4 +1061,204 @@ public function retry_after_error( $response, $order, $retry, $force_save_source
...
+
+	/**
+	 * Changes the text of the "No available methods" message to one that indicates
+	 * the need for a PaymentIntent to be confirmed.
+	 *
+	 * @since 4.2
+	 * @return string the new message.
+	 */
+	public function change_no_available_methods_message() {
+		return __( "Almost there!<br />Your order has already been created, the only thing that still needs to be done is for you to authorize the payment with your bank.", 'woocommerce-gateway-stripe' );
```
Comment (allendav) [inline includes/class-wc-gateway-stripe.php]: https://codex.wordpress.org/I18n_for_WordPress_Developers#HTML

File: assets/js/stripe.js (hunk 1 above)
Comment (RadoslavGeorgiev) [reply assets/js/stripe.js]: Both of those names (`stripe-intent-id` and `stripe-intent-return`) are unique for this situation and would not be displayed multiple times on the same page.

File: assets/js/stripe.js (hunk 2 above)
Comment (RadoslavGeorgiev) [reply assets/js/stripe.js]: I only introduced the field in `sca/master`, so technically it was _never_ removed.

File: includes/class-wc-gateway-stripe.php (hunk 6 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: This comment is a left-over, I performed multiple tests of the flow with Checkout + Pay for Order (instead of a modal shown based on hashes). Now it's removed.

File: includes/class-wc-gateway-stripe.php (hunk 7 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: When the line was initially written there was no available order. Now there is one, so yes: done.

File: includes/class-wc-gateway-stripe.php (hunk 8 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: PHPCS was turned off and VSCode played a trick on me. Now it is correctly indented.

File: includes/class-wc-gateway-stripe.php (hunk 12 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: There should be no floating point numbers here. `get_stripe_amount` and Stripe's API work with positive integers.

File: includes/class-wc-gateway-stripe.php (hunk 9 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: After looking around, I switched to `WC_Stripe_Logger::log` instead. No noise in orders & only logging when needed.

File: assets/js/stripe.js (hunk 1 above)
Comment (allendav) [reply assets/js/stripe.js]: So, why classes and not IDs then?

File: assets/js/stripe.js (hunk 2 above)
Comment (allendav) [reply assets/js/stripe.js]: I mean, it is used below with the others. Why isn't it still a good idea to remove it here?

File: assets/js/stripe.js (hunk 1 above)
Comment (RadoslavGeorgiev) [reply assets/js/stripe.js]: I was merely following the example of all other methods in the file. I don't mind though, so I switched to IDs.

File: assets/js/stripe.js (hunk 2 above)
Comment (RadoslavGeorgiev) [reply assets/js/stripe.js]: I see why this is confusing: I ~am~ was reusing the class in `render_payment_intent_inputs`. 

The intent field that was being removed in `reset` was a hidden field, generated by JavaScript, holding the intent after `handleCardPayment`. Since that field only exists within `sca/*` branches, adding a comment why it was removed when it was never there, might only end up being more confusing.

Comment (allendav) [reply assets/js/stripe.js]: I understand now - in addEventListener we have #stripe-intent-id, #stripe-intent-return and #stripe-intent-error and those are NOT the same as the other selectors used elsewhere  i.e. .wc-stripe-error and .stripe-source

Withdrawing my concern

**Comment by allendav** [comment]
> Note: The wording of the "Amost there!..." message needs some improvement.

I think it's fine to proceed with

**Comment by allendav** [comment]
Tested with "Capture charge immediately" unchecked, but the charge was captured anyways. :(

**Comment by allendav** [comment]
I turned Capture charge immediately back on
I attempted another checkout with
4000 0000 0000 3063
12/23 123
This is the 3D secure "required" card from https://stripe.com/docs/testing#three-ds-cards
It started the flow, but I noted a 400 error in the console:



The network detail for that shows that we attempted to confirm an already confirmed PI without any new information in it:

1a

I accepted the payment, and it completed, but a few more console errors happened. It would be best if we avoided all these unnecessary confirms with no changes.

**Comment by dechov** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/826/commits/5eacb1554e651148c8cc957109d65df9f3b49230 contains a change that escapes the HTML of the order fee & payout:

**Comment by RadoslavGeorgiev** [comment]
>  Tested with "Capture charge immediately" unchecked, but the charge was captured anyways. :(

@DanReyLop already found out that the setting is ignored and opened https://github.com/woocommerce/woocommerce-gateway-stripe/pull/836.

> The network detail for that shows that we attempted to confirm an already confirmed PI without any new information in it

I have communicated this to @thorsten-stripe, and he informed me that they are working on a `handleCardAction` JS handler, which will skip the confirmation step and allow us to immediately open the authorization modal.

For the time being, this generates an additional (and failing) request, but does not affect our workflow.

> Lastly, I went into the wp-admin WooCommerce dashboard and noted that the order still showed "pending payment" - I expected it to be completed?

Although this should've been obvious to me, I had not added a fallback in case a web hook is not configured. This changes in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/826/commits/3bcadca042dd0b9afe1c0ba728debc14d426b02b

> 5eacb15 contains a change that escapes the HTML of the order fee & payout:

@dechov thank you for checking this with an existing order! The webhook that handles the PI success receives a string as the balance transaction ID, but `process_response` expects an object. Because of this, I never saw any of those fields and wouldn't have seen the bug.

Anyway, now the fields are both properly added, and displayed without excessive escaping.

**Comment by DanReyLop** [comment]
> I have communicated this to @thorsten-stripe, and he informed me that they are working on a handleCardAction JS handler, which will skip the confirmation step and allow us to immediately open the authorization modal.

Also, calling `/confirm` on an already confirmed PI is effectively a no-op. It gives an `HTTP 400` error but the `stripe.js` logic recovers from it without any problem.

**Comment by allendav** [comment]
@RadoslavGeorgiev - this should work with or without a webhook set up now, right?

**Comment by RadoslavGeorgiev** [comment]
@allendav yes! Unless you manage to close the tab before you get redirected to the "Thank You" page, but then again: That's what webhooks are for :)

**Comment by thorsten-stripe** [comment]
IIRC we're still using the automatic confirmation path, which means a webhook is needed to catch folks who drop-off after 3DS authentication. If it is crucial to facilitate this without webhooks, you can switch to the manual confirmation flow[0] which is very similar, only difference is it requires a server-side confirm step after 3DS authentication.

[0] https://stripe.com/docs/payments/payment-intents/quickstart#flow-manual-confirmation

**Comment by allendav** [comment]
After the recent changes, this tests fine now:

> 3D Secure Required
> 4000 0000 0000 3063
> 12/23 123

**Comment by allendav** [comment]
I ran into this. Let's fix this as a separate issue. When you do this:

3D Secure Required
4000 0000 0000 3063
12/23 123
Clicked "Fail Test Payment" when prompted

You are immediately returned to the checkout with

Screen Shot 2019-04-12 at 8 03 40 AM

In the backend, the order is created, left in a pending state, with payment method "Stripe" but there is no indication that the customer failed authentication. 

fail-pending

I think it is likely merchants will get concerned about the stripe gateway being broken when they see things like this. Is there a way we could add an order note or something to indicate that 3D Secure was required and the customer failed to authenticate? Please open as a separate issue. No need to fix in this PR.

**Comment by thorsten-stripe** [comment]
@allendav there is two ways to react to this:
1. client: the `handleCardPayment` promise resolves with an error object. The error object has `code:"payment_intent_authentication_failure"` set.
2. server: same code (`last_payment_error.code:payment_intent_authentication_failure`) in the https://stripe.com/docs/api/events/types#event_types-payment_intent.payment_failed event.
You can use this to generate a order note for the merchant.

**Comment by RadoslavGeorgiev** [comment]
@thorsten-stripe the current state is a shortcut, which I took without even realising. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/840 is open and contains the first point (handling the failed promise), as the webhook is already implemented (but @allendav has probably not set it up for his test site).
