### PR TITLE
Fix TypeError when deferred Stripe webhooks run via Action Scheduler

### LINKED ISSUE #5184: Bug: run_webhook_received_action() TypeError on all deferred webhooks — breaks iDEAL/Klarna email notifications
## Description

All `wc_stripe_deferred_webhook` Action Scheduler jobs for redirect-based payment methods (iDEAL, Klarna) fail with:

```
WC_Stripe_Webhook_Handler::run_webhook_received_action(): 
Argument #2 ($notification) must be of type object, array given, 
called in .../class-wc-stripe-webhook-handler.php on line 1346
```

## Root Cause

In `defer_webhook_processing()` (line 1293), the `$webhook_notification` stdClass object is passed to Action Scheduler:

```php
$this->action_scheduler_service->schedule_job(
    time() + $this->deferred_webhook_delay,
    $this->deferred_webhook_action,
    [
        'type'         => $webhook_notification->type,
        'data'         => $additional_data,
        'notification' => $webhook_notification,  // stdClass object
    ]
);
```

Action Scheduler serializes this data for storage. When it deserializes, **stdClass objects become arrays**. This is expected Action Scheduler behavior.

When `process_deferred_webhook()` runs (line 1314), `$notification` is now an `array`. At line 1346:

```php
$this->run_webhook_received_action( (string) $webhook_type, $notification );
```

This calls `run_webhook_received_action()` at line 1670, which has a strict `object` type hint:

```php
private function run_webhook_received_action( string $webhook_type, object $notification ): void {
```

**Result:** TypeError on every deferred webhook execution.

## Impact

- **All iDEAL and Klarna orders** trigger this error (any redirect-based payment method that uses deferred webhooks)
- `payment_complete()` runs before the crash (line 1339), so orders DO transition to Processing
- But Action Scheduler marks the action as **Failed**, and the `wc_stripe_webhook_received` action (line 1684) never fires
- **Customer order confirmation emails may not be sent** — we have confirmed cases where customers received no email for iDEAL orders, and SMTP plugin logs show zero entries for these orders

## Steps to Reproduce

1. Enable iDEAL or Klarna as a payment method
2. Place a test order using iDEAL
3. Complete the payment on the bank redirect page
4. Go to **WooCommerce > Status > Action Scheduler**
5. Search for `wc_stripe_deferred_webhook`
6. All actions show as **Failed** with the TypeError message above

## Environment

- **Plugin version:** 10.5.3
- **WooCommerce:** 10.6.1
- **WordPress:** 6.9
- **PHP:** 8.3
- **Action Scheduler** runs via WP Cron and WP CLI

## Evidence

4 failed actions in production over 2 days, all with identical error:

| Order | Payment Method | Scheduled | Error |
|-------|---------------|-----------|-------|
| 784794 | iDEAL | 2026-03-25 11:17 | TypeError at line 1346 |
| 784798 | iDEAL | 2026-03-25 12:31 | TypeError at line 1346 |
| 784814 | Klarna | 2026-03-25 23:46 | TypeError at line 1346 |
| 784828 | iDEAL | 2026-03-26 13:40 | TypeError at line 1346 |

## Suggested Fix

Cast `$notification` back to object before passing to `run_webhook_received_action()`. In `process_deferred_webhook()`, before line 1346:

```php
// Action Scheduler deserializes stdClass objects as arrays — cast back to object.
if ( is_array( $notification ) ) {
    $notification = json_decode( wp_json_encode( $notification ) );
}
```

Alternatively, change the type hint on `run_webhook_received_action()` from `object` to `object|array` and handle both cases internally.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes STRIPE-1004
Fixes #5184 

Action Scheduler serializes scheduled job arguments. For `wc_stripe_deferred_webhook`, the Stripe webhook stdClass becomes nested arrays on load. `process_deferred_webhook()` then passed that value to `run_webhook_received_action( string $webhook_type, object $notification )`, which triggered a TypeError and failed every deferred job (notably redirect flows such as iDEAL / Klarna).

## Changes proposed in this Pull Request:
- Add `normalize_deferred_webhook_notification_to_object()` method to turn deserialized array payloads back into an object
- Call it at the start of `process_deferred_webhook()` to ensure the data passed to `run_webhook_received_action` is of correct type.

## Testing instructions
- Enable iDEAL or Klarna as a payment method
- Place a test order using iDEAL or Klarna
- Check out to `develop` branch.
- Complete the payment on the bank redirect page
- Go to **WooCommerce > Status > Action Scheduler**
- Search for the `wc_stripe_deferred_webhook` action
- The action should be failed with the TypeError message above
- Check out to this branch and follow the same steps.
-  `wc_stripe_deferred_webhook` actions should be successful now.

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

**Review by diegocurbelo — APPROVED** [review]
The changes look good, and it tests well 👍🏼

File: includes/class-wc-stripe-webhook-handler.php [hunk 1]
```diff
@@ -1311,17 +1311,55 @@ protected function defer_webhook_processing( $webhook_notification, $additional_
...
+
+			$object = json_decode( $json );
+			if ( ! is_object( $object ) ) {
+				throw new Exception( 'Failed to restore deferred webhook notification to an object.' );
+			}
+
+			return $object;
+		}
+
+		if ( is_object( $notification ) ) {
```
Comment (daledupreez) [inline includes/class-wc-stripe-webhook-handler.php]: Not blocking, but I think I would find this a little bit easier to follow if this condition happened before the array checks, so this would effectively be an early return. The logic for arrays is more complex, so I follow that rabbit hole and have to re-establish context when I get to this check.

File: changelog.txt [hunk 2]
```diff
@@ -33,6 +33,7 @@
 * Dev - Hide Stripe's testing assistant on checkout page
 * Dev - Treat misaligned statements as errors in PHPCS ruleset
 * Fix - Put subscription on hold when Stripe Radar blocks a renewal payment to prevent WC Subscriptions from scheduling further retry attempts
+* Fix - Prevent TypeError when Action Scheduler runs deferred webhooks by restoring the Stripe notification payload as an object after deserialization
```
Comment (daledupreez) [inline changelog.txt]: Not blocking, but I think we can simplify this changelog entry.
```suggestion
* Fix - Prevent TypeError when processing deferred webhooks using Action Scheduler
```

**Review by daledupreez — APPROVED** [review]
Changes LGTM and test well.
