### PR TITLE
Fix duplicate payment notifications

### LINKED ISSUE #1061: Double payment complete notification due to duplicate status change
**Describe the bug**

Reported in  2430512-zen

A unique case where a user is experiencing a double payment complete notification in the orders. This is causing the Stripe payout values to show incorrectly, as well as a duplicate status change (double emails). 

https://cld.wthms.co/o8NBVs+
*If the image does not load, please click this link: https://cld.wthms.co/o8NBVs*

**Expected behavior**
A single payment, and status update in the order note section.

**Proposed fix by user**

> I’ve modified the note wrote by your plugin to understand what parts of the code gets actually called. The duplicated “Stripe change” notes were created in `includes/abstracts/abstract-wc-stripe-payment-gateway.php at line 424`.

> In that code block you’re only checking if ‘succeeded’ === $response->status and it’s corrected but as i can see in the log you call that function twice: when the PaymentIntent initiated and when it succeded. And calling it twice cause the error.

**Environment (please complete the following information):**
 - WordPress Version 5.24
 - WooCommerce Version 3.7.1
 - Stripe Plugin Version 4.3.0
 - Browser [e.g. chrome, safari] and Version N/A 
 - Any other plugins installed - Yes, as seen in the System Status Report on the ticket

**Additional context**
Please check the ticket for Background information and slack reference.

### LINKED ISSUE #1062: Payment Complete occurs twice on Woocommerce Subscriptions
**Describe the bug**
When renewing a woocommerce subscription, intermittently the payment goes from pending to complete twice for one order. This results in the hooks being fired twice, emails being sent out twice, etc. I've verified that this doesn't occur with other payment options (e.g. Paypal).

**To Reproduce**
  Start a subscription using the woocommerce stripe gateway plugin.
1. Go to tools->scheduled actions.
2. Click on pending actions.
3. Scroll down and click "run" on your subscription.
4. See the order in woocommerce->orders
    The order will go from pending to complete twice for the same order.

  Note that this doesn't occur every time, so you may have to fire the user's renew subscription action under tools->scheduled actions  more than once to trigger an order that is suffering from this bug.

**Expected behavior**
It should go from pending to complete only once.

**Environment (please complete the following information):**
 - WordPress Version 5.2.4
 - WooCommerce Version 3.7.1
 - Stripe Plugin Version 4.3.0
 - Browser [e.g. chrome, safari] and Version 77.0.3865.120
 - Any other plugins installed 

**Additional context**
This is occuring with sandboxed Stripe subscription renewals. I've never seen it occur on regular purchases. So far it only seems to occur with subscription renewals.

This issue has been raised before and appears to be on-going:

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/889

woocommerce stripe bug

### PR DESCRIPTION
**Pull request by RadoslavGeorgiev**
Fixes #1061. Fixes #1062.

#### Changes proposed in this Pull Request:

1. Use the `lock_order_payment` and `unlock_order_payment` pair of methods to prevent webhooks from interfering with subscription renewal payments.
2. Modify `lock_order_payment` to work without a particular PaymentIntent, needed because the creation and confirmation of renewal intents is a single API-call process.
3. By doing 1. and 2., prevent payment intent success webhooks from interfering with renewal orders completely. This is not needed, because renewals are headless and wouldn't fail because the customer closed their tab or something similar.

#### Testing instructions

1. Prepare the setup.
    1. Create a subscription and purchase it.
    2. Make sure webhooks are enabled.
2. Reproduce the bug
   1. Checkout `master`.
   2. In `WC_Stripe_Subs_Compat::process_subscription_payment`, add a `sleep( 10 )` right after the `create_and_confirm_intent_for_off_session` call.
    3. Process a renewal manually from the subscription screen.
    4. Check the renewal order and notice the duplicate messages.
    5. Remove the `sleep` call.
3. Test
    1. Checkout this branch.
    3. Process a renewal manually from the subscription screen.
    4. Check the renewal order and make sure there are no duplicate messages.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).

### CODE REVIEW

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -1204,18 +1204,18 @@ public function get_intent_from_order( $order ) {
...
 	 */
-	public function lock_order_payment( $order, $intent ) {
+	public function lock_order_payment( $order, $intent = null ) {
 		$order_id       = WC_Stripe_Helper::is_wc_lt( '3.0' ) ? $order->id : $order->get_id();
 		$transient_name = 'wc_stripe_processing_intent_' . $order_id;
 		$processing     = get_transient( $transient_name );
 
 		// Block the process if the same intent is already being handled.
-		if ( $processing === $intent->id ) {
+		if ( -1 == $processing || $processing === $intent->id ) {
```
Comment (v18) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Since `$intent` can be `null`, we need to check if property `id` exists:

```
isset( $intent->id ) && $processing === $intent->id
```

That should fix both of the failing tests.

Also - is there a reason not to use triple equals for `-1 === $processing`?

**Comment by v18** [comment]
Neat solution @RadoslavGeorgiev. Left a small comment, feel free to 🚢 after fixing the tests.

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 1 above)
Comment (RadoslavGeorgiev) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: > Since $intent can be null, we need to check if property id exists:

Good catch, fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1083/commits/7214ca575dd0064e4d0676e597ae343280b187f3.

> Also - is there a reason not to use triple equals for -1 === $processing?

It was because I don't 100% trust types in options, but I decided to do that, so I switched to `'-1'`. Even though I was setting the transient to an integer, it was read as a string 🤷‍♂
