### PR TITLE
Fix legacy method names in order meta

### LINKED ISSUE #2932: New settings page issue
**Describe the bug**
While reviewing https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2870 @mattallan discovered a few issues with payment methods when UPE is disabled.
- In order edit page, the payment method name is wrong. If the order is paid with `EPS` it is showing `Payment via stripe_eps` instead of `Payment via EPS` (same for all other methods)
- ~~In the checkout page for a subscription order, all the stripe methods are showing up~~ (This is the same behavior as the trunk, so not a bug. The subscriptions are created as manually renewing subscriptions for payment methods using source)

**Expected behavior**
- If the order is paid with `EPS`  in order edit page it should show `Payment via EPS` (same for all other methods)
- ~~In the checkout page for a subscription order, only the supported methods should be displayed.~~

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #2932 

## Changes proposed in this Pull Request:
- In https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934/commits/3fbd3d524d03ac9d3464c3ee858333a2f4ffe98e I have reverted the subscription check for Multibanco. I had added this check in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2870 to hide Multibanco as it was showing up as a payment method while purchasing a subscription when UPE was enabled. However, upon testing in `trunk` I found that trunk has the same behavior for Multibanco in UPE and all other methods when UPE is disabled. In short, the existing behavior in the latest releases are, when you have a subscription product in cart, the non-UPE methods using Sources API is available as an option to checkout but the subscription will be created as a manually renewed subscription.
- In https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934/commits/25594a8c3187ebf70a6b48a9d75e4a9f359db52b reverted the changes I made in PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2839. I removed all the stripe methods from `add_gateways` [method](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/woocommerce-gateway-stripe.php#L242) which was called by `woocommerce_payment_gateways` so that they don't appear on the **WooCommerce > Settings > Payments** page. As a result `WC()->payment_gateways->payment_gateways()` does not have these Stripe methods listed. As a result, [here](https://github.com/woocommerce/woocommerce/blob/8c55e53772a20a84f7071089dbf1675bc7dceb02/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L172) the order [can not find the stripe payment method object](https://github.com/woocommerce/woocommerce/blob/8c55e53772a20a84f7071089dbf1675bc7dceb02/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L177) (just has the id) and finally just renders the id [here](https://github.com/woocommerce/woocommerce/blob/8c55e53772a20a84f7071089dbf1675bc7dceb02/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L210). This is the reason behind the order meta payment method name issue in #2932. (There could be other places implicated by `WC()->payment_gateways->payment_gateways()` not having the stripe payment methods, though I have not found others yet)
- As in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934/commits/25594a8c3187ebf70a6b48a9d75e4a9f359db52b I am adding the stripe payment methods to the list again, they are visible on the **WooCommerce > Settings > Payments** page. So in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934/commits/803835fa6b2839307328e8e846192a3dfad3c3c0 I am hiding them using css.
- To show the payment methods in the order saved inside Stripe settings page and not in the order of the outer settings page (where they are hidden), in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934/commits/baf0589ae51b169e467b9d0fab5283aaaf7b83f7 I am unsettling them from the gateway object before using them to the expected position.

#### Reproduce the bug
- Go to the `develop` branch.
- Disable the `New checkout experience` from the Stripe settings page.
- Set Euro as store currency and enable a few payment methods on the settings page (like EPS, giropay etc.)
- Click the customize button, set a title for the enabled methods or keep it as before.
- As a shopper, add a product to the cart and checkout with any Stripe enabled methods except `card`.
- After placing the order, in your wp dashboard go to this order edit page. 
- Notice that the payment method name is displayed as `stripe_xyz` instead of the method title.

wpm

#### Test the fix
- Go to the `fix/2932-non-upe-method-in-order-and-checkout` branch (this branch).
- Disable the `New checkout experience` from the Stripe settings page.
- Set Euro as store currency and enable a few payment methods on the settings page (like EPS, giropay etc.)
- Click the customize button, set a title for the enabled methods or keep it as before.
- As a shopper, add a product to the cart and checkout with any Stripe enabled methods except `card`.
- After placing the order, in your wp dashboard go to this order edit page. 
- Make sure that the payment method name is displayed as the one you have set as the title.

cpm

#### Payment method order in checkout page
- Go to the `fix/2932-non-upe-method-in-order-and-checkout` branch (this branch).
- Disable the `New checkout experience` from the Stripe settings page.
- Reorder payment methods and customize some of their names.
- Reorder the main Stripe method in **WooCommerce > Settings > Payments**. (cod, stripe, cheque)
- As a shopper, go to the checkout page and ensure that the ordering is correct. Expected ordering would be cod, all the Stripe methods as ordered inside the Stripe settings page, cheque.
- Reorder payment methods in Stripe settings page, refresh the checkout page as a shopper and make sure the order is correct.

#### Add payment method page
- Enable UPE
- Enable a few methods including Card, Sepa, iDeal and Bancontact.
- Go to **My Account > Add payment method** page. 
- When you try to add a payment method Card, Sepa, iDeal and Bancontact should be available as options.
- Disable UPE
- Enable a few methods including Card and Sepa
- Go to **My Account > Add payment method** page. 
- When you try to add a payment method Card and Sepa.

### CODE REVIEW

**Review by a-danae — COMMENTED** [review]
Thanks for these changes, @Mayisha!  Glad we caught this!

Here's the summary from a a partial round of testing.

I was able to replicate the issue in `develop` and successfully tested these flows:
- [x]  Payment gateway name in order details. The APM’s name is displayed in the order details, not its gateway ID
- [x]  Reordering the payment methods in WooCommerce > Payments. All of the payment methods from Stripe are displayed together. This group is ordered as expected in relationship with the payment methods introduced by WooCommerce and other extensions, like PayPal Payments, on the checkout pages.
- [x]  Reordering the Stripe Payment methods. They are ordered as expected in relationship with each other on the classic checkout page.
- [x]  SEPA and Cards are displayed on the Add new payment method page when UPE is disabled.

🔴 I also noticed the following unexpected behavior. There’s a fatal error when visiting the Add new payment method page with UPE enabled.

```
Undefined variable: gateway in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php on line 196
Uncaught Error: Call to a member function supports() on null in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:196
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(324): WC_Stripe_UPE_Payment_Gateway->get_available_payment_gateways(Array)
#1 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(333): apply_filters('woocommerce_ava...', Array)
#3 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(535): WC_Payment_Gateways->get_available_payment_gateways()
#4 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(279): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->render_button_wrapper_registrar()
#5 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule. in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php on line 196
```

I'll check out this error, check other flows, and review the code next.

**Comment by a-danae** [comment]
So, the error I mentioned before should have been fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934/commits/4f01c4b0b60ceede0a4bde85724f87840a5da91e.

I updated the branch this PR points to from `develop` to `add/deferred-intent` because I think it'll be better to solve the incoming conflicts while testing this PR, rather than when updating `add/deferred-intent`. Hope it's okay.

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 1]
```diff
@@ -206,29 +207,29 @@ public function __construct() {
...
 	/**
-	 * Include Multibanco in the list of payment methods.
+	 * Include Multibanco in the list of payment methods when available.
 	 * As we are not registering Multibanco to show in the payment settings page and Multibanco is not a UPE payment method,
 	 * we need to include it here separately so that it's available in the checkout, pay for order, add payment method etc. pages.
 	 *
 	 * @param WC_Payment_Gateway[] $gateways A list of all available gateways on the payments settings page.
 	 * @return WC_Payment_Gateway[]          The same list if Multibanco is disabled or a list including the Multibanco method.
 	 */
 	public function get_available_payment_gateways( $gateways ) {
```
Comment (a-danae) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Maybe adding Multibanco here isn't needed with Split PE?

- We're including Multibanco in the gateways at https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934/files#diff-e1e5e9b442c2b5d4105edbdc3787651333c1923dd623677025f72d25796900d6R417, 
- And ordering the gateways isn't supported in UPE

Comment (a-danae) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Updated in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934/commits/ed18ce5b897f0f8580d773aa04f7a31ac3fa26c6, but glad to iterate on it

**Review by a-danae — APPROVED** [review]
Things tests well, thanks @Mayisha 🙂 

I've pushed an update and will proceed to merge it so GlobalStep can include these changes in their test round on Monday. Please feel free to review those when you're back!

I think it'd be good to revisit it, since hiding the gateways from the Payment Methods page with CSS seems a bit fragile. I'd be curious if there's a more robust approach but I couldn't dive there. I wonder if WooPayments needed to handle a similar scenario.

Approving and proceeding to merge.

**Comment by mattallan** [comment]
Nice PR @Mayisha! These changes also fixed refunding via Multibanco 🎉 

Previously if you purchased an order with Multibanco, there was no "Refund $$ via Multibanco" button on the Edit Order page, only manual refunds were supported.

The required change to fix this is to add Multibanco to our `add_gateways()` function so that it's returned when WooCommerce Core calls `WC()->payment_gateways->payment_gateways()`.


> I think it'd be good to revisit it, since hiding the gateways from the Payment Methods page with CSS seems a bit fragile. I'd be curious if there's a more robust approach but I couldn't dive there. I wonder if WooPayments needed to handle a similar scenario.

@a-danae @Mayisha James added a new function recently to hide payment methods on the WooCommerce payment methods list page here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8f0db9433cffe310b6252649bc452c4807bd205c/includes/admin/class-wc-stripe-settings-controller.php#L144

We should be able to replace the CSS approach in this PR by adding Multibanco and any other non-UPE classes to the `hide_gateways_on_settings_page()` function. I don't think it's not a priority to get this fixed before GlobalStep testing, but I'll open up a PR with this change

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php (hunk 1 above)
Comment (Mayisha) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: I agree that we don't need to include Multibanco in this place as we are now registering it in the other place. 

Just noticed one minor UI issue. This function was adding Multibanco to the checkout page right after the Stripe UPE (so that they are together and no other methods come in between). With split UPE all the methods are now separate. I see my checkout page like this when other methods are also enabled.

Comment (a-danae) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: > Just noticed one minor UI issue. This function was adding Multibanco to the checkout page right after the Stripe UPE (so that they are together and no other methods come in between). With split UPE all the methods are now separate. I see my checkout page like this when other methods are also enabled.

Yup, I noticed something similar on my end, but the order is different:


I'm not sure where the order is defined, but instead of addressing this, I'd propose to implement changing the display order for UPE. This functionality is in the original designs, but we phased it out for UPE to implement Split PE first. So, we could tackle both together for 8.1.0. What do you think? I'll create an issue for this if you agree.

Comment (Mayisha) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Sounds good @a-danae :+1:

Comment (a-danae) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Hey hey! Here's the related GH issue to implement this 

- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2994
