### PR TITLE
UPE - Implement the 'Update all subscriptions payment methods' checkbox on My Account → Payment methods 

### LINKED ISSUE #1421: Make "update the payment method" checkbox text consistent with what's in WooCommerce Subscriptions
In https://github.com/woocommerce/woocommerce-gateway-stripe/blob/84b6457d691f47bdbcaa45f4d218ba852532c857/includes/compat/class-wc-stripe-subs-compat.php#L92 we have

> Update the Payment Method used for all of my active subscriptions.

But WooCommerce Subscriptions templates/checkout/form-change-payment-method.php has

> Update the payment method used for %1$sall%2$s of my current subscriptions

We should uncapitalize ours, replace "active" with "current" and consider bolding all like WCSubs does.

This is exposed in /my-account > View Payment Methods > Add payment method

### LINKED ISSUE #3453: Add checkbox to update all Subscriptions with new payment method on UPE stores
**Describe the bug**
While triaging other issues I stumbled on https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1421 which reports an inconsistancy between the text for a specific checkbox displayed on the **My Account > Payment methods > Add Payment method** page. 

I discovered that this feature is not present on stores with the UPE checkout setting.

We should make sure the UPE setting has feature parity with the legacy checkout experience. 

**To Reproduce**

1. Enable the Legacy checkout experience. 
2. Go to **My Account > Payment methods > Add Payment method**
3. Notice the checkbox displayed below the Stripe payment elements. 

<p align="center">
Screenshot 2024-09-23 at 4 17 06 pm
</p> 

4. Disable the legacy checkout experience. 
5. Refresh the **My Account > Payment methods > Add Payment method** page
6. Notice there is no checkbox. 

<p align="center">
Screenshot 2024-09-23 at 4 17 52 pm
</p> 

**Expected behavior**
This feature should be offered to stores with UPE enabled.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3453
Fixes #1421

## Changes proposed in this Pull Request:

In the legacy checkout experience we offered a feature that enabled customers to update all their subscriptions to a new payment method when adding a new method via the **My Account → Payment methods** page. This was never ported over to the UPE gateway.

This PR adds support for this feature for stores with the legacy checkout experience disabled. 

<p align="center">
Screenshot 2024-09-24 at 1 35 13 pm
</br>
<sup>Update all subscriptions checkbox shown on the <strong>My Account → Payment methods</strong> for UPE payment methods.</sup>
</p> 

## Testing instructions

**LEGACY CHECKOUT EXPERIENCE**

1. Enable the Legacy checkout experience.
2. Go to **My Account → Payment methods**.
3. Click **Add payment method**
4. Note that there's a checkbox displayed below the payment elements. 

<p align="center">
Screenshot 2024-09-23 at 4 17 06 pm
</p>

5. Check the 'update all' checkbox. 
6. Enter a new payment method that will be recognisable (eg `5555555555554444`)
7. After adding the payment method, go to **My Account → Subscriptions** and confirm all subscriptions have been updated to the new method. 

<p align="center">
Screenshot 2024-09-24 at 12 58 18 pm
</p>

---

**UPE**

1. Disable the Legacy checkout experience.
2. Enable a redirect payment method that supports Subscriptions like Cash App Pay. 
3. Go to **My Account → Payment methods**.
4. Click **Add payment method**
5. Note that there's a checkbox displayed below the payment elements. 
   - **Note:** On `develop` there is no checkbox.
6. Check the 'update all' checkbox. 
6. Enter a new payment method that will be recognisable (eg `4000056655665556`)
7. After adding the payment method, go to **My Account → Subscriptions** and confirm all subscriptions have been updated to the new method.

**Additional tests**:

1. Leave the checkbox unchecked -- no subscriptions are updated
2. Use a 3DS card -- all subscriptions are updated after the 3DS challenge is confirmed when the checkbox checked.
3. Cash App -- all subscriptions are updated after returning to the site when the checkbox checked.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-method.php [hunk 1]
```diff
@@ -543,16 +543,20 @@ public function payment_fields() {
...
 					$this->save_payment_method_checkbox( $force_save_payment );
 				}
 			}
+
 			if ( $display_tokenization ) {
 				$this->tokenization_script();
 				$this->saved_payment_methods();
 			}
+
+			do_action( 'wc_stripe_payment_fields_' . $this->id, $this->id );
```
Comment (james-allan) [inline includes/payment-methods/class-wc-stripe-upe-payment-method.php:559]: This action existed on the legacy checkout ([here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/issue/3453-add-update-all-subscription-pm-checkbox/includes/class-wc-gateway-stripe.php#L267)), but it was never triggered from the UPE versions of the `payment_fields()`. 

I think it's fine to reintroduce it, however, happy to be persuaded otherwise.

Comment (mattallan) [reply includes/payment-methods/class-wc-stripe-upe-payment-method.php:559]: What's the alternative?

If I understand correctly, the alternative would be to introduce a new `do_action` hook name that's used for UPE specifcally and then attach `display_update_subs_payment_checkout()` to this new hook?

I think it's fine to use the same hook for legacy and UPE :)

File: readme.txt [hunk 2]
```diff
@@ -129,6 +129,8 @@ If you get stuck, you can ask for help in the Plugin Forum.
 == Changelog ==
 
 = 8.8.0 - xxxx-xx-xx =
+* Add - Implemented the "Update all subscriptions payment methods" checkbox on My Account → Payment methods for UPE payment methods.
+* Add - Add support for the new Stripe Checkout Element on the shortcode checkout page.
```
Comment (mattallan) [inline readme.txt:133]: This changelog entry wasn't add as part of: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3436 so I added it when fixing the conflicts

**Review by mattallan — APPROVED** [review]
Nice work on this @james-allan!

I've confirmed the issue on develop with no Update all subscriptions checkbox displayed when the new checkout is enabled: 

While trying to test updating all subscriptions with CashApp, I noticed the subscriptions weren't being updated.

This was caused by the `$payment_method_object` passed to the new `handle_upe_add_payment_method_success()` function being an error:

```
stdClass Object
(
    [error] => stdClass Object
        (
            [code] => resource_missing
            [doc_url] => https://stripe.com/docs/error-codes/resource-missing
            [message] => No such PaymentMethod: '534'
            [param] => payment_method
            [request_log_url] => https://dashboard.stripe.com/acct_1Q38uIK1UrB0EvCu/test/logs/req_lOxmyn9agnnhnM?t=1727324002
            [type] => invalid_request_error
        )

)
```
This was fixed by your previous PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3456 and I've confirmed that updating this branch to the latest `develop` has fixed the issues I was seeing.

Full list of tests I ran:
- [x] LEGACY CHECKOUT EXPERIENCE (unchanged)
    - [x] Update all subscriptions selected
    - [x] Update all subscriptions not selected
- [ ] UPE
    - [x] `develop` no checkbox :x:
    - [x] Update all subscriptions selected. Confirmed all active subscriptions were updated: 
    - [x] Update all subscriptions not selected
    - [x] Checkbox selected and not selected using a 3DS card (`4000000000003220`)
    - [x] Checkbox selected and not selected using an APM (SEPA)
    - [ ] Checkbox selected and not selected using CashApp
