### PR TITLE
Retry failed subs payments with customer id closes #149

### LINKED ISSUE #149: Improved Subscriptions compatibility - trying payments when default credit card is change
#### Affected ticket(s)
516228-zd-woothemes
See ticket for further discussion and details

#### What I expected
When using Stripe and Subscriptions, subscriptions is not notified if the default credit card in Stripe has been changed. According to the Prospress team, this was previously handled properly by the Stripe extension, but since removed.

#### What happened instead
Subscription fails as it tries to charge the old card.

From the custom who reported the issue:
> With WC Subscriptions, the payment card is stored in wp_postmeta in the meta_key _stripe_card_id. When it's time for renewal, WC Subscriptions attempts to process the renewal automatically using this card ID.
If a user has previously deleted this card, WC Subscriptions is not notified, so it fails with error "Stripe Transaction Failed (Customer cus_*********** does not have a linked source with ID card_************.) Order status changed from Pending Payment to Failed."

From Prospress:

> I also think this type of issue may have been prevented in an earlier version of Stripe where it would retry payment just using the customer ID after it failed with a specific card. ie if it failed with a deleted card, it would retry by just using the customer id and therefore would use the new default card. This was removed in a later version when Subscriptions added its own retry system though.
Because that feature has been removed, I would suggest this change be added to the Stripe plugin. The Stripe plugin is better placed to handle this because:
>- it adds that option to make changes to the saved cards from the My Account page.
>- it knows what meta needs to change (if for instance, the meta keys changed in the future, for whatever reason, Subscriptions wouldn't need to be updated)

#### Steps to reproduce the issue

- A user purchases a subscription using Card A. - Card A is added on their Stripe profile.

- They go into member's area and adds a new card (Card B). Card B is added on ther Stripe profile.

- The user marks the card as default on member's area.

- The user removes Card A from member's area.

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by roykho**
Fixes #149 

#### Changes proposed in this Pull Request:
* Fix - Retry failed subscription payments with customer ID.

Retries can fail if customer has changed/removed their associated credit card on file. This fix will try to process their payment via their customer ID instead if that happens. Don't mind the DRY for now as there are several places that needs to be refactored when I get more time.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-gateway-stripe-addons.php [hunk 1]
```diff
@@ -97,6 +97,26 @@ protected function save_source( $order, $source ) {
...
 
 	/**
+	 * Manipulates the payment request specific to subscriptions.
+	 *
+	 * @since 3.1.7
+	 * @version 3.1.7
+	 * @param object $order
+	 * @param object $source
+	 */
+	public function filter_subscription_payment_request( $order, $source ) {
```
Comment (gedex) [inline includes/class-wc-gateway-stripe-addons.php]: Is this called somewhere? Quick grep doesn't show me it's being called or hooked.

**Comment by gedex** [comment]
I tested and it works as expected. Renewal is not failed anymore when the default card is changed and previous card is removed. I just left a question on the usage of `filter_subscription_payment_request`. 

Other thing is notices during renewal process, but that's not caused by this PR. It's related to another issue I've logged #238.

File: includes/class-wc-gateway-stripe-addons.php (hunk 1 above)
Comment (roykho) [inline includes/class-wc-gateway-stripe-addons.php]: Sorry that was left there in error. Should have removed that before committing. It is now removed.

**Comment by roykho** [comment]
@gedex - 2nd round please. I've added the fix for the WC 3.0 notices as well for #238.

**Comment by MrFent** [comment]
What about if:

1. Card A was used in the original subscription
2. That card is still on file
3. Card B also gets added. 
4. Subscription tries to renew, but card A gets declined.
5. Subscription then gets put on hold.

Shouldn't it try card B?

This recently happened to me. Card B would have been successful, but the subscriptions plugin didn't even attempt it.

**Comment by roykho** [comment]
@MrFent not the same issue. This fix here is trying to compensate if the card that was used for subs is now gone by charging against the customer. What you're proposing is try every card linked to the customer until one succeeds.
