### PR TITLE
fix: payment gateways asset path

### LINKED ISSUE #2046: fix: console error on the payments settings screen
**Describe the bug**
There is a console error on the "Payments" settings screen generated by our plugin.

**To Reproduce**
- Ensure you have the `_wcstripe_feature_upe_settings` flag disabled
- Ensure you have UPE checkout enabled and also a couple of payments methods enabled there
- Go to http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout 
- In the console there is an error `Uncaught TypeError: Cannot read property 'registerStore' of undefined`

console error

**Expected behavior**
No console error

### PR DESCRIPTION
**Pull request by frosso**
# Changes proposed in this Pull Request:

Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2046

The path in the payment gateways asset file is wrong, so it's not being included correctly.
Fixing the path, so that the dependencies are correctly queued, so that there's no error in the console:
console error

# Testing instructions

- Ensure you have the `_wcstripe_feature_upe_settings` flag disabled
- Ensure you have the Stripe gateway enabled
- Go to http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout
- No more error in the console!

### CODE REVIEW

File: includes/admin/class-wc-stripe-payment-gateways-controller.php [hunk 1]
```diff
@@ -28,8 +28,7 @@ public function __construct() {
 	}
 
 	public function register_payments_scripts() {
-		$payment_gateways_script_src_url    = plugins_url( 'build/payment_gateways.js', WC_STRIPE_MAIN_FILE );
-		$payment_gateways_script_asset_path = WC_STRIPE_PLUGIN_PATH . 'build/payment_gateways.asset.php';
```
Comment (frosso) [inline includes/admin/class-wc-stripe-payment-gateways-controller.php:32]: The path needed to start with a `/` -> `'/build/payment_gateways.asset.php'` (instead of `'build/payment_gateways.asset.php'`)

**Review by Mayisha — APPROVED** [review]
Thanks for fixing this @frosso. Tested locally and the console error is gone by this fix :100: 

I noticed one thing though. I remember you mentioned that the "disable confirmation modal" will be there only for the new settings. It is now present even if the `_wcstripe_feature_upe_settings` is disabled because [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8ab45098cfd1e8403b6073f3b917908408e90313/woocommerce-gateway-stripe.php#L230) we only check if UPE checkout is enabled (not checking if new settings is enabled)

This is not a bug or does not create any issues either in the functionality. Just wanted to mention to make sure it is aligned with the expected behavior.

**Comment by frosso** [comment]
@Mayisha thanks for bringing that up! That's correct, the confirmation modal should show only when the new settings flag is enabled & UPE is enabled.
It's not a big deal if it shows in the old subs, tho. As long as it works correctly 🤞
