### PR TITLE
Filter out payment methods which do not support current currency

### LINKED ISSUE #1739: UPE - Filter payment methods at checkout by supported currency
**Describe the bug**

Some UPE payment methods only support usage with particular currencies (e.g. giropay, Sofort, and SEPA all require EUR). If store owners set their store's currency to a currency that cannot support an enabled payment method, the store owner is shown a warning notice to change their currency in their store's admin section. If Stripe will support multi-currency, then store owners can enable multiple currencies and allow customers to choose to checkout with their preferred currency.

In either case, if a store's currency does not support usage with any enable payment method, the request to Stripe to create a payment intent will return an error and the UPE will fail to load, even if there are enabled payment methods that do support usage with the currently selected currency. We should filter the list of enabled payment methods by their supported currencies, so that we can avoid this situation and continue to use the UPE at checkout, when one or more currencies may be usable with the present currency.

**To Reproduce**
1. Enable the UPE following the steps in #1659. Add item to cart and proceed to checkout.
2. Set your store to a currency that is not supported by an enabled payment method (e.g. enable Giropay/Sofort, which require EUR, then set currency to USD).
3. UPE will fail to load and error notice will be displayed.

**Expected behavior**

Customer should be able to complete checkout with UPE, if one or more enabled payment methods are compatible with the currency present at checkout. For inspiration, [this function](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-upe-payment-method.php#L113-L121) is used to achieve this desired functionality in WCPay. Also, note that `get_woocommerce_currency` is the correct function to use to get the customer's currency, when multi-currency is enabled. 

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

### PR DESCRIPTION
**Pull request by superdav42**
fixes #1739

# Testing instructions

Enable UPE feature flag. 
```sql
INSERT INTO `wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES (NULL, '_wcstripe_feature_upe', 'yes', 'no') ON DUPLICATE KEY UPDATE `option_value`=VALUES(`option_value`);
```

Enable UPE in Stripe settings and check many payment methods.
Set store currency to not EUR.
Try to checkout with UPE
only Card method should be shown and no errors.
-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

**Comment by EvanDotPro** [comment]
Sorry, I've been tied up with new lead stuff and don't want to keep holding this up. I removed myself and let it randomly assign a new reviewer.

File: includes/class-wc-stripe-intent-controller.php [hunk 1]
```diff
@@ -304,14 +304,21 @@ public function create_payment_intent( $order_id = null ) {
...
 
-		$gateway = new WC_Stripe_UPE_Payment_Gateway();
+		$gateways = WC()->payment_gateways()->payment_gateways();
+		/**
+		 * Our gateway object.
+		 *
+		 * @var $gateway WC_Stripe_UPE_Payment_Gateway
+		 */
+		$gateway                 = $gateways[ WC_Stripe_UPE_Payment_Gateway::ID ];
+		$enabled_payment_methods = $gateway->get_upe_enabled_at_checkout_payment_method_ids();
```
Comment (diegocurbelo) [inline includes/class-wc-stripe-intent-controller.php]: We already discussed that we need to move this methods (and those from the order controller) to the UPE Gateway, but it might be worth mentioning that both the existent Stripe Gateway and the new UPE Stripe Gateway have the same ID (`stripe`)... just to be safe we can add something like this:
```
if ( ! is_a( $gateway, 'WC_Stripe_UPE_Payment_Gateway' ) ) {
    throw new Exception( __( "We're not able to process this payment.", 'woocommerce-gateway-stripe' ) );
}
```

**Review by diegocurbelo — APPROVED** [review]
Code looks good, and tests well! 🚢 

I left a comment but feel free to disregard it, we plan to move the UPE intent code to the UPE gateway anyway.
