### PR TITLE
Fix "no such customer" error on checkout

### LINKED ISSUE #1128: Handle Stripe.com account changes
2657609-zen

**Describe the bug**

Under certain circumstances, store owners may need to change the Stripe.com account.

This will cause the error shown in #1092 but has a large scope of how to fix that.

**To Reproduce**

I chatted to a store owner on WooCommerce.com live chat, this was their scenario:

> We recently went through a legal change that required us to create a new Stripe account. We were using the Stripe/Woo plugin fine previously. After inputting the new Stripe keys for our new account, we tried placing a test order in test mode using my WordPress Admin user, but we received the following error
> 
> No such customer: cus_xxxxxxxxx
> 
> Later we tried to place another test order in incognito mode and it worked, but we wanted to check with you about this, and see if you could take a look and give us directions. Reading some support forums such as the one below it looks like this issue could potentially affect all existing customers.

Also https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1092#issuecomment-571888062 by @richardsplayground 
>  We tried changing the Stripe public/secret keys in the plugin, and immediately started getting this error for all customers that had previously made a transaction with our old Stripe account.

**Expected behavior**

Store owners can change their Stripe.com if required using the Settings screen, our extension handles the code aspect

**Additional context**
p6q7sZ-6uE-p2#comment-19674

cc @compchris per p2 post and @richardsplayground due to your comment in #1092 

@allendav I'm placing Low due to the description of that label - this only affects a small number of users but is a show stopper for those customers so you may want to reprioritize.

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #1128 .

#### Changes proposed in this Pull Request:
- During Checkout, if a user is logged in and performed the checkout before, the associated customer object ID will be stored in the site DB and the object updated in Stripe.
- If the ID and the merchant's Stripe account mismatch for any reason, the checkout will fail on the update step.
- This PR recreates the customer object in the above scenario rather than failing straight away. 
- If the failure occurs more than once, then the error will be shown.

#### Test/reproduction steps:

1. Have two Stripe accounts ready
1. Create a WP/Woo user account for a customer (you can use incognito mode for convenience)
1. Use the keys from one Stripe account on your site
1. Place an order as the user from step 2.
1. Change the keys to another Stripe account (Check user meta table in your db, it should contain `_stripe_customer_id` field)
1. Attempt to place another order
1. The order should go through (`_stripe_customer_id` should contain a different value than before)

### CODE REVIEW

File: includes/class-wc-stripe-customer.php [hunk 1]
```diff
@@ -185,6 +190,14 @@ public function update_customer( $args = array() ) {
 
 		if ( ! empty( $response->error ) ) {
 			if ( $this->is_no_such_customer_error( $response->error ) ) {
+				// This can happen when switching the main Stripe account or importing users from another site.
+				if ( 0 === $retries ) {
+					// If not already tried, recreate the customer and then update it.
+					$this->delete_id_from_meta();
+					$this->create_customer();
+					return $this->update_customer( $args, $retries++ );
+				}
```
Comment (vbelolapotkov) [inline includes/class-wc-stripe-customer.php:199]: @marcinbot this looks like a great solution! Some thoughts and questions on this:

1. At the moment I see `$retries` is used as a boolean flag (either try to create new customer when it's not found or throw). Do you plan to have more than a single retry in the future? If not does it make sense to switch to boolean flag?

2. Does it make sense to delete current customer id from user meta before a new customer is created? Is it better/safer than creating a customer first and then calling `update_id_in_meta`?

3. Three levels of if statements seem to be a good sign for refactoring and extraction some pieces into their own methods. What do you think?

Comment (marcinbot) [reply includes/class-wc-stripe-customer.php]: > At the moment I see $retries is used as a boolean flag (either try to create new customer when it's not found or throw). Do you plan to have more than a single retry in the future? If not does it make sense to switch to boolean flag?

Fixed in 2b82fc6. At first I tried naming it `$retry` but even for me it seemed like a flag that would make the function retry rather than indicate that it is a retry, so I went with int. But not I named the flag `is_retry` and went back to bool, which should be clear.

> Does it make sense to delete current customer id from user meta before a new customer is created? Is it better/safer than creating a customer first and then calling update_id_in_meta?

Fixed in 0a933f0. I was following the pattern set [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1158/commits/0a933f02ed07aaf841d26d0a491698e4b21b993e#diff-f8dd0b04c52dc566825dead0a3b8b84cL270). Looks like `create_customer` would overwrite the existing data so deleting might be redundant, but I extracted both calls to a new function `recreate_customer` so it's clearer what is going on. 

> Three levels of if statements seem to be a good sign for refactoring and extraction some pieces into their own methods. What do you think?

Fixed in 0a933f0. I removed the suggestion of live/test mode. It's not very helpful and it can be really confusing when presented to real customers.

Comment (vbelolapotkov) [reply includes/class-wc-stripe-customer.php]: Thanks for the changes! Looks good! 👍

**Comment by vbelolapotkov** [comment]
> I experimented a bit with storing the Customer ID against the secret key hash and then adding some migration logic. As far as I can see, the scenario you described could affect subscriptions. But I think this is an edge case. With the reports we received there was no mention of subscriptions. Also, there are more places that rely on the id directly being stored in the DB rather than going through the WC_Stripe_Customer class. Refactoring this reliably would be a bigger undertaking with a potentially small payoff.

Thanks for the research and experimenting here!

> In the interest of reducing complexity here, I think we shouldn't fix it in this PR and see if this gets reported and how often.

Understand and fully agree with you!

**Comment by VivekManglani** [comment]
Hey @marcinbot 

I just came across this ticket as I have a website that just had this problem. We switched stripe keys on 1st April and have had customers report the "No such customer ..." error.

I assume your commit solves this problem however I take it it's not pushed as an update yet? In the mean time we've manually deleted all **_stripe_customer_id** meta_keys from the **wp_usermeta** table for customers before 1st April.

We've also got reports of another issue, a "No such source: src_......." error. I believe this is because the customer's saved card source does not exist on the new Stripe account? Does your commit solve this issue too? I believe it should automatically remove the saved payment method as it cannot be found and respond with an error instructing the user to add a new credit card?
