### PR TITLE
Moving existing order lock and bailing out when it is active

### LINKED ISSUE #4149: Woocommerce Checkout Doesn't Progress to Thank You Page after Successful Charge
**Describe the bug**
Yesterday (2025-03-25) we had 4 customers who experienced a problem with the checkout. (For reference we received 50-ish orders successfully that day). They click the 'Pay Now' button on the checkout but the page just stays as it is. However, Stripe processes the charge and returns a charge successful message to the webhook (confirmed in the plugin api log: `2025-03-25T12:47:28+00:00 Debug Webhook received: charge.succeeded`). 

**To Reproduce**
1. Enter payment details on checkout and click 'Pay Now'
2. The checkout does not progress
3. User re-attempts checkout payment
4. User is charged double

**Expected behavior**
When payment is confirmed via the API the order status should progress and the checkout page should progress to the Thank You / Order Confirmed page.

**Screenshots**
Image

**Environment (please complete the following information):**
 - WordPress Version: 6.7.2
 - WooCommerce Version: 9.7.1
 - Stripe Plugin Version: 9.3.1
 - Browser [e.g. chrome, safari] and Version: iPhone Safari, Mac Safari, PC / Desktop
 - Any other plugins installed: WC Order Status Manager (although the orders only go through default statuses i.e. 'pending-payment' and 'processing')
 - PHP: 8.3

**Additional context**
As I mentioned, this affected 4 customers, in slightly different ways. One customer paid twice but it generated two shipments (i.e. the process progressed on the server) but the customer didn't see the Order Confirmation screen the first time. Two customers experienced the same, but the shipment wasn't created (the server didn't process the order). The final customer attempted to pay 3 times but didn't see any Order Confirmation screen. 

The orders vary in payment method: Apple Pay, Google Pay, credit cards, debit cards.

In all these cases the Order Notes show a successful 'payment intent created', but only the ones that progressed also show a 'charge complete' note, however the API log on the server shows the webhook message was received (and there are no delivery errors in the webhook console in Stripe).

### PR DESCRIPTION
**Pull request by wjrosa**
Partially fixes [STRIPE-371](https://linear.app/a8c/issue/STRIPE-371)
Partially fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4149
Suggested in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4432#issuecomment-3014056513
POC PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4450

## Changes proposed in this Pull Request:

This PR applies @annemirasol's suggestion [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4432#issuecomment-3014056513) to reuse the existing order lock functionality instead of creating another (which I tried [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4432)).

This is part of our efforts to avoid duplicate charges.

## Testing instructions

- Checkout to this branch on your test environment (`add/moving-existing-order-lock-and-bailing-out-when-active`)
- Connect your Stripe account
- As a shopper, add any product to your cart
- Open a checkout page in 2 different tabs and fill in all the required information
- On both tabs, try to place the order at the same time (with less than a minute of difference)
- You should see the following error on your second tab:
Screenshot 2025-06-24 at 17 40 31

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 1]
```diff
@@ -1186,6 +1193,9 @@ private function process_payment_with_payment_method( int $order_id ) {
 			);
 		} catch ( WC_Stripe_Exception $e ) {
 			return $this->handle_process_payment_error( $e, $order );
+		} finally {
+			// Ensure the order is unlocked in case of an exception.
+			$this->unlock_order_payment( $order );
```
Comment (Mayisha) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:1197]: To handle the case of an exception, we should call the `unlock` function in the `catch` block instead of `finally`. And also keep the previous `unlock` call in place.  

If we unlock it in finally it might unlock an order which was not locked in the current request.

I haven't been able to reproduce this scenario successfully but I am thinking about this flow-
- Request 1 calls `process_payment_with_payment_method` and adds a lock.
- Request 2 calls `process_payment_with_payment_method` and comes to the newly added condition.

```
if ( $this->is_order_payment_locked( $order ) ) {
				// If the request is already being processed, return an error.
				return [
					'result'   => 'failure',
					'redirect' => '',
					'message'  => __( 'Your payment is already being processed. Please wait.', 'woocommerce-gateway-stripe' ),
				];
			}
```

- Request 2 returns because of this condition but unlocks the order as the unlock call is in finally block.
- A webhook comes and  processes the same order which is now unlocked.

Comment (wjrosa) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:1197]: I think it makes sense conceptually, so I moved the unlock call in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4462/commits/df3087af70026918b977766e892d2afce06c906e

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 2]
```diff
@@ -1033,6 +1033,18 @@ private function process_payment_with_payment_method( int $order_id ) {
...
+				return [
+					'result'   => 'failure',
+					'redirect' => '',
+					'message'  => __( 'Your payment is already being processed. Please wait.', 'woocommerce-gateway-stripe' ),
+				];
+			}
+
+			// Lock the order before we create and confirm the payment/setup intents to prevent Stripe sending the success webhook before this request is completed.
+			$this->lock_order_payment( $order );
+
```
Comment (annemirasol) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: I like how this is readable. Slight concern that it adds an extra "check" step, redundant because checking for an existing lock is already performed inside `lock_order_payment( $order )`. I think we want locking to be ideally with minimal operations as possible, to reduce the surface for race conditions.

Maybe something like this? 
```
// Attempt to acquire lock, bail if already locked
$is_already_locked = $this->lock_order_payment( $order );
if ( $is_already_locked ) {
   return [...];
}
```

What do you think?

**Review by annemirasol — COMMENTED** [review]
I also noticed that we don't display the informative error message for **shortcode** checkout. This should probably be fixed in a separate PR -- IIRC we always output this generic error message for shortcode checkout for server-side errors.

Screenshot 2025-07-08 at 10 33 20 AM

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php (hunk 2 above)
Comment (wjrosa) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: Makes total sense! Updated it in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4462/commits/dfe242f626e760d281de8f57344000290c1984a6

**Review by annemirasol — APPROVED** [review]
LGTM! Thanks for working on this :shipit:

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 3]
```diff
@@ -1785,6 +1775,38 @@ public function unlock_order_payment( $order ) {
...
+	 * @return bool
+	 */
+	protected function is_order_payment_locked( $order ) {
+		$existing_lock = $this->get_order_existing_lock( $order );
+		if ( $existing_lock ) {
+			$parts      = explode( '|', $existing_lock ); // Format is: "{expiry_timestamp}" or "{expiry_timestamp}|{pi_xxxx}" if an intent is passed.
+			$expiration = (int) $parts[0];
+
+			// If the lock is still active, return true.
+			if ( time() <= $expiration ) {
```
Comment (Mayisha) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php:1801]: Just wanted to confirm, is the intent-related check intentionally removed?

**Review by Mayisha — APPROVED** [review]
Thank you for the improvement. Looks good to me. 👍 

I have the same observation as Anne for the shortcode checkout notice and a quick question about the change of logic in the locking method.

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 3 above)
Comment (wjrosa) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php:1801]: Not really, it got lost during the change in the implementation. Thanks for flagging. But I attempted to add it back to see how it would behave, and it does not work correctly due to the lack of payment intent at the beginning of the payment flow. I removed it for good now, along with the remaining references.
