### PR TITLE
Remove hard requirement for customer phone numbers with Apple Pay

### LINKED ISSUE #1303: Stripe Apple Pay requires Phone Number - Need to remove this requirement
**Describe the bug**
User in this forum topic has set the Phone field as optional, but Apple Pay requires them to enter that field because we have requestPayerPhone: true

https://wordpress.org/support/topic/payment-request-buttons-requires-phone-nr/

**Expected behavior**
Per Stripe's documentation the phone number is optional and not a requirement. https://stripe.com/docs/apple-pay/best-practices

### PR DESCRIPTION
**Pull request by reykjalin**
Fixes #1303.

The entirety of the fix is contained in https://github.com/woocommerce/woocommerce-gateway-stripe/commit/3654b4e11843711fa241a90c8476feac9336484f. The other 2 commits are some changes to the linting config, and addressing some pre-existing linting issues. I know it's not strictly part of this issue, but I was touching the code anyway, so I thought I'd clear up some of those.

~~@bmccotter @allendav Do you think the language describing the new option in the Stripe settings is good enough, or would you like to see some changes there?~~

~~Also, should this even be a new option in the settings? Maybe it would be better to add this as a filter instead of a new option in the plugin settings? And maybe we should just respect the WC core setting from the theme customizer?~~

The implementation now respects the [Checkout settings](https://docs.woocommerce.com/document/woocommerce-customizer/#section-17) in the customizer. The fix is now in 3654b4e11843711fa241a90c8476feac9336484f (like before) and 6507aacd1268612241bd5d8095710e04df3b28bf (one-line change).

How do we make this as painless as possible?

#### Changes proposed in this Pull Request:

- Adds a checkbox in the Stripe settings giving merchants the option to require a phone number when customers checkout with Apple Pay.
- Phone numbers are **not required** by default.

#### Testing instructions

1. Delete the `woocommerce_checkout_phone_field` row in the `wp_options` DB table.
1. Try starting a payment using Apple Pay.
2. Confirm that you **need** to add a phone number to the contact details.
3. Now open the WP theme customizer, and navigate to `WooCommerce > Checkout`.
4. Set the `Require Phone Number` option to `optional`.
5. Try starting a payment using Apple Pay.
6. Confirm that you **don't need** to add a phone number to the contact details.
7. Now set the `Require Phone Number` option back to `required`.
8. Try starting a payment using Apple Pay.
9. Confirm that you **need** to add a phone number to the contact details.

The reason we switch from `required` to `optional` and back to `required` is because in step 3 we're relying on the default value of `get_option`. In steps 7 and 10 we're checking the actual value of the setting retreived by `get_option`.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`. _I ran `npm run uglify`, I think that's enough?_.

### CODE REVIEW

**Comment by allendav** [comment]
> And maybe we should just respect the WC core setting from the theme customizer?

Yes, I think so? cc @dechov

**Comment by reykjalin** [comment]
I'll work on respecting the customizer instead of adding options to the Stripe settings menu. We can always revert back to the commit here if we decide the Stripe settings are better.

Please let me know what you think @bmccotter @dechov.

**Comment by reykjalin** [comment]
I've updated the PR to respect the option set in the WP customizer. The slight "disadvange" here is that the phone number is required by default. The huge upside, however, is that we're fully aligned with the WooCommerce Core settings.

**Comment by dechov** [comment]
Not sure exactly what the best interface is here in terms of merchants' needs (and it's certainly possible we didn't consider enough choices in the issue) – the core option aligns with @AashikP's expectation in the [forum thread](https://wordpress.org/support/topic/payment-request-buttons-requires-phone-nr/#post-13400790), but I haven't seen any other suggestion. I'm onboard with the core option 👍 since I think it has similar enough intention, even though it's a less flexible & explicit way.

I think continuing to require the phone number by default makes sense, since I don't think the forum thread or issue was necessarily requesting to change default behavior for everyone.

File: includes/payment-methods/class-wc-stripe-payment-request.php [hunk 1]
```diff
@@ -61,16 +61,18 @@ class WC_Stripe_Payment_Request {
...
-		$this->total_label      = ! empty( $this->stripe_settings['statement_descriptor'] ) ? WC_Stripe_Helper::clean_statement_descriptor( $this->stripe_settings['statement_descriptor'] ) : '';
+		self::$_this                        = $this;
+		$this->stripe_settings              = get_option( 'woocommerce_stripe_settings', array() );
+		$this->testmode                     = ( ! empty( $this->stripe_settings['testmode'] ) && 'yes' === $this->stripe_settings['testmode'] ) ? true : false;
+		$this->publishable_key              = ! empty( $this->stripe_settings['publishable_key'] ) ? $this->stripe_settings['publishable_key'] : '';
+		$this->secret_key                   = ! empty( $this->stripe_settings['secret_key'] ) ? $this->stripe_settings['secret_key'] : '';
+		$this->total_label                  = ! empty( $this->stripe_settings['statement_descriptor'] ) ? WC_Stripe_Helper::clean_statement_descriptor( $this->stripe_settings['statement_descriptor'] ) : '';
+		// Defaults to 'required' to match how core initializes this option.
+		$this->require_phone_with_apple_pay = 'required' === get_option( 'woocommerce_checkout_phone_field', 'required' );
```
Comment (dechov) [inline includes/payment-methods/class-wc-stripe-payment-request.php:75]: If it's no longer reading from `$this->stripe_settings`, I'm not sure it belongs here – and since it's only used in one place, there might not be much reason to set it on the instance – thoughts?

Comment (reykjalin) [reply includes/payment-methods/class-wc-stripe-payment-request.php:75]: Yeah, you're right. I'll move this to where it's loaded into the JS. Thanks! ❤️

Comment (reykjalin) [reply includes/payment-methods/class-wc-stripe-payment-request.php]: Fixed in 16900225601defc539074658623a25cf6a3a7aed 🎉

**Comment by reykjalin** [comment]
>since I think it has similar enough intention, even though it's a less flexible & explicit way.

Yeah, I do think the intention is the same. If we want to provide more flexibility maybe we could add a filter to the value so merchants can add their own logic? I'm not sure if there's any demand for that sort of precise manipulation of the value, so I think we could add the filter another time 🙂

**Review by dechov — APPROVED** [review]
Code changes look good and work properly (following the testing instructions) 👍

Thanks for all the cleanup! Not sure why we would (or wouldn't) comment out those PHPCS rules – do the changes here conflict with them?

Perhaps worth noting that on the "Optional" setting, customers not only "don't need to add a phone number" but actually cannot, which would be more expected from the "Hidden" setting. In my view, this is an acceptable compromise considering that the Customizer setting doesn't map perfectly to the binary payment request parameter.

**Comment by reykjalin** [comment]
> Thanks for all the cleanup! Not sure why we would (or wouldn't) comment out those PHPCS rules – do the changes here conflict with them?

I had an issue with the linting setup and couldn't fix it with composer. However, just to make sure the changes are _actually_ needed I checked out the master branch to try it again... and now the setup works! I'll remove the linting config changes, I must've messed something up in my local setup 🤷‍♂️

**Comment by reykjalin** [comment]
Ok, just removed the commit that messed with `phpcs.xml.dist`, so we should be good to merge 👍 
Thanks for bringing that up @dechov !

**Comment by allendav** [comment]
I'll include this in tomorrow mornings release if it is merged by then

File: includes/payment-methods/class-wc-stripe-payment-request.php [hunk 2]
```diff
@@ -522,10 +526,12 @@ public function scripts() {
...
-				'url'            => wc_get_checkout_url(),
-				'currency_code'  => strtolower( get_woocommerce_currency() ),
-				'country_code'   => substr( get_option( 'woocommerce_default_country' ), 0, 2 ),
-				'needs_shipping' => WC()->cart->needs_shipping() ? 'yes' : 'no',
+				'url'               => wc_get_checkout_url(),
+				'currency_code'     => strtolower( get_woocommerce_currency() ),
+				'country_code'      => substr( get_option( 'woocommerce_default_country' ), 0, 2 ),
+				'needs_shipping'    => WC()->cart->needs_shipping() ? 'yes' : 'no',
+				// Defaults to 'required' to match how core initializes this option.
+				'needs_payer_phone' => 'required' === get_option( 'woocommerce_checkout_phone_field', 'required' ),
```
Comment (allendav) [inline includes/payment-methods/class-wc-stripe-payment-request.php:534]: TIL

**Comment by allendav** [comment]
@reykjalin - how would you like to capture this in the changelog? How about

- Fix: Apple Pay now requires a buyer phone number only if it is required in Customizer > WooCommerce > Checkout

File: includes/payment-methods/class-wc-stripe-payment-request.php (hunk 2 above)
Comment (reykjalin) [reply includes/payment-methods/class-wc-stripe-payment-request.php:534]: Yeah, it took a while to figure that out too! The [WP Customizer documentation](https://developer.wordpress.org/themes/customize-api/customizer-objects/#settings) is particularly wordy, and there's no explicit section on how to retrieve values (that information is at the bottom of the section I linked to called "Settings"). It also doesn't say that the values are only added to the DB **once changed**, which is why it's important to include the default value in the `get_option` call.

Once I had all that figured out, I then had to dig through the  WC Core code to find the correct [option name](https://github.com/woocommerce/woocommerce/blob/788969d2bbfba8f7e177b83504e70e98bc1babdf/includes/customizer/class-wc-shop-customizer.php#L685-L700).

It's simple once you know it though 😛

**Comment by reykjalin** [comment]
@allendav thanks for bringing that up! I forgot to modify the changelog in the PR.

I set it to:

```
= 4.5.4 - 2020-xx-xx =
* Fix - Apple Pay now requires a buyer's phone number only if it's required in Appearance > Customize > WooCommerce > Checkout.
```
