### PR TITLE
ECE: fix cart timeout issues

### LINKED ISSUE #3861: [GlobalStep] Infinite loading screen is displayed upon clicking "Google Pay" or "Link" button on "Product" page.
### Bug Description:
Infinite loading screen is displayed upon clicking "Google Pay" or "Link" button on "Product" page.

### Environment:
Woocommerce Version : WooCommerce 9.6.1
WooCommerce Stripe Payment Gateway: 9.2.0-test
Wordpress version: 6.7.1

PC:
Windows 10:
Chrome (Version 133.0.6943.60)
Firefox (Version 135.0)

### Steps to Reproduce:
1. Create any test site.
2. Install and activate all the required plugins.
3. Upload and activate the WooCommerce Stripe Payment Gateway v9.2.0-test plugin.
4. Connect the store to a Stripe account.
5. As a merchant, go to Stripe settings > Payment Methods tab > Express checkouts, at siteurl/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods.
6. Enable Google Pay / Link.
7. Go to the Payment Request's customization options, under Express checkouts > Apple Pay / Google Pay > Customize at siteurl/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods&area=payment_requests.
8. Under Show express checkouts on, enable options: Product page.
9. Go to any physical product page on frontend.
10. Click the Google Pay / Link button.
11. Observe that, Infinite loading screen is displayed upon clicking "Google Pay" or "Link" button.

### Instruction Link:
https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/v9.2.0-%E2%80%90-Release-testing-instructions

### Actual Result:
Infinite loading screen is displayed upon clicking "Google Pay" or "Link" button on "Product" page.

### Expected Result:
User should be able to pay using Google Pay / Link upon clicking "Google Pay" or "Link" button without any delay on "Product" page.

### Video / Screenshot:

Google Pay:

https://github.com/user-attachments/assets/c1d235c0-b909-4014-acc0-45a852a195ca

Link:

Image

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.6.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.9.0
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.3.16
PHP Post Max Size: 2 GB
PHP Time Limit: 850
PHP Max Input Vars: 6144
cURL Version: 8.12.0
OpenSSL/3.0.15

SUHOSIN Installed: –
MySQL Version: 10.11.10-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 25
page: 9
post: 4
product: 24
product_variation: 7
revision: 3
shop_coupon: 1
shop_order_placehold: 113
wp_font_face: 36
wp_font_family: 12
wp_global_styles: 1
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.6
Query Monitor: by John Blackbourn – 3.17.2
WooCommerce Stripe Gateway: by Stripe – 9.2.0-test
WooCommerce Subscriptions: by WooCommerce – 7.1.0
WooCommerce: by Automattic – 9.6.1

### Inactive Plugins (0) ###


### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
object-cache.php: Memcached

### Must Use Plugins (1) ###

load.php: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 3 KB

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/ -  Contains the woocommerce/cart block
Checkout: #8 - /checkout/ -  Contains the woocommerce/checkout block
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://secretly-everyday.jurassic.ninja
Subscriptions-core Library Version: 7.9.0
Subscription Statuses: wc-active: 21
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

Stripe: wc-active: 21

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon
add-to-cart-with-options-stepper-layout
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-02-11 06:52:58 +00:00
Options: ✔
Notes: 59
Onboarding: skipped

### Action Scheduler ###

Complete: 278
Oldest: 2025-02-10 06:54:47 +0000
Newest: 2025-02-10 10:36:04 +0000

Failed: 1
Oldest: 2025-02-10 07:08:03 +0000
Newest: 2025-02-10 07:08:03 +0000

Pending: 45
Oldest: 2025-02-11 06:54:47 +0000
Newest: 2025-04-10 10:36:53 +0000


### Status report information ###

Generated at: 2025-02-10 14:40:29 +00:00
```
</details>

### PR DESCRIPTION
**Pull request by annemirasol**
Fixes #3861 

## Changes proposed in this Pull Request:

This PR fixes the following issues that prevent express payment from loading properly inside the product page:

   1. The payment modal fails to load because the button `click` event fails to resolve within 1 second (a Stripe rule), due to slow responses from add-to-cart API calls (see #3861)
        - To fix this issue, we added our own timeout to add-to-cart calls, and call `event.resolve()` when we hit it.
            - `event.resolve()` does not need any data from the cart response. 
        - We also added a `isAddToCartSuccessful` flag to prevent the shopper from confirming payment if the product was not added to the cart successfully, and to allow the `shippingaddresschange` event to wait for the item to be added to the cart.
            - We need the item to be in the cart for shipping details to be displayed correctly.
            - The `shippingaddresschange` event has 20s to resolve, so we can afford to wait for the cart for a bit.

   2. The payment modal total amount includes other products that are in the cart, instead of just the current product. In some cases, the cart contains an incompatible product (e.g. pre-order product), and this prevents the current product from being added to the cart and causes ECE to fail.
       - We fixed these issues by clearing the cart before adding the current product. This is similar to [actions performed by the legacy add-to-cart method](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/beb2828170ae9fc1de540fd9b9517cac0e82b71b/includes/payment-methods/class-wc-stripe-express-checkout-ajax-handler.php#L92).
           - We are using the legacy/non-StoreAPI method to clear the cart, as it is faster, and we are under a time restriction. Compared to the StoreAPI method, it does not need to issue a `/cart` request, followed by multiple `/remove-item` requests.  

Screenshot: Inside the product page, the total amount should only include the current product.

| Before | After |
|--------|-------|
|Screenshot 2025-02-10 at 3 38 15 PM | Screenshot 2025-02-10 at 3 38 59 PM |

Screen recording: when network is slow, and add-to-cart operation takes >1s, we can still avoid the Stripe `event.resolve()` 1s timeout for `click`

https://github.com/user-attachments/assets/c5f7dc37-14e2-430f-9a28-ce01a6eea294

## Testing instructions

**Testing timeouts due to slow add-to-cart**
1. Define your shipping zone with both Free shipping and a Flat rate fee.
2. Go to a product page.
3. Open Chrome Developer Tools and under Network, throttle to 3G.
    - In `develop`, the payment modal does not load and the browser console displays a timeout message from Stripe.
    - In this branch, the payment modal loads. Verify that the total amount is correct (when the modal loads completely), including shipping.

**Testing correct total amount**
1. Add a few different products to your cart.
2. Go to a product page, preferably for a product that is not yet in your cart.
3. Click Google Pay.
    - In `develop`, the payment modal will show the total amount of all the items in your cart.
    - In this branch, the payment modal will show only the total amount for the current product.

**Testing conflicting products in cart**
1. Install the Pre-Orders (https://github.com/woocommerce/woocommerce-pre-orders) extensions.
2. Create a pre-order product.
3. Add the pre-order product to cart.
4. Go to a product page and click Google Pay.
    - In `develop`, the payment modal will not load and you will see a console error about incompatible products in the cart.
    - In this branch, you should be able to finish your purchase without any problem.

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: client/entrypoints/express-checkout/index.js [hunk 1]
```diff
@@ -82,6 +82,100 @@ jQuery( function ( $ ) {
...
+		// Here, we enforce a timeout for the addToCart operation. If the operation
+		// takes longer, we will call event.resolve() immediately,
+		// and wait for the addToCart operation to finish after.
+		const addToCartPromise = wcStripeECE.addToCart();
+		const timeout = new Promise( ( resolve ) =>
+			setTimeout( () => {
+				resolve( 'timeout' );
+			}, 700 )
+		);
+		const result = await Promise.race( [ addToCartPromise, timeout ] );
```
Comment (wjrosa) [inline client/entrypoints/express-checkout/index.js:150]: TIL 👍  (or remembered)

File: client/entrypoints/express-checkout/index.js [hunk 2]
```diff
@@ -317,6 +372,17 @@ jQuery( function ( $ ) {
 			);
 
 			eceButton.on( 'confirm', async ( event ) => {
+				if (
+					getExpressCheckoutData( 'is_product_page' ) &&
+					wcStripeECE.isAddToCartSuccessful === false
```
Comment (wjrosa) [inline client/entrypoints/express-checkout/index.js:382]: Is the strict check necessary? Like, is it possible for isAddToCartSuccessful to be of a different type?

**Review by wjrosa — APPROVED** [review]
Code is good and it works as expected!

### Testing timeouts due to slow add-to-cart

> In this branch, the payment modal loads. Verify that the total amount is correct (when the modal loads completely), including shipping.

Screenshot 2025-02-12 at 10 23 03

### Testing correct total amount

> In this branch, the payment modal will show only the total amount for the current product.

Screenshot 2025-02-12 at 10 24 41

Screenshot 2025-02-12 at 10 25 09

### Testing conflicting products in cart

> In this branch, you should be able to finish your purchase without any problem.

Screenshot 2025-02-12 at 10 42 19

File: client/entrypoints/express-checkout/index.js (hunk 2 above)
Comment (annemirasol) [reply client/entrypoints/express-checkout/index.js:382]: It's probably not necessary. Just thought to add it in case there is a code path that didn't set `wcStripeECE.isAddToCartSuccessful`, in which case it would be `undefined` and I want the behavior to proceed as it would normally.

**Comment by annemirasol** [comment]
In https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3862/commits/7fc990c35f0c03b95a771bc74627e1fbf3f39f0a, I added a 1s wait inside the `confirm` event in case add-to-cart is still ongoing, instead of immediately aborting the payment.

This is for the benefit of virtual products, where the user does not have to wait for the shipping options to load, and in case they quickly confirm payment even before the product is added to the cart.
