### PR TITLE
MultiBanco: Fix for HTML tags to print as expected on the Order Confirmation page, and "Thank you for your order" email.

### LINKED ISSUE #2651: HTML tags are not striped  in the MultiBanco confirmation email
**Describe the bug**
The Multibanco confirmation email is adding HTML tags to the transaction details.

Link to image: https://d.pr/i/SrzVK7

**To Reproduce**
Order using Stripe [Multibanco](https://www.multibanco.pt/)

Link to image: https://d.pr/i/QOVAil

**Expected behavior**

The HTML tags to be stripped out.

**Environment (please complete the following information):**
WC Version: 7.8.2
WP Version: 6.2.2
Stripe plugin 7.4.1

### PR DESCRIPTION
**Pull request by anastas10s-afk**
Fixes #2651 #2641 

## Changes proposed in this Pull Request:

This change is necessary for when the MultiBanco option is selected upon checkout, the HTML tags are escaped accordingly, on the Order Confirmation page, and subsequent "Thank you for your order" email.

Tested, with a test installation of mine, and nothing appears to be breaking. Kindly double-check, though. 🙂

### Before:

Screenshot 2023-10-21 at 18 41 14

Screenshot 2023-10-21 at 18 56 47

### After:

Screenshot 2023-10-21 at 19 05 15

Screenshot 2023-10-21 at 19 06 01

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [x] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-gateway-stripe-multibanco.php [hunk 1]
```diff
@@ -194,7 +194,7 @@ public function payment_fields() {
 			data-currency="' . esc_attr( strtolower( get_woocommerce_currency() ) ) . '">';
 
 		if ( $description ) {
-			echo wpautop( esc_html( apply_filters( 'wc_stripe_description', wp_kses_post( $description ), $this->id ) ) );
+			echo wpautop( esc_html( apply_filters( 'wc_stripe_description', esc_html( $description ), $this->id ) ) );
```
Comment (a-danae) [inline includes/payment-methods/class-wc-gateway-stripe-multibanco.php]: How about removing this first escaping to `$description` altogether? I know this was introduced previously, but it may be good to handle it now that we're around 🙂 

We have the `esc_html()` escaping the value returned by the `wc_stripe_description()` filter, so it'll be escaped before being printed. And double-escaping wouldn't be of much help.

```suggestion
			echo wpautop( esc_html( apply_filters( 'wc_stripe_description', $description, $this->id ) ) );
```

**Review by a-danae — COMMENTED** [review]
Hey Anastasio! Thanks for sending this PR 🙂 

I was able to replicate the problem in `develop` and things look good to me after applying these changes.

✅ The HTML tags are printed as expected on the Order Confirmation page.
✅ The HTML tags are printed as expected on the "Thank you for your order" email.

I left a comment about a double-escaping we could fix in this PR. But it's not a blocker because it was there before this PR.

And to approve it, could we please update this branch and include a changelog entry in both `changelog.txt` and `readme.txt` files?

Thanks again for taking the time to tackle this issue! 🙌 And apologies for not reviewing it earlier.

**Comment by bakill3** [comment]
> Hey Anastasio! Thanks for sending this PR 🙂
> 
> I was able to replicate the problem in `develop` and things look good to me after applying these changes.
> 
> ✅ The HTML tags are printed as expected on the Order Confirmation page. ✅ The HTML tags are printed as expected on the "Thank you for your order" email.
> 
> I left a comment about a double-escaping we could fix in this PR. But it's not a blocker because it was there before this PR.
> 
> And to approve it, could we please update this branch and include a changelog entry in both `changelog.txt` and `readme.txt` files?
> 
> Thanks again for taking the time to tackle this issue! 🙌 And apologies for not reviewing it earlier.

Thanks @a-danae, it worked. Been looking to solve this issue, I thought it was a conflict between plugins

File: includes/payment-methods/class-wc-gateway-stripe-multibanco.php (hunk 1 above)
Comment (anastas10s-afk) [reply includes/payment-methods/class-wc-gateway-stripe-multibanco.php]: TIL, thanks!

**Comment by anastas10s-afk** [comment]
Hey Danae! Should be all set now. 🙂
Many thanks for making this feel like a breeze! 🙌

**Review by a-danae — APPROVED** [review]
Ossum, thanks for the updates! Approving and merging.

No way, my pleasure. Thank you again for jumping in, @anastas10s-afk! 🙂
