### PR TITLE
Payment Request: Display "Subtotal" on payment dialogs

### LINKED ISSUE #1605: Missing product subtotal in for Express Payment method in both block checkout flow and shortcode checkout flow.
**Describe the bug**
I first discovered this while testing the Express Payment method integration for the Cart and Checkout block but discovered it also happens for the express payment method integration in the shortcode checkout flows as well. This _also_ happens with WooCommerce Payments. 

The issue is that the payment request modal (Reproduced with Google Pay and Browser Payment Request button) is not showing the products subtotal (but is showing the correct grand total).  However, when I test with the blocks integration with Stripe build into WooCommerce Blocks, the subtotal _is_ showing correctly.

**Testing environment:**

- Stripe or WooCommerce Payments `trunk` - production build. I was able to reproduce the same thing for both (but I was testing with only one of the payment methods active).
- WooCommerce blocks `trunk`.
- Test mode for payments.

My taxes setup is this:

CleanShot 2021-06-15 at 14 52 05@2x

**To Reproduce**
Testing involves adding a product to the cart and triggering Express payment method to checkout (I tested Google Pay via Chrome and Browser Payment Request via Edge). 

When the Express Payment modal loads, you'll see that there is a shipping subtotal and a taxes subtotal, but the product subtotal is not present. Grand Total _is_ correct though.

Here's some screenshots of the broken behaviour:

Browser PaymentRequest button on edge (Stripe and WooCommerce Payments):
CleanShot 2021-06-15 at 14 39 38@2x

Google Pay (Stripe and WooCommerce Payments):
CleanShot 2021-06-15 at 15 08 57@2x

However, if I test with the built-in blocks integration for Stripe, I get the expected behaviour. **To test built-in blocks integration:** Comment out [this line](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/ae73978f0012a250f89c377f34b9b89358f1cca1/woocommerce-gateway-stripe.php#L421).

Here's what it looks like when working as expected:

Built In Blocks integration Google Pay:
CleanShot 2021-06-15 at 15 10 51@2x

Built in Blocks Integration Browser PaymentRequest button:
CleanShot 2021-06-15 at 14 44 17@2x

### PR DESCRIPTION
**Pull request by asumaran**
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1605

Adds `Subtotal` to the "item" list on payment dialogs by PRB

Screen Shot 2021-08-25 at 3 11 25 PM

# Testing instructions

The "Subtotal" line is added to all places **except to the product page**. In the product page the product name is used by default.

- Make sure PRB is enabled
- Create two simple products "product 1" and "product 2". Only add a price. No need to add anything else.
- Visit "product 1's" page. Then click "Add to cart"
- Visit "product 2's" page. Then click "Add to cart"
- Go to Cart page
- Click on PRB
- Subtotal should be present in the order summary. The amount should equals the result of both product prices.

To test if the "itemized" list option is still preserved we need to add some code:

- Install and activate the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin.
- Go to Snippets > Add new.
- Copy the following snippet into the Code text area. Save this snippet as "show itemization".

```php
add_filter('wc_stripe_payment_request_hide_itemization', '__return_false');
```

- Visit "product 1's" page. Then click "Add to cart"
- Visit "product 2's" page. Then click "Add to cart"
- Go to **Cart** page
- Click on PRB
- "Subtotal" line should not be present. Instead every product should be listed.

The same applies for the "Checkout" page and Cart and Checkout blocks.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: tests/phpunit/test-wc-stripe-payment-request.php [hunk 1]
```diff
@@ -149,6 +149,10 @@ public function test_get_shipping_options_returns_chosen_option() {
 
 		$flat_rate              = $this->get_shipping_option( $this->flat_rate_id );
 		$expected_display_items = [
+			[
+				'label'  => 'Subtotal',
+				'amount' => 1000,
+			],
```
Comment (asumaran) [inline tests/phpunit/test-wc-stripe-payment-request.php:155]: This specific test is about checking Shipping Options but here in this PR we will also return the "Subtotal" as part of it.

To change the format of the resulting object of the `get_shipping_options`' method to comply with this method will require a significant refactor which is out of the scope of this PR. So I'm just adding the "Subtotal" item instead.

File: includes/payment-methods/class-wc-stripe-payment-request.php [hunk 2]
```diff
@@ -1665,26 +1665,33 @@ protected function build_display_items( $itemized_display_items = false ) {
...
+		foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
+			$subtotal      += $cart_item['line_subtotal'];
+			$amount         = $cart_item['line_subtotal'];
+			$quantity_label = 1 < $cart_item['quantity'] ? ' (x' . $cart_item['quantity'] . ')' : '';
+			$product_name   = $cart_item['data']->get_name();
+
+			$lines[] = [
+				'label'  => $product_name . $quantity_label,
+				'amount' => WC_Stripe_Helper::get_stripe_amount( $amount ),
+			];
```
Comment (dechov) [inline includes/payment-methods/class-wc-stripe-payment-request.php:1683]: Just a suggestion for a small refactor: what do you think of pushing directly to `$items` here (only if `$display_items`), avoiding the need for this additional array?

**Review by dechov — APPROVED** [review]
&nbsp; | `develop` | this branch
-- | -- | --
Default | develop-default | branch-default
Itemization | develop-itemization | branch-itemization

(Using Google Pay – also tested with Apple Pay.)

Looks good and works well! Left one minor comment but good to ship either way.

File: includes/payment-methods/class-wc-stripe-payment-request.php [hunk 3]
```diff
@@ -1665,26 +1665,33 @@ protected function build_display_items( $itemized_display_items = false ) {
...
+		$lines         = [];
+		$subtotal      = 0;
+		$discounts     = 0;
+		$display_items = ! apply_filters( 'wc_stripe_payment_request_hide_itemization', true ) || $itemized_display_items;
 
-		// Default show only subtotal instead of itemization.
-		if ( ! apply_filters( 'wc_stripe_payment_request_hide_itemization', true ) || $itemized_display_items ) {
-			foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
-				$amount         = $cart_item['line_subtotal'];
-				$subtotal      += $cart_item['line_subtotal'];
```
Comment (dechov) [inline includes/payment-methods/class-wc-stripe-payment-request.php:1676]: Interesting that the subtotal was already being calculated but never used.

Comment (asumaran) [reply includes/payment-methods/class-wc-stripe-payment-request.php:1676]: I tracked down this line and it was created like 4+ years ago. It was never used.

Comment (dechov) [reply includes/payment-methods/class-wc-stripe-payment-request.php:1676]: Same 😄

File: includes/payment-methods/class-wc-stripe-payment-request.php (hunk 2 above)
Comment (asumaran) [reply includes/payment-methods/class-wc-stripe-payment-request.php:1683]: @dechov Sorry! I went ahead and merged the PR without looking to this comment. since the suggested change is small I hope there's no problem that I've merged the PR without addressing this comment.

Comment (dechov) [reply includes/payment-methods/class-wc-stripe-payment-request.php:1683]: Definitely no problem – if you especially agree with the change then it would be appropriate to open another PR and I can give a quick review, but otherwise it's all done 👍
