### PR TITLE
Fix fingerprint set error on legacy checkout

### LINKED ISSUE #3718: Critical error on /checkout/ and /payment-methods/ pages for some customers with saved cards when legacy checkout is enabled
**Describe the bug**
Some of our long-time customers who have multiple saved cards are currently not able to check out due to a regression bug in this plugin. The bug seems related to the changes in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3635/files. Here's the crash info:

`WC_Stripe_Payment_Token_CC::set_fingerprint(): Argument #1 ($fingerprint) must be of type string, null given, called in /www/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-tokens/class-wc-stripe-payment-tokens.php on line 188`

As far as I can tell, this is because the line should actually be `$token->set_fingerprint( $source->card->fingerprint );`, as Stripe's API doesn't return `fingerprint` at the root level of a [source object](https://docs.stripe.com/api/sources/object). The same bug exists on a few other lines in this class as well.

**To Reproduce**
1. Configure a test WP install with the WC, WC Stripe, and WC Subscriptions plugins
2. Enable Stripe legacy checkout
3. Add a credit card via the "Payment Methods" page
4. Purchase a subscription, entering a _different_ credit card during checkout
5. Using a database admin tool, delete the first credit card you added from `wp_woocommerce_payment_tokens` to simulate the case where a card is defined in Stripe but not synced to the WC database
6. Attempt to add another card via the "Payment Methods" page to trigger the bug

**Expected behavior**
The `/checkout/` and `/payment-methods/` pages do not crash when legacy checkout is enabled and customers have saved cards.

**Environment (please complete the following information):**
 - WordPress Version: 6.7.1
 - WooCommerce Version: 9.5.2
 - Stripe Plugin Version: 9.1.1
 - Browser [e.g. chrome, safari] and Version: N/A
 - Any other plugins installed: WooCommerce Subscriptions 7.1.0

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #3718

## Changes proposed in this Pull Request:

This PR fixes a fatal error being thrown when saving payment method tokens with the legacy checkout enabled. The error happens when setting the fingerprint property (used to identify duplicate tokens). The expected object structure was different from the actual format received (`fingerprint` exists inside the payment method details key, [source](https://docs.stripe.com/api/sources/object)).

## Testing instructions

You can follow the test instructions from [the related issue](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3718):
1. Configure a test WP install with the WC, WC Stripe, and WC Subscriptions plugins
2. Enable Stripe legacy checkout
3. Add a credit card via the "Payment Methods" page
4. Purchase a subscription, entering a _different_ credit card during checkout
5. Using a database admin tool, delete the first credit card you added from `wp_woocommerce_payment_tokens` to simulate the case where a card is defined in Stripe but not synced to the WC database
6. Attempt to add another card via the "Payment Methods" page
7. Confirm no fatal errors are thrown

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-tokens/class-wc-stripe-payment-tokens.php [hunk 1]
```diff
@@ -21,12 +21,12 @@ class WC_Stripe_Payment_Tokens {
...
-		WC_Stripe_UPE_Payment_Method_Sepa::STRIPE_ID         => WC_Stripe_UPE_Payment_Gateway::ID . '_' . WC_Stripe_UPE_Payment_Method_Sepa::STRIPE_ID,
-		WC_Stripe_UPE_Payment_Method_Sofort::STRIPE_ID       => WC_Stripe_UPE_Payment_Gateway::ID . '_' . WC_Stripe_UPE_Payment_Method_Sofort::STRIPE_ID,
+		WC_Stripe_UPE_Payment_Method_CC::STRIPE_ID         => WC_Stripe_UPE_Payment_Gateway::ID,
+		WC_Stripe_UPE_Payment_Method_Link::STRIPE_ID       => WC_Stripe_UPE_Payment_Gateway::ID,
+		WC_Stripe_UPE_Payment_Method_Bancontact::STRIPE_ID => WC_Stripe_UPE_Payment_Gateway::ID . '_' . WC_Stripe_UPE_Payment_Method_Bancontact::STRIPE_ID,
+		WC_Stripe_UPE_Payment_Method_Ideal::STRIPE_ID      => WC_Stripe_UPE_Payment_Gateway::ID . '_' . WC_Stripe_UPE_Payment_Method_Ideal::STRIPE_ID,
+		WC_Stripe_UPE_Payment_Method_Sepa::STRIPE_ID       => WC_Stripe_UPE_Payment_Gateway::ID . '_' . WC_Stripe_UPE_Payment_Method_Sepa::STRIPE_ID,
+		WC_Stripe_UPE_Payment_Method_Sofort::STRIPE_ID     => WC_Stripe_UPE_Payment_Gateway::ID . '_' . WC_Stripe_UPE_Payment_Method_Sofort::STRIPE_ID,
```
Comment (diegocurbelo) [inline includes/payment-tokens/class-wc-stripe-payment-tokens.php]: This seems like a linting error; it was OK before.

**Review by diegocurbelo — APPROVED** [review]
The code changes look good, and testing by deleting the first credit card from the db works as expected.

@wjrosa I'm approving this, but let's revert the spacing fixes/changes before merging.

I'll open a PR to fix the linting checks (and the 19 files that need changes)

File: includes/payment-tokens/class-wc-stripe-payment-tokens.php (hunk 1 above)
Comment (wjrosa) [reply includes/payment-tokens/class-wc-stripe-payment-tokens.php]: It was actually fixed automatically by my IDE, but I reverted this in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3743/commits/f384cf3e6dffb80bb4526b2488b26e324e29a95d
