### PR TITLE
Don't mark Stripe Link as enabled in the admin

### LINKED ISSUE #3356: Empty incompatibility plugin registered with Checkout block
**Describe the bug**
There is an empty space within the Compatibility notice displayed by the checkout block. This is registered by this plugin. 

**To Reproduce**
1. Go to the checkout block in the editor
2. Click on the checkout block
3. Notice the empty bultet point within the compatibility notice in the right sidebar (see screenshot)

**Expected behavior**
I would expect to see no empty bullet point in the compatibility notice

**Screenshots**
Screenshot 2024-08-12 at 14 53 13

**Environment (please complete the following information):**
WC 9.2

### PR DESCRIPTION
**Pull request by senadir**
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3356

## Changes proposed in this Pull Request:

This PR resolves an issue in which Stripe Link would be marked as incompatible with Checkout block. To decide if a payment method is compatible or not, Checkout block would compare all registered gateways in `woocommerce_payment_gateways` and make sure they have a corresponding JS paymentGateway or expressPaymentGateway. Stripe Link alongside Google Pay and Apple Pay all use the same `stripe` express payment registry, however, in PHP, Stripe Link register its own gateway class `WC_Stripe_UPE_Payment_Method_Link`. This ends up marking it as incompatible.

There are several possible solutions to this, the least intrusive so far, ~~is to mark `WC_Stripe_UPE_Payment_Method_Link` as disabled on all admin requests. This seems to work fine in admin and frontend, and doesn't break anything from what I saw.~~

Sadly changing `$this->enabled` broke certain unit tests that I couldn't figure out how to fix. I moved the logic to the main `woocommerce_payment_gateways` filter call.
 

This code might break any admin logic that depends on Stripe Link being marked enabled. I checked and couldn't find anything.

Another option was to limit disable to only Gutenberg pages, but it was too early to reach for `get_current_screen`.

Before: (those are before and after from a PR https://github.com/woocommerce/woocommerce/pull/52070 but for this PR, both are considred before).
image
image

After:
image

## Testing instructions

1. Enable Link.
2. Make sure your Checkout page is Checkout block.
3. Go to editor, select the main Checkout block, make sure the sidebar doesn't have any warnings about an incompatible plugin.
4. Do regression testing for Link, making sure it loads on both checkouts and you can place an order with it.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page] (https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply) (Honestly not sure how to write tests for this, as I'm not sure you have E2E flows that cover the editor).
-   [x] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply) **Does not apply.**
-   [ ] Included this PR in the Release Thread scope (or does not apply) Not sure what is this.

### CODE REVIEW

**Comment by senadir** [comment]
Updated logic so it removes Link from the main gateway filter instead of adding logic in the gateway class `WC_Stripe_UPE_Payment_Method_Link`, for some reason that kept failing no matter what value I put in `enabled`, even though it was not being reset manually, the test `test_upe_method_enabled` didn't propogate the value to Link when flipping. `WC_Stripe_Helper::update_main_stripe_settings( $stripe_settings );` setting value was not making maybe. This is even with deleting the `is_admin` check, just simply doing `$this->enabled = self::is_link_enabled() ? 'yes' : 'no'`

The check here still only does `is_admin` because it's too early to check for get_current_screen. I think I can have another filter down the road that reaches directly to wc()->payment_gateways to remove Link. Let's see if this causes problems. All tests passed to me.

**Comment by annemirasol** [comment]
@senadir maybe fixes #3356?

File: woocommerce-gateway-stripe.php [hunk 1]
```diff
@@ -478,6 +478,16 @@ public function add_gateways( $methods ) {
 					}
 				}
 
+				// Don't mark Link as enabled if we're in the admin so it doesn't show up in the checkout editor page.
+				if ( is_admin() ) {
+					$methods = array_filter(
+						$methods,
+						function( $method ) {
+							return ! is_a( $method, 'WC_Stripe_UPE_Payment_Method_Link' );
```
Comment (wjrosa) [inline woocommerce-gateway-stripe.php]: Nit-pick: I would use `WC_Stripe_UPE_Payment_Method_Link::class` instead, just for a more straightforward lookup and to avoid issues with class renaming.

Comment (senadir) [reply woocommerce-gateway-stripe.php]: Good catch!

**Review by diegocurbelo — APPROVED** [review]
Thanks for fixing this @senadir!

I could not find any side effects, all critical flows test well... (the legacy checkout E2E test is failing in guthub because of a timeout, it works fine locally.. and I also tested it manually)

**Comment by senadir** [comment]
I prematurely merged this before testing the refactor 😞 Pushing another PR to fix it. https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3547
