### PR TITLE
Protect against potential for multiple renewal charges on one Order

### LINKED ISSUE #4003: Protect against potential for multiple renewal charges on the 1 order
**Describe the bug**
If there are multiple instances of any of the main Stripe gateway classes instantiated, it can lead to multiple subscription charges. 

**To Reproduce**

> [!note]
> I haven't been able to replicate this naturally. However, the method I used to reproduce it suggests that third-party plugins or future changes could easily trigger this issue unknowingly. **Update** there's evidence in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4003#issuecomment-2693578033 which suggests this could be replicatable without custom code if you refresh the oAuth token in the same request.

1. Enable Stripe legacy checkout. *
1. Add the following code snippet to your site.

```php
add_action( 'woocommerce_scheduled_subscription_payment_stripe', function() {
	// Creating a new instance of the main Stripe Gateway will call `maybe_init_subscriptions()` and attach another `woocommerce_scheduled_subscription_payment_{$id}` hook. 
	new WC_Gateway_Stripe();
}, 1 );
```

3. Skip to step 4 if you already have a subscription you can test on.
   1. Install **WooCommerce Subscriptions** if you don't have it enabled.
   2. If you don't have one, create a subscription product.
   3. Purchase the subscription product using a standard card.
4. Edit the subscription in your admin dashboard.
5. From the actions dropdown on the top right of the screen, select **Process renewal**.
6. Run the action.
7. View your Stripe dashboard and you should see 2 charges for the same order.

Image

**Expected behavior**
Even if there is a flow that creates a new instance of the main Stripe Gateway class, there shouldn't be duplicate renewal charges. 

**Notes**

I reviewed the current `new WC_Gateway_Stripe()` calls and I can see there is potential for this to occur without custom code. For example `gateway_settings_update()` creates an instance but only if the Stripe settings were empty. That's unlikely.  `get_default_stripe_config()` also creates an instance but that occurs when the Stripe oAuth keys are saved and that's also unlikely to happen at the exact moment a subscription renews. 

\* While I mentioned that you have legacy checkout, I believe this would also occur with the new UPE enabled, you'd just be looking at `WC_Stripe_UPE_Payment_Gateway` instead of `WC_Gateway_Stripe`. 

### Potential fix

Update `maybe_init_subscriptions()` to make sure it only ever hooks 1 instance of `'woocommerce_scheduled_subscription_payment_' . $this->id` for each gateway ID. 
ie Stripe hook this for all subscription supporting gateways like Cash App. That's expected, however I don't think you should ever hook 2 `cashapp` or 2 `stripe` instances otherwise you'll see duplicate renewal charges. 

Update `scheduled_subscription_payment()` to check if the order has already been paid. I don't suspect there would ever be a flow that would expect an already paid order to be paid again.

### PR DESCRIPTION
**Pull request by diegocurbelo**
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4003

## Changes proposed in this Pull Request:

This PR adds a check to `maybe_init_subscriptions()` in the Subscriptions Utilities Trait to prevent duplicate renewal charges even if there is a flow that creates a new instance of the main Stripe Gateway class. 

Screenshot_2025-03-07_at_00_47_33

**Behavior before this fix:**
If there are multiple instances of any of the Stripe Gateway classes instantiated, for each instance, the action that calls `scheduled_subscription_payment()`/`process_subscription_payment()` is registered once for each class, which results in multiple subscription charges.

```php
add_action( 'woocommerce_scheduled_subscription_payment_' . $this->id, [ $this, 'scheduled_subscription_payment' ], 10, 2 );
```

More info: pgizk6-go-p2

## Testing instructions

**Add the following code snippet** (to trigger multiple Gateway class instantiation):
```php
add_action( 'init', function() {
	// Creating a new instance of the main Stripe Gateway will call `maybe_init_subscriptions()` and attach another `woocommerce_scheduled_subscription_payment_{$id}` hook.
	new WC_Gateway_Stripe();
	new WC_Stripe_UPE_Payment_Gateway();
}, 1 );
```

> [!note]
> _Skip this if you already have a subscription you can test with_
> 1. Install and enable the WooCommerce Subscriptions plugin.
> 2. Create a subscription product.

**LEGACY CHECKOUT**

1. Enable the legacy checkout experience.
2. Purchase the subscription product using a credit card.
3. Edit the Subscription in your admin dashboard (`WooCommerce > Subscriptions`)
4. From the `Order actions` dropdown (on the top right), select **Process renewal** and run the action:
    Screenshot_2025-03-06_at_20_15_14
5. Check in your Stripe dashboard that only one charge has been made:
    Screenshot_2025-03-06_at_20_06_06

**DEFAULT CHECKOUT**

_**Credit Card**_

1. Disable the legacy checkout experience.
2. Purchase the subscription product using a credit card.
3. Edit the Subscription in your admin dashboard (`WooCommerce > Subscriptions`).
4. From the `Order actions` dropdown (on the top right), select **Process renewal** and run the action
5. Check in your Stripe dashboard that only one charge has been made:

_**SEPA Debit**_
1. Purchase the subscription product using SEPA Debit.
2. Edit the newly created Subscription in your admin dashboard (`WooCommerce > Subscriptions`).
3. From the `Order actions` dropdown (on the top right), select **Process renewal** and run the action.
4. Check in your Stripe dashboard that only one charge has been made:
    Screenshot_2025-03-07_at_01_25_11

_**Cash App Pay**_
1. Purchase the subscription product using Cash App Pay.
2. Edit the newly created Subscription in your admin dashboard (`WooCommerce > Subscriptions`).
3. From the `Order actions` dropdown (on the top right), select **Process renewal** and run the action.
4. Check in your Stripe dashboard that only one charge has been made:
    Screenshot_2025-03-07_at_01_18_51

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 1]
```diff
@@ -29,6 +29,14 @@ public function maybe_init_subscriptions() {
 			return;
 		}
 
+		/**
+		 * We need to attach the callbacks below once per Gateway (CC, SEPA, etc), but only once.
+		 * Therefore we use a statuc flag at class level to indicate that they have been attached.
+		 */
+		if ( self::$has_attached_integration_hooks ) {
+			return;
+		}
```
Comment (james-allan) [inline includes/compat/trait-wc-stripe-subscriptions.php:38]: Hey @diegocurbelo,

I know this is still a draft PR, but I wanted to jump in before I lose the opportunity to review it.

I’m not sure this approach will work because, if I recall correctly, Stripe calls `maybe_init_subscriptions()` for multiple payment methods, like Cash App and the main gateway ('stripe'). It expects `'woocommerce_scheduled_subscription_payment_' . $this->id` to be hooked for each of those individually eg `'woocommerce_scheduled_subscription_payment_cashapp'` and `'woocommerce_scheduled_subscription_payment_stripe'`.

From what I understand, this approach would only allow it to be hooked once in total, whereas it needs to be hooked once per payment method type. For example, if Cash App were enabled, it wouldn’t process Cash App renewals because only the `stripe` hook would be attached.

Comment (diegocurbelo) [reply includes/compat/trait-wc-stripe-subscriptions.php:38]: Thanks for the review @james-allan!

Since each payment method is implemented by its own class (inheriting from `WC_Stripe_Payment_Gateway` or `WC_Stripe_UPE_Payment_Method`) each one would have its own copy of the static variable `$has_attached_integration_hooks` due to how PHP traits and static properties work (it "adds" the property to each class, it's not the same instance for all classes that use the trait).

I can add a better description of the static variable purpose (and behavior), or maybe it's better to change the variable to a map (using the ID as key). It will have just one item, but it will make the code easier to understand. What do you think?

Comment (james-allan) [reply includes/compat/trait-wc-stripe-subscriptions.php:38]: Oh, that makes sense. I initially thought the static variable would be shared across all instances, but you're right. Since the top level class  declares the trait (eg `WC_Stripe_UPE_Payment_Method_Sepa`), the static variable is scoped at the top class level, not across multiple classes using the same trait. 

Ignore me 😄

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 2]
```diff
@@ -29,6 +29,14 @@ public function maybe_init_subscriptions() {
 			return;
 		}
 
+		/**
+		 * We need to attach the callbacks below once per Gateway (CC, SEPA, etc), but only once.
+		 * Therefore we use a statuc flag at class level to indicate that they have been attached.
```
Comment (hsingyuc) [inline includes/compat/trait-wc-stripe-subscriptions.php]: *static ?

**Review by hsingyuc — COMMENTED** [review]
@diegocurbelo, have you considered the option of prevent [creating multiple WC_Gateway_Stripe instance](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/34f1688e443bbd726a6f71b9a8460b4121be060a/woocommerce-gateway-stripe.php#L577) and maybe reuse [get_main_stripe_gateway](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/34f1688e443bbd726a6f71b9a8460b4121be060a/woocommerce-gateway-stripe.php/#L766-L780)? Is this a possibility?

**Review by hsingyuc — COMMENTED** [review]
Do you happen to know what I need to do to activate CC on Stripe?
Screenshot 2025-03-11 at 5 15 50 PM
Screenshot 2025-03-11 at 5 14 10 PM
Screenshot 2025-03-11 at 6 07 58 PM

**Comment by diegocurbelo** [comment]
> Do you happen to know what I need to do to activate CC on Stripe? 

For test mode, we don't need to "activate" the payment methods... maybe the gateway got deactivated after an update?

File: includes/compat/trait-wc-stripe-subscriptions.php (hunk 2 above)
Comment (diegocurbelo) [reply includes/compat/trait-wc-stripe-subscriptions.php]: Yes, the `$has_attached_integration_hooks` is declared as static in the Trait... which means that every class that uses the Trait has its own copy, but that copy is shared among instances of the same class.

**Comment by diegocurbelo** [comment]
> @diegocurbelo, have you considered the option of prevent [creating multiple WC_Gateway_Stripe instance](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/34f1688e443bbd726a6f71b9a8460b4121be060a/woocommerce-gateway-stripe.php#L577) and maybe reuse [get_main_stripe_gateway](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/34f1688e443bbd726a6f71b9a8460b4121be060a/woocommerce-gateway-stripe.php/#L766-L780)? Is this a possibility?

Yes, another option would have been to change the Gateway class to enforce the use of singleton at the Gateway level... but that's a much bigger change, and we'll need to test it thoroughly to make sure it doesn't have any unintended effects.

As part of removing Legacy, we can look into refactoring the code, to implement the gateways as singleton (or maybe even just one Gateway with internal LPM handling 🤷🏼)

File: includes/compat/trait-wc-stripe-subscriptions.php (hunk 2 above)
Comment (hsingyuc) [reply includes/compat/trait-wc-stripe-subscriptions.php]: Sorry, I forgot to edit the comment. Should `Therefore we use a statuc flag...` be `static flag`?

**Review by hsingyuc — APPROVED** [review]
I suppose this is the best way to do it as a quick fix. 👍

**Comment by kaushikasomaiya** [comment]
@diegocurbelo @james-allan Wondering if there is a chance this might have introduced a different issue - working with the same merchant now their subscriptions are failing with 

> scheduled action 31774 (subscription payment) failed to finish processing due to the following exception: Unable to change subscription status to "on-hold". in plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscription.php:450  

Looking at the flow - one possibility is the subscription_suspension might not be getting declared for some reason? but unable to think of a scenario that would make this possible 

Just a note that like the last time, investigating one of the affected subs, the wc_stripe_refresh_connection action was included in the same batch.

**Comment by james-allan** [comment]
> Wondering if there is a chance this might have introduced a different issue - working with the same merchant now their subscriptions are failing with

Hmm yeah that might be related to this PR. At first it didn't seem related but I think I can see how the changes this PR could lead to that error. _Noting that I haven't actually tested this but looking at the order of things in the `maybe_init_subscriptions()` function I can see how that might occur._

The `self::$has_attached_integration_hooks` check is before the `$this->supports` declaration. 
So, if the `self::$has_attached_integration_hooks` check prevents the rest of `maybe_init_subscriptions()` to run, I can see how payment methods wouldn't declare their subscription related support flags.

**Comment by kaushikasomaiya** [comment]
If it helps: They switched to New checkout exp before this occurred.
