### PR TITLE
Fix order not showing stripe fees for asynchronous payments closes #671

### LINKED ISSUE #671: Bug: Stripe fees/payout don't display on Orders page after asynchronous payment charge successful
#### What I expected

Stripe fees & payout information to display on the Orders page after successful charge using asynchronous payment method (SEPA, SOFORT)

#### What happened instead

Stripe fees & payout do not display. Based on my digging, this is because the [`process_webhook_charge_succeeded` function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/d67475365dee9ef73ebcb06ddd1a96f0b729fc3b/includes/class-wc-stripe-webhook-handler.php#L332) does not update/add the Stripe currency. Since a currency has never been added due to the empty `balance_transaction` object in the initial response from Stripe (because of the asynchronous payment method), the Stripe fees and payout do not display on the Order page because the [`display_order_fee` function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3d0875fd029c262612399063bee7cb79cb974c0f/includes/class-wc-gateway-stripe.php#L863) and [`display_order_payout` function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3d0875fd029c262612399063bee7cb79cb974c0f/includes/class-wc-gateway-stripe.php#L900) check for `$currency` to not be empty:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3d0875fd029c262612399063bee7cb79cb974c0f/includes/class-wc-gateway-stripe.php#L873

#### Steps to reproduce the issue

Purchase a product using SOFORT or SEPA (in Test Mode, the `owner[name]` must be set to 'charge_succeeded').
- Stripe then sends a `charge succeeded` response to the wc_stripe webhook
- The plugin processes the response and changes the Order status to 'processing' and marks the Stripe charge complete.
- The Stripe fees & payout still do not display.

Adding 
`$currency = ! empty( $balance_transaction->currency ) ? strtoupper( $balance_transaction->currency ) : null;`
`WC_Stripe_Helper::update_stripe_currency( $order, $currency );`

to the [`update_fees` function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/06a170d12af9c0d8ac0d300f00f2188669606aa5/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L850) eliminates the issue, though I haven't been able to test for other potential side effects.

Happy to submit a Pull Request if you'd like.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by roykho**
Fixes #671

#### Changes proposed in this Pull Request:
* Fix - Asynchronous payment methods such as SEPA, did not show order Stripe fees/net after payment succeed.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -879,6 +879,26 @@ public function update_fees( $order, $balance_transaction_id ) {
...
+	 * @param int $balance_transaction_id
+	 */
+	public function update_currency( $order, $balance_transaction_id ) {
+		$order_id = WC_Stripe_Helper::is_pre_30() ? $order->id : $order->get_id();
+
+		$balance_transaction = WC_Stripe_API::retrieve( 'balance/history/' . $balance_transaction_id );
+
+		if ( empty( $balance_transaction->error ) ) {
+			$currency = ! empty( $balance_transaction->currency ) ? strtoupper( $balance_transaction->currency ) : null;
+			WC_Stripe_Helper::update_stripe_currency( $order, $currency );
```
Comment (bor0) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: What happens if we set the currency to null? Should we update the conditional to branch here to `empty( error ) && ! empty( currency )`?

Comment (bor0) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Makes sense.
