### PR TITLE
Fix transactions failing with trailing slash

### LINKED ISSUE #1066: Live transactions fail with "trailing slash" error
**Describe the problem**
Reporting as per @allendav and [this slack thread](https://a8c.slack.com/archives/C9976E5MJ/p1571256124020500)

Ticket: zd-2426982

Recently we had a customer who could not process Live transactions through Stripe. Test mode transactions worked, however when they tried live transactions they got the following error:

```
 [error] => stdClass Object
        (
            [message] => Unrecognized request URL (POST: /v1/payment_intents/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.
            [type] => invalid_request_error
        )
```

When contacting Stripe their support team said that this was essentially a 404 error due to a trailing `/` on being added to the end of the request. They said that this was a problem with the plugin, and that we would need to fix the request that's being sent to Stripe.

That didn't make sense since the request would work fine when using my Stripe credentials. Same site, same setup, only difference being my Stripe account, not theirs. Also since the customer can't impact the format of the requests the plugin sends to Stripe, it didn't make sense.

Ultimately the problem was resolved by simply inputting a new set of Public/Secret keys and new webhook secret.

It seems to me that either the error message that was given was incorrect. Or that the issue was the second possibility mentioned in the error:
`If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code`
I'm not sure if credentials would be an "Identifier" in this case or not? If they are, that would explain the problem being resolved by generating new credentials.

I don't think/know if there is anything on our side to "fix" but it would be good to know for the proper context of why that error was returned to save a lot of time for us/stripe/our customers trying to chase this down in the future.

**I'm not sure how to replicate this.**

### PR DESCRIPTION
**Pull request by vbelolapotkov**
Fixes #1066 .

#### Changes proposed in this Pull Request:
The issue is caused by error object returned from Stripe API when test mode payment intent associated with the order is fetched in the live mode. The error object was mistakenly treated as an intent object (with empty id). Hence further POST request is sent to the wrong URL `payment_intents/` and fails.

To fix the issue extra check of the response object is added. Errors are logged and `false` is returned instead of payment intent in such cases.

#### Testing instructions

There is no known reliable way to reproduce the issue.
Added some unit tests so running PHP unit tests is the only way of testing at the moment.
See #1163 for instructions on setting up and running unit tests.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -1248,32 +1248,77 @@ public function save_intent_to_order( $order, $intent ) {
...
+	}
+
+	/**
+	 * Retrieves the payment intent, associated with an order for WooCommerce < 3.0
+	 *
+	 * @param WC_Order $order The order to retrieve an intent for.
+	 * @return obect|bool     Either the intent object or `false`.
+	 */
+
+	private function pre_3_0_get_intent_from_order( $order ) {
```
Comment (marcinbot) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php:1279]: It wasn't great, but I preferred the old way of doing this, where the logic for getting intents was all in one place, and only the ID retrievals changed depending on the WC version. If multiple conditionals were a problem, then maybe we should have moved them to their own functions that would check the version, such as `get_payment_intent_id` and `get_setup_intent_id`.

But it might not need to be addressed since we'll be dropping support for WC 3.0 in the next release. Two functions might actually make it easier to remove the code.

Comment (vbelolapotkov) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php:1279]: > But it might not need to be addressed since we'll be dropping support for WC 3.0 in the next release. Two functions might actually make it easier to remove the code.

That's exactly why I decided to extract pre 3.0 sequence into its own method 🙂
Do you still want me to put it back?

Comment (marcinbot) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php:1279]: > Do you still want me to put it back?

No, I think it's fine as it is now :)

**Comment by vbelolapotkov** [comment]
@marcinbot thanks for the review! I've rebased the branch onto master to separate from #1163 .

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 2]
```diff
@@ -1248,32 +1248,77 @@ public function save_intent_to_order( $order, $intent ) {
...
+		return false;
+	}
+
+	/**
+	 * Retrieves the payment intent, associated with an order for WooCommerce < 3.0
+	 *
+	 * @param WC_Order $order The order to retrieve an intent for.
+	 * @return obect|bool     Either the intent object or `false`.
+	 */
+
```
[the remark this answers is not in the document]
Comment (vbelolapotkov) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Good catch! I need to setup linter for that project 🤦‍♂ 
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1164/commits/64b37132a037dfdb05123b79d46ede09da5f11bc.

File: .gitignore [hunk 3]
```diff
@@ -20,3 +20,9 @@ deploy-to-wp-org.sh
 
 # Test configs
 tests/e2e/config/local-*
+
+# VS Code
+.vscode
```
[the remark this answers is not in the document]
Comment (vbelolapotkov) [reply .gitignore]: It doesn't really matter IMO, I just added it manually in two different branches and have forgotten 🙂Anyway it's part of #1163 now.
