### PR TITLE
PI: Do not update an intent's customer after intent creation.

### LINKED ISSUE #1068: Guest customer unable to process payment after zip code fails validation
A **guest** customer has reported being unable to make a payment, with the error "Sorry, we are unable to process your payment at this time. Please retry later.". Looking at the order notes, it looks like it initially failed zip code verification, then the customer returned the next day to retry several times (with different cards), but only the "unable to process" error is shown in the notes.

The logs show 6 repetitions of a block beginning with "sources/src_[...]", going through "Info: Begin processing payment for order ..." and ending with:

```
payment_intents/pi_[...] request: Array
(
    [source] => src_[...]
    [customer] => cus_[...]
)
```

The customer id changes each repetition (maybe because they are a guest?). Finally the request seems to go through and there's the following error:

```
[code] => payment_intent_unexpected_state
            [doc_url] => https://stripe.com/docs/error-codes/payment-intent-unexpected-state
            [message] => You cannot modify `customer` on a PaymentIntent once it already has been set. To fulfill a payment with a different Customer, cancel this PaymentIntent and create a new one
```

**Steps to reproduce (in test mode)**

1. Checkout as guest, using the zip and address line 1 validation error card number: 4000000000000010, which correctly displays the zip code invalid error
2. Retry payment using a valid card number (i.e. 4242424242424242)
3. Error shows: "Sorry, we are unable to process your payment at this time. Please retry later."

Running the latest WC and Stripe versions.

### PR DESCRIPTION
**Pull request by RadoslavGeorgiev**
Fixes #1068 .

#### Changes proposed in this Pull Request:

- Reuse the customer, already associated with a PaymentIntent

During the creation of PaymentIntents, they get associated with a Stripe customer, if one is available. Since `4.3.0` this is always the case, because we are generating Stripe customers for every transaction.

If there is a validation error during the confirmation of a payment intent, the current code base creates a new customer (when using guest checkout) and tries to update the payment intent, however the intent is already in a state, which does not allow that update.

**This PR** introduces the `update_customer` method of `WC_Stripe_User`, and the necessary logic to call it.

#### Testing instructions

Test without this branch first:

1. Checkout as guest, using the zip and address line 1 validation error card number: `4000000000000010`, which correctly displays the zip code invalid error
2. Retry payment using a valid card number (i.e. `4242424242424242`)
3. Error shows: "Sorry, we are unable to process your payment at this time. Please retry later."

After switching to the branch, try the same steps. There should be no errors.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -641,6 +645,8 @@ public function prepare_source( $user_id, $force_save_source = false ) {
 		if ( ! $customer_id ) {
 			$customer->set_id( $customer->create_customer() );
 			$customer_id = $customer->get_id();
+		} else {
+			$customer->update_customer();
```
Comment (v18) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Why do we need to call `update_customer()` here? From what I can see, we aren't sending the new `source` to stripe, and what we're getting back from the API call in `update_customer` is a customer object (https://stripe.com/docs/api/customers/update) with what looks like no differences to what we had before. The customer ID is already going to be correct since we set it earlier using `$customer->set_id( $existing_customer_id );`.

File: includes/class-wc-gateway-stripe.php [hunk 2]
```diff
@@ -578,7 +578,18 @@ public function process_payment( $order_id, $retry = true, $force_save_source =
...
 
-			$prepared_source = $this->prepare_source( get_current_user_id(), $force_save_source );
+			// Check whether there is an existing intent.
+			$intent = $this->get_intent_from_order( $order );
+			if ( isset( $intent->object ) && 'setup_intent' === $intent->object ) {
+				$intent = false; // This function can only deal with *payment* intents
+			}
+
+			$stripe_customer_id = null;
+			if ( $intent ) {
```
Comment (v18) [inline includes/class-wc-gateway-stripe.php]: We should check that `$intent->customer` is set. I know technically it should be set at this point, but we could be defensive just in case.

**Comment by v18** [comment]
Works great, Rado. I left a couple of minor comments. Otherwise, it's ready to 🚢 .

I tested using these credit cards:
4000000000000002 (declines)
4242424242424242 (goes through)

And went through these cases:
- normal product checkout
- subscription
- creating an account
- setup intent (there's what seems to be a bug here, I'll make an issue later)

File: includes/class-wc-gateway-stripe.php (hunk 2 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1075/commits/5c48e76acf1bfc889bbd4506509dd31b929b0a0b

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 1 above)
Comment (RadoslavGeorgiev) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: > Why do we need to call update_customer() here? From what I can see, we aren't sending the new source to stripe, and what we're getting back from the API call in update_customer is a customer object (https://stripe.com/docs/api/customers/update) with what looks like no differences to what we had before.

Most of the time this call is redundant, yes. But customers might also fix/change their names, as well as their email address while changing the credit card they entered. In this case, the customer object needs to be updated.

Now, at the time `update_customer` and the `POST` request are executed, we do not have the data about the customer. In order to avoid this call, we'd first need another `GET` and a comparison of the data in Stripe and the one we have. This means that if the details _did_ change, we'd have two API calls (get and update), instead of just having this one call (update) anyway.

**Comment by RadoslavGeorgiev** [comment]
> Works great, Rado. I left a couple of minor comments. Otherwise, it's ready to 🚢 .

Thanks for the comments! I'm leaving the PR in "Needs Review" state because I'd like to have the conversation resolved first.

> setup intent (there's what seems to be a bug here, I'll make an issue later)

What's the bug? I'm curious what's broken and why it needs a separate issue.

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 1 above)
Comment (v18) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Ok, I see  👍 Nice.

**Comment by v18** [comment]
> What's the bug? I'm curious what's broken and why it needs a separate issue.

The bug isn't related to the customer being created again. It's about showing the "thank you" / "Order received" screen even when a credit card is declined. And... now I can't seem to repro anymore. 🙂

**Comment by RadoslavGeorgiev** [comment]
This sounds suspicious, but I guess others will report if it happened again. I'm merging this one...
