### PR TITLE
Use settings statement descriptor in account summary API

### LINKED ISSUE #2297: Statement descriptor value is not present in accounts REST API response - blocks mobile intent creation
**Describe the bug**
Even when set in the plug-in settings:

descriptor

the statement descriptor in the accounts REST API response is empty:

IMG_0301

**This is a must fix for the mobile apps. We can't create payment intents without a descriptor.**

Observed with plugin version 6.0.0

cc @ctarda @malinajirka - this is a must fix - we cannot create payment intents without a descriptor - payment intent creation fails

### PR DESCRIPTION
**Pull request by brianyu28**
Fixes #2297

## Changes proposed in this Pull Request:

There are currently two ways a merchant can set their statement descriptor. They can do so via the **Payments & transactions** settings for the extension (`/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`), and they can also do so via the **Account details** settings on their Stripe account (https://dashboard.stripe.com/settings/account). According to the [Stripe documentation](https://woocommerce.com/document/stripe/#setup-and-configuration), we use the descriptor from the extension settings if it's present, falling back to the Stripe account's statement descriptor only if the descriptor in the extension settings is left blank.

Currently, the account summary API returns only data (e.g. statement descriptor) from Stripe's account API. This PR updates the API to obey the same default/fallback behavior for statement descriptors as the rest of the extension: default to the extension settings descriptor and fall back to the Stripe descriptor if needed. Per a suggestion from @allendav, if both the extension settings descriptor and Stripe descriptor are both blank, this PR also adds a default descriptor which is a sanitized version of the site title. 

## Testing instructions

To make a request to the account summary API, run `curl --user username:password 'http://YOUR_SITE/wp-json/wc/v3/wc_stripe/account/summary'` with [Basic Auth](https://github.com/WP-API/Basic-Auth) installed.

* In the **Stripe extension settings** on the merchant store, set the statement descriptor to something (e.g. `Test Descriptor A`) and "Save changes."
* Make a request to the account summary API, verify that you see `Test Descriptor A`.
* In the **Stripe dashboard account settings** at https://dashboard.stripe.com/settings/account, set the statement descriptor to something else (e.g. `Test Descriptor B`) and "Save."
* Make a request to the account summary API, verify that you still see `Test Descriptor A` and not `Test Descriptor B`.
* In the **Stripe extension settings** on the merchant store, set the statement descriptor to `Test (Descriptor) C`. Note the parentheses, which are invalid characters in a statement descriptor.
* Make a request to the account summary API, verify that you see `Test Descriptor C` without the parentheses.
* In the **Stripe extension settings** on the merchant store, set the statement descriptor to the empty string and "Save changes."
* Make a request to the account summary API, verify that you see `Test Descriptor B`. (Note that here you may instead see an older value from your Stripe account's settings. If you do, you can delete the `_transient_wcstripe_account_data_test` transient to clear the extension's cached data and re-run the API.)
* Testing what happens when both descriptor fields are blank is trickier because Stripe doesn't allow you to update the descriptor to be blank. Instead, create a new Stripe account and give it a name. It will by default have no statement descriptor. Copy the new keys into the Stripe extension settings.
* Make a request to the account summary API, verify that the descriptor is now your site's title.
* To ensure that the site title is being sanitized, set the site title to a string longer than 22 characters with at least one special character (e.g. parentheses).
* Make a request to the account summary API, verify that the descriptor is truncated to 22 characters and doesn't contain special characters.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/admin/class-wc-rest-stripe-account-controller.php [hunk 1]
```diff
@@ -98,13 +106,22 @@ public function get_account() {
...
+		}
+
 		return new WP_REST_Response(
 			[
 				'has_pending_requirements' => $this->account->has_pending_requirements(),
 				'has_overdue_requirements' => $this->account->has_overdue_requirements(),
 				'current_deadline'         => $account['requirements']['current_deadline'] ?? null,
 				'status'                   => $this->account->get_account_status(),
-				'statement_descriptor'     => $account['settings']['payments']['statement_descriptor'] ?? '',
+				'statement_descriptor'     => $statement_descriptor,
```
Comment (a-danae) [inline includes/admin/class-wc-rest-stripe-account-controller.php:124]: Should we make these defaults consistent in other places where we use the statement descriptor? Like in[ the gateways](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L131), for example.

Thinking on a scenario where a customer would make a purchase on the same store through the site and then through the app, and the statements descriptors would be different for each purchase.

Not sure if this would be the case or if this is something we'd like to adjust. I don't think this is a blocker either way. We could check this out in a different issue if it's something we'd like to address.

**Review by a-danae — APPROVED** [review]
Thanks for the fix and for the detailed testing instructions, @brianyu28!

I followed the test cases and all of them return the expected results. 

I left a question about whether to adjust other places where the statement descriptor is used to have the fallback we're introducing in this PR. But everything looks good here 👌

File: includes/admin/class-wc-rest-stripe-account-controller.php (hunk 1 above)
Comment (brianyu28) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: It looks like the way the extension currently behaves is to pass `null` to Stripe if there is no statement descriptor, and Stripe then uses a default value of "Stripe" as the descriptor if there's none present.

Let me check with @allendav to see what the ideal behavior is from mobile's perspective. If this API returned `null` for the statement descriptor if none is present, could the apps pass on the `null` value to the payment intents API to let Stripe use its own default statement descriptor? (It seems to me from the Stripe's API docs that `null` is allowed but the empty string is not.) Or would there be some other reason that would require a non-null value?

Comment (allendav) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: I'll take a look

Comment (allendav) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: It works and although not explicitly stated in the text, the optional type (`String?`) suggests it in the docs as well: 

https://stripe.dev/stripe-terminal-ios/docs/Classes/SCPPaymentIntentParameters.html#/c:objc(cs)SCPPaymentIntentParameters(py)statementDescriptor

I'll post a PR to the mobile app to pass nil to Stripe when creating a payment intent for an in-person payment when an empty string is given by the account endpoint

fyi @ctarda @malinajirka

Comment (allendav) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: https://github.com/woocommerce/woocommerce-ios/issues/6040

Comment (brianyu28) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: Thanks for checking, @allendav! If Stripe's API accepts nil, I'm inclined to have the `wc_stripe/account/summary` endpoint in the extension return `null` for the statement descriptor (instead of the empty string), if that works for you?

Comment (allendav) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: I'll test that today and see if that causes any iOS hiccups. cc @malinajirka for Android

Comment (malinajirka) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: We'll need to update the Android app as `statement_descriptor` is currently defined as a non-nullable String. Having said that, it shouldn't cause any issues. Just let me know when you make the final decision and I'll update the code accordingly. (just a note, that we can't do this change in WCPay since it's a breaking change. However, the app with Stripe extension support hasn't been released yet, so the change here is fine.)

Comment (brianyu28) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: @allendav @malinajirka I've updated this branch to:

- Return the WC Stripe settings statement descriptor if non-empty.
- Otherwise, return the Stripe settings statement descriptor if non-empty.
- Otherwise, return `null`.

As a result, you should be able to pass what you get from this API directly to Stripe on payment intent creation, since it will always be either a non-empty string or null. Can you test this on iOS/Android to see if this behavior will work for you?

Comment (allendav) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: Can do

Comment (malinajirka) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: Thanks @brianyu28!

I've tested the following settings of the statement descriptor(on Android):
1. Extension (empty), Stripe (empty) - 🟢 it's automatically set to "Stripe"
2. Extension ("my statement descriptor"), Stripe (empty) - 🟢 "my statement descriptor" was used
3. Extension (empty), Stripe ("my statement descriptor) - 🟠  null was returned from the API, is there perhaps some cache? 

To run the test `3` I first emptied the value in the extension and I updated the descriptor in Stripe's dashboard afterwards. 
However, if I first update the value in Stripe's dashboard and then update the value in the extension, it is correctly set to whatever is set on Stripe's dashboard. So I think this PR works as expected, the extension just fetches the current value from Stripe only when the statement descriptor field is updated in the extension (or perhaps after some time)

Comment (brianyu28) [reply includes/admin/class-wc-rest-stripe-account-controller.php:124]: The extension does cache Stripe account data so it's not hitting Stripe's API for every request, so this sounds like the expected behavior. Thanks for testing, @malinajirka! Planning to merge this today so that it's included in the 6.2.0 release.

**Comment by allendav** [comment]
Thank you @brianyu28 ! I just tested this against the latest trunk of WooCommerce iOS and it works great with and without a descriptor in settings. Thanks again.

fyi @ctarda @malinajirka
