### PR TITLE
Fixes orders that require manual review due to risk/fraud rules being marked as processing/completed before approval

### LINKED ISSUE #2679: Order put on-hold, a immediately moved back to processing when payment is marked for-review by radar rule
**Describe the bug**

Transactions are labeled as `for review` by Stripe radar rules and placed `on-hold` in WooCommerce, but then immediately set to `processing` likely because of a `charge.succeeded` webhook.

It might be a similar problem than https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2536

**To Reproduce**
No consistent way of reproducir the issue found.

**Expected behavior**
The order remains in `on-hold` status until the payment is reviewed in the Stripe Dashboard.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**
p1691657520301449-slack-C7U3Y3VMY

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #2679 

## Changes proposed in this Pull Request:

> [!NOTE]
> This PR requires a bit more testing but I'm pushing up my current changes to get an initial review of the approach taken. I've only tested basic flows like processing high-risk fraud payments, payments flagged for manual review via custom rules, and regular non-risk payments. Areas I still need to test:
> - [x] how subscription purchases and renewals are handled
> - [x] 3DS cards
> - [x] APM that requires redirect
> - [x] `review.open` webhook sent before and after payment_intent/charge.succeeded webhook

The way we handle payments/charges that have been flagged for manual review by Stripe is we do the following:
1. Process the `payment_intent.succeeded` webhook and mark the order as processing/completed
2. If the charge requires manual review, Stripe will send an `review.open` event, which we listen for and put that order on-hold and store its current status in `_stripe_status_before_hold` metadata.
3. Store manager reviews the risky payment and approves it from their Stripe dashboard
4. We then process the `review.closed` webhook by restoring the status of the order back to its original status stored in `_stripe_status_before_hold`.

This flow relies heavily on the order in which these webhooks are sent/processed.
The succeeded event needs to come first and then `review.open`.

The issue described in #2679 is what happens when the `review.open` webhook is sent/processed first, the order is put on-hold and then the `payment_intent.succeeded` event is handled soon after, which then updates the status to processing. This results in the order in WooCommerce being processing/completed and ready to ship, but still waiting for manual approval in Stripe.

The expected behaviour is for orders to remain on-hold until the payment risk has been manually looked and approved, regardless of the order in which the webhooks are processed.

## Testing instructions

1. Make sure you have Stripe webhooks set up and working with your test store (I personally use ngrok on my local site)
2. Set up a custom review rule in Stripe Dashboard by going to https://dashboard.stripe.com/test/settings/radar/rules
3. Click on `Add Rule` within the Review Rules section:
image
4. Set the "Review if" condition to something that will cause purchases by your test customer to be flagged by the rule. For example I created a rule with **`Review if :email_domain: = 'example.com'`**
5. Go back to your store and attempt to purchase an product using any card.
6. View the order from the WP Admin > Edit Order page and confirm the order is on-hold and has note: image
7. View the order meta and confirm `_stripe_status_before_hold` is set to processing.
8. Go to https://dashboard.stripe.com/test/radar/reviews to see active payments that require review.
9. Approve the payment then wait for the `review.closed` webhook to be processed on your store.
10. Confirm the on-hold order is now set to processing.
11. Disable the review rule in Stripe and make a test purchase again with `4242424242424242` to confirm successful payments are working and don't have the on hold meta set.

### More tests

- Other [risk-related test cards](https://docs.stripe.com/testing?testing-method=card-numbers#fraud-prevention) (like the failure cases)
- When purchasing a subscription product, the parent order and subscription should remain on-hold while there's a pending manual review. Once approved, the order should be processing and subscription should be activated.
- Responding with "refund" instead of approving, should result in the order being refunded

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Comment by mattallan** [comment]
After writing up the PR description I decided this PR needs more testing before I get extra eyes on it so I've removed the review request for now and will request it again once it's ready

**Comment by mattallan** [comment]
I found a few problems while testing this PR and have pushed up a few more changes:

- [92a8a5e](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3063/commits/92a8a5e32c2f519428f3620f93a6151788324ff6) when the `review.open` webhook is being handled at the same time as the `payment_intent|charge.succeeded` event, the "before hold" meta wasn't saved yet and so we sometimes kept marking the orders as processing even though it was flagged as manual renewal.
  - To fix this I just got rid of part of the condition that fails when both events are processed simultaneously
- [1bf6801](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3063/commits/1bf6801535555058a2aa2d0d5285e2e6a93a996a) fixes an issue where if I closed the manual review without approving the payment/charge, the webhook handling was still updating the order status to completed.
- [9e3ce9b](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3063/commits/9e3ce9bb9847af8c1c74796f7cd4a05090b2b8f8) if I close the review by refunding the order, the order in WooCommerce isn't refunded because we have no way of linking the refund ID or charge ID to the order.

**Comment by mattallan** [comment]
In testing 3DS cards I noticed meta was being duplicated and so I pushed up a separate PR for this as I could reproduce it on `develop https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3078

This PR should be ready for a review now :)

**Review by a-danae — COMMENTED** [review]
Great job identifying the replication steps for that issue, @mattallan ! Thanks for diving there and for explaining what was going on.

Partial review here. I've only tested the main replication steps so far and things are looking good 🙂 

Wanted to leave a note here of some different steps I took to replicate the problem in `develop`:
- Keep the site offline so it doesn't receive any webhooks
- Place the order
- On the Stripe dashboard, confirm the events are marked as "Pending webhook response" when you visit the payment intent details, at `https://dashboard.stripe.com/test/payments/pi_xyz`
- Make the store online again. I used JT
- Resend the `review.opened` webhook
- Then resend the `charge.succeeded` webhook

Continuing testing over here!

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -2089,4 +2105,66 @@ private function get_source_object_from_request() {
...
+	 *
+	 * @since 8.3.0
+	 *
+	 * @param WC_Order    $order  The order.
+	 * @param string|null $status The status to store. Defaults to the current order status. Also accepts 'default_payment_complete' which will fetch the default status for payment complete orders.
+	 * @param bool        $save   Whether to save the order.
+	 *
+	 * @return void
+	 */
+	protected function set_stripe_order_status_before_hold( $order, $status = null, $save = true ) {
```
Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: How about making `$status` required, since we always pass a value for it?

Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Curious about `$save`. Would removing it simplify the code, since we always pass `false` for this parameter?

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 2]
```diff
@@ -2089,4 +2105,66 @@ private function get_source_object_from_request() {
...
+	 * Helper method to retrieve the status of the order before it was put on hold.
+	 *
+	 * @since 8.3.0
+	 *
+	 * @param WC_Order $order          The order.
+	 * @param string   $default_status The default status to return if the metadata is not set. Defaults to the payment complete status.
+	 *
+	 * @return string The status of the order before it was put on hold.
+	 */
+	protected function get_stripe_order_status_before_hold( $order, $default_status = null ) {
```
Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Would it be simpler to remove `$default_status` because we never pass a value for this parameter?

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 3]
```diff
@@ -2089,4 +2105,66 @@ private function get_source_object_from_request() {
...
+		if ( is_null( $default_status ) ) {
+			$default_status = apply_filters( 'woocommerce_payment_complete_order_status', $order->needs_processing() ? 'processing' : 'completed', $order->get_id(), $order );
+		}
+
+		return $order->get_meta( '_stripe_status_before_hold', true ) ?? $default_payment_complete_status;
```
Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Did we mean `$default_status` instead of `$default_payment_complete_status`?

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 4]
```diff
@@ -2089,4 +2105,66 @@ private function get_source_object_from_request() {
...
+	 * @since 8.3.0
+	 *
+	 * @param WC_Order $order          The order.
+	 * @param string   $default_status The default status to return if the metadata is not set. Defaults to the payment complete status.
+	 *
+	 * @return string The status of the order before it was put on hold.
+	 */
+	protected function get_stripe_order_status_before_hold( $order, $default_status = null ) {
+		if ( is_null( $default_status ) ) {
+			$default_status = apply_filters( 'woocommerce_payment_complete_order_status', $order->needs_processing() ? 'processing' : 'completed', $order->get_id(), $order );
```
Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: I read this twice to be sure what was the first parameter of the `apply_filters` function. Although this is fully functional and makes sense, would it be more readable if we split it?

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 3 above)
Comment (a-danae) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Would it be worth returning early the value of `$order->get_meta( '_stripe_status_before_hold' )` when it isn't empty? We wouldn't need `$default_status` in that scenario, or all the processing we do to define its value.

🤏 non-important nit just for readability... The default value of `get_meta()` [seems to be](https://woocommerce.github.io/code-reference/classes/WC-Data.html#method_get_meta) `true`, so looks like we could leave it out?

Comment (mattallan) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: :o Nice find!! Thanks Danae! I've refactored this function in [e5075ed](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3063/commits/e5075ed034e8643310741aed0f7f3a7d9fcabcb2) and have resolved this issue

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 4 above)
Comment (mattallan) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Thanks for the suggestion! I definitely agree with this :) I've split this up a little bit in the latest changes to hopefully help with readability.

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 1 above)
Comment (mattallan) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Thanks!! Fixed in [533bbb4](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3063/commits/533bbb4f8452c5a1d416b821f925482dab002ce8)

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 2 above)
Comment (mattallan) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Agreed! The final changes of this PR are different to when I originally wrote this function so I'm glad you found these unnecessary defaults and params :)

**Review by a-danae — APPROVED** [review]
Aaaand everything tested well over here 👍 Also, thanks for the updates in the code!

✅ The order status doesn't change to "Processing" when the webhooks are triggered in an unexpected order and a Radar review is pending, both for regular products and subscriptions.
✅ Orders with a payment blocked by Radar rules work as expected, both when webhooks are triggered in an expected and unexpected sequence.
✅ Tested using charges with different [outcome.type](https://docs.stripe.com/api/charges/object#charge_object-outcome-type) values at the time payment_intent.succeeded and charge.succeeded events were triggered. The order status behaved as expected.
✅ Refunded Radar manual reviews updated the order status as expected, both when the webhooks were triggered in an expected and unexpected order.
✅ The orders processed with 3DS cards transitioned as expected.

We just need the changelog entries and we'd be ready to go 🙂 thanks for your work here, @mattallan !

Also, would it be worth including [release-specific](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/v8.3.0-%E2%80%90-Release-testing-instructions) test cases for this for GS to test?

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 2 above)
Comment (a-danae) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Ah yeah, classic leftovers from a previous approach 😄 thanks for iterating on them!

**Comment by mattallan** [comment]
Thanks so much @a-danae for the review and testing of this issue. It wasn't an easy problem to fix, so I appreciate you taking the time to review this and think through the changes!!

I've added a changelog entry in [440a048](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3063/commits/440a0485aef83817f73a101ecf35faa3745134a7) and also conducted some more tests.

> Also, would it be worth including [release-specific](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/v8.3.0-%E2%80%90-Release-testing-instructions) test cases for this for GS to test?

I think this is a good idea! I'll get them added today or tomorrow :)
