### PR TITLE
Fix payment method description on checkout page

### LINKED ISSUE #3272: [HC] Stripe is showing unwanted messages on the payment options on version 8.5
**Describe the bug**
When using 8.5 some payment methods show an unwanted message on checkout.
It's the message that explains the payment method for the store owner, but it shouldn't be shown to the customers.

This only happens with the new checkout experience.

**To Reproduce**
1. Have Stripe 8.5
2. Check the credit card option on checkout

**Expected behavior**
For the message to not show.

**Screenshots**

image
image

Here's a screenshot of my checkout on 8.4
image

**Environment (please complete the following information):**
 - WordPress Version: 6.5.5
 - WooCommerce Version: 9.1.1
 - Stripe Plugin Version 8.5
 - Browser and Version: [Chrome 126 on Windows 11](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have/)
 - Any other plugins installed: I tested with only Woo and Stripe active and on the Storefront theme

**Additional context**
Reported **[here](https://wordpress.org/support/topic/version-8-5-0-shows-messages-in-credit-card-and-sepa-dropdown-on-checkout-page/)**.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #3272 
Some more discussions in p1720692041109859-slack-C055WHLA98D

If the description is set to empty, we are not showing the default description on the checkout page now.

## Changes proposed in this Pull Request:
- When the description of a payment method is empty, we are now returning empty instead of the default description to show on the checkout page ([8af6045](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3282/commits/8af6045f95a05c495f34ccb617fa050fc72171d4)). 
- This PR has two more additional tweak commits.
    - Removed this unnecessary response data https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3282/commits/b70d6f7cdaa59d9acbb9fd4fc2d04d5a49cf5b22
    - Removed this Multibanco specific condition which was needed when Multibanco was available only in Sources API regardless of UPE enabled/disabled (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3282/commits/f7f1a061fdfcb85b96043a8d3737ad7fff82e5e5). As Multibanco is available is UPE now, this check is unnecessary. 

## Testing instructions
- Go to the Stripe settings page and disable the legacy checkout experience (enable UPE).
- Go to the payment methods tab.
- Enable the card method and make the description empty.
- Go to the checkout page and check the card element.
- In `develop` branch you would see the admin facing default description showing up there. In this branch no default description will show up on the checkout page when the description is empty.
- Test this for other Stripe payment methods too. 
- Test the legacy and new checkout experience. 
- Test on shortcode and block checkout page.

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-method.php [hunk 1]
```diff
@@ -112,10 +112,11 @@ public function __construct() {
 		$main_settings     = get_option( 'woocommerce_stripe_settings' );
 		$is_stripe_enabled = ! empty( $main_settings['enabled'] ) && 'yes' === $main_settings['enabled'];
 
-		$this->enabled  = $is_stripe_enabled && in_array( static::STRIPE_ID, $this->get_option( 'upe_checkout_experience_accepted_payments', [ 'card' ] ), true ) ? 'yes' : 'no';
-		$this->id       = WC_Gateway_Stripe::ID . '_' . static::STRIPE_ID;
-		$this->testmode = ! empty( $main_settings['testmode'] ) && 'yes' === $main_settings['testmode'];
-		$this->supports = [ 'products', 'refunds' ];
+		$this->enabled    = $is_stripe_enabled && in_array( static::STRIPE_ID, $this->get_option( 'upe_checkout_experience_accepted_payments', [ 'card' ] ), true ) ? 'yes' : 'no';
+		$this->id         = WC_Gateway_Stripe::ID . '_' . static::STRIPE_ID;
+		$this->has_fields = true;
```
Comment (Mayisha) [inline includes/payment-methods/class-wc-stripe-upe-payment-method.php:117]: This is set to fix an issue where a payment method section is not loaded (except for the title) if the description is empty (check the logic [here](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/checkout/payment-method.php#L28)). As the section is not loaded, the Stripe payment element fails to mount.

Comment (james-allan) [reply includes/payment-methods/class-wc-stripe-upe-payment-method.php:117]: 👍 confirmed that without this, UPE methods (like CashApp) won't display anything when selected, if it doesn't have a description. eg:

<p align="center">
Screenshot 2024-07-29 at 4 12 27 PM
</p>

**Review by james-allan — APPROVED** [review]
Changes look good. Thanks Mayisha. 

| Before | After |
|--------|--------|
| Screenshot 2024-07-29 at 4 01 34 PMScreenshot 2024-07-29 at 4 03 33 PM| Screenshot 2024-07-29 at 4 00 50 PMScreenshot 2024-07-29 at 4 05 12 PM | 

If I enter a description in the settings, it shows correctly on the checkout. 




| Screenshot 2024-07-29 at 4 06 57 PM | Screenshot 2024-07-29 at 4 06 08 PMScreenshot 2024-07-29 at 4 06 33 PM |
|--------|--------|
