### PR TITLE
Display Multibanco details in Order Received page and Order Confirmation email

### LINKED ISSUE #3625: Multibanco payment information doesn't show on Thank you page and Order Confirmation email
9015318-zen

**Describe the bug**

After [completing the Stripe's recent requirements](https://woocommerce.com/document/stripe/admin-experience/updated-requirements-for-stripe-plugin-mid-2024/), when a customer places an order with Multibanco, the Entity and Reference numbers show up in a pop-up but not on the Order received page (when the pop-up is closed) or the order confirmation email. This information used to show in both places in previous versions.

Image

**To Reproduce**
1. Site must first have completed the [Stripe's recent requirements](https://woocommerce.com/document/stripe/admin-experience/updated-requirements-for-stripe-plugin-mid-2024/)
2. Place an order with Multibanco
3. Notice how the the Entity and Reference numbers show up in a pop-up but not on the Order received page (when the pop-up is closed) or the order confirmation email

**Expected behavior**
Entity and Reference numbers should also show on the Order received page (when the pop-up is closed) or the order confirmation email, like in these screenshots:

Thank you page:
Image

Order confirmation email: 
Image

**Environment (please complete the following information):**
 - WordPress Version: 6.7
 - WooCommerce Version: 9.4.1
 - Stripe Plugin Version: 8.9.0

**Workarounds**

As suggested in C7U3Y3VMY/p1732118377790839:

> the simplest, and not recommended, workaround is to use the legacy checkout. Since this part wasn't correctly moved to the new experience
> another possible solution is to do the work we need to do themselves:

> 1 - Copy the email_instructions method from the WC_Gateway_Stripe_Multibanco class to WC_Stripe_UPE_Payment_Method_Multibanco
> 2 - Add this line to the __construct method of the same class (WC_Stripe_UPE_Payment_Method_Multibanco)

		// Customer Emails
		add_action( 'woocommerce_email_before_order_table', [ $this, 'email_instructions' ], 10, 3 );

### PR DESCRIPTION
**Pull request by annemirasol**
Fixes #3625 

## Changes proposed in this Pull Request:
Display Multibanco payment instruction details in the Order Received/Thank You page, and in the Order Confirmation email for added convenience to the shopper. This feature was present in the legacy checkout.

## Testing instructions
1. Make sure your webhooks are enabled and working.
2. Set your shop currency to `EUR` and enable Multibanco as a payment method.
3. Install your email logging plugin of choice, e.g. Post SMTP Email Log
4. As a shopper, purchase something using Multibanco.
5. Verify that the Order Received/Thank You page displays the Multibanco payment instruction details.
6. Using your email logging plugin, verify that the order confirmation email contains the Multibanco payment instruction details.

| Before | After |
|--------|-------|
|Screenshot 2024-12-17 at 10 59 23 AM | Screenshot 2024-12-17 at 10 59 07 AM |
| Screenshot 2024-12-17 at 11 02 24 AM| Screenshot 2024-12-17 at 11 52 47 AM |

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php [hunk 1]
```diff
@@ -29,6 +29,104 @@ public function __construct() {
...
+		$payment_method = $order->get_payment_method();
+		if ( ! $sent_to_admin && 'stripe_multibanco' === $payment_method && $order->has_status( 'on-hold' ) ) {
+			$this->get_instructions( $order, $plain_text );
+		}
+	}
+
+	/**
+	 * Gets Multibanco payment instructions for the customer.
+	 *
+	 * @param WC_Order $order
```
Comment (Mayisha) [inline includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php:69]: Nitpick:  missing the `$plain_text` param.

File: includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php [hunk 2]
```diff
@@ -29,6 +29,104 @@ public function __construct() {
...
+	 */
+	public function get_instructions( $order, $plain_text = false ) {
```
Comment (Mayisha) [inline includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php:72]: In [legacy experience](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3c8c8de87421ba65808bcf8583137ceb4e674127/includes/payment-methods/class-wc-gateway-stripe-multibanco.php#L243), the instructions were in Portuguese. But here, they are in English. Is this intentional?

File: includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php [hunk 3]
```diff
@@ -29,6 +29,104 @@ public function __construct() {
...
+			esc_html_e( 'Amount:', 'woocommerce-gateway-stripe' ) . "\n\n";
+			echo wp_kses_post( $data['amount'] ) . "\n\n";
+			echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n\n";
+			esc_html_e( 'Entity:', 'woocommerce-gateway-stripe' ) . "\n\n";
+			echo esc_html( $data['entity'] ) . "\n\n";
+			echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n\n";
+			esc_html_e( 'Reference:', 'woocommerce-gateway-stripe' ) . "\n\n";
+			echo esc_html( $data['reference'] ) . "\n\n";
+			esc_html_e( 'Voucher URL:', 'woocommerce-gateway-stripe' ) . "\n\n";
+			echo esc_html( $data['hosted_voucher_url'] ) . "\n\n";
```
Comment (Mayisha) [inline includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php]: In the `save_instructions` method we are saving only amount, entity and reference. `hosted_voucher_url` is missing there.

Comment (annemirasol) [reply includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php]: Good catch. I was initially storing and displaying that field, but decided against it in the end. Removed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3664/commits/063a5b5ad78c28963d80c8b44e05e162840d3fcb

File: includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php (hunk 1 above)
Comment (annemirasol) [reply includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php:69]: Added in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3664/commits/74ff57cea98261b04310c3d916103ed1720c236e, thanks!

File: includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php (hunk 2 above)
Comment (annemirasol) [reply includes/payment-methods/class-wc-stripe-upe-payment-method-multibanco.php:72]: Yes, I decided to use English text in the code since we are using `esc_html_e()` to translate to the determined locale anyways, and Stripe docs say Multibanco is available in Europe and US.

**Comment by annemirasol** [comment]
@Mayisha Thanks for the feedback. Addressed and ready for another look!

**Review by Mayisha — APPROVED** [review]
Thanks for the update @annemirasol. Looks good to me 👍
