### PR TITLE
Fix: allow to edit uncaptured orders

### LINKED ISSUE #3723: Totals of pre-authorized but not yet captured orders are not editable.
**Describe the bug**
Starting with version 9.1.0, it is no longer possible to edit totals of pre-authorized but not yet captured orders. With version 9.0.0 these orders are editable.

Edit: I see this change in the changelog:
>  Update - Prevent editing of orders awaiting payment capture.

I see this pull request:

https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3652

So it sounds like this never worked correctly?

> Reason: The authorized amount in Stripe does not get updated with the order total. Attempting to capture payment when the order total is not the same as the authorized amount results in failure.

I asked the merchant who reported it in 9281515-zen to confirm if they were able in the past to edit order totals and capture the payment with a different than original amount.

But, on my test site, with Stripe in test mode, if I edit the total and capture - it works, this is what I see on Stripe side:

Image

**To Reproduce**
1. Tick the `Issue an authorization on checkout, and capture later` checkbox in the settings of Stripe payment method, and save.
2. With the latest version of Stripe plugin, place an order. While the order status is "on hold" or even if we change it to "pending payment" - there is no pencil icon next to totals so we can't adjut the amount before capturing the charge.
3. Downgrade/roll back Stripe to version 9.0, and repeat the process. The pencil icon is there and totals are editable.

**Expected behavior**
Order totals should be editable.

**Screenshots**
9.0.0:

Image

9.1.0 and 9.1.1:

Image

**Environment (please complete the following information):**
 - WordPress Version 6.7.1
 - WooCommerce Version 9.5.2
 - Stripe Plugin Version 9.1.0, 9.1.1
 - Browser Chrome
 - Any other plugins installed yes but that shouldn't make a difference, bug confirmed on two separate sites.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #3723 

When authorize and capture later is enabled and a charge is authorized for a particular order, we can not charge a higher amount for that order. The payment fails with an error in this case. In https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3646 I disabled the edit for uncaptured orders. This took away the ability to partial capture as well. If a merchant updates the order total to the same or less amount, the payment succeeds and this is a common use-case for some merchants. So the order should be editable. (check [this comment](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3646#issuecomment-2583070113) and WooPayments reference)

## Changes proposed in this Pull Request:
- Made the uncaptured orders editable again.
- Showing a warning message on the order edit page about the failure scenario if the total is updated to be greater than the authorized amount. Borrowed the warning message from the WooPayments docs.

## Testing instructions
- Enable `Issue an authorization on checkout, and capture later` in the Stripe settings page.
- As a shopper, purchase a product using a card.
- As an admin go to the order edit page. Confirm from the order notes that the charge has been authorized, the order is now editable and there is a warning message about the uncaptured order.

Screenshot 2025-01-21 at 6 12 20 PM

- As a shopper purchase a product with another payment method (such as COD) and confirm that the warning is not displayed on the order edit page.
- Now disable `Issue an authorization on checkout, and capture later` in the Stripe settings page.
- As a shopper, purchase a product using a card.
- As an admin go to the order edit page and confirm that the warning message is not displayed.

### CODE REVIEW

File: includes/class-wc-stripe-order-handler.php [hunk 1]
```diff
@@ -43,77 +43,27 @@ public static function get_instance() {
...
+		$order = wc_get_order( $order_id );
 		// Bail if payment method is not manual capture supporting stripe method.
 		if ( ! WC_Stripe_Helper::payment_method_allows_manual_capture( $order->get_payment_method() ) ) {
 			return $editable;
 		}
 
 		try {
 			$intent = $this->get_intent_from_order( $order );
-
 			if ( $intent && 'requires_capture' === $intent->status ) {
```
Comment (wjrosa) [inline includes/class-wc-stripe-order-handler.php]: We can make use of the new constant class here `WC_Stripe_Intent_Status::REQUIRES_CAPTURE`

**Review by wjrosa — APPROVED** [review]
Code is good and it works as expected:

> As an admin go to the order edit page. Confirm from the order notes that the charge has been authorized, the order is now editable and there is a warning message about the uncaptured order.

Screenshot 2025-01-21 at 11 05 29

> As an admin go to the order edit page and confirm that the warning message is not displayed.

Screenshot 2025-01-21 at 11 10 59

But tests are broken. And I left an optional suggestion
