### PR TITLE
Handle subs renewal failed payment closes #247

### LINKED ISSUE #247: Processing a failed subscription payment php errors and incorrect order notes
#### Affected ticket(s)
https://woothemes.zendesk.com/agent/tickets/567914
569260-zd-woothemes

#### What I expected

When a failed renewal order is payment is processed I expected the order status to be set to failed with standard order notes to explain that. 

#### What happened instead

Order status is transitioned from pending to on-hold and then to failed and capture and authorise order notes are added. 
lvaljnf5x5-1200x1200
https://cloudup.com/cxivFla7kZC

Capture payment immediately is enabled https://cloudup.com/ckz3jLKlSAU

Locally I'm also receiving the following errors: 

```
PHP Notice:  Undefined property: WP_Error::$id in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 853
PHP Notice:  Undefined property: WP_Error::$captured in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 854
PHP Notice:  Undefined property: WP_Error::$captured in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 866
PHP Notice:  Undefined property: WP_Error::$id in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 874
PHP Notice:  Undefined property: WP_Error::$id in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 880
PHP Notice:  Undefined property: WP_Error::$id in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 881
```
#### Steps to reproduce the issue
If you already have a subscription setup with Stripe already go to step 2

1. Purchase a subscription product
2. Go to the WP admin dashboard and navigate to **WooCommerce > Subscriptions**
3. Edit the subscription 
4. Edit the billing details and tweak the Stripe customer and card IDs to force a failure (https://cloudup.com/cZjSGGCJ8Gl)
5. From the subscription actions dropdown process a renewal payment (https://cloudup.com/cNiqWhI22_9)
6. Scroll down to the related orders and view the newly created renewal order
7. Notice the order notes are representative of authorise and capture being enabled when it's not. (https://cloudup.com/cJ0stvC78Uu)

The extra status transition (pending to on-hold to failed) is causing extra subscription related emails to be sent which is what this ticket is reporting. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by roykho**
Fixes #247

#### Changes proposed in this Pull Request:
* Fix - Handle a subscription renewal failed payment order correctly to prevent orders going into onhold status.

When a subs order is renewed, sometimes payment fails. When this happens the order is not handled properly and it first goes into on-hold status and then fail. But doing this, causes order email to be sent to customers again causing confusion.

This patch properly handles the error and prevents the order going into on-hold. Instead it will just fail.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-gateway-stripe-addons.php [hunk 1]
```diff
@@ -149,6 +149,8 @@ public function process_subscription_payment( $order = '', $amount = 0 ) {
 					'site_url'       => esc_url( get_site_url() ),
 				);
 				$response          = WC_Stripe_API::request( $request );
+			} elseif ( ! empty( $response->errors ) ) {
```
Comment (gedex) [inline includes/class-wc-gateway-stripe-addons.php]: we could simplify this with just `else` as when `WP_Error` is instantiated it has, at least, one error stored.
