### PR TITLE
Fix order amount for currencies with 3 decimal places

### LINKED ISSUE #2720: The charged amount is divided by 10 for three-decimal currencies
**Describe the bug**

Originally reported in zd-7121714

https://wordpress.org/support/topic/three-decimal-currencies-are-unsupported/

When the site currency is set one of the [three decimal currencies here](https://stripe.com/docs/currencies?presentment-currency=AE#three-decimal), the total will be divided by 10. So if an order total is 35.20, Stripe will only charge 3.5.

**To Reproduce**

- Switch your Stripe test account to a region that [supports these currencies](https://stripe.com/docs/currencies?presentment-currency=AE#three-decimal), such as the UAE. 

- Set the site currency to BHD (Bahraini or Jordanian Dinar).
- Try to place an order.
- Check the amount charged in Stripe.

Link to image: https://d.pr/i/b13Ivp

Link to image: https://d.pr/i/KyQzxo

**Expected behavior**
The order amount should be charged exactly as it is displayed in WooCommerce.

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #2720 

## Changes proposed in this Pull Request:

This PR fixes the handling of currencies with [3 decimal places](https://docs.stripe.com/currencies?presentment-currency=AE#three-decimal). We do this by using the existing `WC_Stripe_Helper::get_stripe_amount` method, always passing the currency, and improving it to identify those specific currencies. When any if found, we multiple the amount by 100 and round the last digit as mentioned [here](https://docs.stripe.com/currencies?presentment-currency=AE#three-decimal).

## Testing instructions

- Change the country of your Stripe account to "United Arab Emirates"
- Checkout to this branch on your local environment
- Setup your Stripe keys
- Change your store currency to any of the [3-decimal places ones](https://docs.stripe.com/currencies?presentment-currency=AE#three-decimal)
- Start it with `npm run up`
- Place an order
- Verify that you can see the correct amount on Stripe (instead of 10% of it, as it happens in the `develop` branch)
- Confirm the same behavior with both UPE enabled or disabled

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [x] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/class-wc-stripe-helper.php [hunk 1]
```diff
@@ -181,8 +181,13 @@ public static function get_stripe_amount( $total, $currency = '' ) {
...
 		}
 
-		if ( in_array( strtolower( $currency ), self::no_decimal_currencies() ) ) {
+		$currency = strtolower( $currency );
+
+		if ( in_array( $currency, self::no_decimal_currencies(), true ) ) {
 			return absint( $total );
+		} elseif ( in_array( $currency, self::tree_decimal_currencies(), true ) ) {
+			$amount = absint( wc_format_decimal( ( (float) $total * 100 ), wc_get_price_decimals() ) ); // For tree decimal currencies.
+			return $amount - ( $amount % 10 ); // Round the last digit down. See https://docs.stripe.com/currencies?presentment-currency=AE#three-decimal
```
Comment (mattallan) [inline includes/class-wc-stripe-helper.php:191]: Is this calculation correct?

Using the example from the stripe docs:

> For example, 5.124 KWD must be rounded to 5120 or 5130.

When I test this amount using the following code: `WC_Stripe_Helper::get_stripe_amount( 5.124, 'KWD' );`, it's returning 510. Not 5120 according to Stripe.

Is this right?

File: includes/class-wc-stripe-helper.php [hunk 2]
```diff
@@ -255,6 +260,22 @@ public static function no_decimal_currencies() {
 		];
 	}
 
+	/**
+	 * List of currencies supported by Stripe that has three decimals
+	 * https://docs.stripe.com/currencies?presentment-currency=AE#three-decimal
+	 *
+	 * @return array $currencies
+	 */
+	private static function tree_decimal_currencies() {
```
Comment (mattallan) [inline includes/class-wc-stripe-helper.php]:
```suggestion
	private static function three_decimal_currencies() {
```

Small typo in the function name :)

**Review by mattallan — COMMENTED** [review]
Hey @wjrosa, I'm trying to confirm the fix on this branch but when I look at the payment in Stripe, it's still showing the incorrect amount (expected 5.120, but getting 0.510):

Woo
image


Stripe
image

I tested both UPE enabled and disabled and got the same results.

Here's my testing instructions:
1. Create a Stripe account for UAE and input the account keys
2. Set your store currency to Kuwaiti Dinar (KWD) and set it to 3 decimal places
3. Create a simple product with price set to 5.124
4. Purchase the product through the checkout
5. Open the stripe dashboard and go to payments, and notice the price is 0.510

I think this issue is actually caused by the `get_stripe_amount()` function not multiplying the total by the correct number, specifically the `* 100` part.

If my store has set the currency to use 3 decimal places, I think we need to multiple the total by 1000, instead of 100.
To fix this we should be able do something like:


```
$cent_precision = pow( 10, wc_get_price_decimals() );
$amount         = absint( wc_format_decimal( ( (float) $total * $cent_precision ), wc_get_price_decimals() ) );
```

File: includes/class-wc-stripe-helper.php (hunk 1 above)
Comment (mattallan) [reply includes/class-wc-stripe-helper.php:191]: I figured out the problem while writing my review 😄 

The issue is the `* 100` when you have the **Number of decimals** setting found under **WooCommerce > Settings > General** set to 3 (instead of 2).

To fix this I think we need to do something like:

```
$cent_precision = pow( 10, wc_get_price_decimals() );
$amount         = absint( wc_format_decimal( ( (float) $total * $cent_precision ), wc_get_price_decimals() ) );
```

Comment (wjrosa) [reply includes/class-wc-stripe-helper.php:191]: Great catch! I forgot about this setting, sorry! I have included your suggestion and also updated the unit tests 👍

Comment (wjrosa) [reply includes/class-wc-stripe-helper.php:191]: It stopped working when the settings were configured for two decimal places. I am looking 👀

Comment (wjrosa) [reply includes/class-wc-stripe-helper.php:191]: Oh OK, hardcoding the decimal multiplier to `1000` did the trick. Working for me with both decimal places settings. Can you repeat your tests as well please, @mattallan?

File: tests/phpunit/test-wc-stripe-helper.php [hunk 3]
```diff
@@ -196,13 +196,13 @@ public function test_get_legacy_individual_payment_method_settings() {
...
-	 * @return void
-	 * @dataProvider provide_test_get_order_by_intent_id
-	 */
+	* Test for `get_order_by_intent_id`
+	*
+	* @param string $status              The order status to return.
+	* @param bool   $success             Whether the order should be found.
+	* @return void
+	* @dataProvider provide_test_get_order_by_intent_id
+	*/
```
Comment (mattallan) [inline tests/phpunit/test-wc-stripe-helper.php]:
```suggestion
	 * Test for `get_order_by_intent_id`
	 *
	 * @param string $status              The order status to return.
	 * @param bool   $success             Whether the order should be found.
	 * @return void
	 * @dataProvider provide_test_get_order_by_intent_id
	 */
```

Not sure what happened here but the indentation is slightly off.

File: tests/phpunit/test-wc-stripe-helper.php [hunk 4]
```diff
@@ -222,10 +222,10 @@ public function test_get_order_by_intent_id( $status, $success ) {
...
 
 	/**
-	 * Data provider for `test_get_order_by_intent_id`
-	 *
-	 * @return array
-	 */
+	* Data provider for `test_get_order_by_intent_id`
+	*
+	* @return array
+	*/
```
Comment (mattallan) [inline tests/phpunit/test-wc-stripe-helper.php]:
```suggestion
	 * Data provider for `test_get_order_by_intent_id`
	 *
	 * @return array
	 */
```

File: changelog.txt [hunk 5]
```diff
@@ -1,6 +1,7 @@
 *** Changelog ***
 
 = 8.1.0 - xxxx-xx-xx =
+* Fix - The payment amount over Stripe when purchasing using currencies with 3 decimal places.
```
Comment (mattallan) [inline changelog.txt]: The wording of this changelog entry is a little off so I've made a small suggestion:

```suggestion
* Fix - Incorrect payment amount sent to Stripe when using three-decimal currencies.
```

File: readme.txt [hunk 6]
```diff
@@ -129,6 +129,7 @@ If you get stuck, you can ask for help in the Plugin Forum.
 == Changelog ==
 
 = 8.1.0 - xxxx-xx-xx =
+* Fix - The payment amount over Stripe when purchasing using currencies with 3 decimal places.
```
Comment (mattallan) [inline readme.txt]:
```suggestion
* Fix - Incorrect payment amount sent to Stripe when using three-decimal currencies.
```

**Review by mattallan — APPROVED** [review]
Thanks @wjrosa for the latest changes!

I've retested this PR using KWD with the price decimal setting set to both 2 and 3 decimal places, and also tested regular US accounts/currency and everything appears to be working.

I've made a few more suggestions, but none of them are blocking so I'm happy to approve this one. Nice work!

File: includes/class-wc-stripe-helper.php (hunk 1 above)
Comment (mattallan) [reply includes/class-wc-stripe-helper.php:191]: Nice find and thanks for adding a unit test to this one!

> hardcoding the decimal multiplier to 1000 did the trick. Working for me with both decimal places settings.

Interesting! I didn't think that would be the solution so I'm sorry for the bum steer with using the `pow()` calculation.

I've tested the latest and confirmed it's working as expected with your changes 💃

Comment (wjrosa) [reply includes/class-wc-stripe-helper.php:191]: No worries! I couldn't find the bug with the three decimal settings if it weren't for you 🙌
