### PR TITLE
Display the WeChat Pay icon on the legacy checkout

### LINKED ISSUE #3466: WeChat icon is not shown on the shortcode/legacy checkout
**Describe the bug**
The WeChat Pay icon is currently not shown on the legacy checkout.

Screenshot 2024-09-25 at 11 23 54 am

**To Reproduce**
1. Enable the WeChat Pay payment method in the Stripe settings.
2. Create a page with the shortcode checkout (if you don't have one setup).
3. Place a product in the cart.
4. Go to the shortcode checkout and note that the icon is missing next to the WeChat payment method. 

**Expected behavior**
The WeChat Pay icon should be shown.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3466

## Changes proposed in this Pull Request:

This is small PR fixes an issue that caused the WeChat Pay icon to not be displayed on the legacy/shortcode checkout.

| Before | After |
|--------|--------|
| Screenshot 2024-09-26 at 2 20 01 pm | Screenshot 2024-09-26 at 2 16 31 pm | 

I noticed while looking at the changes in #3449 that there was an outlier to this list of Payment method icons that WeChat Pay didn't follow the same format. Based on that, I guessed that there must have been an issue with fetching the WeChat Pay icon unless there was code that mapped the `wechat_pay` gateway to use `wechat`, [like there is for cards](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8.7.0/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L272). I found that there wasn't and therefore there would be an issue fetching the icon dynamically [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8.7.0/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L216). 

## Testing instructions

1. From your Stripe Payment method settings.
2. Enable WeChat Pay
3. Go to a legacy/shortcode checkout
   - On `develop` there won't be a WeChat icon displayed.
   - On this branch there should be an icon shown. 

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -338,7 +338,7 @@ public function payment_icons() {
 			'wc_stripe_payment_icons',
 			[
 				WC_Stripe_Payment_Methods::ALIPAY      => '<img src="' . WC_STRIPE_PLUGIN_URL . '/assets/images/alipay.svg" class="stripe-alipay-icon stripe-icon" alt="Alipay" />',
-				'wechat'                               => '<img src="' . WC_STRIPE_PLUGIN_URL . '/assets/images/wechat.svg" class="stripe-wechat-icon stripe-icon" alt="Wechat Pay" />',
```
Comment (james-allan) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php:341]: I went back to previous commits to see when this issue might have been introduced. This `'wechat'` key was added 6 years ago in https://github.com/woocommerce/woocommerce-gateway-stripe/commit/5e4415c088ec22d8a0e2499e5393fdf0a9a8040f. That makes me think this icon was never shown on the classic checkout when we built the UPE method for it.

**Review by mattallan — APPROVED** [review]
Thanks @james-allan for the PR!

Code changes look good and I've confirmed issue is fixed on this branch. Approving :)

| `develop` | `issue/3466-wechat-icon-shortcode-checkout` |
|--------|--------|
| image| image|
