### PR TITLE
Fix fatal error when changing payment method for a subscription

### LINKED ISSUE #2078: UPE - Fatal error when changing payment method for subscription
Internal ref: p1634091616216900-slack-C7U3Y3VMY

**Describe the bug**
When changing the payment method as a shopper for a subscription with UPE enabled, a fatal error occurs:

```
Call to undefined method WC_Stripe_UPE_Payment_Gateway::create_token_from_setup_intent()
```

**To Reproduce**
1. Ensure you have WooCommerce subscriptions installed.
2. Ensure you have UPE enabled.
3. As a merchant, create a subscription product.
4. As a shopper, purchase the subscription product.
5. As a shopper, navigate to **My account > Subscriptions**, and select the recently purchased subscription.
6. Click "Change payment" and proceed to add a new credit card as the payment method.
7. Notice a fatal error occurs.

### PR DESCRIPTION
**Pull request by ricardo**
Fixes #2078

## Changes proposed in this Pull Request:

- Bring back the `create_token_from_setup_intent` function that was removed in this commit: https://github.com/woocommerce/woocommerce-gateway-stripe/commit/66ecaa434d556c0e47cf9e1e44a04006a9ebac8d.

## Testing instructions

1. Ensure you have WooCommerce subscriptions installed.
2. Ensure you have UPE enabled.
3. As a merchant, create a subscription product.
4. As a shopper, purchase the subscription product.
5. As a shopper, navigate to My account > Subscriptions, and select the recently purchased subscription.
6. Click "Change payment" and proceed to add a new credit card as the payment method.
7. Ensure changing the payment method works in this branch.

FWIW: There's a small flickering after the UPE form is submitted. Submitting the form via JavaScript after the UPE redirect might not be the best solution, although it's consistent with WCPay at the moment. We might want to reconsider if that's really necessary in another issue.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).

### CODE REVIEW

**Review by diegocurbelo — COMMENTED** [review]
The error is not present anymore, and it shows a "Payment method updated." message after changing the payment method.

Just noticed something weird... when the payment method is changed to a new card, the card gets added to the customer's saved payments list correctly, but the subscription payment method is set to the first saved payment method in the list, not the one just added.

**Comment by ricardo** [comment]
> when the payment method is changed to a new card, the card gets added to the customer's saved payments list correctly, but the subscription payment method is set to the first saved payment method in the list, not the one just added.

@diegocurbelo good catch! That was because the cache wasn't being cleared. It should be fixed now.

I also noticed an edge case where if you have 10+ saved payment methods it won't work because of the current 10 token limitation. But I don't think this relates to the scope of this PR.

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 1]
```diff
@@ -1224,6 +1224,42 @@ private function is_setup_intent_success_creation_redirection() {
...
+	/**
+	 * Adds a token to current user from a setup intent id.
+	 *
+	 * @param string  $setup_intent_id ID of the setup intent.
+	 * @param WP_User $user            User to add token to.
+	 *
+	 * @return WC_Payment_Token_CC|WC_Payment_Token_WCPay_SEPA The added token.
+	 *
+	 * @since x.x.x
+	 * @version x.x.x
```
Comment (superdav42) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:1236]: Probably we should remove these tags or is there a process to update them during release?

Comment (ricardo) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:1236]: There's a step in woorelease which updates these.

**Review by diegocurbelo — APPROVED** [review]
> That was because the cache wasn't being cleared. It should be fixed now.

Tests perfectly now!... thanks @ricardo 🚢 🚢
