### PR TITLE
fix: fatal error with Elementor+WooFunnels

### LINKED ISSUE #2019: Fatal error in `WC_REST_Stripe_Settings_Controller::__construct()`
**Describe the bug**
Reported in the forums:

```
WC_REST_Stripe_Settings_Controller::__construct() must be an instance of WC_Stripe_Payment_Gateway, null given
```

https://wordpress.org/support/topic/version-5-6-critical-error-with-elementor/

**To Reproduce**
Seems to be possibly related to Elementor.
Error is happening when editing pages in Elementor.

**UPDATE:** this is an issue when using "WooFunnels Funnel Builder" together with Elementor, not an issue with Elementor itself.

**Expected behavior**
No fatal error.

### PR DESCRIPTION
**Pull request by frosso**
# Changes proposed in this Pull Request:

It looks like WooFunnels resets the gateways when editing Elementor pages, like so:
```
		add_action( 'wfacp_after_checkout_page_found', function () {
			add_filter( 'woocommerce_payment_gateways', [ __CLASS__, 'unset_gateways' ], 1000 );
		} );


...

	final public static function unset_gateways( $gateways ) {
		if ( WFACP_Common::is_theme_builder() ) {
			foreach ( $gateways as $key => $gateway ) {
				if ( 'WC_Gateway_COD' != $gateway ) {
					unset( $gateways[ $key ] );
				}
			}
		}

		return $gateways;
	}
```

This is obviously problematic, because we do `WC()->payment_gateways()->payment_gateways()[ WC_Gateway_Stripe::ID ]` to get the Stripe gateway.
And when we pass it to `WC_REST_Stripe_Settings_Controller` on init, the plugin might create an error.

For this reason, I created a `get_main_stripe_gateway()` method so that only one instance of the Stripe gateway is always present.
And it can be consumed by our plugin.

# Testing instructions
I haven't been able to reproduce this error yet, but all reports include the following plugins installed alongside Elementor and Elementor Pro:
```
WooFunnels Funnel Builder
WooFunnels Funnel Builder Pro
```

I ensured the settings page with the `_wcstripe_feature_upe_settings` flag enabled is still working like before.

### CODE REVIEW

File: woocommerce-gateway-stripe.php [hunk 1]
```diff
@@ -593,16 +599,44 @@ public function register_routes() {
...
+
+				return $this->stripe_gateway;
+			}
+
+			/**
+			 * Use only in tests.
+			 * Running this will not unregister the hooks set by the gateway class.
+			 */
+			// phpcs:ignore WordPress.NamingConventions.ValidFunctionName.MethodNameInvalid
+			public function _TESTS_ONLY__unset_main_stripe_gateway() {
```
Comment (frosso) [inline woocommerce-gateway-stripe.php]: I needed this so that tests wouldn't fail in `tests/phpunit/test-wc-stripe.php` - otherwise we would always have the incorrect instance of the Stripe gateway saved.

File: woocommerce-gateway-stripe.php [hunk 2]
```diff
@@ -593,16 +599,44 @@ public function register_routes() {
...
 				}
 			}
+
+			/**
+			 * Returns the main Stripe payment gateway class instance.
+			 *
+			 * @return WC_Stripe_Payment_Gateway
+			 */
+			public function get_main_stripe_gateway() {
+				if ( ! is_null( $this->stripe_gateway ) ) {
```
Comment (superdav42) [inline woocommerce-gateway-stripe.php:621]: I don't think this one property is enough to:
>  only one instance of the Stripe gateway is always present.

The core code will construct it's own instance of the gateway which is why we were using `WC()->payment_gateways()->payment_gateways()[ WC_Gateway_Stripe::ID ]`
We should try this core method first and if the gateway is not set there create our own instance.

As the code is multiple instances could exist registering duplicate filters in their constructor.

File: woocommerce-gateway-stripe.php [hunk 3]
```diff
@@ -593,16 +599,44 @@ public function register_routes() {
...
 					$stripe_account_keys_controller->register_routes();
 				}
 			}
+
+			/**
+			 * Returns the main Stripe payment gateway class instance.
+			 *
+			 * @return WC_Stripe_Payment_Gateway
+			 */
+			public function get_main_stripe_gateway() {
```
Comment (superdav42) [inline woocommerce-gateway-stripe.php:620]: Probably be convenient to make this static. At least other parts or the code are using `WC()->payment_gateways()->payment_gateways()[ WC_Gateway_Stripe::ID ]` if this was static they could use this method too.

**Review by superdav42 — CHANGES_REQUESTED** [review]
I think we need to make changes. It's probably good enough for this but there could be other problems with the possibility of multiple gateway instances being created.

File: woocommerce-gateway-stripe.php (hunk 1 above)
Comment (superdav42) [reply woocommerce-gateway-stripe.php]: I think there's a better hack we could use with https://www.php.net/manual/en/closure.bind.php I'll experiment.

File: woocommerce-gateway-stripe.php (hunk 2 above)
Comment (frosso) [reply woocommerce-gateway-stripe.php:621]: The core code won't construct its own instance, because in the `woocommerce_payment_gateways` filter we're passing the instance from the `get_main_stripe_gateway()` method.
When `woocommerce_payment_gateways` is called in core, the code already checks if it's a class or if it's a string representing a class: https://github.com/woocommerce/woocommerce/blob/0c44ab857a9b041727ab8c16fd182ee9b700818e/includes/class-wc-payment-gateways.php#L95-L113

Let me know if I missed something there!

File: woocommerce-gateway-stripe.php (hunk 3 above)
Comment (frosso) [reply woocommerce-gateway-stripe.php:620]: It's still possible to get this via a static method, like I did in `includes/migrations/class-allowed-payment-request-button-types-update.php`:
```
woocommerce_gateway_stripe()->get_main_stripe_gateway()
```

The problem with static methods is that they're slightly harder to test for.

File: woocommerce-gateway-stripe.php (hunk 2 above)
Comment (superdav42) [reply woocommerce-gateway-stripe.php:621]: My bad. I missed that you are passing an object [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2023/files#diff-e1e5e9b442c2b5d4105edbdc3787651333c1923dd623677025f72d25796900d6R380) now.

File: woocommerce-gateway-stripe.php [hunk 4]
```diff
@@ -593,16 +599,44 @@ public function register_routes() {
...
+			}
+
+			/**
+			 * Use only in tests.
+			 * Running this will not unregister the hooks set by the gateway class.
+			 */
+			// phpcs:ignore WordPress.NamingConventions.ValidFunctionName.MethodNameInvalid
+			public function _TESTS_ONLY__unset_main_stripe_gateway() {
+				$this->stripe_gateway = null;
+			}
```
Comment (superdav42) [inline woocommerce-gateway-stripe.php]:
```suggestion
```
Remove this ugly hack.

File: tests/phpunit/test-wc-stripe.php [hunk 5]
```diff
@@ -109,6 +109,7 @@ function() {
 	}
 
 	private function reloadPaymentGateways() {
+		woocommerce_gateway_stripe()->_TESTS_ONLY__unset_main_stripe_gateway();
```
Comment (superdav42) [inline tests/phpunit/test-wc-stripe.php]:
```suggestion
		Closure::bind(
			function () {
				$this->stripe_gateway = null;
			},
			woocommerce_gateway_stripe(),
			WC_Stripe::class
		)();
```
Use this more beautiful hack.
Closure::bind will redefine the scope to WC_Stripe::class and set $this to woocommerce_gateway_stripe() granting access to protected and private properties.

**Review by superdav42 — APPROVED** [review]
Get rid of ugly hack and it's g2g.

**Review by superdav42 — APPROVED** [review]
Get rid of ugly hack and it's g2g.

File: woocommerce-gateway-stripe.php (hunk 4 above)
Comment (frosso) [reply woocommerce-gateway-stripe.php]: Done in 9e6635b3

File: tests/phpunit/test-wc-stripe.php (hunk 5 above)
Comment (frosso) [reply tests/phpunit/test-wc-stripe.php]: Thanks for the suggestion, done in 9e6635b3
