### PR TITLE
PR: SCA: Add PaymentIntent confirmations as a step in the checkout

### LINKED ISSUE #840: SCA: Mark orders as failed after unsuccessful authorisation
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/826 changed the way payment intents are generated and handled, but does not introduce a handler for failed SCA authorisations.

### Steps to reproduce

0. Disable webhooks
1. Add items to the cart
2. Try using a card, which requires 3DS
3. Decline the payment in the Stripe SCA modal

### Expected result

The order status changes to "Failed" and a note is added about the failed payment.

### Actual result

The order status remains "Pending Payment" and there are no notes.

### Suggestion

If webhooks are properly set up, `WC_Stripe_Webhook_Handler` will properly mark the order as failed. Use the logic from `process_payment_intent_success` (and rename it, as it also handles failed payments) in combination with a custom-triggered `wc-ajax` endpoint.

Props @allendav for discovering this issue!

### PR DESCRIPTION
**Pull request by RadoslavGeorgiev**
Fixes #840 .

#### Changes proposed in this Pull Request:

The original purpose of this PR was to mark orders as failed when an SCA authorization fails. My initial plan was to fire an AJAX call from JS to the server in order to verify that the intent failed, and set the order status to "Payment Failed".

This status was already being updated by webhooks, but only when they are set up, which is not the case for most of our merchants. While considering situations with disabled webhooks and trying to setup the proper AJAX calls, I came to a couple of realizations:

1. The code in the current `sca/master` branch might interfere with extensions, which use the `woocommerce_payment_successful_result` filter, and there seem to be a lot of those: https://github.com/search?q=woocommerce_payment_successful_result&type=Code
2. It is possible that in certain flows merchants would never reach the "Order Received" page, which would prevent the PI/order status from being checked.

In order to deal with those issues while also handling the failed SCA auth scenario, I implemented the following changes in this PR:

1. `WC_Gateway_Stripe::process_payment` no longer returns a hash on the checkout page. Instead, it returns an array containing `result` (`success`), `redirect` (standard Order Received Page), and most importantly an `intent_secret` property, which contains the PI secret. This property is later used within `modify_successful_payment_result` to generate the hash. Since the filter is added with a high priority (99999), it should be able to make use of `redirect` URLs, modified by other extensions.
2. Instead of including the URL of the "Order Received" page in the redirect hash, and redirecting to it on success, there is a new intermediate URL/step.
The new URL looks like this: `https://domain.com/?wc-ajax=wc_stripe_verify_intent&order=1229&nonce=a5fb595c7e&redirect_to=http%3A%2F%2Fdomain.com%2Fcheckout%2Forder-received%2F1229%2F%3Fkey%3Dwc_order_MRBXtOqgSdI93
    - `wc_stripe_verify_intent` is the name of the hook, handled in the new `WC_Stripe_Intent_Controller`. This class is needed because `WC_Gateway_Stripe` is not initialized early enough.
    - The order ID and nonce are used in order to locate the order to check. Based on the order meta, the ID of the PaymentIntent is already accessible and its status can already be checked (`WC_Gateway_Stripe::verify_intent_after_checkout`).
    - `redirect_to` includes the URL, generated during checkout, including all filters applied to `woocommerce_payment_successful_result`.

Our JS will redirect to this new URL in order for the server to check the order/payment status, and only then will the client be redirected to the final Order Received screen.

#### Testing instructions

There is no single result to expect from those changes, so testing flows might differ, but it would be best to check orders' notes after a combination of the following scenarios:

- Start on the checkout page (no order exists yet) __or__ to submit the checkout form, and navigate to the "My Orders" page once the PaymentIntent modal gets shown. This way you can test the "Pay for Order" screen.
- Accept __or__ Reject the SCA authentication.
- Do all of the above with webhooks enabled __or__ disabled.

In all of those cases you should see the proper order notes and status changes appear in the admin.

Note: PI checks are also performed on the "Order Received" screen through this line:

```php
add_filter( 'woocommerce_thankyou_order_id', array( $this, 'thankyou_order_id' ), 100 );
```

Make sure to test the process both when the filter is enabled and disabled.

Question: After all of those redirects, should we keep this filter at all?

### CODE REVIEW

**Comment by allendav** [comment]
@jrodger @DanReyLop - please review for @RadoslavGeorgiev today or tomorrow - thank you

File: assets/js/stripe.js [hunk 1]
```diff
@@ -818,48 +812,65 @@ jQuery( function( $ ) {
...
 						throw response.error;
 					}
 
-					if ( 'succeeded' === response.paymentIntent.status ) {
-						window.location = successRedirectURL;
+					if ( 'succeeded' !== response.paymentIntent.status ) {
+						return;
 					}
+
+					window.location = redirectURL;
```
Comment (DanReyLop) [inline assets/js/stripe.js]: Have you encountered any problem when doing a `window.location` redirect to an AJAX endpoint?  Would it still work if the `&is_ajax` suffix was always added? I'm thinking that redirecting to an AJAX endpoint is a hack and may cause some problems, but if it doesn't, I'm fine with it.

File: includes/class-wc-gateway-stripe.php [hunk 2]
```diff
@@ -1136,22 +1148,111 @@ public function get_saved_payment_method_option_html( $token ) {
...
+
+	/**
+	 * Executed between the "Checkout" and "Thank you" pages, this
+	 * method updates orders based on the status of associated PaymentIntents.
+	 *
+	 * @since 4.2.0
+	 * @param WC_Order $order The order which is in a transitional state.
+	 */
+	public function verify_intent_after_checkout( $order ) {
+		if ( 'pending' !== $order->get_status() && 'failed' !== $order->get_status() ) {
```
Comment (DanReyLop) [inline includes/class-wc-gateway-stripe.php]: What's the point of executing the rest of this function if the order is in `failed` status? Do you think it's possible that the intent succeeds after the order was somehow marked as failed?

File: includes/class-wc-gateway-stripe.php [hunk 3]
```diff
@@ -1136,22 +1148,111 @@ public function get_saved_payment_method_option_html( $token ) {
...
+		$intent = $this->get_intent_from_order( $order );
+		if ( ! $intent ) {
+			// No intent, redirect to the order received page for further actions.
+			return;
+		}
+
+		if ( 'succeeded' === $intent->status ) {
+			// Proceed with the payment completion.
+			$this->process_response( end( $intent->charges->data ), $order );
+		} else {
```
Comment (DanReyLop) [inline includes/class-wc-gateway-stripe.php]: Could the intent be still in a `processing` status at this point? Like, not succeded, but not failed yet? Is there any possibility that the SCA flow will complete "asynchronously" and so the site **has to** rely on Webhooks? If that's a possibility, I would reconsider this logic (marking the order immediately as `failed`).

File: includes/class-wc-stripe-intent-controller.php [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+
+			if ( ! isset( $_GET['is_ajax'] ) ) {
+				$redirect_url = isset( $_GET['redirect_to'] ) // wpcs: csrf ok.
+					? esc_url_raw( wp_unslash( $_GET['redirect_to'] ) ) // wpcs: csrf ok.
+					: $gateway->get_return_url( $order );
+
+				wp_safe_redirect( $redirect_url );
+			}
+		} catch ( WC_Stripe_Exception $e ) {
+			wp_die( esc_html( $e->getMessage() ) );
```
Comment (DanReyLop) [inline includes/class-wc-stripe-intent-controller.php]: This is not a good UX. This should redirect to a proper WooCommerce error page (if it's not AJAX) and return a plain error if it's AJAX so the client can show a proper error message. I'm fine creating a new issue to address this, this PR is already quite big.

File: includes/class-wc-stripe-webhook-handler.php [hunk 5]
```diff
@@ -600,12 +600,12 @@ public function process_payment_intent_success( $notification ) {
...
 		$order_id = WC_Stripe_Helper::is_wc_lt( '3.0' ) ? $order->id : $order->get_id();
 		if ( 'payment_intent.succeeded' === $notification->type || 'payment_intent.amount_capturable_updated' === $notification->type ) {
-			if ( 'processing' === $order->get_status() || 'completed' === $order->get_status() ) {
+			if ( 'pending' !== $order->get_status() && 'failed' !== $order->get_status() ) {
 				return;
 			}
 
 			$charge = end( $intent->charges->data );
-			WC_Stripe_Logger::log( "Stripe PaymentIntent $intent->id succeeded for order $order_id" );
+			WC_Stripe_Logger::log( "Stripe PaymentIntent $intent->id succeeded for order $order_id from" );
```
Comment (DanReyLop) [inline includes/class-wc-stripe-webhook-handler.php]: I think this `from` shouldn't be here.
```suggestion
			WC_Stripe_Logger::log( "Stripe PaymentIntent $intent->id succeeded for order $order_id" );
```

**Comment by DanReyLop** [comment]
I've updated the PR with `sca/master` (there was a trivial merge conflict).

> Question: After all of those redirects, should we keep this filter at all?

I'd say that the redirect is more robust. Now the flow is `Checkout -> Intermediate page -> Thank you`, so if the user arrived to the Thank You page, it means that the `Intermediate page` has been executed too. No need to keep the old filter, unless you can think of an use case where it may still be needed.

File: includes/class-wc-gateway-stripe.php (hunk 2 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: Yes. If a customer submits the checkout form and gets to the SCA verification step, but decline, they remain on the checkout page (with an error message of course.

If they try to submit again and this time accept the SCA verification, the same order will be marked as paid/processing, instead of creating a new one.

Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: The same applies if they go to the "Pay for Order" screen of an order with a failed payment.

Comment (DanReyLop) [reply includes/class-wc-gateway-stripe.php]: Cool, thanks for the explanation 👍

File: includes/class-wc-gateway-stripe.php (hunk 3 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: I am sure I discussed the reliability on webhooks with @thorsten-stripe at one point and we don't _have to_ rely on them. If that was the case, even though it would have been much more complicated for our merchants, it would've made this whole PR redundant.

Additionally if that was the case, during my testing I should've seen a failed and then completed order at one point, which I didn't.

File: includes/class-wc-stripe-webhook-handler.php (hunk 5 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-stripe-webhook-handler.php]: The text included some more details at one point, and I thought I removed them completely, but obviously I didn't see a small bit of it. 👍

File: includes/class-wc-gateway-stripe.php (hunk 3 above)
Comment (thorsten-stripe) [reply includes/class-wc-gateway-stripe.php]: This holds true for card payments, however in the future we will unify non-card payments in the PaymentIntent API, meaning then the PI could be in processing state for an unknown amount of time.

**Comment by RadoslavGeorgiev** [comment]
> if the user arrived to the Thank You page, it means that the Intermediate page has been executed too

Reading this, I found out what I was doing wrong. If the payment is not completed, users *could* go to the "Order Details" page (which is why I switched to `woocommerce_account_view-order_endpoint` in 
af95662), but they would not land on the "Thank You" one. So even if this is a very rare scenario, I think it's worth to keep the ~filter~ action.

File: includes/class-wc-gateway-stripe.php (hunk 3 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: Thank you for updating us on this @thorsten-stripe.

To avoid marking pending orders as failed, in 97aa482 I changed the behavior. Now we will only mark the order as failed when the PI status is `requires_payment_method`.

Note: This PR/branch does not affect any alternative payment methods at the moment, but it is likely for this code to be reused when PIs are implemented for non-card payments, which is why I added the change.

File: includes/class-wc-stripe-intent-controller.php (hunk 4 above)
Comment (RadoslavGeorgiev) [reply includes/class-wc-stripe-intent-controller.php]: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/858 created.

My thinking at the moment was that only malformed client requests should be able to cause issues, but you are right: We need to handle those cases in a better way.

File: includes/class-wc-gateway-stripe.php (hunk 3 above)
Comment (DanReyLop) [reply includes/class-wc-gateway-stripe.php]: > To avoid marking pending orders as failed, in 97aa482 I changed the behavior. Now we will only mark the order as failed when the PI status is requires_payment_method.

I see that in the `failed_sca_auth` function, a similar check is made, which is now redundant:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/5796dad8d21d70210bfd9ad525b6be04ec4806ce/includes/class-wc-gateway-stripe.php#L1379

Comment (RadoslavGeorgiev) [reply includes/class-wc-gateway-stripe.php]: Good point. I removed the second line. `requires_action` should also not appear at that point, so the line really did become completely redundant.

**Comment by DanReyLop** [comment]
Code looks good.

I tested all these and they all work as expected:
- Accepted SCA, webhooks enabled.
- Rejected SCA, webhooks enabled. Later I re-tried SCA (accepted it) in the "My Orders" page.
- Accepted SCA, webhooks disabled.
- Rejected SCA, webhooks disabled. Later I re-tried SCA (accepted it) in the "My Orders" page.

The only issue I found is that, when a Intent succeeds and webhooks are enabled, the order notes are duplicated:
Screenshot 2019-05-02 at 16 47 50

**Comment by RadoslavGeorgiev** [comment]
@DanReyLop I added a locking mechanism in ef07d8f51cb85005423d4f2ae56cfdf90b38cd34.

There are a few reasons for the problem:
1. `WC_Gateway_Stripe::verify_intent_after_checkout` waits for the intent to be retrieved from the Stripe API while the webhook is already being processed. Checking the status later, ex. after retrieving the intent, didn't work though. Probably because the order data has already been loaded into memory much earlier.
2. Reloading the order is a bit tricky. I tried this bit of code, but even that was not sufficient:
    ```php
    clean_post_cache( $order->get_id() );
    $order->get_data_store()->read( $order );
    ```
3. Using transients seems to do the job, because even if a transient is not loaded into the cache, WP will try to retrieve it from `wp_options` though an additional database query.

I ran many tests with this configuration, and it seems to work.
