### PR TITLE
Split upe w' deferred intent - don't display APMs on classic checkout while auth and capture is enabled

### LINKED ISSUE #2923: Split UPE w' Deferred Intent - APMs shown on classic checkout with auth and capture enabled
**Describe the bug**
With Auth and Capture enabled, APMs are being shown on the classic checkout. With auth and capture enabled, only card payments are allowed. 

| Screenshot 2024-02-20 at 11 35 12 am | Screenshot 2024-02-20 at 11 35 42 am |
|--------|--------|

**To Reproduce**

1. Checkout the `add/deferred-intent` branch
2. Under **WooCommerce > Settings > General**, set the store currency to EUR
3. Under the Stripe Payment methods tab, enable all available APMs. 
4. Under the Stripe Settings tab, enable the Updated Checkout Experience and the _'authorization on checkout, and capture later'_ setting.
6. As a shopper, add a product to your cart and go to the classic checkout. 
7. Notice all APMs are displayed. 

Screenshot 2024-02-20 at 11 42 21 am

**Expected behavior**
Only cards should be available under this situation.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #2923 

## Changes proposed in this Pull Request:

When you enable authorize and capture in the Stripe plugin settings, a modal pops up to explain that only card payments will be available while using auth and capture. 

This works as expected on the block checkout, however it doesn't on the classic checkout. All APMS were being shown even though auth and capture were enabled.

| Screenshot 2024-02-20 at 11 35 12 am | Screenshot 2024-02-20 at 11 42 21 am |
|--------|--------|

This PR fixes that. 

## Testing instructions

1. Under **WooCommerce > Settings > General**, set the store currency to EUR
2. Under the Stripe Payment methods tab, enable all available APMs. 
3. Under the Stripe Settings tab, enable the Updated Checkout Experience and the _'authorization on checkout, and capture later'_ setting.
6. As a shopper, add a product to your cart and go to the classic checkout. 
   - On the `add/deferred-intent` branch notice all APMs are displayed.
   - On the this branch only cards are shown. 
7. Turn off authorize and capture and all payment methods should be now shown again. 

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-method.php [hunk 1]
```diff
@@ -218,6 +218,11 @@ public function is_enabled_at_checkout( $order_id = null ) {
 			return $this->is_reusable();
 		}
 
+		// Note: this $this->is_automatic_capture_enabled() call will fall through to the UPE gateway class.
```
Comment (mattallan) [inline includes/payment-methods/class-wc-stripe-upe-payment-method.php]:
```suggestion
		// Note: this $this->is_automatic_capture_enabled() call will be handled by $this->__call() and fall through to the UPE gateway class.
```

I had a moment where I forgot about the __call() function and was confused how it would call the UPE gateway when it extends the `WC_Payment_Gateway` class 🙈 I made a small suggestion to avoid any confusion to my future self and others

**Review by mattallan — APPROVED** [review]
Thanks @james-allan for the PR. The code changes look good to me and tests well. I just made a small suggestion on the inline comment to clarify how the UPE gateway function is called.

- With Authorize and Capture enabled :+1:

| `develop` | `fix/2923` |
|--------|--------|
|image|image|

- With capture immediately :+1:

image

File: includes/payment-methods/class-wc-stripe-upe-payment-method.php (hunk 1 above)
Comment (james-allan) [reply includes/payment-methods/class-wc-stripe-upe-payment-method.php]: Good idea :)
