### PR TITLE
Fix Payment Request button for Puerto Rico and handle error for unsupported countries

### LINKED ISSUE #1203: When non-supported country is chosen and Payment Request button enabled - variable product functionality breaks
**Describe the bug**

When the country for Store Address is something other than the supported countries for Payment Request buttons - set at **WooCommerce > Settings > General > Store Address** - the variable product functionality breaks and a JS console warning is logged.

Original issue:

-------------------------

WooCommerce considers Puerto Rico as a country* but Stripe designates it as a State of the United States. This means when a WooCommerce site is using the Stripe payment gateway extension and the Payment Request buttons, "we" report this to Stripe via `wc_stripe_supported_countries` as a country `PR` - Stripe then looks on their list and doesn't find it, so it rejects the Payment Request button creation. 

```
Uncaught IntegrationError: Invalid value for paymentRequest(): country should be one of the following strings: AE, AT, AU, BE, BR, CA, CH, CZ, DE, DK, EE, ES, FI, FR, GB, GR, HK, IE, IN, IT, JP, LT, LU, LV, MX, MY, NL, NO, NZ, PH, PL, PT, RO, SE, SG, SI, SK, US. You specified: PR.
    at new t (https://js.stripe.com/v3/?ver=3.0:1:10981)
    at Pt (https://js.stripe.com/v3/?ver=3.0:1:19535)
    at Ot (https://js.stripe.com/v3/?ver=3.0:1:19606)
    at new t (https://js.stripe.com/v3/?ver=3.0:1:77203)
    at ba (https://js.stripe.com/v3/?ver=3.0:1:104901)
    at e.<anonymous> (https://js.stripe.com/v3/?ver=3.0:1:163370)
    at e.paymentRequest (https://js.stripe.com/v3/?ver=3.0:1:27321)
    at Object.startPaymentRequest ([...]wp-content/plugins/woocommerce-gateway-stripe/assets/js/stripe-payment-request.min.js?ver=4.3.3:1:5152)
    at Object.init ([...]wp-content/plugins/woocommerce-gateway-stripe/assets/js/stripe-payment-request.min.js?ver=4.3.3:1:8373)
    at HTMLDocument.<anonymous> ([...]/wp-content/plugins/woocommerce-gateway-stripe/assets/js/stripe-payment-request.min.js?ver=4.3.3:1:8420)
```

What also happens at this point is, I think, JavaScript functionality is disabled so variable product selection doesn't work as expected. Both dropdowns work but the Ajax request isn't used to check stock and variation selection. The `Clear` button doesn't work.

Disabling the Payment Request buttons from the Stripe payment gateway settings returns the functionality. 

* https://github.com/woocommerce/woocommerce/commit/b9a02ba98cd30371590f07c811bedb8767a97399 
* https://github.com/woocommerce/woocommerce/pull/22468

Support for `PR` in the Payment Request button was added to Stripe via #845 

I'm unsure how useful this is but since @DanReyLop mentioned having to create some custom code for other scenarios, I looked for similar and found this - https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/693

> Oh, something similar happened to our integration with USPS. In that case, an address with country: PR was rejected as invalid, but an address with country: US, state: PR was accepted. We had to write a bit of code to transform those Puerto Rico, Guam, Virgin Islands, etc addresses. We'll probably need to do something similar for Stripe. 

Semi-related - 53-gh-woocommerce/woocommerce-shipping-usps

**Context**

forum thread prompting this - https://wordpress.org/support/topic/uncaught-integrationerror-invalid-value-for-paymentrequest-country-should-be/#post-12826393

Stripe.com docs link - Puerto Rico is classed as a state but no other unincorporated territory is treated as such, others aren't supported - https://support.stripe.com/questions/stripe-availability-for-outlying-territories-of-supported-countries

Internal Slack - p1589366017120800-slack-C9976E5MJ

**To Reproduce**
1. Set base country as Puerto Rico
2. Enable Payment Request buttons via Stripe payment gateway settings
3. Use Safari or another Payment Request button supporting browser like Chrome or Edge to load a variable product page
4. Notice no Payment Request button and variation selection doesn't reload the selections
5. Check browser console for error
6. Uncheck Payment Request button setting and resave Stripe Payment Request button settings
7. Reload product page and see that variation selection is as expected

**Expected behavior**

As Puerto Rico is supported by Stripe.com, the extension needs to support all available APMs as expected.

**Screenshots**

Gif - https://d.pr/i/DbHiAj

**Environment (please complete the following information):**
 - WordPress 5.4.1
 - WooCommerce 4.1.0
 - Stripe 4.3.3
 - Browser [e.g. chrome, safari] and Version Edge 84.0.508.0, Version 13.1 (15609.1.20.111.8) 
 - Any other plugins installed - Jetpack and Akismet

<details>
`
### WordPress Environment ###

WordPress address (URL): [redacted]
Site address (URL): [redacted]
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.18
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.70.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.22-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: wp_
Total Database Size: 2.56MB
Database Data Size: 1.12MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 40
customize_changeset: 1
page: 9
post: 2
product: 30
product_variation: 7
revision: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.5
Jetpack by WordPress.com: by Automattic – 8.5
WooCommerce Stripe Gateway: by WooCommerce – 4.3.3 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce: by Automattic – 4.1.0

### Inactive Plugins (2) ###

AMP: by AMP Project Contributors – 1.5.3
Gutenberg: by Gutenberg Team – 8.0.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2020-05-11 06:38:40 +0000
Newest: 2020-05-12 07:33:07 +0000

Pending: 1
Oldest: 2020-05-18 05:54:02 +0000
Newest: 2020-05-18 05:54:02 +0000

`
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by ricardo**
Issue: #1203.
Fixes #1203.

# Changes proposed in this Pull Request:

- Wrap the stripe payment request in a try...catch, so we can display a better error message for unsupported countries and make so that it doesn't break other JavaScript from the product page as reported in the above issue. (I was able to replicate everything, except for the part where it breaks the "Clear" functionality from a variable products page - I guess something fixed that before this PR).
- Adapt an existing method to display an error message in the UI, and fix an existing issue where it was displaying the error message 3 times in the product page. Edit: We later decided not to display an error message for unsupported countries, but the `displayErrorMessage` function was kept refactored and fixed.
- Adapt the payment request for Puerto Rico, which is the [only US territory that's supported by Stripe](https://support.stripe.com/questions/stripe-availability-for-outlying-territories-of-supported-countries). The merchant's country must be set to "US" in order for it to work.

# Testing instructions

There are two different scenarios where this fix should be tested:

## Puerto Rico

1. Set base country as Puerto Rico.
2. Enable Payment Request buttons via Stripe payment gateway settings.
3. Use Safari or another Payment Request button supporting browser like Chrome to load product page.
4. Notice the Payment Request button works as expected and no errors are thrown.

puerto-rico

## Non-supported countries

1. Set base country as China.
2. Enable Payment Request buttons via Stripe payment gateway settings.
3. Use Safari or another Payment Request button supporting browser like Chrome to load product page.
4. Notice the console error. The error is logged for troubleshooting, but shouldn't break anything.
5. It should not render a Payment Request button.

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: assets/js/stripe-payment-request.js [hunk 1]
```diff
@@ -147,37 +147,47 @@ jQuery( function( $ ) {
...
-		abortPayment: function( payment, message ) {
-			payment.complete( 'fail' );
-
+		displayErrorMessage: function( message ) {
 			$( '.woocommerce-error' ).remove();
 
 			if ( wc_stripe_payment_request_params.is_product_page ) {
-				var element = $( '.product' );
-
+				var element = $( '.product' ).first();
```
Comment (dechov) [inline assets/js/stripe-payment-request.js:159]: Nice fix for duplicate error messages showing up in some cases.

File: assets/js/stripe-payment-request.js [hunk 2]
```diff
@@ -147,37 +147,47 @@ jQuery( function( $ ) {
...
 				element.before( message );
 
 				$( 'html, body' ).animate({
 					scrollTop: element.prev( '.woocommerce-error' ).offset().top
 				}, 600 );
 			} else {
 				var $form = $( '.shop_table.cart' ).closest( 'form' );
+				// Need to check if element exists, otherwise an error is thrown on checkout.
```
Comment (dechov) [inline assets/js/stripe-payment-request.js:167]: 👍 – did you run into this / is it easily reproducible?

**Review by dechov — COMMENTED** [review]
I've reproduced the issue both with Puerto Rico and with unsupported countries (including the broken variations UI) & validated the fixes for both cases using the provided instructions 🎉 

I must not have thought it through when we discussed it, since I'm now pretty uneasy about the error notice showing up for the customer. The button not showing up on page load isn't necessary a _problem_ from the customer's perspective, and I think the notice would cause unnecessary concern. (The `displayErrorMessage` refactor looks good to me either way.) What do you think?

File: assets/js/stripe-payment-request.js (hunk 2 above)
Comment (ricardo) [reply assets/js/stripe-payment-request.js:167]: Yes, I ran into this. An error is thrown at checkout because the element doesn't exist. 

If I remember it correctly, the function was made to work only on the product page and cart page, but the startPayment is triggered on the checkout page (maybe something to be improved), and would call this function, causing the error.

**Comment by ricardo** [comment]
@dechov 

> I must not have thought it through when we discussed it, since I'm now pretty uneasy about the error notice showing up for the customer. The button not showing up on page load isn't necessary a problem from the customer's perspective, and I think the notice would cause unnecessary concern. (The displayErrorMessage refactor looks good to me either way.) What do you think?

You're probably right! But I believe we should have a better way to let the customer know that the payment request button won't work, and why. I don't know of a good way to handle this right now.

I can take out this notice and keep the `displayErrorMessage` refactor.

**Comment by ricardo** [comment]
@dechov

I've removed the error message for unsupported countries.

Let me know if there's anything else we might wanna change.

**Review by dechov — APPROVED** [review]
Tested through cases once again quickly. Code LGTM and works well. Can fix changelog conflict and merge 🚀
