### PR TITLE
Move Alipay and Multibanco inside Stripe settings when UPE is disabled

### LINKED ISSUE #2852: Move Alipay and Multibanco inside Stripe settings
In PR #2839 all the Stripe methods were moved inside the Stripe settings page and the interface was updated as a common settings page for both UPE and non-UPE. However, for non-UPE scenario, Stripe Alipay and Stripe Multibanco was not moved and they are still listed on the payment settings page. 

#### Steps to reproduce the issue
- Go to Stripe settings page and disable UPE.
- You will find that Alipay and Multibanco are not listed in the Stripe settings page.
- Go to WooCommerce > Settings > Payments. You will find the methods listed here.

#### Expected behavior
- Alipay and Multibanco should be listed in the Stripe settings page with the other Stripe methods.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #2852 

## Changes proposed in this Pull Request:
- Alipay and Multibanco are also moved inside the Stripe settings page for UPE disabled state.

**Before**
ali-multi before

**After**
ali-multi after

## Testing instructions
- Go to the Stripe settings page and disable UPE.
- Go to the `Payment methods` tab on the Stripe settings page. Alipay and Multibanco should be listed here.
- Enable/Disable these 2 methods and make sure they are available on the checkout page as per settings.

### CODE REVIEW

File: woocommerce-gateway-stripe.php [hunk 1]
```diff
@@ -371,17 +371,19 @@ public function plugin_row_meta( $links, $file ) {
...
 				$methods[] = $this->get_main_stripe_gateway();
 
-				// These payment gateways will always be visible, regardless if UPE is enabled or disabled:
-				$methods[] = WC_Gateway_Stripe_Alipay::class;
-				$methods[] = WC_Gateway_Stripe_Multibanco::class;
+				// These payment gateways will be visible in the main settings page, if UPE enabled.
+				if ( WC_Stripe_Feature_Flags::is_upe_checkout_enabled() ) {
+					$methods[] = WC_Gateway_Stripe_Alipay::class;
+					$methods[] = WC_Gateway_Stripe_Multibanco::class;
+				}
```
Comment (Mayisha) [inline woocommerce-gateway-stripe.php:386]: In this PR, Alipay and Multibanco are moved inside the Stripe settings page only for UPE disabled state.

Currently in `develop` when UPE is enabled, these 2 methods are not part of UPE. And they are rendered individually on the checkout page. 




I will handle them in a separate PR for UPE enabled state.

Comment (james-allan) [reply woocommerce-gateway-stripe.php:386]: I'm not sure if this is related to this but if you have UPE enabled, Alipay and Multibanco settings aren't shown anywhere - either in the Payments table or the Stripe Payment methods list.

| Screenshot 2024-01-31 at 1 39 22 pm | Screenshot 2024-01-31 at 1 39 00 pm |
|--------|--------|

Is this the part you mean you'll address separately?

File: includes/class-wc-stripe-helper.php [hunk 2]
```diff
@@ -419,29 +421,51 @@ public static function get_legacy_payment_method( $id ) {
...
+						$id = str_replace( 'stripe_', '', $payment_method_class::ID );
+						if ( ! in_array( $id, $payment_method_ids, true ) ) {
+							$ids[] = $id;
+						}
+
+						return $ids;
+					}
+				);
+
+				$payment_method_ids = array_merge( $payment_method_ids, $remaining_payment_method_ids );
```
Comment (james-allan) [inline includes/class-wc-stripe-helper.php]: At first this was a little tough to wrap my head around. I think I understand it now but I wonder if using a loop would make this easier to follow.

```suggestion
				foreach ( $payment_method_classes as $payment_method_class ) {
					$id = str_replace('stripe_', '', $payment_method_class::ID);

					if ( ! in_array( $id, $payment_method_ids, true ) ) {
						$payment_method_ids[] = $id;
					}
				}
```

Note you can get rid of the array merge because the loop approach is just appending each missing element to the end of the original array anyway.

**Review by james-allan — APPROVED** [review]
Changes look good. I left a clarifying question and a possible suggestion. If you intend to fix missing payment methods when UPE is enabled separately, that's all good and so approved this PR.

File: woocommerce-gateway-stripe.php (hunk 1 above)
Comment (Mayisha) [reply woocommerce-gateway-stripe.php:386]: > Is this the part you mean you'll address separately?

Not exactly this. In a separate PR I will move them inside the Stripe settings page but for now you should see them on the main payment settings page (For UPE enabled). I see them on the payment settings page -

upe enabled

Could you please check if you have these changes in your local? :eyes:  
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2853/commits/fa6f6ab382f3c7a5075d4062bcd86278bcb5802a

Comment (james-allan) [reply woocommerce-gateway-stripe.php:386]: Yep that was it. Thanks @Mayisha.

**Comment by james-allan** [comment]
The latest changes look good. My previous PR approval is still set on this PR. :)
