### PR TITLE
Fix issue in processing a 0 amount subscription.

### LINKED ISSUE #2607: $0/month Subscriptions unable to process on Stripe 7.3
1) 6243181-zen

User has the following setup:

1) Variable Subs with switching enabled

2) Switch settings:
https://d.pr/i/5t5nd5 
Full Size: https://d.pr/i/5t5nd5

Issue: When we have an active Subscription with $0/month cost (Virtual), upgrading to a paid subscription doesn't work with Stripe: (only occurs when prorating)

https://d.pr/i/q2kqvL 
Full Size: https://d.pr/i/q2kqvL

> parameter_invalid_integer - payment_method_options[card][mandate_options][amount]
This value must be greater than or equal to 1.

Able to replicate on my test site.

```
{
  "capture_method": "automatic",
  "description": "Woo Site Generator - Order 15",
  "payment_method_options": {
    "card": {
      "mandate_options": {
        "start_date": "1682753385",
        "amount_type": "fixed",
        "interval": "month",
        "interval_count": "1",
        "reference": "15",
        "supported_types": {
          "0": "india"
        },
        "amount": "0"
      }
    }
  },
  "metadata": {
    "payment_type": "recurring",
    "order_id": "15",
    "site_url": "http://localhost:8888/woogenerator/sites/wp-8559227",
    "customer_email": "xx@woocommerce.com",
    "save_payment_method": "true",
    "customer_name": "Test test"
  },
  "setup_future_usage": "off_session",
  "customer": ["cus_xx"](https://dashboard.stripe.com/test/customers/xx),
  "currency": "usd",
  "payment_method": "pm_xx",
  "amount": "2400",
  "payment_method_types": {
    "0": "card"
  }
}

```

2) 6253081-zen

Merchant's prepaid subscriptions ($0/month with a signup fee) aren't being processed.

>   Sorry, we are unable to process your payment at this time. Please retry later.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2607

If a store has any free subscription product (subscription price 0), purchasing the subscription fails. This happens for both regular, 3DS cards and 3DS cards that need a mandate. It also happens for all currencies. 
This PR fixes the main issue by avoiding setting mandate options when the subscription amount is 0. It will unblock the merchants using all other currencies which do not need a mandate but are blocked because of this error.

Stores using INR and cards that need to create a mandate will require the mandate options later if the subscription is updated to have a price (from free). This part of the fix will be implemented in [a separate PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2633).

## Changes proposed in this Pull Request:
- avoid setting mandate options when the subscription amount is 0.

## Testing instructions
- Create a subscription with 0 amount and a sign-up fee.
- As a shopper go to the shop page and purchase the subscription.
- Test with UPE enabled and disabled both.
- Test with different store currencies like USD, Euro, INR, etc.
- Test with regular card and 3DS card.

### CODE REVIEW

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 1]
```diff
@@ -592,6 +592,10 @@ public function add_subscription_information_to_intent( $request, $order, $prepa
 			$sub_amount += WC_Stripe_Helper::get_stripe_amount( $sub->get_total() );
 		}
 
+		if ( 0 === $sub_amount ) {
```
Comment (a-danae) [inline includes/compat/trait-wc-stripe-subscriptions.php:597]: (🤏) May be good to add a comment here about why we're skipping the processing below in this case? For future reference.

**Review by a-danae — APPROVED** [review]
Thanks for creating a separate PR for handling this case, @Mayisha ! 

Things look good. I tested the following scenarios:

**Non-UPE**
✅ 0 amount subscription. USD + regular card 
✅ 0 amount subscription. USD + regular card renewal
✅ 0 amount subscription. USD + 3DS card
✅ 0 amount subscription. USD + 3DS card renewal
✅ Regular subscription. USD + regular card
✅ Regular subscription. USD + regular card + renewal
✅ free trial subscription + USD + regular card
✅ free trial subscription + USD + regular card renewal
✅ 0 amount subscription. INR + Indian card
✅ 0 amount subscription. INR + Indian card renewal

**UPE**
✅ 0 amount subscription. USD + regular card
✅ 0 amount subscription. USD + regular card renewal
✅ 0 amount subscription. USD + 3DS card
✅ 0 amount subscription. USD + 3DS card renewal
✅ free trial subscription + USD + regular card
✅ free trial subscription + USD + regular card renewal
✅ 0 amount subscription. INR + Indian card
✅ 0 amount subscription. INR + Indian card renewal
