### PR TITLE
Set transaction URL for Stripe APMs

### LINKED ISSUE #3061: [APM] Charge ID on the Edit order page isn't linking to the Stripe dashboard
**Describe the bug**

When processing a payment with an APM (at least with Ali[ay and SEPA), we're not adding a link to the charge ID to go to the Stripe dashboard.

**To Reproduce**
1. Select Euro as the store currency, under Currency options at `/wp-admin/admin.php?page=wc-settings&tab=general`
2. On the Stripe settings page, enable SEPA or any other APM, at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`
3. As a shopper, add a product to the cart and proceed to the checkout page
4. Select SEPA or any other APM and place the order
5. As a merchant, go to the Edit order page for this order, at `/wp-admin/admin.php?page=wc-orders&action=edit&id=< order id >`
6. Under "Order #xyz details", notice the charge ID is displayed, but it's not linked to the Stripe dashboard
image

**Expected behavior**

We have a link to the payment intent details page on the Stripe dashboard for Cards. I'd expect APMs to also have this link.

image

Note: Let's make sure things work fine when the Legacy experience is enabled.

### PR DESCRIPTION
**Pull request by annemirasol**
Fixes #3061 

## Changes proposed in this Pull Request:
When viewing order details, we want the charge ID to link to the Stripe dashboard. We are already doing this for CCs, by [overriding get_transaction_url() inside WC_Stripe_Payment_Gateway](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/05a1284876c575da4961725f9bbd557e701e095e/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L381). We want to do this inside `WC_Stripe_UPE_Payment_Method` as well, to have the same behavior for APMs.

**BEFORE: charge ID does not link to Stripe dashboard**
Screenshot 2024-08-28 at 9 59 16 AM

**AFTER: charge ID links to Stripe dashboard**
Screenshot 2024-08-28 at 9 59 36 AM

## Testing instructions
1. Enable APMs (e.g. Alipay) as a payment method in the Stripe settings: `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`
2. As a shopper, add a product to your cart and go to checkout. Use an APM, e.g. Alipay, to pay.
3. As the merchant, go to the order details page: `wp-admin/admin.php?page=wc-orders&action=edit&id=<ORDER-ID-FROM-PREVIOUS-STEP>`
4. Under the "Order #<ID> details" header, you should see something like "AlipayPayment via Alipay (py_3Ps8zuIMUtoK6Gfh0UF2DfWd)." The charge ID should link to the Stripe dashboard payments page, e.g. `https://dashboard.stripe.com/test/payments/py_3Ps8zuIMUtoK6Gfh0UF2DfWd`
5. Test for regressions by going through checkout using a credit card, and verifying that credit card order IDs are still linked to the Stripe dashboard.

 

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-method.php [hunk 1]
```diff
@@ -661,4 +661,21 @@ public function save_payment_method_checkbox( $force_checked = false ) {
...
+	/**
+	 * Gets the transaction URL.
+	 * Overrides WC_Payment_Gateway::get_transaction_url().
+	 *
+	 * @param  WC_Order $order Order object.
+	 * @return string
+	 */
+	public function get_transaction_url( $order ) {
+		if ( $this->testmode ) {
+			$this->view_transaction_url = 'https://dashboard.stripe.com/test/payments/%s';
```
Comment (wjrosa) [inline includes/payment-methods/class-wc-stripe-upe-payment-method.php]: Since now we are repeating this string, maybe we should consider moving it to a new constant (not a blocker).

**Review by wjrosa — APPROVED** [review]
Code is good and it works as expected!
Screenshot 2024-08-28 at 14 03 04

Left a minor comment.

File: includes/payment-methods/class-wc-stripe-upe-payment-method.php (hunk 1 above)
Comment (annemirasol) [reply includes/payment-methods/class-wc-stripe-upe-payment-method.php]: Good call @wjrosa! I moved common logic to `WC_Stripe_Helper` in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3383/commits/73c440e2d0461e8a26f286cea2b035df813a7abd, and smoke-tested the changes. LMK what you think!

Comment (wjrosa) [reply includes/payment-methods/class-wc-stripe-upe-payment-method.php]: Thanks for changing it. Looks good!
