### PR TITLE
Fix: PaymentMethods of type card cannot be attached to Customers directly without 3DS due to Indian payment regulations

### LINKED ISSUE #2664: PaymentMethods of type card cannot be attached to Customers directly without 3DS due to Indian payment regulations.
**Describe the bug**
Recurring payments are not working for INR

**To Reproduce**
1. Shop location Inida, currency INR
2. Try to purchase a subscription

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**
p1682659323078299-slack-C7U3Y3VMY

6208763-zd-woothemes

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #2664 

Subscription purchases and recurring payments are not working for INR. The transaction fails with the following error-

> invalid_request_error
PaymentMethods of type card cannot be attached to Customers directly without 3DS due to Indian payment regulations. Please instead provide the PaymentMethod and Customer alongside a SetupIntent or PaymentIntent with the setup_future_usage parameter. See https://support.stripe.com/questions/guide-for-saving-cards-in-india for more details.

## Changes proposed in this Pull Request:
- The issue occurs for the attach customer request. Removed the code that calls the `attach_source` function (which then makes the API call to attach the customer) from the checkout flow (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2964/commits/1d0ed3b53fc243a0d02b56afd18fb3b6ffe9f947) and add payment method from `My Account` page flow (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2964/commits/8542f66afd0ebd4cf4b6747abac4a31984e0af40)
- Removing the request does not have any impact and does not break any flow. As in both of the flows we create an intent down the line with `setup_future_usage` which on the Stripe end attaches the payment method to the customer (even without any request sent from our end)

### How to reproduce
- Disable the `New checkout experience` (UPE)
- Connect to an Indian Stripe account. (the error can be reproduced only for the Indian Stripe accounts)
- Set store currency to INR.
- As a shopper add a subscription product to the cart and go to the checkout page.
- Try to purchase the subscription with an [India issued card](https://docs.stripe.com/india-recurring-payments?integration=paymentIntents-setupIntents#testing) (`4000003560000123`)
- You should encounter an error and payment should fail.
- If you check the logs in your Stripe dashboard you should find an error for the attach payment method request (`POST /v1/payment_methods/pm_1OwHVQSGrDfhP3zSiJ5xVeAC/attach`)

> invalid_request_error
PaymentMethods of type card cannot be attached to Customers directly without 3DS due to Indian payment regulations. Please instead provide the PaymentMethod and Customer alongside a SetupIntent or PaymentIntent with the setup_future_usage parameter. See https://support.stripe.com/questions/guide-for-saving-cards-in-india for more details.

### Test the fix
1. Disable the `New checkout experience` (UPE)
2. Connect to an Indian Stripe account.
3. Set store currency to INR.
4. As a shopper add a subscription product to the cart and go to the checkout page.
5. Try to purchase the subscription with an [India issued card](https://docs.stripe.com/india-recurring-payments?integration=paymentIntents-setupIntents#testing) (`4000003560000123`)
6. The payment should be successful.
7. Find the `_stripe_mandate_id` order meta for this order in your database and ensure that it has a value.
8. In your Stripe dashboard, find this customer and ensure that the card is attached to the customer.
9. Now enable the `New checkout experience` (UPE). Test steps 2-8 and ensure that there is no error.

### Test saving card
- Test saving a regular card (`4242424242424242`) and an India issued card (`4000003560000123`) from `My Account` page for both UPE enabled and disabled state.

### Test creating an account
1. As a new shopper add a simple product to cart. 
2. On the checkout page select create new account and save payment method checkbox.
3. Complete the purchase with an India issued card (`4000003560000123`).
4. In your Stripe dashboard, find this customer and ensure that the card is attached to the customer.
5. Test steps 1-4 with a regular card (`4242424242424242`)
6. Test steps 1-5 for both UPE enabled and disabled state. 

### Additional testing
- Test any other flow which needs attaching a payment to a customer or saving a payment method that you can think of.
- Test the flows for a non Indian Stripe account as well.

### CODE REVIEW

File: includes/class-wc-stripe-customer.php [hunk 1]
```diff
@@ -193,6 +193,34 @@ protected function generate_customer_request( $args = [] ) {
...
 
+	/**
+	 * If customer does not exist, create a new customer. Else retrieve the Stripe customer through the API to check it's existence.
+	 * Recreate the customer if it does not exist in this Stripe account.
+	 *
+	 * @return string Customer ID
+	 *
+	 * @throws WC_Stripe_Exception
+	 */
+	public function maybe_create_customer( $should_recreate_customer = false ) {
```
Comment (Mayisha) [inline includes/class-wc-stripe-customer.php]: The [attach_source](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f4fd6119a58c83c2aa26ded8f362df3b52356150/includes/class-wc-stripe-customer.php#L405) function used to [recreate a customer](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f4fd6119a58c83c2aa26ded8f362df3b52356150/includes/class-wc-stripe-customer.php#L405) apart from sending the `/attach` customer request. We want to avoid the `/attach` customer request but in a case when the customer does not exist yet, we need the recreate customer part. This function is introduced to handle that scenario.

File: includes/class-wc-stripe-customer.php [hunk 2]
```diff
@@ -617,7 +645,7 @@ public function delete_id_from_meta() {
 	 *
 	 * @return string ID of the new Customer object.
 	 */
-	private function recreate_customer() {
+	public function recreate_customer() {
```
Comment (mattallan) [inline includes/class-wc-stripe-customer.php]: Do we still need to update this function from private to public?
I'm assuming you made this change so that it could be used in the intent controller but it doesn't look like that is the case anymore.

I don't have any issues with this being public, just checking with you if this is intentional :)

**Review by mattallan — APPROVED** [review]
Nice changes @Mayisha and thanks for explaining the reason for these changes in the PR description and inline 😄 Much appreciated!!

I've tested the following cases:

- [x] Confirmed bug on `develop`
image
- [x] Confirmed fixed on `fix/2664-attach-customer-inr`
    - [x] No error in stripe dashboard
    - [x] Confirmed `_stripe_mandate_id` order meta is set
    - [x] Confirmed card is attached to customer in stripe
- [x] Indian Stripe Account
    - [x] Confirmed saving a new card from checkout
        - [x] `4000003560000123`
        - [x] `4242424242424242`
    - [x] Confirmed adding a new card via My Account page and confirm it's attached to customer in Stripe
    - [x] Confirmed using an existing saved card
    - [x] Above tests with UPE disabled
    - [x] Above tests wiith UPE enabled
- [x] US Stripe Account
    - [x] Confirmed saving a new card from checkout
        - [x] Cards (4242)
        - [x] APMs (SEPA)
    - [x] Confirmed adding a new card My Account
    - [x] Confirmed using an existing saved card
    - [x] With UPE disabled/enabled

I believe this is good to me merged :)
