### PR TITLE
Fix PHP fatal error in WC 8.5.0 when updating a user with saved tokens from the WP dashboard

### LINKED ISSUE #2834: Fatal error when updating a user that has saved Stripe tokens, with WC 8.5.0
**Describe the bug**
A PHP fatal error is triggered when updating a user that has saved Stripe tokens.

**To Reproduce**
1. Log in as a customer in the WC store
2. Go to My account > Payment methods > Add payment method `siteurl/my-account/add-payment-method/`
3. Add a card, like `4242424242424242`
4. As the store admin, go to the edit page for this user `siteurl/wp-admin/users.php`
5. Click on "Update user"
6. Notice there's a fatal error

```
PHP Fatal error:  Uncaught Error: Call to undefined function wc_add_notice() in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php:160
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(324): WC_Gateway_Stripe->show_update_card_notice(2, 'billing')
#1 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /var/www/html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-profile.php(243): do_action('woocommerce_cus...', 2, 'billing')
#4 /var/www/html/wp-includes/class-wp-hook.php(324): WC_Admin_Profile->save_customer_meta_fields(2)
#5 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /var/www/html/wp-admin/user-edit.php(157): do_action('edit_user_profi...', 2)
#8 {main}
  thrown in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 160
```

**Expected behavior**
Updating an user must not trigger any error.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version: Not relevant
 - WooCommerce Version: 8.5.0
 - Stripe Plugin Version: 7.9.0
 - Browser [e.g. chrome, safari] and Version: Not relevant
 - Any other plugins installed: None

**Additional context**

Reported in:
- https://wordpress.org/support/topic/major-fatal-error-and-conflict-w-8-5-1-and-stripe-gateway/
- p1705391584942949-slack-CHG7MTCAF

This error is happening because the WC action woocommerce_customer_save_address used to be triggered only on the My Account page. Since 8.5.0, this action is also triggered when updating a user from the WP dashboard (https://github.com/woocommerce/woocommerce/pull/39254).
We’re using the wc_add_notice() function in the callback for that action. This function isn’t defined when the action is triggered on the admin side.

### PR DESCRIPTION
**Pull request by a-danae**
Fixes #2834 

## Changes proposed in this Pull Request:

- Bail out early in `WC_Gateway_Stripe::show_update_card_notice()` when the action `woocommerce_customer_save_address` is called from the WP dashboard.

## Testing instructions

**Testing the error isn't triggered anymore**
1. Ensure you have WC 8.5.0 or newer installed
2. Log in as a customer in the WC store
3. Go to My account > Payment methods > Add payment method `siteurl/my-account/add-payment-method/`
4. Add a card, like 4242424242424242
5. As the store admin, go to the edit page for this user `siteurl/wp-admin/users.php`
6. Click on "Update user"
7. Confirm no error is triggered

### Regression tests

**Testing the WC notice continues to be displayed in the frontend**
1. Log in as the customer with the saved cards
2. Go to My account > Addresses > Edit billing address `siteurl/my-account/edit-address/billing/`
3. Click on "Save address"
4. Confirm a WC notice is added at the top of the page saying "If your billing address has been changed for saved payment methods, be sure to remove any [saved payment methods](http://localhost:8082/my-account/payment-methods/) on file and re-add them."
  image

**Testing the WC notice isn't displayed when updating the billing address**

1. Log in as the customer with the saved cards
2. Go to My account > Addresses > Edit shipping address `siteurl/my-account/edit-address/shipping/`
3. Click on "Save address"
4. Confirm the WC notice saying "If your billing address has been changed for saved payment methods..." isn't displayed

**Testing the WC notice isn't displayed when the user doesn't have saved tokens**
1. Log in as a customer with no saved cards (or delete the card for the user you used previously)
2. Go to My account > Addresses > Edit billing address `siteurl/my-account/edit-address/billing/`
3. Click on "Save address"
4. Confirm the WC notice saying "If your billing address has been changed for saved payment methods..." isn't displayed

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/class-wc-gateway-stripe.php [hunk 1]
```diff
@@ -150,7 +150,12 @@ public function is_available() {
 	 * @param string $load_address The address to load.
 	 */
 	public function show_update_card_notice( $user_id, $load_address ) {
-		if ( ! $this->saved_cards || ! WC_Stripe_Payment_Tokens::customer_has_saved_methods( $user_id ) || 'billing' !== $load_address ) {
+		if (
+			is_admin() ||
```
Comment (a-danae) [inline includes/class-wc-gateway-stripe.php:154]: This `is_admin()` is the only change within the conditional. The rest is just formatting.

An alternative I contemplated is directly checking whether `wc_add_notice` is defined. I opted  for using `is_admin()` instead because the notice is only intended to be displayed in the frontend, where [the function should always be defined](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-woocommerce.php#L625-L627).

Comment (diegocurbelo) [reply includes/class-wc-gateway-stripe.php:154]: I agree, `is_admin()` makes it clear that the notice should only be  shown in the admin dashboard.

**Review by diegocurbelo — APPROVED** [review]
Thanks for the quick fix @a-danae... the solution looks good, and it tests well 🚢
