### PR TITLE
Prevent Stripe API calls after detecting the API keys are not valid (401 response from API)

### LINKED ISSUE #4270: Unauthorized API requests tried far to many times
**Describe the bug**

A failed authorization attempt to the API results in a large number of retries, after a test account of mine was disabled 119 failed attempts were made to the stripe gateway, 119 in total:

* 96 to the `v1/payment_method_configurations` endpoint
* 21 to the `v1/account` endpoint 
* 1 to the `v1/payment_method_domains` endpoint
* 1 o the `v1/webhook_endpoints` endpoint

It's possible these were jobs catching up over the course of a week as I'd been on some PTO but the requests were blocking causing the page to apparently stall.

**To Reproduce**
1. Connect to a test account
2. Install and Activate Query Monitor
3. Go in to the database to modify the account details to be incorrect
4. Hit the Dashboard
5. The QM HTTP requests tab will show many failed attempts

**Expected behavior**

Re-authorization should be limited to one or two requests.

**Screenshots**

Image

**Environment (please complete the following information):**
 - WordPress Version 6.9-alpha-60170
 - WooCommerce Version 9.8.2
 - Stripe Plugin Version dab50f1780d225314dab985e53d285c7d17b065b (feature branch PR)
 - Browser [e.g. chrome, safari] and Version N/A
 - Any other plugins installed
    - Deposits
    - Query Montor
    - Various development focused MU-plugins: speed up cron jobs, prevent order number conflicts, etc.

**Additional context**

This occurred after my account was shutdown during a tidy up (it was intended to be against a woopayments account but they got the wrong one)

### PR DESCRIPTION
**Pull request by diegocurbelo**
Fixes #4270
Relates to STRIPE-445

## Changes proposed in this Pull Request:

This PR implements a mechanism to prevent unnecessary Stripe API calls when the API keys are invalid (401 response). 
- Added an option to track invalid API keys state
- Added automatic clearing of invalid API keys state when new keys are saved
- Updated the notice messages, and the state in the connection status check to show the Account as disconnected when API keys are invalid

This helps reduce unnecessary API calls and improves error notices/UI for merchants with invalid API credentials:

Screenshot 2025-05-15 at 16 16 00

Screenshot 2025-05-16 at 10 42 29

Screenshot 2025-05-16 at 12 50 36

## Testing instructions

1. Navigate to `WP-Admin > WooCommerce > Settings > Payments`, and select the `Stripe` option from the list
2. Go to the `Settings` tab and make sure the account is correctly connected:
    Screenshot 2025-05-16 at 13 10 22
3. Replace the API keys with an invalid value:
    `wp option patch update woocommerce_stripe_settings test_secret_key 'sk_test_INVALID'`
4. Navigate to the `WP-Admin` dashboard and check that Stripe notice is shwon:
    Screenshot 2025-05-16 at 13 13 54
5. Navigate to `WP-Admin > WooCommerce > Settings > Payments`, and select the `Stripe` option from the list 
6. Go to the `Settings` tab and make sure the account status has the connection error message:
    Screenshot 2025-05-16 at 13 16 09
7. Click `Configure connection` and make sure the Account status is `Disconnected`
    Screenshot 2025-05-16 at 13 16 59
8. Click the `Create or connect a test account` button, a re-connect your account
9. Check that after returning to the WP-Admin dasboard, the top notice is no longere present, and the acount status section has been restored:
    Screenshot 2025-05-16 at 13 25 43

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [x] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/class-wc-stripe-api.php [hunk 1]
```diff
@@ -233,6 +247,13 @@ public static function request( $request, $api = 'charges', $method = 'POST', $w
 	public static function retrieve( $api ) {
 		WC_Stripe_Logger::log( "{$api}" );
 
+		// If we have a transient indicating that the secret key is not valid, we dont't attempt the API call and we return an error.
+		$transient_key = WC_Stripe_Mode::is_test() ? self::TEST_MODE_INVALID_API_KEYS_TRANSIENT_KEY : self::LIVE_MODE_INVALID_API_KEYS_TRANSIENT_KEY;
+		$invalid_api_keys_detected = get_transient( $transient_key );
+		if ( $invalid_api_keys_detected ) {
+			return new WP_Error( 'stripe_error', __( 'The Stripe API keys are not valid.', 'woocommerce-gateway-stripe' ) );
+		}
+
```
Comment (daledupreez) [inline includes/class-wc-stripe-api.php]: I think we should do this check before we trigger the logger, otherwise we're going to flood the logs.
```suggestion
		// If we have a transient indicating that the secret key is not valid, we don't attempt the API call and we return an error.
		$transient_key = WC_Stripe_Mode::is_test() ? self::TEST_MODE_INVALID_API_KEYS_TRANSIENT_KEY : self::LIVE_MODE_INVALID_API_KEYS_TRANSIENT_KEY;
		$invalid_api_keys_detected = get_transient( $transient_key );
		if ( $invalid_api_keys_detected ) {
			return new WP_Error( 'stripe_error', __( 'The Stripe API keys are not valid.', 'woocommerce-gateway-stripe' ) );
		}

		WC_Stripe_Logger::log( "{$api}" );

```

File: includes/class-wc-stripe-api.php [hunk 2]
```diff
@@ -242,6 +263,13 @@ public static function retrieve( $api ) {
 			]
 		);
 
+		// If we get a 401 error, we know the secret key is not valid, we save a transient to avoid making calls until the secrect key gets updated.
+		if ( ! empty( $response['response']['code'] ) && 401 === $response['response']['code'] ) {
```
Comment (daledupreez) [inline includes/class-wc-stripe-api.php]: We should guard against `$response` being a `WP_Error` instance.
```suggestion
		if ( is_array( $response ) && ! empty( $response['response']['code'] ) && 401 === $response['response']['code'] ) {
```

File: includes/class-wc-stripe-api.php [hunk 3]
```diff
@@ -242,6 +263,13 @@ public static function retrieve( $api ) {
...
+			$transient_key = WC_Stripe_Mode::is_test() ? self::TEST_MODE_INVALID_API_KEYS_TRANSIENT_KEY : self::LIVE_MODE_INVALID_API_KEYS_TRANSIENT_KEY;
```
Comment (daledupreez) [inline includes/class-wc-stripe-api.php]: We should still have the local variable from the top of the function available. Maybe we can call it `$invalid_key_transient_key` and re-use the value from above?

File: includes/class-wc-stripe-api.php [hunk 4]
```diff
@@ -242,6 +263,13 @@ public static function retrieve( $api ) {
...
+			set_transient( $transient_key, true );
```
Comment (daledupreez) [inline includes/class-wc-stripe-api.php]: Do we want to do this immediately in all cases? Or only after we've triggered multiple failures in a short period of time?

I worry that there may be other situations where one or two 401 responses could occur -- I wouldn't want to stop a merchant's payments if that occurs.

Also, do we want to record the timestamp that we took the action? That may be useful when debugging and trying to understand what is going on.

**Review by daledupreez — COMMENTED** [review]
I think this is the general approach should work well, with a concern about triggering the code after one 401 response.

More broadly, I think we also need to clear the transient when we save/update the Stripe keys, which feels like it ought to occur in `WC_Stripe_Connect->save_stripe_keys()` and whatever code we use to disconnect/clear keys.

File: includes/class-wc-stripe-api.php [hunk 5]
```diff
@@ -242,6 +263,12 @@ public static function retrieve( $api ) {
 			]
 		);
 
+		// If we get a 401 error, we know the secret key is not valid, we save a transient to avoid making calls until the secrect key gets updated.
+		if ( is_array( $response ) && ! empty( $response['response']['code'] ) && 401 === $response['response']['code'] ) {
+			set_transient( $invalid_api_keys_transient_key, true );
+			return json_decode( '' ); // The UI expects this empty response in case of invalid API keys.
```
Comment (daledupreez) [inline includes/class-wc-stripe-api.php]: I believe `json_decode( '' ) === null`. Can we just return `null` instead?

File: includes/class-wc-stripe-api.php [hunk 6]
```diff
@@ -231,6 +245,13 @@ public static function request( $request, $api = 'charges', $method = 'POST', $w
 	 * @param string $api
 	 */
 	public static function retrieve( $api ) {
+		// If we have an option flag indicating that the secret key is not valid, we dont't attempt the API call and we return an error.
```
Comment (daledupreez) [inline includes/class-wc-stripe-api.php]: Nit: typo
```suggestion
		// If we have an option flag indicating that the secret key is not valid, we don't attempt the API call and we return an error.
```

File: includes/class-wc-stripe-api.php [hunk 7]
```diff
@@ -242,6 +263,18 @@ public static function retrieve( $api ) {
 			]
 		);
 
+		// If we get a 401 error, we know the secret key is not valid.
+		if ( is_array( $response ) && ! empty( $response['response']['code'] ) && 401 === $response['response']['code'] ) {
```
Comment (daledupreez) [inline includes/class-wc-stripe-api.php]: Minor thought: my code in #4327 is extremely defensive in this check, just to make sure that we have all the data we're expecting. Not blocking, but it may be worth being super-defensive to make sure we don't break in unexpected ways.
```suggestion
		if ( is_array( $response ) && isset( $response['response'] ) && is_array( $response['response'] ) && isset( $response['response']['code'] ) && 401 === $response['response']['code'] ) {
```

File: changelog.txt [hunk 8]
```diff
@@ -7,6 +7,7 @@
 * Update - Remove BACS from the unsupported 'change payment method for subscription' page.
 * Fix - Fix payment method title display when new payment settings experience is enabled
 * Fix - Prevent styles from non-checkout pages affecting the appearance of Stripe element.
+* Fix - Prevert further Stripe API calls if API keys are invalid (401 response).
```
Comment (daledupreez) [inline changelog.txt]: Nit: typo
```suggestion
* Fix - Prevent further Stripe API calls if API keys are invalid (401 response).
```

File: readme.txt [hunk 9]
```diff
@@ -118,6 +118,7 @@ If you get stuck, you can ask for help in the [Plugin Forum](https://wordpress.o
 * Update - Remove BACS from the unsupported 'change payment method for subscription' page.
 * Fix - Fix payment method title display when new payment settings experience is enabled
 * Fix - Prevent styles from non-checkout pages affecting the appearance of Stripe element.
+* Fix - Prevert further Stripe API calls if API keys are invalid (401 response).
```
Comment (daledupreez) [inline readme.txt]: Typo
```suggestion
* Fix - Prevent further Stripe API calls if API keys are invalid (401 response).
```

File: client/settings/account-details/index.js [hunk 10]
```diff
@@ -133,11 +133,11 @@ const AccountDetails = () => {
 					{ createInterpolateElement(
 						isTestModeEnabled
 							? __(
-									"Seems like the test API keys we've saved for you are no longer valid. If you recently updated them, use the <strong>Configure Connection</strong> button below to reconnect.",
+									"We couldn't connect to your account, it seems like the test API keys we've saved for you are no longer valid. Please use the <strong>Configure connection</strong> button below to reconnect.",
```
Comment (ebinnion) [inline client/settings/account-details/index.js:136]: Not urgent in this case. But, will this break internationalization of this string in the patch release?

Comment (daledupreez) [reply client/settings/account-details/index.js:136]: Good call.

**Review by daledupreez — COMMENTED** [review]
Overall, this is looking good and tests as described.

I do think we need to fix the typos in the changelogs, and I had one minor comment about possibly making the path to identify the response code more defensive.

File: client/settings/account-details/index.js (hunk 10 above)
Comment (daledupreez) [reply client/settings/account-details/index.js:136]: That said, I think the trade-off for correctly communicating the status is probably worth it.

File: includes/class-wc-stripe-api.php [hunk 11]
```diff
@@ -242,6 +263,18 @@ public static function retrieve( $api ) {
 			]
 		);
 
+		// If we get a 401 error, we know the secret key is not valid.
```
Comment (wjrosa) [inline includes/class-wc-stripe-api.php:266]: Maybe we could consider later changing this to check for anything different from 200, to cover more possible issues.

File: client/settings/account-details/index.js (hunk 10 above)
Comment (diegocurbelo) [reply client/settings/account-details/index.js:136]: Correct, new strings need to be translated in the community translations site: https://translate.wordpress.org/projects/wp-plugins/woocommerce-gateway-stripe/

File: includes/class-wc-stripe-api.php (hunk 11 above)
Comment (daledupreez) [reply includes/class-wc-stripe-api.php:266]: My proposed changes in #4327 take that approach when looking at responses. 😁

**Review by daledupreez — APPROVED** [review]
Thanks for the cleanup, @diegocurbelo! 🚀

File: includes/class-wc-stripe-api.php (hunk 4 above)
Comment (malithsen) [reply includes/class-wc-stripe-api.php]: @diegocurbelo @daledupreez Did we address this concern somewhere? I wonder if one-off 401s are contributing to [this potential false positive issue](https://wordpress.org/support/topic/version-9-5-1-falsely-thinks-account-is-disconnected/) a user mentioned in forums

Comment (diegocurbelo) [reply includes/class-wc-stripe-api.php]: API Keys can not be temporary disabled, only revoked; so getting one 401 means that we need new keys (there is no way for them to become valid again).

The user in the forum mentions that payments are still coming through, so we are not blocking API calls because of a 401 (the 401 flag is not set). It seems to have been a problem with the account cache; if the account can't be read (because of a timeout or a 500, 429 errors etc) the UI assumes the account is disconnected and show the notices.

We show refactor the account settings (and global notices) to account for the new flows we added to the Stripe API connector (which might cause the account/PM list to be null temporary), but that might be to big of a change for a patch release.

Comment (malithsen) [reply includes/class-wc-stripe-api.php]: That makes more sense. Thanks Diego! I see that it was resolved after clearing cache/transients.
