### PR TITLE
Make UPE method titles consistent and translatable.

### LINKED ISSUE #1967: Check payment menthod title and label
**Describe the bug**
In some payment method the title and label are not consistent, the idea of this issue is to define for each payment method the desired spelling:

- Label: Credit card / debit card
- Title: Credit card / debit card

- Label: giropay
- Title: Pay with giropay

- Label: EPS
- Title: Pay with EPS

- Label: Bancontact
- Title: Pay with Bancontact

- Label: iDEAL
- Title: Pay with iDEAL

- Label: Sepa Direct Debit
- Title: Pay with SEPA Direct Debit

- Label: Przelewy24
- Title: Pay with Przelewy24

- Label: SOFORT
- Title: Pay with SOFORT

### PR DESCRIPTION
**Pull request by EvanDotPro**
This simply addresses #1967.

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-method-cc.php [hunk 1]
```diff
@@ -22,7 +22,7 @@ class WC_Stripe_UPE_Payment_Method_CC extends WC_Stripe_UPE_Payment_Method {
 	public function __construct() {
 		parent::__construct();
 		$this->stripe_id   = self::STRIPE_ID;
-		$this->title       = 'Credit card / debit card';
+		$this->title       = __( 'Pay with credit card / debit card', 'woocommerce-gateway-stripe' );
```
Comment (cesarcosta99) [inline includes/payment-methods/class-wc-stripe-upe-payment-method-cc.php:25]: In the issue, "credit card" is not supposed to contain "Pay with". Did you add it intentionally?

Comment (EvanDotPro) [reply includes/payment-methods/class-wc-stripe-upe-payment-method-cc.php:25]: I'm pretty sure what @diegocurbelo put were the titles/labels as he saw them in the code when writing the issue, including the inconsistencies (i.e., the missing "Pay with" and Sepa vs SEPA.

**Review by cesarcosta99 — APPROVED** [review]
LGTM :shipit:
