### PR TITLE
Send 'mandate_options' only for supported currencies

### LINKED ISSUE #2988: Error when processing payments in currencies not eligible for India subscription mandates
**Describe the bug**

We've receive at least 1 merchant reporting this error when processing subscription related payments. 

<p align="center">
Screenshot 2024-03-13 at 5 02 31 pm
</p>

The error is caused by the Stripe plugin including mandate data necessary to process subscription payments from India issued cards. Stripe docs ([direct link](https://docs.stripe.com/india-recurring-payments?integration=paymentIntents-setupIntents#create-mandate)) suggest that: 

> **Note**
> You can pass the payment_method_options[card][mandate_options] parameter for all requests. Stripe ignores these parameters if your customer is using a non-India issued card because the regulation doesn’t apply to them.

However it appears there may be some validation of the transaction currency. I haven't been able to replicate this issue on a test account using an invalid currency (AUD, MXN) and an India issued card. 

**Steps to test**

1. Set your store currency to an in-eligible currency. eg MXN.
2. Install Woo Subscriptions. 
3. Create a subscription product if you don't have one. 
4. Purchase the subscription using a card issued in India. 
   - Stripe provide these test cards: https://docs.stripe.com/india-recurring-payments?integration=paymentIntents-setupIntents#testing
   - `4000003560000008` is another generic India card you can use for testing.
5. According to this error a merchant has reported. This should lead to an error. 

I cannot replicate myself. It could be a test vs live mode thing.

**Expected behavior**
Based on the error in Stripe, we could exclude this mandate data when the order currency is an invalid currency based on the list found here: https://docs.stripe.com/india-recurring-payments?integration=paymentIntents-setupIntents#create-mandate

**Additional context**

7879498-zd-a8c (p1710300612177349-slack-C7U3Y3VMY)

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #2988 

Mandate data are required to process subscription payments with India issued cards. According to Stripe [docs](https://docs.stripe.com/india-recurring-payments?integration=paymentIntents-setupIntents#create-mandate) we can send the mandate data for all types of cards.

> You can pass the payment_method_options[card][mandate_options] parameter for all requests. Stripe ignores these parameters if your customer is using a non-India issued card because the regulation doesn’t apply to them.

However, there is a restriction with the currency and only the following list of currencies is supported by the INR mandate for international business.

> [ 'inr', 'usd', 'eur', 'gbp', 'sgd', 'cad', 'chf', 'sek', 'aed', 'jpy', 'nok', 'myr', 'hkd' ]

## Changes proposed in this Pull Request:
- Sending the `mandate_option` only when the order currency is supported.

## Testing instructions
- Use the `develop` branch.
- Set your store currency to an in-eligible currency. eg MXN.
- Install Woo Subscriptions.
- Create a subscription product if you don't have one.
- Purchase the subscription using a card issued in India.
    - Stripe provide these test cards: https://docs.stripe.com/india-recurring-payments?integration=paymentIntents-setupIntents#testing
    - 4000003560000008 is another generic India card you can use for testing.
- The payment will fail and you will see an error notice regarding the supported currencies.

error notice

- Now checkout this branch and follow the above steps again.
- This time you should be able to complete the purchase without any error.
- Check the logs in your admin dashboard. Find the payment intent request, it should not contain any `mandate_option` field.

### Additional tests
**Regular card**
- Set your store currency to a supported currency.
- Purchase subscriptions with a regular card card. (`4242424242424242`).
- The purchase should be successful.
- Check the logs in your admin dashboard. Find the payment intent request in logs, it should have the `mandate_option` field.
- Find the response in logs. The `mandate` field should be empty.

**Regular card**
- Set your store currency to a supported currency.
- Purchase subscriptions with an India issued card. (`4000003560000008`).
- The purchase should be successful.
- Check the logs in your admin dashboard. Find the payment intent request in logs, it should have the `mandate_option` field.
- Find the response in logs. The `mandate` field should have a mandate id.
- Find the `_stripe_mandate_id` order meta for this order in your database. The value should match the returned mandate id.

### CODE REVIEW

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 1]
```diff
@@ -653,11 +653,18 @@ private function get_mandate_for_subscription( $order, $payment_method ) {
...
+	 * @param WC_Order $subscriptions Subscriptions for the renewal order.
+	 * @param string   $currency The currency of the order.
 	 * @return array the mandate_options for the subscription order.
 	 */
-	private function create_mandate_options_for_order( $order, $subscriptions ) {
+	private function create_mandate_options_for_order( $order, $subscriptions, $currency ) {
 		$mandate_options = [];
 
+		// India recurring payment mandates can only be requested for the following currencies.
+		if ( ! in_array( $currency, [ 'inr', 'usd', 'eur', 'gbp', 'sgd', 'cad', 'chf', 'sek', 'aed', 'jpy', 'nok', 'myr', 'hkd' ], true ) ) {
```
Comment (mattallan) [inline includes/compat/trait-wc-stripe-subscriptions.php:664]: Should we `strtolower` the `$currency` to be on the safe side here?

---

Also making a note I've confirmed the currencies in this list according to stripe docs:
`INR` + `USD, EUR, GBP, SGD, CAD, CHF, SEK, AED, JPY, NOK, MYR, HKD`

File: includes/compat/trait-wc-stripe-subscriptions.php [hunk 2]
```diff
@@ -612,7 +612,7 @@ public function add_subscription_information_to_intent( $request, $order, $prepa
 		}
 
 		// Add mandate options to request to create new mandate if mandate id does not already exist in a previous renewal or parent order.
-		$mandate_options = $this->create_mandate_options_for_order( $order, $subscriptions_for_renewal_order );
+		$mandate_options = $this->create_mandate_options_for_order( $order, $subscriptions_for_renewal_order, $request['currency'] );
```
Comment (mattallan) [inline includes/compat/trait-wc-stripe-subscriptions.php]: This is a very small nit-pick and not sure if it's worth worrying about, but this request data is filterable, it okay to assume `$request['currency']` will always exist here? I'm thinking worst case a third-party could hook onto `wc_stripe_generate_create_intent_request` earlier than us and remove 'currency' from request args. 🤠 

Maybe we could fall back to the `$order->get_currency()` if it's not set? Not sure if we need to bother with this though. Thoughts?

**Review by mattallan — APPROVED** [review]
Hey @Mayisha I couldn't replicate this issue on `develop` but from the issue I see James also couldn't reproduce it.

Here's how I was trying to reproduce on `develop`:
1. Using my existing AU stripe account
2. Set store currency to MXN
3. Purchase a subscription using `4000003560000008`
4. Payment went through without an issue
5. I also tried a Mexican and Indian Stripe accounts but couldn't reproduce the issue

---

Based on the code changes and reading the stripe docs, these set of changes look good.

I had only some minor nit-pick changes, but they aren't blocking at all so I'm happy to approve.

File: includes/compat/trait-wc-stripe-subscriptions.php (hunk 2 above)
Comment (Mayisha) [reply includes/compat/trait-wc-stripe-subscriptions.php]: Thanks @mattallan. This sounds like a better idea. I have addressed it in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3010/commits/23acc8cb4a91a101e693db9b8d2b57bd55456eb3

**Comment by Mayisha** [comment]
> Hey @Mayisha I couldn't replicate this issue on develop but from the issue I see James also couldn't reproduce it.

@mattallan I could reproduce it when I used a Mexican Stripe account with `mxn` as store currency.
