### PR TITLE
Fix possible issue with undefined variable: prepared_source

### LINKED ISSUE #894: Undefined variable `$prepared_source`
#### What I expected

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-webhook-handler.php#L183

It would appear `$prepared_source` is not defined at this point.

I don't understand the code enough to suggest a definitive fix for this problem. At a guess, should this be:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-webhook-handler.php#L161

Based on the comment on line 159? 

#### What happened instead

I have not yet run the code to see what goes wrong here. 

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by reykjalin**
# Changes proposed in this Pull Request:

Fixes #894
Supercedes #1514 

# Testing instructions

Really difficult to test. The way I did it was to set a breakpoint when the webhook code is triggered and compared the values from `prepare_order_source( $order )` and the ones we manually added to `$source_object`. You can trigger the webhook code by making a test payment through iDeal.

To set up iDeal set the store currency to **EUR** and enable the iDeal payment method.

I don't know how to trigger the code that includes the other change, but I went with the same kind of update.

I'm not even sure if the if-statements we were worried about can be triggered.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-stripe-order-handler.php [hunk 1]
```diff
@@ -107,22 +107,19 @@ public function process_redirect_payment( $order_id, $retry = true, $previous_er
...
 			 * a different idempotency key and retry for success.
 			 */
-			if ( $this->need_update_idempotency_key( $source_object, $previous_error ) ) {
+			if ( $this->need_update_idempotency_key( $prepared_source, $previous_error ) ) {
 				add_filter( 'wc_stripe_idempotency_key', [ $this, 'change_idempotency_key' ], 10, 2 );
 			}
 
 			// Make the request.
-			$response = WC_Stripe_API::request( $this->generate_payment_request( $order, $source_object ), 'charges', 'POST', true );
+			$response = WC_Stripe_API::request( $this->generate_payment_request( $order, $prepared_source ), 'charges', 'POST', true );
```
Comment (reykjalin) [inline includes/class-wc-stripe-order-handler.php:122]: I'm really not sure how to trigger this code, but I went with a change that seemed to work for the webhooks.

What I tried to trigger this:

- 3DS payment from the checkout page
- iDeal payment
- 3DS payment from the "pay for order" page (accessible from the **Customer payment page** link in the order details screen).

**Review by reykjalin — COMMENTED** [review]
I tagged @diegocurbelo in this PR specifically because he reviewed Jesse's previous PR #1514. He may have some insights here.

Aside from that the code being changed here hasn't been touched in 4 years so I'm not sure how to test it properly. I'd love your insights and thoughts on that @asumaran and @diegocurbelo .

Maybe we need to try to delete a source object in the Stripe dashboard to properly test this? I just thought of that now as my day is ending, so maybe that's something to look into?

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 2]
```diff
@@ -728,7 +728,7 @@ public function prepare_order_source( $order = null ) {
 		if ( $order ) {
 			$order_id = $order->get_id();
 
-			$stripe_customer_id = get_post_meta( $order_id, '_stripe_customer_id', true );
+			$stripe_customer_id = $this->get_stripe_customer_id( $order );
```
Comment (asumaran) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php:731]: Nice

File: includes/class-wc-stripe-order-handler.php (hunk 1 above)
Comment (asumaran) [reply includes/class-wc-stripe-order-handler.php:122]: I haven't found any other way to trigger this code. Since the code is too old I was thinking it was something that we forgot to remove. Thanks for leaving instructions!

**Review by asumaran — APPROVED** [review]
Looks good to me! I remember touching this code while working on https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1507 but haven't found any issues. Unless @diegocurbelo has something to add I think this is good to go.

**Review by diegocurbelo — APPROVED** [review]
I like the change to use `prepare_order_source()`..

LGTM 🚢
