### PR TITLE
Fix when capturing a charge from authorize, Stripe fees not displayin…

### LINKED ISSUE #713: Stripe fee does not show for previously authorized transactions
#### Affected ticket(s)
1357548-zd-woothemes

#### What I expected
Whether a charge has been previously authorized, or immediately captured - you should see the Stripe fees on the order details.

#### What happened instead
Stripe fees do not show for transactions that were previously authorized

#### Steps to reproduce the issue
- Disable the `Capture charge immediately` option
- Make a purchase and authorize the payment
- As the Administrator, capture the authorized payment by setting the order to _Processing_
- Observer the order summary, that there is no Stripe fee information

The customer also passed along that they noticed differences in the API response for orders that were authorized before they were captured:

Image Link: http://cld.wthms.co/PHqeWl

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by roykho**
…g closes #713

Fixes #713

#### Changes proposed in this Pull Request:
* Fix - When capturing a charge from authorize, Stripe fees not displaying.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-stripe-order-handler.php [hunk 1]
```diff
@@ -259,6 +259,10 @@ public function capture_payment( $order_id ) {
 						$net = ! empty( $result->balance_transaction->net ) ? WC_Stripe_Helper::format_balance_fee( $result->balance_transaction, 'net' ) : 0;
 						WC_Stripe_Helper::update_stripe_fee( $order, $fee );
 						WC_Stripe_Helper::update_stripe_net( $order, $net );
+
+						// Store currency stripe.
+						$currency = ! empty( $result->balance_transaction->currency ) ? strtoupper( $result->balance_transaction->currency ) : null;
+						WC_Stripe_Helper::update_stripe_currency( $order, $currency );
```
Comment (laurendavissmith) [inline includes/class-wc-stripe-order-handler.php]: wouldn't we only want to call this if `$currency` is not `null`? i didn't follow the full flow through the code so i may be misreading

Comment (roykho) [reply includes/class-wc-stripe-order-handler.php]: So we want the meta to save whether it is set or not.
