### PR TITLE
Fix UPE style transition keys for font smoothing properties to prevent warning

### LINKED ISSUE #5155: CSS logic for font smoothing needs to be updated
### Description

In testing various things today, I noticed console warnings when rendering Stripe in development:
> [Stripe.js] stripe.elements(): "webkitFontSmoothing" is not a supported property for ".Text"

The warnings applied to `.Text`, `.Input`, `.Text--redirect`, and `.Input--invalid`. Per the [Stripe appearance API documentation](https://docs.stripe.com/elements/appearance-api?api-integration=paymentintents&q=accordion#supported-css-properties), only `-webkit-font-smoothing` and `-moz-osx-font-smoothing` are supported.

This is a bug introduced by #5113 earlier this week, as that code changed to use the camel case property names.

### Steps to reproduce

1. Enable Stripe on a site and create a test Stripe connection
2. Enable the Stripe payment method
3. Add a product to your cart
4. Open your browser console
5. Navigate to checkout
6. You should see the warnings appear if your theme specifies either of those CSS rules

### Expected behavior

There should be no warnings related to CSS properties.

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes STRIPE-STRIPE-996
Fixes #5155 

## Changes proposed in this Pull Request:
This PR reverts the commit https://github.com/woocommerce/woocommerce-gateway-stripe/commit/961d18aaa32cc931868d823f9ad6c6c3d6cec03b added in PR https://github.com/woocommerce/woocommerce-gateway-stripe/issues/5155 where we changed the keys `MozOsxFontSmoothing` and `webkitFontSmoothing` in camelCase which is not supported by the Stripe element. 

## Testing instructions
- Enable Stripe on a site and connect to a Stripe account.
- Enable some Stripe payment methods
- As a shopper, add a product to your cart
- Open your browser console
- Navigate to the checkout page
- In `develop`, you should see the following warnings appear if your theme specifies either of those CSS rules.

- In this branch, these warnings should not be there.

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

**Review by diegocurbelo — APPROVED** [review]
LFTM 👍🏼 

**BEFORE**
Image

**AFTER**
No warnings in the console

**Review by daledupreez — COMMENTED** [review]
@Mayisha, I think we need to map the properties into the appearance fields rather than use the old property names. The issue is that direct access via `computedStyles[ dashedPropertyName ]` doesn't get the related styles from the original object.

**Comment by daledupreez** [comment]
Or, expressed differently, we need to make sure that all font smoothing properties from the computed styles are correctly being set into the appearance fields.

**Review by wjrosa — APPROVED** [review]
Looks good to me 👍 . Feel free to request my review again if Dale's comment requires a rework

**Comment by Mayisha** [comment]
> I think we need to map the properties into the appearance fields rather than use the old property names. The issue is that direct access via computedStyles[ dashedPropertyName ] doesn't get the related styles from the original object.

@daledupreez I have updated this PR. Could you please check and confirm if this is the solution you proposed?

File: client/styles/upe/index.js [hunk 1]
```diff
@@ -315,6 +319,14 @@ export const getFieldStyles = ( selector, upeElement ) => {
...
+		if ( fontSmoothingProps.includes( property ) ) {
+			const mappedProperty = computedStylePropertyMaps[ property ];
+			if ( typeof styles[ mappedProperty ] !== 'undefined' ) {
+				filteredStyles[ property ] = styles[ mappedProperty ];
+			}
+			continue;
+		}
+
 		if ( typeof styles[ property ] !== 'undefined' ) {
 			filteredStyles[ property ] = styles[ property ];
```
Comment (daledupreez) [inline client/styles/upe/index.js]: While this gets the job done, I am not a fan of the implementation as it splits the mapping constants and the processing logic and it has two code paths that do the same thing. I think this could be cleaner if we implemented a function like `getSourcePropertyName( propertyName )` in `upe-styles.js` and then use a single code path in this logic? (We could then export only the function, drop `fontSmoothingProps`, and keep computedStylePropertyMaps local.)

```js
export const getSourcePropertyName = ( propertyName )  => {
	return computedStylePropertyMaps[ propertyName ] || propertyName;
};
```


```suggestion
		const sourceProperty = getSourcePropertyName( property );

		if ( typeof styles[ sourceProperty ] !== 'undefined' ) {
			filteredStyles[ property ] = styles[ sourceProperty ];
```

File: client/styles/upe/upe-styles.js [hunk 2]
```diff
@@ -8,6 +8,16 @@ const paddingColorProps = [
...
 ];
 
+export const fontSmoothingProps = [
+	'-webkit-font-smoothing',
+	'-moz-osx-font-smoothing',
+];
+
+export const computedStylePropertyMaps = {
+	'-webkit-font-smoothing': 'WebkitFontSmoothing',
+	'-moz-osx-font-smoothing': 'MozOsxFontSmoothing',
```
Comment (daledupreez) [inline client/styles/upe/upe-styles.js:13]: Good catch on `WebkitFontSmoothing` and `webkitFontSmoothing` both being valid.

File: client/styles/upe/index.js (hunk 1 above)
Comment (Mayisha) [reply client/styles/upe/index.js]: Thanks for explaining in detail. I have updated the code as per this suggestion.

**Comment by Mayisha** [comment]
> Looks good to me 👍 . Feel free to request my review again if Dale's comment requires a rework

@wjrosa requested you review again.

**Review by wjrosa — APPROVED** [review]
Latest changes still looks good to me 👍
