### PR TITLE
Attach the source when a customer adds a legacy SEPA token via My Acccount

### LINKED ISSUE #3240: Legacy SEPA tokens using sources aren't being attached to the customer
**Describe the bug**

When the Legacy checkout experience is enabled, SEPA tokens are created on the store, but they are not attached to the Stripe customer.

This works fine in 8.0.1.

**To Reproduce**

1. Select EUR as the store currency
2. Enable the Legacy checkout experience, At Stripe settings > Settings tab, `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`
3. Enable SEPA under the Stripe payment methods. At Stripe settings > Payment methods tab `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`
4. Log in as a shopper
5. Go to My account > Payment methods > Add payment method, at `/my-account/add-payment-method/`
6. Add a SEPA payment method
7. Notice a token is successfully created
8. Go to the Stripe dashboard > Customers > The customer associated with the shopper you just logged in. At `https://dashboard.stripe.com/test/customers/<cus_xyz>`
9. Notice there's no SEPA payment method attached

**Expected behavior**

When adding a token for a shopper, this should also be attached to the Stripe customer.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #3240

## Changes proposed in this Pull Request:

On sites with the legacy checkout experience enabled, customers who add SEPA payment methods via the **My Account → Payment methods** weren't having their payment methods attached on the Stripe Account.

This PR fixes that.

## Testing instructions

**REPLICATE THE BUG**

1. Enable the legacy checkout experience in Stripe settings.
2. Set your store currency to EUR
3. Enable SEPA. 
4. Go to your **My Account → Payment methods**
5. Note the payment methods you have saved.
6. Add a new SEPA token. eg `IE94AIBK93115212345672`.
7. View the customer in your Stripe dashboard. 
8. Note that the new payment method you added is missing. 

| Screenshot 2024-07-05 at 12 00 49 PM | Screenshot 2024-07-05 at 12 01 05 PM |
|--------|--------|
<sup>Card ending in `5672` is missing in Stripe</sup>

**CONFIRM THE FIX**

9. Checkout this branch. 
10. Add a SEPA token again.
11. Confirm the new token is attached to the customer in Stripe. 

| Screenshot 2024-07-05 at 12 07 20 PM | Screenshot 2024-07-05 at 12 06 53 PM |
|--------|--------|

 

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -845,27 +845,14 @@ public function prepare_source( $user_id, $force_save_source = false, $existing_
...
+			$maybe_saved_card = isset( $_POST[ 'wc-' . $payment_method . '-new-payment-method' ] ) && ! empty( $_POST[ 'wc-' . $payment_method . '-new-payment-method' ] );
 
-				if ( ! empty( $response->error ) ) {
-					throw new WC_Stripe_Exception( print_r( $response, true ), $this->get_localized_error_message_from_response( $response ) );
-				}
-				if ( is_wp_error( $response ) ) {
-					throw new WC_Stripe_Exception( $response->get_error_message(), $response->get_error_message() );
+			if ( $force_save_source || ( $user_id && $this->saved_cards && $maybe_saved_card ) ) {
+				$response = $this->maybe_attach_source_to_customer( $source_object, $customer );
+				if ( $response ) {
```
Comment (wjrosa) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: If `$response` is used here just to check if the process was successful, I would replace the return with a boolean.

Comment (james-allan) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: 👍 changed in [1615f92](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3246/commits/1615f927047bf6b48728d2ae60c7b8384a0916cc)

**Review by wjrosa — APPROVED** [review]
Thanks for fixing this and for your help on Slack! It works as expected:
Screenshot 2024-07-08 at 13 48 14
