### PR TITLE
ECE: Add support for custom fields in block checkout

### LINKED ISSUE #2969: Custom checkout fields not getting included in checkout form data submitted by GPay/Apple Pay
**Describe the bug**
Encountered an issue with our Smart Coupons plugin affecting custom fields on the checkout page. When utilizing GPay/Apple Pay, the Checkout form data does not include information from these custom fields.

Upon inspecting the getOrderData function ([ref](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/assets/js/stripe-payment-request.js#L92)), it appears that the function generates a checkout form data with predefined, hardcoded fields. Unfortunately, there is no mechanism to extend or add additional data, similar to WooCommerce checkout on the PHP side.

Also,  incorporating additional data through JS code in the AJAX call is not feasible due to the use of iframes for rendering GPay/Apple Pay payment buttons.

Do let me know if any further details are needed for this.

### PR DESCRIPTION
**Pull request by annemirasol**
Partially fixes STRIPE-205
Partially fixes #2969 

## Changes proposed in this Pull Request:
This PR adds support for ECE and custom checkout fields, limited to: 
- block checkout, and
- fields added via Additional Checkout Fields API (i.e. `woocommerce_register_additional_checkout_field()`).

In subsequent PRs, we will add support for
- custom fields added by third-party plugins that use `extensions` (block checkout only) (#4394)
- custom fields for classic checkout

## Testing instructions
 1. Add custom checkout fields to the block checkout:
    - Install [Code Snippets](https://wordpress.org/plugins/code-snippets/) or a similar plugin, and add the snippet provided in the comment below.
2. As a shopper, add a product to cart and go to block checkout.
3. Notice the additional fields in the checkout form. Fill out these fields.
4. Use express checkout to complete your purchase.
5. Verify in the Order Confirmation page that the fields have been persisted.
   - You may also check the `wp_wc_orders_meta`.
   - The `meta_key` will be prefixed with `_wc_billing/`, `_wc_shipping/` or `_wc_other/`.
6. Try using ECE in the product or cart pages.
   - Verify there are no unexpected failures. See known limitations about required custom fields below.
   - Verify it avoids using stale session data: since the custom fields are not presented to the shopper inside these pages, there should be no custom data stored for these orders.

Known limitations:
- When marking a custom field as "required" in `woocommerce_register_additional_checkout_field()`, express checkout will fail when the data is not provided. This invariably means ECE is not usable outside of the block checkout page.
- When validation fails, the error message from the server is displayed but the input field is not highlighted in red

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

**Comment by annemirasol** [comment]
Sample code snippet to add custom fields via the Additional Checkout Fields API:

```
add_action(
	'woocommerce_init',
	function() {
		woocommerce_register_additional_checkout_field(
			array(
				'id'            => 'my-plugin/gov-id',
				'label'         => 'Government ID',
				'optionalLabel' => 'Government ID (optional)',
				'location'      => 'address',
				'attributes'    => array(
					'autocomplete'     => 'government-id',
					'aria-describedby' => 'some-element',
					'aria-label'       => 'custom aria label',
					'pattern'          => '[A-Z0-9]{5}', // A 5-character string of capital letters and numbers.
					'title'            => 'Title to show on hover',
					'data-custom'      => 'custom data',
				),
			),
		);
		
		woocommerce_register_additional_checkout_field(
			array(
				'id'       => 'my-plugin/marketing-opt-in',
				'label'    => 'Do you want to subscribe to our newsletter?',
				'location' => 'contact',
				'type'     => 'checkbox',
			)
		);
		
		woocommerce_register_additional_checkout_field(
			array(
				'id'          => 'my-plugin/how-did-you-hear-about-us',
				'label'       => 'How did you hear about us?',
				'placeholder' => 'Select a source',
				'location'    => 'order',
				'type'        => 'select',
				'options'     => [
					[
						'value' => 'google',
						'label' => 'Google'
					],
					[
						'value' => 'facebook',
						'label' => 'Facebook'
					],
					[
						'value' => 'friend',
						'label' => 'From a friend'
					],
					[
						'value' => 'other',
						'label' => 'Other'
					],
				]
			)
		);
	}
);
```

File: client/express-checkout/utils/normalize.js [hunk 1]
```diff
@@ -85,9 +51,256 @@ export const normalizeOrderData = ( {
...
+ * @param {Object} data The standard billing address data.
+ *
+ * @return {Object} The custom billing address data.
+ */
+const getCustomBillingAddressData = ( data ) => {
+	// We need to specifically pass empty fields when not on the block checkout page,
+	// to avoid sending "hidden" and possibly stale data from previous transactions,
+	// e.g. shopper is on the product page (hence, no checkout form fields are displayed),
+	// but session still holds data from a previous checkout.
+	if ( ! isBlockCheckoutPage() ) {
```
[the remark this answers is not in the document]
Comment (annemirasol) [reply client/express-checkout/utils/normalize.js:159]: This is okay as-is.

File: client/express-checkout/payment-flow.js [hunk 2]
```diff
@@ -3,7 +3,12 @@ import { getErrorMessageFromNotice, normalizeOrderData } from './utils';
 
 const handlePaymentFlowException = ( event, exception, abortPayment ) => {
 	let errorMessage;
-	if ( exception.message ) {
+
+	if ( exception.code === 'rest_invalid_param' && exception.data?.params ) {
```
Comment (wjrosa) [inline client/express-checkout/payment-flow.js:7]: Optional: I would move this to a constant.

File: client/express-checkout/utils/normalize.js [hunk 3]
```diff
@@ -36,45 +38,9 @@ export const normalizeOrderData = ( {
...
-			phone,
-			country: shipping?.address?.country ?? '',
-			address_1: shipping?.address?.line1 ?? '',
-			address_2: shipping?.address?.line2 ?? '',
-			city: shipping?.address?.city ?? '',
-			state: shipping?.address?.state ?? '',
-			postcode: shipping?.address?.postal_code ?? '',
-			method: [ event?.shippingRate?.id ?? null ],
-		},
+		billing_address: getBillingAddressData( event ),
```
Comment (wjrosa) [inline client/express-checkout/utils/normalize.js:42]: Nice refactor!

File: client/express-checkout/utils/normalize.js [hunk 4]
```diff
@@ -85,9 +51,256 @@ export const normalizeOrderData = ( {
...
+ * @param {Object} event Stripe's event object.
+ *
+ * @return {Object} The shipping address data.
+ */
+const getShippingAddressData = ( event ) => {
+	const shipping = event?.shippingAddress ?? {};
+
+	const data = {
+		first_name:
+			shipping?.name?.split( ' ' )?.slice( 0, 1 )?.join( ' ' ) ?? '',
```
Comment (wjrosa) [inline client/express-checkout/utils/normalize.js]: Optional: Maybe we could have a helper method for the names, since both share the same logic

File: client/express-checkout/utils/normalize.js [hunk 5]
```diff
@@ -85,9 +51,256 @@ export const normalizeOrderData = ( {
...
+	// to avoid sending "hidden" and possibly stale data from previous transactions,
+	// e.g. shopper is on the product page (hence, no checkout form fields are displayed),
+	// but session still holds data from a previous checkout.
+	if ( ! isBlockCheckoutPage() ) {
+		return emptyCustomFieldObject( [ 'address' ] );
+	}
+
+	const customerData = getCustomerDataFromStore();
+
+	if ( ! customerData || ! customerData.shippingAddress ) {
```
Comment (wjrosa) [inline client/express-checkout/utils/normalize.js]:
```suggestion
	if ( ! customerData?.shippingAddress ) {
```

**Review by wjrosa — APPROVED** [review]
Code is good and works as expected! Left some optional comments.

> 5. Verify in the Order Confirmation page that the fields have been persisted.

Screenshot 2025-06-11 at 12 37 37

> 6. Try using ECE in the product or cart pages.

> Verify there are no unexpected failures. See known limitations about required custom fields below.

Screenshot 2025-06-11 at 12 40 10

> Verify it avoids using stale session data: since the custom fields are not presented to the shopper inside these pages, there should be no custom data stored for these orders.

Screenshot 2025-06-11 at 13 07 36
(custom field not displayed after checking out using the product page)

File: client/express-checkout/utils/normalize.js (hunk 4 above)
Comment (annemirasol) [reply client/express-checkout/utils/normalize.js]: Updated in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4390/commits/ba69e4d76ad5de68465632e366754d6e10d967f0

**Comment by annemirasol** [comment]
Tested before merging:
- purchases via express checkout on product page
   - verified no unexpected errors
   - verified no stale custom field data is submitted
- purchases via express checkout block/classic cart
   - verified no unexpected errors
   - verified no stale custom field data is submitted
- purchases via express checkout on block checkout
   - verified custom field data is saved
- purchases via credit card on block checkout
   - verified no unexpected errors
