### PR TITLE
Redirect to correct page when payment fails

### LINKED ISSUE #3066: [APM] Wrong redirection destination when the payment fails on the Pay for order page
**Describe the bug**

When using the Pay for order page and an APM that uses redirects, like Alipay, Klarna, Bancontact, etc. shoppers are redirected to the checkout page instead of the Pay for order page when the payment fails.

**To Reproduce**
1. Select EUR as the store currency, at `/wp-admin/admin.php?page=wc-settings&tab=general`
2. Enable giropay, at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`
3. As a merchant, create a new WC order at `/wp-admin/admin.php?page=wc-orders&action=new`
4. As a shopper, visit the Pay for Order page for this newly created order
image

5. Select giropay as the payment method
6. Click on Pay for order
7. On the Stripe's giropay test payment page, click on "Fail test payment"
8. Notice that you redirected to either the Checkout or the Cart page, but not to the Pay for Order page

**Expected behavior**
As a shopper, I'd expect to be redirected to the Pay for Order page if the payment processing fails. This way I can smoothly resume the process.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/c7426159-51b7-4dd7-8baf-12a7f6bf7916)

### PR DESCRIPTION
**Pull request by annemirasol**
Fixes #3066 

## Changes proposed in this Pull Request:
When on the Pay for Order page, and the redirect-based payment method fails, the shopper gets redirected to the Cart/Checkout page instead of back to Pay for Order.

This PR fixes that behavior by tracking where to return the shopper so they can easily resume the process.

## Testing instructions
1. Enable redirect-based payment methods such as Afterpay and Klarna.
2. In WooCommerce > Orders, manually create an order.
    - Under Billing Address, add the customer's name and an address that is compatible with the payment method you plan to use, e.g. US, UK, etc. for Afterpay.
    - Under Shipping Address, click "Copy billing address" or enter a name and address.
    - Add an item to the order, and click Create.
3. Open the Pay for Order page in an incognito window.
Screenshot 2024-12-27 at 10 42 04 AM

4. Initiate payment using a redirect-based payment method, e.g. Afterpay.
5. Click "Fail test payment" on the auth page, or "X" or "Cancel" on an intermediate page.
6. In `develop`, the shopper gets redirected to an empty Cart page.
7. In this branch, the shopper gets returned to the Pay for Order page.

| Before | After |
|--------|-------|
| Screenshot 2024-12-27 at 11 13 44 AM | Screenshot 2024-12-27 at 11 13 11 AM |

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 1]
```diff
@@ -1196,7 +1203,12 @@ public function maybe_process_upe_redirect() {
 			return;
 		}
 
-		$this->process_upe_redirect_payment( $order_id, $intent_id, $save_payment_method );
+		$redirect_on_error = '';
+		if ( isset( $_GET['redirect_on_error'] ) && self::REDIRECT_ON_ERROR_PAY_FOR_ORDER === $_GET['redirect_on_error'] ) {
```
Comment (wjrosa) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php]: (optional) Since this is the only possible option, we could also treat this as a boolean (like `redirect_to_pay_for_order_on_error`). But this does not make sense if we have any indication that other URLs will be supported in the future.

**Review by wjrosa — APPROVED** [review]
Code is good and it works as expected!

I can confirm the redirect:
Screenshot 2024-12-27 at 18 55 09

Left an optional suggestion.

**Comment by annemirasol** [comment]
> (optional) Since this is the only possible option, we could also treat this as a boolean (like redirect_to_pay_for_order_on_error). But this does not make sense if we have any indication that other URLs will be supported in the future.

@wjrosa This is a great suggestion. I don't think it's likely that we'll need to support a redirect to a third URL, so it makes sense to just use a boolean flag, similar to how we use the `pay_for_order` flag [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/fd1ab0a8c11d7631cfc94541ab0bd8612068a1e5/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L390), for example. The changes have been simplified by a lot in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3682/commits/7aaf43021ab2042f971d8c75a79e03ead7cd292c, thanks!

Asking for re-review since I re-wrote quite a bit.

**Review by wjrosa — APPROVED** [review]
Thanks for the update, Anne! It looks great 👍
