### PR TITLE
[Split PE] Don't render the Stripe Link payment method option on classic checkouts

### LINKED ISSUE #2925: Split PE - Link shown as an empty payment method option on classic checkout
**Describe the bug**
On the latest `add/deferred-intent` branch sites which have Link enabled have an empty Link payment method shown on the classic checkout.

<p align="center">
Screenshot 2024-02-20 at 5 37 42 pm
</p>

**To Reproduce**
1. Checkout the latest `add/deferred-intent` branch
2. Enter Stripe API credentials for a US based account. 
   - Note: the Stripe account needs to have a US address, simply setting your WC store to the US won't work. 
3. Set the store currency to USD.
3. On the Stripe Payment methods settings enable **Link**

<p align="center">
Screenshot 2024-02-20 at 5 39 56 pm
</p>

4. Add an item to the cart. 
5. Go to the checkout page and note that the Stripe Link express elements have been displayed, but there's also an empty payment gateway option with Link. 

| Screenshot 2024-02-20 at 5 41 31 pm | Screenshot 2024-02-20 at 5 41 41 pm |
|--------|--------|

**Expected behavior**
Link isn't a payment method we need to display standard payment method fields for. There should be no Link option in the list of payment methods.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #2925 

## Changes proposed in this Pull Request:

On the **`add/deferred-intent`** branch, Stripe Link is currently being rendered on the classic  checkout with no payment element fields. 

<p align="center">
Screenshot 2024-02-21 at 3 17 04 pm
</p> 

This PR fixes that by making sure Link isn't enabled on Checkout. Link isn't a traditional payment method. A Link Express Payment button is rendered and once authenticated, the existing credit card fields are populated with that accounts card on file. _see example below_.

<p align="center">
Screenshot 2024-02-21 at 3 19 49 pm
</p> 

With that in mind, there's no need for the a separate Link payment element to be shown on the checkout. 

> [!note]
> This only impacts the classic checkout. Block checkout isn't effected by this bug. 

## Testing instructions

1. Checkout the latest `add/deferred-intent` branch
2. Enter Stripe API credentials for a US based account. 
   - Note: the Stripe account needs to have a US address, simply setting your WC store to the US won't work. 
3. Set the store currency to USD.
3. On the Stripe Payment methods settings enable **Link**

<p align="center">
Screenshot 2024-02-20 at 5 39 56 pm
</p>

4. Add an item to the cart. 
   - Go to the checkout page and note that the Stripe Link express elements have been displayed, but there's also an empty payment gateway option with Link. 
   - On this branch no Link option is shown. 

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Comment by james-allan** [comment]
Just noting that unit tests are failing on this branch because there's a number of unit tests that expect that Link is enabled on checkout. I'm not really sure what alternative approaches exist or whether I just need to update these tests.

**Comment by james-allan** [comment]
So I've pushed https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2930/commits/af44ac9138ef63eca2bd64ff76d9e7fb1a152ece which fixes the unit tests but I'm not sure if its the right approach either. I'll have to do some further research into the `is_available()` method what impact this could have.

File: includes/payment-methods/class-wc-stripe-upe-payment-method-link.php [hunk 1]
```diff
@@ -87,10 +87,15 @@ public function is_available_for_account_country() {
...
+	 * Link isn't like a traditional UPE payment method as it is not shown as a standard payment method at checkout.
+	 * Customers use the Stripe Link button and the existing credit card fields to enter their payment details. The payment is then treated as a card.
+	 *
+	 * We return false here so the payment method isn't considered available by WooCommerce and rendered as a payment method at checkout.
+	 *
 	 * @return bool
 	 */
 	public function is_available() {
-		return $this->is_available_for_account_country() && parent::is_available();
+		return false;
```
Comment (james-allan) [inline includes/payment-methods/class-wc-stripe-upe-payment-method-link.php:98]: On it's own, this change looks a little scary because changing a function to simply return `false`, however, after considering the history of this function, I think this change is fine. 

On `develop` the `is_available()` function in `WC_Stripe_UPE_Payment_Method` use to return `true`. [[code ref](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L122-L124)]. 

The UPE Link method class had a bit more logic in it's `is_available()` function [[code link](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-method-link.php#L79-L85)], however, in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2820 it was changed because `is_available()` is an inherited function of `WC_Payment_Gateway` and so when we changed all UPE elements to be `WC_Payment_Gateway`s, these `is_available()` functions took on a new meaning as WooCommerce uses this `is_available()` function to determine which payment methods to display to customers on the checkout. 

With this in mind, I think returning false because we don't want WooCommerce to display this method on the checkout makes logical sense. Let me know if you see an issue with this approach. 

In my testing, making purchases with Link still works fine because as I included in the function doc, the processing payment method is the card gateway when a customer completes a purchase using Link.

**Review by wjrosa — APPROVED** [review]
LGTM!

Tested and works as expected 👍
