### PR TITLE
Make webhook user agent validation optional

### LINKED ISSUE #1195: !BROKEN! on AWS Cloudfront.
Update by @dwainm:

Add a filter is_valid_request return value . Pass along the function parameters.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/70640ab3a2dd3dfc4a700dee3dc2393fcaca95a7/includes/class-wc-stripe-webhook-handler.php#L93-L95

----

**Original Issue**
Plugin has conflict with Amazon Cloudfront CDN whereby the correct User Agent is forcefully rewritten by the CDN. On all requests, the User Agent is modified to "Amazon Cloudfront".  This causes all webhook requests to return 400 even when correctly setup by failing on line 93 of /includes/class-wc-stripe-webhook-handler.php.

If I comment out lines 93-95 I get expected behaviour. 

The Cloudfront specification can be found here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html

Commenting out the three lines is sufficient but it’s not a long term fix. Please can you introduce an exception or a way of being able to disable this specific security measure.

Wordpress.org support ticket: https://wordpress.org/support/topic/cloudfront-user-agent/#post-12826607

**Environment (please complete the following information):**
 - WordPress Version - all
 - WooCommerce Version - 4.0.1
 - Stripe Plugin Version - 4.3.3
 - Browser [e.g. chrome, safari] and Version - all browsers

### PR DESCRIPTION
**Pull request by vbelolapotkov**
# Changes proposed in this Pull Request:

Based on #1483 and superceeds it.
Fixes #1195 

Description: 

* Make user agent validation a fallback for the cases when webhooks secret is not configured in plugin settings.
* Add filter to user agent validation to allow custom validations for environments like AWS Cloudfront.

From #1483:

> As described in the aforementioned issue, when using this plugin while behind an Amazon CloudFront CDN, all webhook requests fail with status 400. This is because the Amazon CloudFront overwrites the User-Agent header for all requests with Amazon CloudFront ([as described in their specs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#request-custom-user-agent-header)). Right now, though, a webhook request is considered valid only when its User-Agent header is empty or contains the word Stripe (see [WC_Stripe_Webhook_Handler::is_valid_request](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/0cf7865a6367e25073e5270f07f9e724363f851c/includes/class-wc-stripe-webhook-handler.php#L93-L95)).

> I've introduced a filter to allow website owners to specify a different User-Agent validation format (the default remains /Stripe/). This should provide an opt-in workaround for users trying to use webhooks while behind an Amazon CloudFront CDN, without affecting users relying on existing functionalities.

# Testing instructions

UA validation check.
1. In an existing installation make sure webhook sercret is not set in the plugin settings.
2. Add a filter (eg. via child theme) with name wc_stripe_webhook_validate_user_agent, returning true;
3. Send a webhook request with a custom User-Agent header not matching default check.
4. The webhook request should succeed (previously, it only did if the User-Agent contained the word 'Stripe').

UA fallback check.
1. Update filter introduced above to always return false;
2. Send a webhook request. It should fail.
3. Configure webhook secret in the plugin and DO NOT change or remove filter.
4. Send signed webhook request from Stripe (Stripe cli might be helpful). Request should succeed.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/class-wc-stripe-webhook-handler.php [hunk 1]
```diff
@@ -106,36 +106,49 @@ public function validate_request( $request_headers, $request_body ) {
...
+	 * Verify User Agent of the incoming webhook notification. Used as fallback for the cases when webhook secret is missing.
+	 *
+	 * @since 5.0.0
+	 * @version 5.0.0
+	 * @param array $request_headers The request headers from Stripe.
+	 * @return string The validation result (e.g. self::VALIDATION_SUCCEEDED )
+	 */
+	private function validate_request_user_agent( $request_headers ) {
+		$ua_is_valid = empty( $request_headers['USER-AGENT'] ) || preg_match( '/Stripe/', $request_headers['USER-AGENT'] );
+		$ua_is_valid = apply_filters( 'wc_stripe_webhook_validate_user_agent', $ua_is_valid, $request_headers );
```
Comment (ricardo) [inline includes/class-wc-stripe-webhook-handler.php]: Before looking at the code, I was confused about what was expected from this filter because of its name.

I didn't know if it should validate the User-Agent or if it would perform User-Agent validation.

Perhaps a clearer description of what it does could be something like `wc_stripe_webhook_is_valid_user_agent`. - Thinking in terms of function naming. 

But I'm still new to WP, so if that kind of nomenclature doesn't apply to filters/actions, you can ignore this comment.

File: includes/class-wc-stripe-webhook-handler.php [hunk 2]
```diff
@@ -106,36 +106,49 @@ public function validate_request( $request_headers, $request_body ) {
...
+	/**
+	 * Verify User Agent of the incoming webhook notification. Used as fallback for the cases when webhook secret is missing.
+	 *
+	 * @since 5.0.0
+	 * @version 5.0.0
+	 * @param array $request_headers The request headers from Stripe.
+	 * @return string The validation result (e.g. self::VALIDATION_SUCCEEDED )
+	 */
+	private function validate_request_user_agent( $request_headers ) {
+		$ua_is_valid = empty( $request_headers['USER-AGENT'] ) || preg_match( '/Stripe/', $request_headers['USER-AGENT'] );
```
Comment (ricardo) [inline includes/class-wc-stripe-webhook-handler.php:146]: Looks like the previous implementation allowed the User-Agent to be empty with
```php
! empty( $request_headers['USER-AGENT'] ) && ! preg_match( '/Stripe/', $request_headers['USER-AGENT'] )
```

But now we shouldn't, otherwise it would be invalid, right?

```php
! empty( $request_headers['USER-AGENT'] ) && preg_match( '/Stripe/', $request_headers['USER-AGENT'] );
```

File: tests/phpunit/test-wc-stripe-webhook-state.php [hunk 3]
```diff
@@ -72,6 +72,15 @@ public function tearDown() {
 		delete_option( WC_Stripe_Webhook_State::OPTION_TEST_LAST_ERROR );
 	}
 
+	private function cleanup_webhook_secret () {
+		$stripe_settings = get_option( 'woocommerce_stripe_settings', array() );
+		unset( $stripe_settings['webhook_secret'] );
+		unset( $stripe_settings['test_webhook_secret'] );
+		unset( $stripe_settings['testmode'] );
```
Comment (ricardo) [inline tests/phpunit/test-wc-stripe-webhook-state.php]: I'd remove this `unset( $stripe_settings['testmode'] );` because this is already being done in `tearDown`.

And just a small tweak in `cleanup_webhook_secret ()` with the extra space.

(We are almost done with a PHPCS PR, so we don't need to worry about coding standards 🙌)

**Review by ricardo — CHANGES_REQUESTED** [review]
This tests really well with the following request:

```
curl --header "User-Agent: CloudFront" \
    --request POST \
    --data '{"created":'$(date +%s)',"type":"foo"}' \
    "http://localhost:8082/?wc-api=wc_stripe"
```

And the following filter:

```php
add_filter( 'wc_stripe_webhook_validate_user_agent', '__return_true' );
```

Code LGTM 👍 nice job on this PR!

Just a few comments below:

File: includes/class-wc-stripe-webhook-handler.php (hunk 2 above)
Comment (vbelolapotkov) [reply includes/class-wc-stripe-webhook-handler.php:146]: I've left our own check the same. Previous check was for invalid UA, I've invertied it (`! a && ! b === ! (a || b)`) to check if it is valid.

> Looks like the previous implementation allowed the User-Agent to be empty with

So does this implementation.

> But now we shouldn't, otherwise it would be invalid, right?

I don't see the reason why the UA shouldn't be empty. I'm not sure if Stripe always sets UA header.

File: includes/class-wc-stripe-webhook-handler.php (hunk 1 above)
Comment (vbelolapotkov) [reply includes/class-wc-stripe-webhook-handler.php]: Good point, renamed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1493/commits/19f18350844c2c4a2615f9cc8f9f81bb176575d2.

File: tests/phpunit/test-wc-stripe-webhook-state.php (hunk 3 above)
Comment (vbelolapotkov) [reply tests/phpunit/test-wc-stripe-webhook-state.php]: Thanks for spotting this! Indeed, it's hard to notice without linter in place. Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1493/commits/0c6bb63824fa7c31981363564551ee5e6e5642fb

Comment (vbelolapotkov) [reply tests/phpunit/test-wc-stripe-webhook-state.php]: btw, I've noticed linter in GitHub actions checks but it's not available locally. Is it the case? If it's available would be nice to have an npm command and pre commit hook to lint the changes.

Comment (ricardo) [reply tests/phpunit/test-wc-stripe-webhook-state.php]: @vbelolapotkov we had the [PHP CodeSniffer PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1445) merged yesterday. `npm lint:php` and `npm lint:php-fix` were added. You probably need `composer install` and `npm run up` again next time.

File: includes/class-wc-stripe-webhook-handler.php (hunk 2 above)
Comment (ricardo) [reply includes/class-wc-stripe-webhook-handler.php:146]: I thought this PR would enforce the UA to be valid if webhook secret is empty.

> I don't see the reason why the UA shouldn't be empty. I'm not sure if Stripe always sets UA header.

🤔 IDK either... I think it's safer to leave it this way.

File: tests/phpunit/test-wc-stripe-webhook-state.php (hunk 3 above)
Comment (vbelolapotkov) [reply tests/phpunit/test-wc-stripe-webhook-state.php]: Fantastic, thank you! I haven't made a rebase and so haven't seen them :)

File: includes/class-wc-stripe-webhook-handler.php (hunk 2 above)
Comment (vbelolapotkov) [reply includes/class-wc-stripe-webhook-handler.php:146]: > I thought this PR would enforce the UA to be valid if webhook secret is empty.

It kind of does, but empty UA was considered as valid, hence I haven't touched that part.

**Review by ricardo — APPROVED** [review]
Changes look good to me 🚢 

Feel free to add some warning/description about the webhook secret or merge as is.

**Comment by vbelolapotkov** [comment]
Thanks for review @ricardo! I decided to go without warning/message for now because I'm not sure what would be a good approach here. Createdd https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1496 to follow up.
