### PR TITLE
After failed/declined process, valid cards were not accepted closes #96

### LINKED ISSUE #96: Version 3.0.5 Checkout Modal popup not displayed but payment continues to be attempted after using fraudulent test card.
#### What I expected

Using the checkout modal I enter the stripe test card 4100000000000019, the card is rejected and error "card_declined: Your card was declined." is displayed.  I expect when I click the "Continue To Payment" button on the checkout page that the checkout modal will be displayed again and I can try to enter a different card.
#### What happened instead

When I click the "Continue To Payment" button for the second or any subsequent time *after* the initial usage and failure of stripe test card 4100000000000019, the checkout modal popup does *not* appear.  What is worse is that the transaction is actually submitted again and again each time I click the "Continue To Payment" button with the fraudulent card and information and failed transaction even though the checkout modal popup does not appear.
#### Steps to reproduce the issue

1. Activate Checkout Modal.
2. Add items to card and proceed to checkout page.
3. Click "Continue To Payment" button.
4. Enter stripe test card 4100000000000019 with future exp. date and 3 digit cvc.
5. Card is processed, popup receives green check.
6. Checkout page gets error: card_declined: Your card was declined.
7. Without reloading the page, click the "Continue To Payment" button.
8. Checkout Modal popup does not appear.
9. Charge is still submitted from previous entered data and rejects.
10. Checkout page continues to get error: card_declined: Your card was declined.
11. Goto step 7 and repeat, each time you will effectively submit another charge with fraudulent card.
12. Finally go to your stripe account and see all the failed charges.

* As I recall there were a couple other cases where this same issue came up.  Must be related to the type of error.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

### PR DESCRIPTION
**Pull request by roykho**
Fixes #96

cc @gedex for review

#### Changes proposed in this Pull Request:
* Fix - After a failed/declined process, valid cards are not accepted.

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: woocommerce-gateway-stripe.php [hunk 1]
```diff
@@ -134,7 +134,7 @@ public function init() {
 		add_action( 'woocommerce_order_status_on-hold_to_refunded', array( $this, 'cancel_payment' ) );
 		add_filter( 'woocommerce_get_customer_payment_tokens', array( $this, 'woocommerce_get_customer_payment_tokens' ), 10, 3 );
 		add_action( 'woocommerce_payment_token_deleted', array( $this, 'woocommerce_payment_token_deleted' ), 10, 2 );
-		add_action( 'woocommerce_payment_token_set_default', array( $this, 'woocommerce_payment_token_set_default' ) );
+		add_action( 'woocommerce_payment_token_set_default', array( $this, 'woocommerce_payment_token_set_default' ) );
```
Comment (gedex) [inline woocommerce-gateway-stripe.php]: Extra space at the end of the line.
