### PR TITLE
Show Stripe Link button only if link is enabled in the settings

### LINKED ISSUE #2479: Stripe Link button do not disappear even if it is disabled
**Describe the bug**
The ‘Link pay Faster’ button does not disappear even if it disabled from Stripe > Express Checkout settings

**To Reproduce**
1. Enable Stripe Link from WooCommerce > Settings > Payments > Stripe > Express Checkout 
2. Go to the cart page -> See the "Stripe Link" button
3. Now, disable Stripe Link Express checkout 
4. See the button does not disappear

**Expected behavior**

The button should disappear if the Stripe Link option is disabled

**Screenshots**

**Workaround**

The only way to remove the Stripe Link button is to disable it from the Stripe dashboard itself: https://dashboard.stripe.com/settings/link

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #2479 

## Changes proposed in this Pull Request:
The Link payment request button is showing up in the cart/checkout page irrespective of the settings in the **Stripe -> Express Checkout** section. To prevent this from appearing merchants has to either disable Google/Apple Pay from the **Stripe -> Express Checkout** section or disable the Link from Stripe itself.

The reason behind this issue is when the payment request (Google/Apple) is enabled in **Stripe -> Express Checkout** settings and we check the `canMakePayment` ability in `assets/js/stripe-payment-request.js` from Stripe, it returns the status for all the types (Google Pay, Apple Pay, Link). On an incognito browser or on a browser where Google Pay or Apple Pay is not available, as the fallback it renders the next enabled method (which is Link here) if the Link payment request button is enabled in the Stripe settings.

### How to reproduce the issue
- Test on `develop` branch.
- Enable Link in payment request button on your Stripe dashboard (https://dashboard.stripe.com/settings/link)
- Go to **Stripe -> Express Checkout** settings.
- Enable Google/Apple Pay and disable Link.
- Open the browser in incognito mode (to ensure that Google/Apple Pay is not available) and add a product to the cart.
- Go to the cart page and find the `Pay with Link` button.

### Testing instructions
- Test on this branch.
- Enable Link in payment request button on your Stripe dashboard (https://dashboard.stripe.com/settings/link)
- Go to **Stripe -> Express Checkout** settings
- Enable Google/Apple Pay and disable Link.
- Open the browser in incognito mode (to ensure that Google/Apple Pay is not available) and add a product to the cart.
- Go to the cart page and ensure the `Pay with Link` button is not there.
- Now enable Link in **Stripe -> Express Checkout** settings.
- Reload the previous cart page incognito and ensure that the `Pay with Link` button is present.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

File: assets/js/stripe-payment-request.js [hunk 1]
```diff
@@ -376,6 +376,11 @@ jQuery( function( $ ) {
 					if ( ! result ) {
 						return;
 					}
+
+					if ( result.link && ! wc_stripe_payment_request_params.stripe.allow_link ) {
```
Comment (a-danae) [inline assets/js/stripe-payment-request.js]: The reported issue doesn't happen anymore with these changes 🎉 but the behavior changed when other payment request types are enabled. Steps:

1. Set up Google Pay in Chrome (or Apple Pay in Safari)
2. As a merchant, enable Google Pay and Apple Pay and disable Link
3. As a shopper, visit the checkout page in a browser where Google Pay or Apple Pay would show up
4. Notice that the Google Pay/Apple Pay button doesn't show up
5. Checkout `develop`, build the scripts, and reload the checkout page
6. Notice that the Google Pay/Apple Pay button shows up

image

Maybe we should bail only if other payment request types aren't available?

**Review by a-danae — CHANGES_REQUESTED** [review]
Hey, thanks for addressing this Mayisha!

Looking good! The issue seems to be solved, but the behavior of other PRBs changed a bit. I've left a comment below with the details. That behavior should stay the same as it was, right?

Besides that, just a heads up not to forget the changelog entry for this change 🙂 Thanks again!

File: assets/js/stripe-payment-request.js (hunk 1 above)
Comment (Mayisha) [reply assets/js/stripe-payment-request.js]: Good catch @a-danae :face_with_head_bandage: 
Fixed this in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2628/commits/edd96b2843fd17b4af1b7069bae03cf49551a5ff and now checking for other enabled types before the early return.

**Review by a-danae — APPROVED** [review]
Looks good and the code makes sense to me. Thanks for the adjustments @Mayisha !

**Comment by cremigerhonig** [comment]
its still an issue in Germany. please see here

Image
also here

Image

I try to remove it using CSS like this

```
.p-LinkAutofillPrompt {
  display: none!important;
}
```

and

```
.AnimateSinglePresenceItem.p-LinkAutofillPrompt-animationItem {
  display: none;
}
```

no changes

I also turn of under 

https://dashboard.stripe.com/settings/link
no changes
I also try to turn of under
https://dashboard.stripe.com/settings/payment_methods

but stripe keeps telling me that woocomerce (the payment plugin) is handling the payments so I cant do anything..

what to do?

this is also mentioned here

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2479

**Comment by cremigerhonig** [comment]
I just noticed 

when I have stripe gateway as second payment option while using the customizer to block css

```
.p-LinkAutofillPrompt {
  display: none!important;
}
```
then the link text is not display

the reason is that stripe is loading the link text with a little delay. try it yourself
