### PR TITLE
Make sure UPE methods are only enabled if the main gateway is enabled

### LINKED ISSUE #2849: [Split PE] APMs show up on the checkout page when the main Stripe gateway is disabled
**Describe the bug**
APMs show up on the checkout page when the main Stripe gateway is disabled

**To Reproduce**
1. Select Euro as the store currency (Under WooCommerce > Settings > General)
2. In the Stripe plugin settings page, enable UPE
3. Enable several APMs. Like SEPA or giropay (Under the Stripe plugin settings page > Payment methods)
4. Go to WooCommerce > Settings > Payments
5. Disable Stripe
6. Go to the checkout page
7. Notice that the APMs continue to be displayed

**Expected behavior**
I'd expect all of the payment gateways that are coming from Stripe to get disabled when the main gateway is disabled.

**Screenshots**

https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/6651f639-9eef-4acb-8cb8-b9f5ef79fc5d

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #2849 
## Changes proposed in this Pull Request:

This PR fixes an issue where APMs were being displayed on the classic checkout despite Stripe being deactivated. 

> [!note]
> This doesn't affect the block checkout because the payment methods shown on the block checkout use different logic. Namely `WC_Stripe_Blocks_Support::is_active()` checks if the main gateway is enabled. 

## Testing instructions

**APMs**

1. Change your store currency to Euros at **WooCommerce > Settings**
2. In the Stripe payment method settings (WooCommerce > Payments > Stripe) enter API credentials for an account with EU APMs enabled.
3. Enable UPE in the **Stripe > Advanced** settings. 
4. On the payment methods tab enable multiple payment methods (EPS, SEPA, GiroPay etc). 
5. On the **WooCommerce > Settings > Payments** screen disable Stripe.

<p align="center">
Screenshot 2024-01-24 at 1 45 21 pm
</p>

6. Go to a Classic/Shortcode checkout page. 
    - On `add/deferred-intent` (base branch) you'll notice the APMs are being shown. Note: card is not. 
    - On this branch no Stripe payment methods are being shown.

| Before | After |
|--------|--------|
| Screenshot 2024-01-24 at 1 50 34 pm | Screenshot 2024-01-24 at 1 51 08 pm | 

**Cards**

1. Enable Stripe in **WooCommerce > Settings > Payments**
1. On the Stripe payment methods tab enable multiple payment methods (EPS, SEPA, GiroPay etc) and disable the Credit card payment method.
3. Go to a Classic/Shortcode checkout page. 
    - On `add/deferred-intent` (base branch) you'll notice that the card payment section is still shown but not working. 
    - On this branch no card payment section is shown.

| Before | After |
|--------|--------|
| Screenshot 2024-01-24 at 5 10 30 pm | Screenshot 2024-01-24 at 5 11 39 pm | 

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

### CODE REVIEW

**Comment by james-allan** [comment]
I'm putting this one on hold because the latest changes I made to this PR broke some payment methods on the classic checkout when the credit card payment method isn't enabled.

**Comment by a-danae** [comment]
Oh, okay. I was reviewing this PR just now. I noticed an unexpected behavior during the review, so I'll come back later to continue the review but leave this around in the meantime: 

1. Check out `add/deferred-intent`
2. Go to WooCommerce > Settings > Payments
3. Enable Stripe
4. Check out this branch
5. Go to WooCommerce > Settings > Payments
6. Notice Stripe is disabled

If you go to Stripe > Settings, it shows as enabled.

Looks like the value of the WooCommerce toggle doesn't follow the value from within the Stripe > Settings tab.
https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/51a59f5d-686e-4459-a29f-3851b0c88f5c

**Comment by james-allan** [comment]
Sorry @a-danae. I think this is ready for review now. :)

> but leave this around in the meantime:

I hadn't noticed that the gateway was appearing disabled on this branch. 😅 It didn't actually disable the payment method unless you saved it I think. Anyway I've fixed that in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2851/commits/3d4489fbfbbb60712470d4e760b873fd5f5a913e.

File: includes/class-wc-stripe-blocks-support.php [hunk 1]
```diff
@@ -413,10 +415,38 @@ private function add_order_meta( \WC_Order $order, $payment_request_type ) {
...
 			$gateway = $gateways['stripe'];
-			return array_filter( $gateway->supports, [ $gateway, 'supports' ] );
+		} elseif ( $this->is_upe_method_available( $gateways ) ) {
+			$gateway = WC_Stripe::get_instance()->get_main_stripe_gateway();
+		} else {
+			return [];
+		}
+
+		return array_filter( $gateway->supports, [ $gateway, 'supports' ] );
+	}
```
Comment (james-allan) [inline includes/class-wc-stripe-blocks-support.php:428]: For some background, this change and the one above are essentially the same underlying issue. The blocks support file was reliant on the 'stripe' payment method being in the list of available payment methods. Because the "stripe" payment method is the main UPE gateway and is only available if cards are enabled, disabling cards would prevent these two blocks supportive functions to no longer work as expected. 

I've changed them both so if Stripe isn't available, it will check if any of our UPE methods are available. If at least 1 UPE method is enabled, it will load the script params and the payment methods support features.

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 2]
```diff
@@ -493,7 +493,7 @@ public function payment_fields() {
 				<div id="wc-stripe-upe-errors" role="alert"></div>
 				<input id="wc-stripe-payment-method-upe" type="hidden" name="wc-stripe-payment-method-upe" />
 				<input id="wc_stripe_selected_upe_payment_type" type="hidden" name="wc_stripe_selected_upe_payment_type" />
-				<input type="hidden" id="wc-stripe-is-deferred-intent" name="wc-stripe-is-deferred-intent" value="1" />
+				<input type="hidden" class="wc-stripe-is-deferred-intent" name="wc-stripe-is-deferred-intent" value="1" />
```
Comment (james-allan) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:496]: If cards were disabled, the core `WC_Stripe_UPE_Payment_Gateway::payment_fields()` wouldn't run and so wouldn't include this hidden element. I've added it to all our UPE method payment fields so it should now always be included. 

Its my understanding that these may be removed anyway once we no longer need the deferred intent flag.

File: includes/class-wc-stripe-blocks-support.php [hunk 3]
```diff
@@ -224,11 +224,13 @@ private function should_show_payment_request_button() {
...
+		$js_configuration   = [];
+		$available_gateways = WC()->payment_gateways->get_available_payment_gateways();
 
-		$gateways = WC()->payment_gateways->get_available_payment_gateways();
-		if ( isset( $gateways['stripe'] ) ) {
-			$js_configuration = $gateways['stripe']->javascript_params();
+		if ( isset( $available_gateways['stripe'] ) ) {
+			$js_configuration = $available_gateways['stripe']->javascript_params();
+		} elseif ( $this->is_upe_method_available( $available_gateways ) ) {
+			$js_configuration = WC_Stripe::get_instance()->get_main_stripe_gateway()->javascript_params();
```
Comment (a-danae) [inline includes/class-wc-stripe-blocks-support.php:233]: Nitting a bit about an edge case here:

1. Enable UPE
2. Disable all of the payment method types from the Stripe > Settings > Payment methods tab
3. Go to the block checkout and open the console
4. Notice there's an error saying 
```
Uncaught TypeError: Cannot convert undefined or null to object
    at entries (<anonymous>)
    at ./client/blocks/upe/index.js (index.js:37:1)
    at __webpack_require__ (upe_blocks.js?ver=50d725475582a9d2698bf6e8d71a443e:20:30)
    at upe_blocks.js?ver=50d725475582a9d2698bf6e8d71a443e:84:18
    at upe_blocks.js?ver=50d725475582a9d2698bf6e8d71a443e:87:10
```

This is coming from [this line](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/deferred-intent/client/blocks/upe/index.js#L24). The JS param `paymentMethodsConfig`, defined [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/deferred-intent/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L326) isn't provided in this case.

It'd be great not to load those scripts when no payment gateways are enabled, but it's probably better to handle this in a separate issue to keep this PR small.

File: includes/class-wc-stripe-blocks-support.php (hunk 1 above)
Comment (a-danae) [reply includes/class-wc-stripe-blocks-support.php:428]: Sounds great. From what I've tested, things are working as expected, and the issues we saw before aren't happening anymore.

I also think needing this workaround means things could be structured better in the plugin... What do you think? Not thinking of doing it now, though, such a refactor would be big and not worth it at this point, but to start evaluating it for the future.

**Review by a-danae — COMMENTED** [review]
Review in progress. Things are looking good 🙂 

I'll come back to this but wanted to share what I have so far. No blockers.

**Review by a-danae — APPROVED** [review]
Great job here, @james-allan ! 🙂 Things look good to me.

In both the block and checkout pages:
✅ The APMs don’t show up when disabling Stripe from the WooCommerce > Settings > Payments page.
✅ When Cards is disabled and APMs are enabled, the card payment method type isn’t displayed on the checkout while APMs continue to be displayed.

Also...
✅ The toggle state of Stripe on the WooCommerce > Settings > Payments page is consistent with the state of the “Enable Stripe” option on the Stripe > Settings tab.
✅ The code makes sense to me.

The only unexpected behavior I found isn't related to these changes, and it got better with this PR. It's about the Add Payment Method page. I opened a separate issue for it (https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2862)

Thanks for addressing this!

File: includes/class-wc-stripe-blocks-support.php (hunk 3 above)
Comment (james-allan) [reply includes/class-wc-stripe-blocks-support.php:233]: > It'd be great not to load those scripts when no payment gateways are enabled, but it's probably better to handle this in a separate issue to keep this PR small.

Sounds good. :) I'll file an issue for it

**Comment by james-allan** [comment]
> I also think needing this workaround means things could be structured better in the plugin... What do you think?

Yeah I agree, it's a little strange code smell sort of thing that isn't intuitive to folks working on this so I think it would be better if it didn't work like that. As you mentioned, it would require a major restructure so perhaps something we can look into later. 


Thanks for the review. :)

File: includes/class-wc-stripe-blocks-support.php (hunk 3 above)
Comment (james-allan) [reply includes/class-wc-stripe-blocks-support.php:233]: To close the loop here. Here's the new issue for this: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2865
