### PR TITLE
Fix variable dump in ACH customer error message when retrying a payment

### LINKED ISSUE #3991: ACH: Raw variable dump appears in customer error message when retrying a payment
**Describe the bug**
When retrying a failed ACH payment, a raw variable dump appears in the customer error message. This issue occurs in both the Blocks and Shortcode checkouts.

**To Reproduce**
1. Attempt to pay with ACH using the test account `000777777771` and routing number `110000000`. The payment should fail.  
2. Without refreshing the page, retry the payment using the account `000000000009` and routing number `110000000`.  
3. Observe that the error message includes a raw variable dump.  

**Note:** These test accounts are from Stripe’s documentation: [Testing ACH](https://docs.stripe.com/payments/ach-direct-debit#testing-ach).  

**Expected behavior**
On the second attempt, the payment should be processed successfully without displaying a raw variable dump in the error message.
If an error message is displayed, it must be useful for the shopper.

**Screenshots**

https://github.com/user-attachments/assets/b0071f8d-0029-4ccf-a203-06c3d3c7c45e

**Environment (please complete the following information):**
 - WordPress 6.7.2
 - WooCommerce 9.7.0

**Additional context**

### PR DESCRIPTION
**Pull request by rafaelzaleski**
Fixes #3991

## Changes proposed in this Pull Request:

This PR removes the variable dump in the ACH customer error message when retrying a payment.

## Testing instructions

1. Reproduce the bug in `develop` by following the instructions in #3991.
2. Switch to this PR and repeat the steps in #3991.
3. The customer error message should no longer contain the variable found in step 1.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Fix customer error message when retrying a payment with ACH.</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

**Comment by rafaelzaleski** [comment]
The `charge_exceeds_source_limit` error is intended for merchants, not shoppers. I’ve created https://github.com/woocommerce/woocommerce-gateway-stripe/issues/4046 to refactor the `WC_Stripe_Exception` class to better handle the messages we display for shoppers and merchants.

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php [hunk 1]
```diff
@@ -602,8 +602,13 @@ public function process_response( $response, $order ) {
...
 				$localized_message = __( 'Payment processing failed. Please retry.', 'woocommerce-gateway-stripe' );
-				$order->add_order_note( $localized_message );
-				throw new WC_Stripe_Exception( print_r( $response, true ), $localized_message );
+				$order->add_order_note(
+					property_exists( $response, 'outcome' ) && isset( $response->outcome->seller_message )
+						? $response->outcome->seller_message
+						: $localized_message
+				);
+
+				throw new WC_Stripe_Exception( $localized_message, $localized_message );
```
Comment (asumaran) [inline includes/abstracts/abstract-wc-stripe-payment-gateway.php]: Is this intentional, passing the same string for both parameters? Since the first parameter of `WC_Stripe_Exception` is expected to be [the original error message](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/100cb610a44d39fc9513840a554a392796234c2c/includes/class-wc-stripe-exception.php#L29).

**Review by asumaran — COMMENTED** [review]
@rafaelzaleski The PR tested as expected. I was able to reproduce the bug in develop and saw the new Payment processing failed. Please retry. error message in the UI when using your branch.

I just left a minor question/suggestion.

File: includes/abstracts/abstract-wc-stripe-payment-gateway.php (hunk 1 above)
Comment (rafaelzaleski) [reply includes/abstracts/abstract-wc-stripe-payment-gateway.php]: You’re right—the JSON response was sending the full response instead of the second parameter. I fixed it in [this commit](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4039/commits/18706090d444f717bdfddd81986603afdf7909d0) and reverted the exception to include the full response in the first parameter.

**Review by asumaran — APPROVED** [review]
LGTM!
