### PR TITLE
Fix/issue 728

### LINKED ISSUE #728: Subscriptions: "Change Payment" Updated Card Not Used For manuell Renewals
Maybe Same Problem like here:
#281 and #722 

1. scenario:
- active subscription. Payment for renewal-order failed because of a problem with the creditcard. For example declined.
- We let the customer know about it. 
- Customer will add a new payment source (new Creditcard) in his account. Steps to add a new creditcard: Customer goes to his account, adds a new payment. Select the button, that this should be used for future payments. confirmation.
- after it we "retry renewal payment" for the failed order in order actions on the admin-order-detailpage.
- Payment fails again. The process tries to renewal the payment again with the old creditcard/source. Not the new one. But the new one is added as source in Stripe.

2. Scenario:
- Customer added a new payment source
- We create in the subscription-Detail-Page a manuell renewal
- payment failed, because it tries to renewal the payment again with the old creditcard/source. Not the new one. But the new one is added as source in Stripe.

For both scenarios, future automatic payment will use the new creditcard. Only for manuell or existing orders not.

### PR DESCRIPTION
**Pull request by roykho**
Fixes #728

#### Changes proposed in this Pull Request:
* Add - Ability to update all active subscription's payment method when adding a payment.
* Add - Hook to show update all active subscription's payment method checkbox `wc_stripe_display_update_subs_payment_method_card_checkbox`.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/compat/class-wc-stripe-sepa-subs-compat.php [hunk 1]
```diff
@@ -74,6 +76,52 @@ public function is_subs_change_payment() {
 		return ( isset( $_GET['pay_for_order'] ) && isset( $_GET['change_payment_method'] ) );
 	}
 
+	/**
```
Comment (budzanowski) [inline includes/compat/class-wc-stripe-sepa-subs-compat.php]: A large chunk of code duplicated. Can it be DRY and moved to a utility class or common ancestor, if there is one?
