### PR TITLE
Guard against fatal error on Inbox data store load

### LINKED ISSUE #1371: 4.5.4 Broke my site
Priority: CRITICAL (Can't figure out how to add the label)

The latest update completely broke my site, was unable to access backend even in safe mode. Got fatalerror message Had to downgrade to stop This is the log:

Error Details
=============
An error of type E_ERROR was caused in line 107 of the file /wp-content/plugins/woocommerce/includes/class-wc-data-store.php. Error message: Uncaught Exception: Invalid data store. in /wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('admin')
#1 /wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php(79): WC_Data_Store::load('admin-note')
#2 /wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php(37): WC_Stripe_Inbox_Notes::should_show_marketing_note()
#3 /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay-registration.php(235): WC_Stripe_Inbox_Notes::notify_on_apple_pay_domain_verification(true)
#4 /wp-includes/class-wp-hook.php(287): WC_Stripe_Apple_Pay_Registrati

That's where the log I received via email cuts off. The problem was immediately fixed by downgrading tp 4.5.3. My PHP version is 7.3.16. Latest Wordpress and Woocommerce.

### PR DESCRIPTION
**Pull request by dechov**
Fixes #1371

#### Changes proposed in this Pull Request:
Adds try/catch around Data Store loads, to prevent fatal error being thrown on that call.

Unfortunately I'm unable to reproduce the error, so cannot confirm first-hand at this point whether this fix solves the fatal.

-------------------
- [ ] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

### CODE REVIEW

File: includes/admin/class-wc-stripe-inbox-notes.php [hunk 1]
```diff
@@ -39,16 +39,18 @@ public static function notify_on_apple_pay_domain_verification( $verification_co
...
+				if ( ! empty( $failure_note_ids ) ) {
+					$note_id = array_pop( $failure_note_ids );
+					$note    = WC_Admin_Notes::get_note( $note_id );
+					if ( false !== $note && WC_Admin_Note::E_WC_ADMIN_NOTE_ACTIONED !== $note->get_status() ) {
+						$note->set_status( WC_Admin_Note::E_WC_ADMIN_NOTE_ACTIONED );
+						$note->save();
+					}
 				}
-			}
+			} catch ( Exception $e ) {}  // @codingStandardsIgnoreLine.
```
Comment (reykjalin) [inline includes/admin/class-wc-stripe-inbox-notes.php:53]: Instead of a try/catch with an empty catch block, maybe it would be better to wrap with [`method_exists`](https://www.php.net/manual/en/function.method-exists.php)?

```php
if ( method_exists( 'WC_Data_Store', 'load' ) ) {
    // ...
}
```

Comment (reykjalin) [reply includes/admin/class-wc-stripe-inbox-notes.php:53]: And maybe we should log an error indicating that the merchant might want to update WC to get the data store?

**Review by reykjalin — CHANGES_REQUESTED** [review]
Looks good functionality-wise, although I think we might be able to go without the try/catch blocks? See comment for details.

File: includes/admin/class-wc-stripe-inbox-notes.php (hunk 1 above)
Comment (reykjalin) [reply includes/admin/class-wc-stripe-inbox-notes.php:53]: Actually, we do need the try/catch, nevermind!

Didn't read the error message carefully enough 😬

**Review by reykjalin — APPROVED** [review]
Approving it since conversations have been resolved.

We might want to add logging when things fail, however, but that's not a blocker.

**Comment by lkraav** [comment]
Can this crash possibly be reproduced with `add_filter( 'woocommerce_admin_disabled', '__return_true' );`?

For example, woocommerce/automatewoo just discovered a host of issues to trigger in this scenario.

**Comment by dechov** [comment]
It can indeed – thank you @lkraav!
