### PR TITLE
Fix fatal error when payment method ID is missing

### LINKED ISSUE #3934: Argument 2 passed to WC_Stripe_UPE_Payment_Gateway::set_payment_method_id_for_order() must be of the type string, null given
9405541-zen

I am still investigating why merchant's checkout page doesn't make a `/v1/payment_methods` request to get pm_ ID value but when that happens, we get a blank value assigned here:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/6c5f25444f1f990637778fa50d7b49ec36af189a/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L2195

Further, this causes a critical error when attempted to set the payment method:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/6c5f25444f1f990637778fa50d7b49ec36af189a/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L872

> Argument 2 passed to WC_Stripe_UPE_Payment_Gateway::set_payment_method_id_for_order() must be of the type string, null given

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #3934

## Changes proposed in this Pull Request:

This PR fixes a possible fatal error that might happen when a payment method ID could not be retrieved, by setting some default values during payment information array initialization.

## Testing instructions

Code review should be enough.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Tested on mobile (or does not apply)

### Changelog entry

-   [ ] This Pull Request does not require a changelog entry. (Comment required below)

<details>

<summary>Changelog Entry Comment</summary>

#### Comment 

</details>

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

**Review by Mayisha — APPROVED** [review]
Adding these default values is a good idea and will prevent the fatal error. 👍

File: includes/payment-methods/class-wc-stripe-upe-payment-gateway.php [hunk 1]
```diff
@@ -2217,6 +2217,10 @@ protected function prepare_payment_information_from_request( WC_Order $order ) {
 			'return_url'                    => $this->get_return_url_for_redirect( $order, $save_payment_method_to_store ),
 			'use_stripe_sdk'                => 'true', // We want to use the SDK to handle next actions via the client payment elements. See https://docs.stripe.com/api/setup_intents/create#create_setup_intent-use_stripe_sdk
 			'has_subscription'              => $this->has_subscription( $order->get_id() ),
+			'payment_method'                => '',
+			'payment_method_details'        => [],
+			'payment_type'                  => 'single', // single | recurring.
+			'capture_method'                => $capture_method,
```
Comment (annemirasol) [inline includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:2223]: @wjrosa Can we exclude the default capture method at this level? Amazon Pay doesn't like it and complains (when capture method is manual), because it needs to be under payment_method_options?

Comment (wjrosa) [reply includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:2223]: Oh OK! I drafted this PR to revert the setting for this specific parameter here https://github.com/woocommerce/woocommerce-gateway-stripe/pull/4019
