### PR TITLE
Fix ECE crash when address has no defined shipping rates

### LINKED ISSUE #3538: [ECE] Error when shopper address is not covered in Shipping
**Describe the bug**
When the address(es) connected to the Apple Pay or Google Pay account is not in a valid shipping zone (i.e. not defined in WC > Settings > Shipping), we get an `IntegrationError` in the browser console, and the ECE modal never launches.

**To Reproduce**
1. Take note of the shipping addresses connected to your Google Pay account.
   - If you are on the Google Pay Test Group, these are the shipping addresses: https://developers.google.com/pay/api/android/guides/resources/test-card-suite#mock-testing 
2. Go to WooCommerce > Settings > Shipping and define a shipping zone that does not cover your Google Pay account address.
   - If you are on the Google Pay Test Group, you can define a country like `Philippines` as your only shipping zone.
3. Enable Stripe ECE.
   - Force `is_stripe_ece_enabled()` to return `true`, or add `_wcstripe_feature_ece` with a value of `yes` to your `wp_options` table.
5. As a shopper, add a shippable product to cart and go to checkout.
6. Verify that you see Google Pay (and possibly other express payment methods).
7. Click "Pay".
8. Notice that the modal never launches and the page is stuck in the loading animation.
9. Check the browser console. You will see the following error:

```
Uncaught (in promise) IntegrationError: When `shippingAddressRequired` is true, you must specify `shippingRates`.
```

**Additional context**
- Also happens if the Google Pay has multiple shipping addresses available, and the default address on-load (i.e. first, or last selected address) is not defined as a shipping zone, even if one of the addresses is defined.
- Happens only for block cart and block checkout.
- The same thing happens for Apple Pay and Link.
- This doesn't happen for PRBs.

### PR DESCRIPTION
**Pull request by annemirasol**
Fixes #3538 

## Changes proposed in this Pull Request:
For block cart and block checkout, when Apple Pay, Google Pay or Link loads and the default address (first address, or last selected address) is not defined under Shipping, we get an `IntegrationError` and the cart/checkout page gets stuck trying to load the modal.

This happens because for block cart and block checkout, we pass a potentially empty `shippingRates` array option to ECE. When `shippingRates` is empty but `shippingAddressRequired` is `true`, the Stripe JS library throws an error and bails ([Stripe docs](https://docs.stripe.com/js/element/events/on_click?type=expressCheckoutElement#element_on_click-handler-resolve-shippingAddressRequired)).

This issue does not happen inside the Product and shortcode pages because we are always passing a non-empty "pending" `shippingRates` array when ECE loads.

To fix the issue, we will do the same for block cart and block checkout: when we do not have shipping rates for the current address, we will pass a "pending" shipping rates array. With this change, ECE will not crash the page, and the user has a chance to change to a valid shipping address, in case of multiple available addresses.

## Testing instructions
1. Join the Google Pay test group to easily get multiple shipping addresses available to your account: https://groups.google.com/g/googlepay-test-mode-stub-data
2. As the merchant, set up your shipping zones such that only Japan is defined, with a free or flat rate shipping.
3. As the shopper, clear cookies and add a product to your cart.
4. For both block cart and block checkout, verify the following behavior:
   - On `develop`: Google Pay modal does not launch and the page is stuck loading.
   - On this branch: 
      - Google Pay modal launches without any error.
      - Shopper still cannot proceed with the purchase if an address other than Japan is selected.
      - Shipping computation is correct when selecting a valid shipping address.
6. Regression test: the product, shortcode cart and shortcode checkout pages should not be affected and should behave the same as above.

**Google Pay**
| Before | After |
| ------------- | ------------- |
| Screenshot 2024-10-29 at 1 05 19 PM  | Screenshot 2024-10-29 at 1 06 01 PM |

**Apple Pay**
| Before | After |
| ------------- | ------------- |
| Screenshot 2024-10-30 at 12 18 37 PM | Screenshot 2024-10-30 at 12 19 07 PM |

**Link**
| Before | After |
| ------------- | ------------- |
| Screenshot 2024-10-30 at 12 29 41 PM | Screenshot 2024-10-30 at 12 27 15 PM |

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [x] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [x] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

### CODE REVIEW

File: includes/payment-methods/class-wc-stripe-express-checkout-helper.php [hunk 1]
```diff
@@ -277,6 +272,39 @@ public function get_product_data() {
 		return apply_filters( 'wc_stripe_payment_request_product_data', $data, $product );
 	}
 
+	/**
+	 * JS params data used by cart and checkout pages.
+	 *
+	 * @param array $data
+	 */
+	public function get_checkout_data() {
```
Comment (wjrosa) [inline includes/payment-methods/class-wc-stripe-express-checkout-helper.php:280]: I think it would be nice to have a simple unit test for this method.

**Review by wjrosa — APPROVED** [review]
The code is good, and it works as expected! Left a minor suggestion.

> On develop: Google Pay modal does not launch and the page is stuck loading.

Screenshot 2024-10-30 at 15 27 41

> On this branch:
> Google Pay modal launches without any error.

Screenshot 2024-10-30 at 15 28 52

> Shopper still cannot proceed with the purchase if an address other than Japan is selected.

Screenshot 2024-10-30 at 15 29 23

Screenshot 2024-10-30 at 15 31 51

File: includes/payment-methods/class-wc-stripe-express-checkout-helper.php (hunk 1 above)
Comment (annemirasol) [reply includes/payment-methods/class-wc-stripe-express-checkout-helper.php:280]: Unit tests in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3560/commits/c9c7efe72b7a5e403d806ad935bcee8392d9b5a0, thanks!
